{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.30.0.jar",
          "url": "runelite-jshell-4.30.0.jar",
          "size": 26557,
          "sha512": "35a15a6522c750b048e704ddf2384008523332744db1c5f7e9337b0887d73c20d5011be8ec9522e839502dbbd716460fb0aae4dde6d44416b1e22e81c195eb72",
          "sha256": "743d698ffef6031f02f22127e79db7f41a1517ab06d1018cd6c1c57e0ef8b82c",
          "sha1": "7086b8cae204c80b5ba70fa1da04cfe9f83b5b1d",
          "md5": "d467bdebcbcfb548e92cc66c171ddc82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.30.0.jar",
          "url": "runelite-jshell-4.30.0.jar",
          "size": 26557,
          "sha512": "35a15a6522c750b048e704ddf2384008523332744db1c5f7e9337b0887d73c20d5011be8ec9522e839502dbbd716460fb0aae4dde6d44416b1e22e81c195eb72",
          "sha256": "743d698ffef6031f02f22127e79db7f41a1517ab06d1018cd6c1c57e0ef8b82c",
          "sha1": "7086b8cae204c80b5ba70fa1da04cfe9f83b5b1d",
          "md5": "d467bdebcbcfb548e92cc66c171ddc82"
        }
      ]
    }
  ]
}
