{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.2.jar",
          "url": "http-api-4.9.2.jar",
          "size": 157341,
          "sha512": "2184db7e3470e2931027ec8441761bb5378bd9cfc1f23c4ba2795f92dad68313770172359ff0a0fa48a6de2c2a6730e14f4aa0ddf8c1a036287b0005e1bdd8e0",
          "sha256": "97108c9f5f922e97269cfa1fb6086da412c7beeac400461fe71807c78331c4d8",
          "sha1": "39cd0fe5d96eb430f73493ce4fd134c0985aaf7f",
          "md5": "02e04c5828c437477a77f7f7a1372be6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.2.jar",
          "url": "http-api-4.9.2.jar",
          "size": 157341,
          "sha512": "2184db7e3470e2931027ec8441761bb5378bd9cfc1f23c4ba2795f92dad68313770172359ff0a0fa48a6de2c2a6730e14f4aa0ddf8c1a036287b0005e1bdd8e0",
          "sha256": "97108c9f5f922e97269cfa1fb6086da412c7beeac400461fe71807c78331c4d8",
          "sha1": "39cd0fe5d96eb430f73493ce4fd134c0985aaf7f",
          "md5": "02e04c5828c437477a77f7f7a1372be6"
        }
      ]
    }
  ]
}
