{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "cb1d904cc52d82f89e98cd80f64d0adf927e5e87ac875a213a6e0ac36c0d9f7763afbf5f9e51db491a241cf2fdcaa1bc6349f2b32cd0ada696d254c6afbd826c",
          "sha256": "17dc83d5fd0c534b6ee6f7f9c0a65133558bcbddd34380d583776c527a6faf84",
          "sha1": "6aa66a591984bfb655bd6b1c07448c89bb9e64be",
          "md5": "2d2b54b34af39d07e65b817834843938"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "cb1d904cc52d82f89e98cd80f64d0adf927e5e87ac875a213a6e0ac36c0d9f7763afbf5f9e51db491a241cf2fdcaa1bc6349f2b32cd0ada696d254c6afbd826c",
          "sha256": "17dc83d5fd0c534b6ee6f7f9c0a65133558bcbddd34380d583776c527a6faf84",
          "sha1": "6aa66a591984bfb655bd6b1c07448c89bb9e64be",
          "md5": "2d2b54b34af39d07e65b817834843938"
        }
      ]
    }
  ]
}
