{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "49c4204897ddf774b2f311fcf57cb047b27db38abb8c0b416ff5cd0e37b470350837df04cfec182cfe53c1e73720206e5905cddaf76afc98b39d9b464a7e48c3",
          "sha256": "613983c36c313670d9193cf24b40a43b78de4985338ade412c2408027dd934a0",
          "sha1": "8f444b0eeb0fb10911e9c2a5293b4343069066a4",
          "md5": "7ba88a9e3691b9066b570bbcf118c6df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "49c4204897ddf774b2f311fcf57cb047b27db38abb8c0b416ff5cd0e37b470350837df04cfec182cfe53c1e73720206e5905cddaf76afc98b39d9b464a7e48c3",
          "sha256": "613983c36c313670d9193cf24b40a43b78de4985338ade412c2408027dd934a0",
          "sha1": "8f444b0eeb0fb10911e9c2a5293b4343069066a4",
          "md5": "7ba88a9e3691b9066b570bbcf118c6df"
        }
      ]
    }
  ]
}
