{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "2bf1d71586359cf1ca2d138a747f0d1593d4d9f8edb3d03f195e2ff7a5de8aac80f23a7117dee101b7ae9fee81813919614359e33952b23b49d8c4f36cf86d9c",
          "sha256": "5b9eb866d22ad8ca20c4db0adcd1c2ad9d7f0c137b97ab244d3252635fcf1386",
          "sha1": "0f966e35050ce8a623452a48b6043463ac0f0ef4",
          "md5": "def59eaffd592d4c686c1af4a49d0a61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "2bf1d71586359cf1ca2d138a747f0d1593d4d9f8edb3d03f195e2ff7a5de8aac80f23a7117dee101b7ae9fee81813919614359e33952b23b49d8c4f36cf86d9c",
          "sha256": "5b9eb866d22ad8ca20c4db0adcd1c2ad9d7f0c137b97ab244d3252635fcf1386",
          "sha1": "0f966e35050ce8a623452a48b6043463ac0f0ef4",
          "md5": "def59eaffd592d4c686c1af4a49d0a61"
        }
      ]
    }
  ]
}
