{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.6.1.jar",
          "url": "runelite-api-4.6.1.jar",
          "size": 1258915,
          "sha512": "17c74ebf9f6a5588e3182f6d575b68949fe9a0fc56d91e190dfcf82a6f3fd5e2f625eed2dfc5b5e8cf647ba8bc29181b56f9744e65de501e194f7b9cc1aa6ef0",
          "sha256": "3b1562b10e700c63584c43ed7417bc6816f1d73a2750b5433da6eddd6591e714",
          "sha1": "94afb03ec74df58acb7e5264dfc4f290e689ac86",
          "md5": "9dfd616065ed685892e3941a3e2cd719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.6.1.jar",
          "url": "runelite-api-4.6.1.jar",
          "size": 1258915,
          "sha512": "17c74ebf9f6a5588e3182f6d575b68949fe9a0fc56d91e190dfcf82a6f3fd5e2f625eed2dfc5b5e8cf647ba8bc29181b56f9744e65de501e194f7b9cc1aa6ef0",
          "sha256": "3b1562b10e700c63584c43ed7417bc6816f1d73a2750b5433da6eddd6591e714",
          "sha1": "94afb03ec74df58acb7e5264dfc4f290e689ac86",
          "md5": "9dfd616065ed685892e3941a3e2cd719"
        }
      ]
    }
  ]
}
