{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "56stvg6vpff2jn5hcncetngajy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.1.0.jar",
          "url": "runelite-jshell-4.1.0.jar",
          "size": 22754,
          "sha512": "8658b0df6b5e164300f7958fa523b08855b6e329f124b89dd77155bc2d5af48876c6d20f61f72a9afe749a32920266820473f633cef095d65c2cd8d16fbf8cbc",
          "sha256": "f8031f44a9e5ca14241ef63fa18be7222ba00e57edfda62d69d0b4440699eff7",
          "sha1": "9faf9b0e2e14659efb785e1e79adc66d13a6fff7",
          "md5": "7c9693f392930f14ad8cb41bf77022a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.1.0.jar",
          "url": "runelite-jshell-4.1.0.jar",
          "size": 22754,
          "sha512": "8658b0df6b5e164300f7958fa523b08855b6e329f124b89dd77155bc2d5af48876c6d20f61f72a9afe749a32920266820473f633cef095d65c2cd8d16fbf8cbc",
          "sha256": "f8031f44a9e5ca14241ef63fa18be7222ba00e57edfda62d69d0b4440699eff7",
          "sha1": "9faf9b0e2e14659efb785e1e79adc66d13a6fff7",
          "md5": "7c9693f392930f14ad8cb41bf77022a3"
        }
      ]
    }
  ]
}
