{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149686,
          "sha512": "bce4fa2ce8a3e6677fcfd329e510e34e0bc98dc17973c444e7cdc25cd0b94ed82c7caa4a1c1cb70f314a011df86dd1b57c29c759679f2ce13c0847ad3cbff1ee",
          "sha256": "c309a509f33d717c09f9c02736aab415a3274dbeaa5928d594edd40917a462aa",
          "sha1": "1e1e0d71b578013bd75d266524358cab54d5776a",
          "md5": "26e96da3c68f20f82ea895a5cdf47b5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149686,
          "sha512": "bce4fa2ce8a3e6677fcfd329e510e34e0bc98dc17973c444e7cdc25cd0b94ed82c7caa4a1c1cb70f314a011df86dd1b57c29c759679f2ce13c0847ad3cbff1ee",
          "sha256": "c309a509f33d717c09f9c02736aab415a3274dbeaa5928d594edd40917a462aa",
          "sha1": "1e1e0d71b578013bd75d266524358cab54d5776a",
          "md5": "26e96da3c68f20f82ea895a5cdf47b5d"
        }
      ]
    }
  ]
}
