{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149749,
          "sha512": "ab6abef0f29db805c80dbe8316cc9be12f73f5c248889b57c49696c159c0e3e6d9cb309a7ebdfada4292fbac486be4746899a6af26ebb6af33cff2bd54e4b0b2",
          "sha256": "312e69adf8e41da7840df6619347d75f36dd80a319fd40d693c832df74db5645",
          "sha1": "b42b11a4c270abcf0c06ca226378f7780407ea5c",
          "md5": "23e34dfb1f4630bc58707cf42588a6f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149749,
          "sha512": "ab6abef0f29db805c80dbe8316cc9be12f73f5c248889b57c49696c159c0e3e6d9cb309a7ebdfada4292fbac486be4746899a6af26ebb6af33cff2bd54e4b0b2",
          "sha256": "312e69adf8e41da7840df6619347d75f36dd80a319fd40d693c832df74db5645",
          "sha1": "b42b11a4c270abcf0c06ca226378f7780407ea5c",
          "md5": "23e34dfb1f4630bc58707cf42588a6f7"
        }
      ]
    }
  ]
}
