{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149749,
          "sha512": "59bad3803a21177bcb74e0a7541d76c9d0fa9ddba9f0e466bded8c60d63a67abbd556541a81d419e374f25099ea03c593a4e65e94d8bf8788a64335425493085",
          "sha256": "439c03bc31b1314c34ad359a1661373834b6067d9ee7d1c5ce7435368915d911",
          "sha1": "c89967116722e0bbf7d8f9bb6cc5945ff386f7a5",
          "md5": "1295540feaca1edb086c29317e3769f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149749,
          "sha512": "59bad3803a21177bcb74e0a7541d76c9d0fa9ddba9f0e466bded8c60d63a67abbd556541a81d419e374f25099ea03c593a4e65e94d8bf8788a64335425493085",
          "sha256": "439c03bc31b1314c34ad359a1661373834b6067d9ee7d1c5ce7435368915d911",
          "sha1": "c89967116722e0bbf7d8f9bb6cc5945ff386f7a5",
          "md5": "1295540feaca1edb086c29317e3769f7"
        }
      ]
    }
  ]
}
