{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1346955,
          "sha512": "c490ebfb74f145b4a67371fe2e831c11ecd625224ddeeb71a30eb47eb1459b69e82ee1fce5f95598f8453bf2c5aa3cff8ffd51d0319e7560b0ef26f628c15a06",
          "sha256": "6da20c4d285c46f2c9da6bda80d437a69cc9b59bc216bf51774b6df75b9b4999",
          "sha1": "56c28b555f07cdf4ba519b7fd10e3e03e63d3ad2",
          "md5": "db3be9a0ba8b4ab1475ed72d6a3bfa25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1346955,
          "sha512": "c490ebfb74f145b4a67371fe2e831c11ecd625224ddeeb71a30eb47eb1459b69e82ee1fce5f95598f8453bf2c5aa3cff8ffd51d0319e7560b0ef26f628c15a06",
          "sha256": "6da20c4d285c46f2c9da6bda80d437a69cc9b59bc216bf51774b6df75b9b4999",
          "sha1": "56c28b555f07cdf4ba519b7fd10e3e03e63d3ad2",
          "md5": "db3be9a0ba8b4ab1475ed72d6a3bfa25"
        }
      ]
    }
  ]
}
