{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.2.jar",
          "url": "runelite-jshell-4.17.2.jar",
          "size": 26552,
          "sha512": "36cac054f999a72c81957d62dd32825ddc5ef2701c01c412a85d8c26a79dc3c40b699745dda3b3f6faa11b6105a92509b5de1c1fab82f3ed42e8713978d2b979",
          "sha256": "3f58e09da11fc0ef9beedd40819f4094c7f9a8eee77c0a1da6db83a2c36f8361",
          "sha1": "e7e28e1c00beb3a7e0a39271f7239ec7772201f9",
          "md5": "7504c54c04a83850881d1d544d5aec2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.2.jar",
          "url": "runelite-jshell-4.17.2.jar",
          "size": 26552,
          "sha512": "36cac054f999a72c81957d62dd32825ddc5ef2701c01c412a85d8c26a79dc3c40b699745dda3b3f6faa11b6105a92509b5de1c1fab82f3ed42e8713978d2b979",
          "sha256": "3f58e09da11fc0ef9beedd40819f4094c7f9a8eee77c0a1da6db83a2c36f8361",
          "sha1": "e7e28e1c00beb3a7e0a39271f7239ec7772201f9",
          "md5": "7504c54c04a83850881d1d544d5aec2b"
        }
      ]
    }
  ]
}
