{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.2.jar",
          "url": "runelite-jshell-4.17.2.jar",
          "size": 26552,
          "sha512": "1ca9aa132e18a6317adebee96b425d8daa5a804c402d6294c56771fe9c84fcdb17cbaeaeece13cf716f0f68ec5afc47da8d1ec338c9d53f383de89b5a20191bd",
          "sha256": "911c91f0c8d41de6ba778a4580fd63133a66a567aaf4a5dc500745e6854745a2",
          "sha1": "02754113e7916cde4c96082d10b95de7fcde95eb",
          "md5": "81307ebb246d168c5e938cb81e5d442e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.2.jar",
          "url": "runelite-jshell-4.17.2.jar",
          "size": 26552,
          "sha512": "1ca9aa132e18a6317adebee96b425d8daa5a804c402d6294c56771fe9c84fcdb17cbaeaeece13cf716f0f68ec5afc47da8d1ec338c9d53f383de89b5a20191bd",
          "sha256": "911c91f0c8d41de6ba778a4580fd63133a66a567aaf4a5dc500745e6854745a2",
          "sha1": "02754113e7916cde4c96082d10b95de7fcde95eb",
          "md5": "81307ebb246d168c5e938cb81e5d442e"
        }
      ]
    }
  ]
}
