{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.2.jar",
          "url": "runelite-jshell-4.17.2.jar",
          "size": 26552,
          "sha512": "fe216db917a2da6008f9b9d198470e0bb6f3f448239023803faae0b51fddef55ea801c40c1404f0171cd0b5e25eb292ebb250551aef04fb120f1f63010c3cd5f",
          "sha256": "6e92a862b1cfba9ddfecbba218ac4167557db9eca92ddbce58b95c66a1dc33d8",
          "sha1": "d8d8bb955e91b09970bd61af3c3b60b3bd2c4b92",
          "md5": "a4b704632c5d89ffbcbde21e213a1dd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.2.jar",
          "url": "runelite-jshell-4.17.2.jar",
          "size": 26552,
          "sha512": "fe216db917a2da6008f9b9d198470e0bb6f3f448239023803faae0b51fddef55ea801c40c1404f0171cd0b5e25eb292ebb250551aef04fb120f1f63010c3cd5f",
          "sha256": "6e92a862b1cfba9ddfecbba218ac4167557db9eca92ddbce58b95c66a1dc33d8",
          "sha1": "d8d8bb955e91b09970bd61af3c3b60b3bd2c4b92",
          "md5": "a4b704632c5d89ffbcbde21e213a1dd8"
        }
      ]
    }
  ]
}
