{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.23.0.jar",
          "url": "http-api-4.23.0.jar",
          "size": 99206,
          "sha512": "6dcea4317f0b3d89297e3e30d7c25ec32819895ba55984198305f42fb7471af2fb45b6bd8b2cda006c51a1570d8509ff5a92123b08ed2ab6dbcd681153f32f8b",
          "sha256": "f2f6e0f4d6c8d174076ac03ed663ac636368e01362ff28f5bdb6c40d40379691",
          "sha1": "1aca70e05e93ed7e22e455da561a70a9047e9ae7",
          "md5": "f8d072706e86a08f7007b2dd9425e8df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.23.0.jar",
          "url": "http-api-4.23.0.jar",
          "size": 99206,
          "sha512": "6dcea4317f0b3d89297e3e30d7c25ec32819895ba55984198305f42fb7471af2fb45b6bd8b2cda006c51a1570d8509ff5a92123b08ed2ab6dbcd681153f32f8b",
          "sha256": "f2f6e0f4d6c8d174076ac03ed663ac636368e01362ff28f5bdb6c40d40379691",
          "sha1": "1aca70e05e93ed7e22e455da561a70a9047e9ae7",
          "md5": "f8d072706e86a08f7007b2dd9425e8df"
        }
      ]
    }
  ]
}
