{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.23.0.jar",
          "url": "http-api-4.23.0.jar",
          "size": 99207,
          "sha512": "23926725395b40fdb57bc27f0b5126c37de88c004499f419cc04a6f4e236411d181e2f3ab73c1ed60b2cbaea093bb9fbf9270345bd52683552f0a7ef38b3deb7",
          "sha256": "3802690e5ca8e60171ef5016a529169eebf75aabc2b8b91e084c4538ad5486b1",
          "sha1": "f69a8a8204115a9cd0897ff1aff98b5cdfbd144f",
          "md5": "ff268dbfee059242616ea57826638a7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.23.0.jar",
          "url": "http-api-4.23.0.jar",
          "size": 99207,
          "sha512": "23926725395b40fdb57bc27f0b5126c37de88c004499f419cc04a6f4e236411d181e2f3ab73c1ed60b2cbaea093bb9fbf9270345bd52683552f0a7ef38b3deb7",
          "sha256": "3802690e5ca8e60171ef5016a529169eebf75aabc2b8b91e084c4538ad5486b1",
          "sha1": "f69a8a8204115a9cd0897ff1aff98b5cdfbd144f",
          "md5": "ff268dbfee059242616ea57826638a7b"
        }
      ]
    }
  ]
}
