{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.23.0.jar",
          "url": "http-api-4.23.0.jar",
          "size": 99206,
          "sha512": "7b0fe743c843720a0680e8020c938fba2ae8fb3ba682c0a289faaf5ff9e63f2f94ec04c3a819ff59b0e25855e1fa96f253fe5f0cfa33a4aa4aea9eab9dcf8072",
          "sha256": "91879daf3fdfc40159c6663980dfac63d36e500bbb05813d1a88d135ef62b403",
          "sha1": "1dd7a714551c8613e99c26c145ea53406e21704b",
          "md5": "dceba68d7234e3daa6c87def7985bde5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.23.0.jar",
          "url": "http-api-4.23.0.jar",
          "size": 99206,
          "sha512": "7b0fe743c843720a0680e8020c938fba2ae8fb3ba682c0a289faaf5ff9e63f2f94ec04c3a819ff59b0e25855e1fa96f253fe5f0cfa33a4aa4aea9eab9dcf8072",
          "sha256": "91879daf3fdfc40159c6663980dfac63d36e500bbb05813d1a88d135ef62b403",
          "sha1": "1dd7a714551c8613e99c26c145ea53406e21704b",
          "md5": "dceba68d7234e3daa6c87def7985bde5"
        }
      ]
    }
  ]
}
