{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.22.0.jar",
          "url": "http-api-4.22.0.jar",
          "size": 99205,
          "sha512": "a6a55d0762bcdae209fa778c97d7b64e4fc65768bd801e84cbcc1a7c81cd0df5a8dd0bbf990ad4d071e2ed9d60fbddcb13438e25e58d3e0d92c557c6ce47dfdf",
          "sha256": "03043cde61650ca406eaea6e940520cb030075c61b8d39040d39b62b5cec1d82",
          "sha1": "1441fea579cfec2da7479c6b95f45fabd6cd3244",
          "md5": "7e1b3c18c3d194479b1dddbbb4828999"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.22.0.jar",
          "url": "http-api-4.22.0.jar",
          "size": 99205,
          "sha512": "a6a55d0762bcdae209fa778c97d7b64e4fc65768bd801e84cbcc1a7c81cd0df5a8dd0bbf990ad4d071e2ed9d60fbddcb13438e25e58d3e0d92c557c6ce47dfdf",
          "sha256": "03043cde61650ca406eaea6e940520cb030075c61b8d39040d39b62b5cec1d82",
          "sha1": "1441fea579cfec2da7479c6b95f45fabd6cd3244",
          "md5": "7e1b3c18c3d194479b1dddbbb4828999"
        }
      ]
    }
  ]
}
