{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.22.0.jar",
          "url": "http-api-4.22.0.jar",
          "size": 99205,
          "sha512": "d67cb3d8b87716f23af172c3f93d0374b03a1594b4d67be4d1c354952e88ba20f6e6781987197f79c8feb99e542e19ac1a63843d0990437b85b9d5282ef37922",
          "sha256": "a711997c55dfe9ed9ab949b86fdb917bf099d540d33ca76891522eba988a09ea",
          "sha1": "9d8b52026f4299c68cd3bd50e53d9195aa940387",
          "md5": "151e6de3bb8b9869f5b0b3fe927b2882"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.22.0.jar",
          "url": "http-api-4.22.0.jar",
          "size": 99205,
          "sha512": "d67cb3d8b87716f23af172c3f93d0374b03a1594b4d67be4d1c354952e88ba20f6e6781987197f79c8feb99e542e19ac1a63843d0990437b85b9d5282ef37922",
          "sha256": "a711997c55dfe9ed9ab949b86fdb917bf099d540d33ca76891522eba988a09ea",
          "sha1": "9d8b52026f4299c68cd3bd50e53d9195aa940387",
          "md5": "151e6de3bb8b9869f5b0b3fe927b2882"
        }
      ]
    }
  ]
}
