{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.22.0.jar",
          "url": "http-api-4.22.0.jar",
          "size": 99205,
          "sha512": "dfcac44a53eb0558d438bb8c43a367aa64db4ad9559392a39ecc3b629500b6ed205a3a5051312c642561bfb5e33cfd00bca17845eb371eeba85eec0ad3265b70",
          "sha256": "9086a7eda6b9c3c757a1e4858e2348184060872216b77162e39156c4c6c32b99",
          "sha1": "49f3967f970b3511aa83d5cb293c2ec9257f45c6",
          "md5": "cb29d81e46b5b9bce97c90d7c4cd1533"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.22.0.jar",
          "url": "http-api-4.22.0.jar",
          "size": 99205,
          "sha512": "dfcac44a53eb0558d438bb8c43a367aa64db4ad9559392a39ecc3b629500b6ed205a3a5051312c642561bfb5e33cfd00bca17845eb371eeba85eec0ad3265b70",
          "sha256": "9086a7eda6b9c3c757a1e4858e2348184060872216b77162e39156c4c6c32b99",
          "sha1": "49f3967f970b3511aa83d5cb293c2ec9257f45c6",
          "md5": "cb29d81e46b5b9bce97c90d7c4cd1533"
        }
      ]
    }
  ]
}
