{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "8a98f3ef085c910331df22c9db35823e9d00ca2056f9b92c9cd4ad52e4467bc99b827292111bafaf5e068572171f10eb55de5259a727f2cf71b0d948b3778917",
          "sha256": "93f2767b1ad33cd210c32625796ba7bc6dd364b69029b3373c2b4cd8ccf79ad8",
          "sha1": "2b4c58e914dfa1ef2997d2ac087a005ce5fa431a",
          "md5": "9a1618644200e50f151ee44a4113544f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "8a98f3ef085c910331df22c9db35823e9d00ca2056f9b92c9cd4ad52e4467bc99b827292111bafaf5e068572171f10eb55de5259a727f2cf71b0d948b3778917",
          "sha256": "93f2767b1ad33cd210c32625796ba7bc6dd364b69029b3373c2b4cd8ccf79ad8",
          "sha1": "2b4c58e914dfa1ef2997d2ac087a005ce5fa431a",
          "md5": "9a1618644200e50f151ee44a4113544f"
        }
      ]
    }
  ]
}
