{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "1a8e6fb40169b1a54074e3738e935e423e72d98388489552f884b81fc0c401e518d29cc328a92d097ed44e3cfe3dd82d5596719a5e118b505ccd976c58e68200",
          "sha256": "b7a6bb0cd8c5420eb79bd678b502a75da481d480203955c0180ed35ed7744b03",
          "sha1": "fdf08c582d591db64163bcc84c5876926b623478",
          "md5": "a1666b1a7d76606e16dde6fe8c29797b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "1a8e6fb40169b1a54074e3738e935e423e72d98388489552f884b81fc0c401e518d29cc328a92d097ed44e3cfe3dd82d5596719a5e118b505ccd976c58e68200",
          "sha256": "b7a6bb0cd8c5420eb79bd678b502a75da481d480203955c0180ed35ed7744b03",
          "sha1": "fdf08c582d591db64163bcc84c5876926b623478",
          "md5": "a1666b1a7d76606e16dde6fe8c29797b"
        }
      ]
    }
  ]
}
