{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "56stvg6vpff2jn5hcncetngajy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.1.0.jar",
          "url": "http-api-4.1.0.jar",
          "size": 159320,
          "sha512": "83249a10623fba6a9c869d449ddcc57403fffa47dab8b497d08b627e87c5998adbb0b1f71c8400559a0831719f700de286843d042074f67716546e215c455c16",
          "sha256": "c41e09368cb6fd5a191f1c9ed0810b5cbfbaa27b2abd1ed4c0f8a499656fcf84",
          "sha1": "4194a402365f6fe8b1128ffb04f8eda0394feb83",
          "md5": "f622e1c2eebe139b8aada19a6178d550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.1.0.jar",
          "url": "http-api-4.1.0.jar",
          "size": 159320,
          "sha512": "83249a10623fba6a9c869d449ddcc57403fffa47dab8b497d08b627e87c5998adbb0b1f71c8400559a0831719f700de286843d042074f67716546e215c455c16",
          "sha256": "c41e09368cb6fd5a191f1c9ed0810b5cbfbaa27b2abd1ed4c0f8a499656fcf84",
          "sha1": "4194a402365f6fe8b1128ffb04f8eda0394feb83",
          "md5": "f622e1c2eebe139b8aada19a6178d550"
        }
      ]
    }
  ]
}
