{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 136352,
          "sha512": "19e271a23d77b788bbf207d12839ab2dda9cfe4b96b59ce05e6ab26c9e210deef03cb94d2193d50ffb0a3d6ea63c75201484ae270856ed3720cb726de2b5794e",
          "sha256": "0d8f33673975c0af02c9aa5631c6c006dd0818b710392e3ce0cb5afdc0eaea95",
          "sha1": "14997d11a1008f7d3f1bfbaf1fe6ecdbd1717a9e",
          "md5": "3c13b46d47ca7a71dc4f79cf3beb0a2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 136352,
          "sha512": "19e271a23d77b788bbf207d12839ab2dda9cfe4b96b59ce05e6ab26c9e210deef03cb94d2193d50ffb0a3d6ea63c75201484ae270856ed3720cb726de2b5794e",
          "sha256": "0d8f33673975c0af02c9aa5631c6c006dd0818b710392e3ce0cb5afdc0eaea95",
          "sha1": "14997d11a1008f7d3f1bfbaf1fe6ecdbd1717a9e",
          "md5": "3c13b46d47ca7a71dc4f79cf3beb0a2d"
        }
      ]
    }
  ]
}
