{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "4db959b0e296ab89a690cf131e4558c578c6e8830b17b6010ca2d30914cf3fe6cc901a4b003438becca0d882d7d0417050ea054d453f70762f93a240b173e50a",
          "sha256": "b853bcbf9af573bd972eddf667decca9e7577cc76056645e5e214b1f53d05b91",
          "sha1": "b51728dc2016109bf55dbbe8a75ce75d1335b99c",
          "md5": "78de0250f50ef662f1dcd629afe0608c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "4db959b0e296ab89a690cf131e4558c578c6e8830b17b6010ca2d30914cf3fe6cc901a4b003438becca0d882d7d0417050ea054d453f70762f93a240b173e50a",
          "sha256": "b853bcbf9af573bd972eddf667decca9e7577cc76056645e5e214b1f53d05b91",
          "sha1": "b51728dc2016109bf55dbbe8a75ce75d1335b99c",
          "md5": "78de0250f50ef662f1dcd629afe0608c"
        }
      ]
    }
  ]
}
