{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "7cbd379b0a7d91b8831f37971b43331da7caffe304dafe3763e4193a3643c2ef14ecbdcaf29589ba70c4ecb65b468f5a6f9e54eced860fb03f3e70b4b0a277df",
          "sha256": "5dcc734307186dd4743812117330f493b67e9011a1951269bdd2f5e7b9308955",
          "sha1": "8bb7d624d3c3ba861e8d54ff605ac9b505889100",
          "md5": "0527fbef264113086639b48ce697876a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "7cbd379b0a7d91b8831f37971b43331da7caffe304dafe3763e4193a3643c2ef14ecbdcaf29589ba70c4ecb65b468f5a6f9e54eced860fb03f3e70b4b0a277df",
          "sha256": "5dcc734307186dd4743812117330f493b67e9011a1951269bdd2f5e7b9308955",
          "sha1": "8bb7d624d3c3ba861e8d54ff605ac9b505889100",
          "md5": "0527fbef264113086639b48ce697876a"
        }
      ]
    }
  ]
}
