{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "59b68c7f4fb0e529e2f9213a5a50fadface8ac3c870ebcd37ae14868a0f6cbafcb64489b83458883edff3a07df949abc95ad7572b6dceb94961096ede6a62944",
          "sha256": "8b02da01912502efc50f42d1f4eab2c5418e2b33b7e6e22c9bcd3a3bc9ac1bc1",
          "sha1": "40d7e781e1892238e6b8ea37e856bdc1f036983f",
          "md5": "f8021abc6fbdf49a1efb9871dbe7a499"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "59b68c7f4fb0e529e2f9213a5a50fadface8ac3c870ebcd37ae14868a0f6cbafcb64489b83458883edff3a07df949abc95ad7572b6dceb94961096ede6a62944",
          "sha256": "8b02da01912502efc50f42d1f4eab2c5418e2b33b7e6e22c9bcd3a3bc9ac1bc1",
          "sha1": "40d7e781e1892238e6b8ea37e856bdc1f036983f",
          "md5": "f8021abc6fbdf49a1efb9871dbe7a499"
        }
      ]
    }
  ]
}
