{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.5.jar",
          "url": "http-api-4.20.5.jar",
          "size": 99211,
          "sha512": "6c6a146a23eb31954cec3e5d8d9e16205228ef57138764dc0ef78060847bd469c8ec700121946d5cbe3e0f4d4ad403043a77d0266b2a425cdd84f0b03683f1f9",
          "sha256": "46cc8c28d180f8752e79c5b42d501a3f0d638f927c7067545adc769f73108e29",
          "sha1": "6afabb79fa1890227faefce00f7e0dc5fb69bb16",
          "md5": "d0938cee65429fad40d73a4f0875fb5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.5.jar",
          "url": "http-api-4.20.5.jar",
          "size": 99211,
          "sha512": "6c6a146a23eb31954cec3e5d8d9e16205228ef57138764dc0ef78060847bd469c8ec700121946d5cbe3e0f4d4ad403043a77d0266b2a425cdd84f0b03683f1f9",
          "sha256": "46cc8c28d180f8752e79c5b42d501a3f0d638f927c7067545adc769f73108e29",
          "sha1": "6afabb79fa1890227faefce00f7e0dc5fb69bb16",
          "md5": "d0938cee65429fad40d73a4f0875fb5d"
        }
      ]
    }
  ]
}
