{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.5.jar",
          "url": "http-api-4.20.5.jar",
          "size": 99206,
          "sha512": "d93eda0b3d5a59e1aa67873657ae124ef2a81270b05d02946b36b602e329eaa90672c2a58d7f1c92d328a3ef445578cbfae18014b24369463b0a691578f40cd7",
          "sha256": "fb7ed1df522458d37aeec3a94f98b1a083f5b8823282c30bd15845d11eefc78a",
          "sha1": "4945bf18d0f73f8499c8a747f9550f8b8c506c89",
          "md5": "22d534c9a5843fd245d535c14829ce59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.5.jar",
          "url": "http-api-4.20.5.jar",
          "size": 99206,
          "sha512": "d93eda0b3d5a59e1aa67873657ae124ef2a81270b05d02946b36b602e329eaa90672c2a58d7f1c92d328a3ef445578cbfae18014b24369463b0a691578f40cd7",
          "sha256": "fb7ed1df522458d37aeec3a94f98b1a083f5b8823282c30bd15845d11eefc78a",
          "sha1": "4945bf18d0f73f8499c8a747f9550f8b8c506c89",
          "md5": "22d534c9a5843fd245d535c14829ce59"
        }
      ]
    }
  ]
}
