{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "57fda57fa7d738cb2a49a38b405438f32899b2301604afa81f1641673fa4202a3c25eddb869c04290bfada05ae24b38847023d72d16e46c5fb8116ea2e8d40b6",
          "sha256": "b3a8b114ff6cd2870cb79650b5c4e04a3ebb7c898ab8f0ea13704e1291d74fb2",
          "sha1": "2435b8993f0e51f0ac18b3464d18d52681232b3d",
          "md5": "2d0c838336f448c593fb73be2a3c0605"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "57fda57fa7d738cb2a49a38b405438f32899b2301604afa81f1641673fa4202a3c25eddb869c04290bfada05ae24b38847023d72d16e46c5fb8116ea2e8d40b6",
          "sha256": "b3a8b114ff6cd2870cb79650b5c4e04a3ebb7c898ab8f0ea13704e1291d74fb2",
          "sha1": "2435b8993f0e51f0ac18b3464d18d52681232b3d",
          "md5": "2d0c838336f448c593fb73be2a3c0605"
        }
      ]
    }
  ]
}
