{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "1339f907dd466003eec116daca09a491651611017df854e8cc089ac19e73f3d57e17c08d78810678059bd7cd3d698b4b8abf02e244b3fa46ff2f7a2e28af4940",
          "sha256": "9dcebf63bb4a63436e839ded68fb774ca59fcdf684d1bd11ac042c677c89b787",
          "sha1": "fedda990ef2716b2194a7b35d522996a763e0bd9",
          "md5": "b0f196c829d2a9382f3215996999cc47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "1339f907dd466003eec116daca09a491651611017df854e8cc089ac19e73f3d57e17c08d78810678059bd7cd3d698b4b8abf02e244b3fa46ff2f7a2e28af4940",
          "sha256": "9dcebf63bb4a63436e839ded68fb774ca59fcdf684d1bd11ac042c677c89b787",
          "sha1": "fedda990ef2716b2194a7b35d522996a763e0bd9",
          "md5": "b0f196c829d2a9382f3215996999cc47"
        }
      ]
    }
  ]
}
