{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ykvyow6bxjehzhussrimfbumam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.1.0.jar",
          "url": "runescape-api-4.1.0.jar",
          "size": 107731,
          "sha512": "d38ceb1011b2f245434e1f1fbde46f4d1ef7437ea9e754f40aa28395ca71beaaf63e8d52aa0f3861d6ca92b830f59fb53465628763ac48e25dc758a286f63ebc",
          "sha256": "119449cb2caf093bc47d9ef67781b2a325ee066f9406f9effa3671c2c86fa5b5",
          "sha1": "2035a854a1069811b19892a9d507d78877c0cde4",
          "md5": "35cb75cf359b5fc2d6bed0b5a45ba1ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.1.0.jar",
          "url": "runescape-api-4.1.0.jar",
          "size": 107731,
          "sha512": "d38ceb1011b2f245434e1f1fbde46f4d1ef7437ea9e754f40aa28395ca71beaaf63e8d52aa0f3861d6ca92b830f59fb53465628763ac48e25dc758a286f63ebc",
          "sha256": "119449cb2caf093bc47d9ef67781b2a325ee066f9406f9effa3671c2c86fa5b5",
          "sha1": "2035a854a1069811b19892a9d507d78877c0cde4",
          "md5": "35cb75cf359b5fc2d6bed0b5a45ba1ac"
        }
      ]
    }
  ]
}
