{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.0.jar",
          "url": "runelite-jshell-4.25.0.jar",
          "size": 26557,
          "sha512": "8b78e6d445a2030efd6f1f130e3de48651f03cc29c78579645238e8a67890c87fe3b42e967b337b6cbe46fe1bebbaf6236140fdb95008390aec3643bdf7b2889",
          "sha256": "9b5ee97839b0559cafbf748cf1ca46fd2fcd47d53cd77f1f1da07c9bc1c6d38a",
          "sha1": "53751c6932d59cc9cbb726511b474d7c7647670a",
          "md5": "4b1af487f64f47a341d3ddda259ea670"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.0.jar",
          "url": "runelite-jshell-4.25.0.jar",
          "size": 26557,
          "sha512": "8b78e6d445a2030efd6f1f130e3de48651f03cc29c78579645238e8a67890c87fe3b42e967b337b6cbe46fe1bebbaf6236140fdb95008390aec3643bdf7b2889",
          "sha256": "9b5ee97839b0559cafbf748cf1ca46fd2fcd47d53cd77f1f1da07c9bc1c6d38a",
          "sha1": "53751c6932d59cc9cbb726511b474d7c7647670a",
          "md5": "4b1af487f64f47a341d3ddda259ea670"
        }
      ]
    }
  ]
}
