{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.0.jar",
          "url": "runelite-jshell-4.25.0.jar",
          "size": 26557,
          "sha512": "38a21fd16ab5095ed0b83aee8094cec2e2ebec2ed2c494e2c808c697b48b02b6eee965c5a40feb6f855921e0f402a01bd1d2ffb3b13579b14a113fd08d3458c9",
          "sha256": "8cc113bf4edc1f96d3b006cf79c293d2868b4f4d6feac731dc7b56ef170454b5",
          "sha1": "9c2ecad5c80f1f26cdc9b0969461579ca5cb0434",
          "md5": "e0997de6d84d77a2b2963f099e9e7a7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.0.jar",
          "url": "runelite-jshell-4.25.0.jar",
          "size": 26557,
          "sha512": "38a21fd16ab5095ed0b83aee8094cec2e2ebec2ed2c494e2c808c697b48b02b6eee965c5a40feb6f855921e0f402a01bd1d2ffb3b13579b14a113fd08d3458c9",
          "sha256": "8cc113bf4edc1f96d3b006cf79c293d2868b4f4d6feac731dc7b56ef170454b5",
          "sha1": "9c2ecad5c80f1f26cdc9b0969461579ca5cb0434",
          "md5": "e0997de6d84d77a2b2963f099e9e7a7d"
        }
      ]
    }
  ]
}
