{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b52zjzvrcrgw7fp7hwtctbb7oe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.1.0.jar",
          "url": "http-api-4.1.0.jar",
          "size": 159320,
          "sha512": "d621a24d53db96cd5b7e3dbfed1bb7d5b0452e65d3633361588364fe6943f35b9c43b30e130580661db33e5a0fd812f073e42357704347ce97f0abaa14a2d70c",
          "sha256": "c8e9560fa8ad8b0eeb80d2739841a4eb25bdfb0a1a8c0b9b464cbcc4646183d1",
          "sha1": "a89f72f01f21eb71b33bf14a882f8fe49fa0e391",
          "md5": "2fe1ccb6e04b5205072e73a75e8befa3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.1.0.jar",
          "url": "http-api-4.1.0.jar",
          "size": 159320,
          "sha512": "d621a24d53db96cd5b7e3dbfed1bb7d5b0452e65d3633361588364fe6943f35b9c43b30e130580661db33e5a0fd812f073e42357704347ce97f0abaa14a2d70c",
          "sha256": "c8e9560fa8ad8b0eeb80d2739841a4eb25bdfb0a1a8c0b9b464cbcc4646183d1",
          "sha1": "a89f72f01f21eb71b33bf14a882f8fe49fa0e391",
          "md5": "2fe1ccb6e04b5205072e73a75e8befa3"
        }
      ]
    }
  ]
}
