{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "11ab7d475c0b613f1b243fb8db512157257aa0958cf363c73ee4433e173b355bec20e82ae0ff97c8e91c6513bf971f00fe421872bcae2fbec4a8ad14e3829ff5",
          "sha256": "9c4f3c35bca152d639a6b6668f1496ae9758d07b94737166003b728a6272e269",
          "sha1": "025610cda8e1e054eaa1484170606a19cf9e9bd3",
          "md5": "ffa46fb68198a84c278f1cbbc60b5ae5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "11ab7d475c0b613f1b243fb8db512157257aa0958cf363c73ee4433e173b355bec20e82ae0ff97c8e91c6513bf971f00fe421872bcae2fbec4a8ad14e3829ff5",
          "sha256": "9c4f3c35bca152d639a6b6668f1496ae9758d07b94737166003b728a6272e269",
          "sha1": "025610cda8e1e054eaa1484170606a19cf9e9bd3",
          "md5": "ffa46fb68198a84c278f1cbbc60b5ae5"
        }
      ]
    }
  ]
}
