{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99213,
          "sha512": "844775af5f3450130ef3477f14ef03f06c8fa7bcb515e970b6d71f19165a918cff04b76d87f32837c41df233f3b02c74868274560346c4924172307703e88ef2",
          "sha256": "8678bf89ee757ebf1cea02f3b1f4298f422264d5d87682104cb3b36c74b29594",
          "sha1": "a33ae3ae927888a14a063c2a8d4c29bcf930d01e",
          "md5": "9a78f0526976d1483a06e6b86e411ca0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99213,
          "sha512": "844775af5f3450130ef3477f14ef03f06c8fa7bcb515e970b6d71f19165a918cff04b76d87f32837c41df233f3b02c74868274560346c4924172307703e88ef2",
          "sha256": "8678bf89ee757ebf1cea02f3b1f4298f422264d5d87682104cb3b36c74b29594",
          "sha1": "a33ae3ae927888a14a063c2a8d4c29bcf930d01e",
          "md5": "9a78f0526976d1483a06e6b86e411ca0"
        }
      ]
    }
  ]
}
