{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "e2a7826d5b021ed441a0b6776adc41f524e5677060c214113d427c2b0e7e85f6db9306bd8da02f16f5798f378fcc67addb2624766c68558dce2d654f39c7f3c0",
          "sha256": "59f70384b13a3db7b8765d8489be4f04d9d5922a0e7540b785556958dd197dfe",
          "sha1": "a6df2a7670bfcb2ebb9e516e1de05b7767ab200f",
          "md5": "ff546407d854f807414850ee63be062e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "e2a7826d5b021ed441a0b6776adc41f524e5677060c214113d427c2b0e7e85f6db9306bd8da02f16f5798f378fcc67addb2624766c68558dce2d654f39c7f3c0",
          "sha256": "59f70384b13a3db7b8765d8489be4f04d9d5922a0e7540b785556958dd197dfe",
          "sha1": "a6df2a7670bfcb2ebb9e516e1de05b7767ab200f",
          "md5": "ff546407d854f807414850ee63be062e"
        }
      ]
    }
  ]
}
