{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159869,
          "sha512": "2d065bee80a10b7e637e9c605d0c524b223af550154fac8323d08c8a3b465a7b9d933d2262e55c63a911dad501b9a836228865556261363dc41c344af010b038",
          "sha256": "43dbbc026e973aa5a5be741871ffcba4207b9474419d939d12c1780d4cc048dd",
          "sha1": "0cc62ee17b4af0320b96b5e1cfa2d9bc9a242a5a",
          "md5": "69ba1f5e7e4453bb8369ffeb3dc961d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159869,
          "sha512": "2d065bee80a10b7e637e9c605d0c524b223af550154fac8323d08c8a3b465a7b9d933d2262e55c63a911dad501b9a836228865556261363dc41c344af010b038",
          "sha256": "43dbbc026e973aa5a5be741871ffcba4207b9474419d939d12c1780d4cc048dd",
          "sha1": "0cc62ee17b4af0320b96b5e1cfa2d9bc9a242a5a",
          "md5": "69ba1f5e7e4453bb8369ffeb3dc961d2"
        }
      ]
    }
  ]
}
