{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "05f31a0ac2aedc3a979d36d98675f543d1b1a42c5aadc6af462b8aafc6cce20156d5d17c0b528a51ab5888407f9253e0a8a8190fa95ac839ef195b823f27a2bc",
          "sha256": "cdf38dd2179e0d0e51e96881437513e6b317e526509d114ec6fb01d026abc81f",
          "sha1": "7cf06ba9ae2625cb8f5ca216ef41a53d30eb214d",
          "md5": "a4cc2879207ea860927c67bb54b28dcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "05f31a0ac2aedc3a979d36d98675f543d1b1a42c5aadc6af462b8aafc6cce20156d5d17c0b528a51ab5888407f9253e0a8a8190fa95ac839ef195b823f27a2bc",
          "sha256": "cdf38dd2179e0d0e51e96881437513e6b317e526509d114ec6fb01d026abc81f",
          "sha1": "7cf06ba9ae2625cb8f5ca216ef41a53d30eb214d",
          "md5": "a4cc2879207ea860927c67bb54b28dcc"
        }
      ]
    }
  ]
}
