{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "f9a2d8335268eafb8daa0fb6cabc88b3d48a47d67635bb772ebf15852a7e515de6c8d11e6c6e150d78f94532ca282fa6d43807ab336c5382adbe4598cdd64637",
          "sha256": "d1a06919622db14901e13939f0f77cbb19151e310a2da84fbb635dcc69adef74",
          "sha1": "a7cb4a481f8e79314050af3e91648cb66d1516b0",
          "md5": "b0b39edff62bb861e112e7903a37e489"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "f9a2d8335268eafb8daa0fb6cabc88b3d48a47d67635bb772ebf15852a7e515de6c8d11e6c6e150d78f94532ca282fa6d43807ab336c5382adbe4598cdd64637",
          "sha256": "d1a06919622db14901e13939f0f77cbb19151e310a2da84fbb635dcc69adef74",
          "sha1": "a7cb4a481f8e79314050af3e91648cb66d1516b0",
          "md5": "b0b39edff62bb861e112e7903a37e489"
        }
      ]
    }
  ]
}
