{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "2bbb6e46d62f631ce5a135834474ae5c7debcc4637c60931d28eddb60c5c5d54fd45ea2f74c9a4cb86971499111936b074b1c68f9cf617464912f9a6621368df",
          "sha256": "c17e466e1dd7c5bdd486503eaa9252d933138602defa8e122d380c603bed579d",
          "sha1": "cf1c2675c18a684e85782792aae047530e070519",
          "md5": "e7e1b4a9bc3109497066ff01a08b5e60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "2bbb6e46d62f631ce5a135834474ae5c7debcc4637c60931d28eddb60c5c5d54fd45ea2f74c9a4cb86971499111936b074b1c68f9cf617464912f9a6621368df",
          "sha256": "c17e466e1dd7c5bdd486503eaa9252d933138602defa8e122d380c603bed579d",
          "sha1": "cf1c2675c18a684e85782792aae047530e070519",
          "md5": "e7e1b4a9bc3109497066ff01a08b5e60"
        }
      ]
    }
  ]
}
