{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.10.jar",
          "url": "http-api-4.9.10.jar",
          "size": 158533,
          "sha512": "d10b1a6e6adeed281cfe262c48e8d9ac5ff20eec50b79b5019a0cdb75af0b1aa9a87fa7c446484b43e14ad457a82d3a85425fa3243c677fc1a841a1c9605840b",
          "sha256": "ea6c1dd3003e2d198af1ca787568488fc641626b25b93c0d3bd6bcc0b10d1d95",
          "sha1": "30f62668e30626b8994b517c39225a5de121b6f9",
          "md5": "db83ae1bc0e3a4c543307058ceba67c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.10.jar",
          "url": "http-api-4.9.10.jar",
          "size": 158533,
          "sha512": "d10b1a6e6adeed281cfe262c48e8d9ac5ff20eec50b79b5019a0cdb75af0b1aa9a87fa7c446484b43e14ad457a82d3a85425fa3243c677fc1a841a1c9605840b",
          "sha256": "ea6c1dd3003e2d198af1ca787568488fc641626b25b93c0d3bd6bcc0b10d1d95",
          "sha1": "30f62668e30626b8994b517c39225a5de121b6f9",
          "md5": "db83ae1bc0e3a4c543307058ceba67c8"
        }
      ]
    }
  ]
}
