{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.10.jar",
          "url": "http-api-4.9.10.jar",
          "size": 158533,
          "sha512": "800f10d24c557a7a0211199e7828bb4c3a4df7cc8fdc79f7e10552047e64c9dc90a1d5d76f243cc0bb2dfc2e27ebe9274383483fa80332ade56f6771db12f060",
          "sha256": "3d6b7f3d0dcef261338732b7bddd424761335c837a6fa1fceb48aa5af9956c12",
          "sha1": "496510f1a1659b00b239fb1fcc40d839d57da0e5",
          "md5": "8f85f431462126d69ea75a7b85cabcec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.10.jar",
          "url": "http-api-4.9.10.jar",
          "size": 158533,
          "sha512": "800f10d24c557a7a0211199e7828bb4c3a4df7cc8fdc79f7e10552047e64c9dc90a1d5d76f243cc0bb2dfc2e27ebe9274383483fa80332ade56f6771db12f060",
          "sha256": "3d6b7f3d0dcef261338732b7bddd424761335c837a6fa1fceb48aa5af9956c12",
          "sha1": "496510f1a1659b00b239fb1fcc40d839d57da0e5",
          "md5": "8f85f431462126d69ea75a7b85cabcec"
        }
      ]
    }
  ]
}
