{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.0.jar",
          "url": "http-api-4.17.0.jar",
          "size": 136347,
          "sha512": "9fce16396bd410bd10802a073dca0ae73477cee1232472d7dd5740fcbbc9f24eb94cc709fd4e042038f17175bcc4b895f1f255d7d02e5a3fe19e3b855e162445",
          "sha256": "2cbddd68e7726431bd5a26a8a7a2288069f2d7fb550bfd920d75ed7bcb6f7051",
          "sha1": "30ca6eb57cfef85d2ca6c9b1d589c00b05c72d28",
          "md5": "56fd6f2e90d2e38872337f1a15916c01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.0.jar",
          "url": "http-api-4.17.0.jar",
          "size": 136347,
          "sha512": "9fce16396bd410bd10802a073dca0ae73477cee1232472d7dd5740fcbbc9f24eb94cc709fd4e042038f17175bcc4b895f1f255d7d02e5a3fe19e3b855e162445",
          "sha256": "2cbddd68e7726431bd5a26a8a7a2288069f2d7fb550bfd920d75ed7bcb6f7051",
          "sha1": "30ca6eb57cfef85d2ca6c9b1d589c00b05c72d28",
          "md5": "56fd6f2e90d2e38872337f1a15916c01"
        }
      ]
    }
  ]
}
