{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.0.jar",
          "url": "http-api-4.17.0.jar",
          "size": 136347,
          "sha512": "2b938979e6a759e094d8321830cf207065f975363dbf2d2d839ba3431002d02239ca3de48025849583312d5defbf31ca7e14c9b387699b7522e9f113bc760704",
          "sha256": "a4c339bde4691340075096e6fcc6675ef5a28328fe206b8c298befa213e2b344",
          "sha1": "3006cb09afc68dca5fd4c1b49a54528c03d265aa",
          "md5": "db67c08e4fe53bf41259ef13aee3bd71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.0.jar",
          "url": "http-api-4.17.0.jar",
          "size": 136347,
          "sha512": "2b938979e6a759e094d8321830cf207065f975363dbf2d2d839ba3431002d02239ca3de48025849583312d5defbf31ca7e14c9b387699b7522e9f113bc760704",
          "sha256": "a4c339bde4691340075096e6fcc6675ef5a28328fe206b8c298befa213e2b344",
          "sha1": "3006cb09afc68dca5fd4c1b49a54528c03d265aa",
          "md5": "db67c08e4fe53bf41259ef13aee3bd71"
        }
      ]
    }
  ]
}
