{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.0.jar",
          "url": "http-api-4.17.0.jar",
          "size": 136353,
          "sha512": "3011b28f3f68caa46196974fd9eddd5d447860d3b8686d515078d49e321d45ba8a7b50748e5610371adf833a806fc1bfb69d4800f61d64677c02cb33d8a3ab9a",
          "sha256": "61770ec1f435a7d6658ab2a057440e02b16beca54d89f3d9540f3c8ad8951225",
          "sha1": "66b7fe61e354fdf7629419e22a656e5d543c77b2",
          "md5": "78679eacf781cda5f6ae1de80ee65520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.0.jar",
          "url": "http-api-4.17.0.jar",
          "size": 136353,
          "sha512": "3011b28f3f68caa46196974fd9eddd5d447860d3b8686d515078d49e321d45ba8a7b50748e5610371adf833a806fc1bfb69d4800f61d64677c02cb33d8a3ab9a",
          "sha256": "61770ec1f435a7d6658ab2a057440e02b16beca54d89f3d9540f3c8ad8951225",
          "sha1": "66b7fe61e354fdf7629419e22a656e5d543c77b2",
          "md5": "78679eacf781cda5f6ae1de80ee65520"
        }
      ]
    }
  ]
}
