{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "6ea4de1040d45c6de20050812cd1ae0d14da105c58421a8ccb8ee3ed43bf4d107a7fa658a744c44b2d3aa672548223267a7c7d65ee447b1976d5624bc8be853d",
          "sha256": "2ee5829f1e89f9783487b362f4ad91b787f4f998d98d54707bc1f97f2b9add09",
          "sha1": "96009e2b482bfb0567d7f35c7ea513a7934508a3",
          "md5": "d187eadd460771a0286a516f61aaf1f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "6ea4de1040d45c6de20050812cd1ae0d14da105c58421a8ccb8ee3ed43bf4d107a7fa658a744c44b2d3aa672548223267a7c7d65ee447b1976d5624bc8be853d",
          "sha256": "2ee5829f1e89f9783487b362f4ad91b787f4f998d98d54707bc1f97f2b9add09",
          "sha1": "96009e2b482bfb0567d7f35c7ea513a7934508a3",
          "md5": "d187eadd460771a0286a516f61aaf1f5"
        }
      ]
    }
  ]
}
