{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "40f4db181035d4ebf24e62c0b97c7d92ae09e3195e21d58375c96571f31d1e571c37394399d3550dd28ace08fb0486a6dbcaa986990e6032e06e6e28b0720b11",
          "sha256": "6660d11c96be6c988e199bf272ce18db6e82ab76c0f9b66ba35a5e14f714065f",
          "sha1": "db6b28bcde0463f0f4ea90415f3001c731e3e76a",
          "md5": "ffcb5c6cbfe6041407e210c002d82b7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "40f4db181035d4ebf24e62c0b97c7d92ae09e3195e21d58375c96571f31d1e571c37394399d3550dd28ace08fb0486a6dbcaa986990e6032e06e6e28b0720b11",
          "sha256": "6660d11c96be6c988e199bf272ce18db6e82ab76c0f9b66ba35a5e14f714065f",
          "sha1": "db6b28bcde0463f0f4ea90415f3001c731e3e76a",
          "md5": "ffcb5c6cbfe6041407e210c002d82b7d"
        }
      ]
    }
  ]
}
