{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "66c3af3acc01e69b7c71b7f4d9e7f77581921770ab220832fe988d6ae32e712e0298e734ba7ff8012d209f620d9c6ed3e2fe20d26d53cd9be7a3405551e80e01",
          "sha256": "780a02943264db0ea33d5b8212ec0eef3e4729dab98e22cfeaad7cc3d00531fa",
          "sha1": "88ecb859b494b19991dc6f1dcbed802962d54ceb",
          "md5": "e2c89654d13845736c150b6286495df2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.26.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.26.1.jar",
          "url": "runescape-api-4.26.1.jar",
          "size": 150217,
          "sha512": "66c3af3acc01e69b7c71b7f4d9e7f77581921770ab220832fe988d6ae32e712e0298e734ba7ff8012d209f620d9c6ed3e2fe20d26d53cd9be7a3405551e80e01",
          "sha256": "780a02943264db0ea33d5b8212ec0eef3e4729dab98e22cfeaad7cc3d00531fa",
          "sha1": "88ecb859b494b19991dc6f1dcbed802962d54ceb",
          "md5": "e2c89654d13845736c150b6286495df2"
        }
      ]
    }
  ]
}
