{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.10.jar",
          "url": "http-api-4.9.10.jar",
          "size": 158609,
          "sha512": "8e5a013f1d034badc2183788a9a0060bf33389f0ce2f637ba2704ca1da1ad4069eb5b4909b4e1b7db365f23c7060fc1be412606d1b7bbc2cca8e8170c49b24e6",
          "sha256": "d9d4429526cb3f1b945d9d5ca56028703699cf5992560f2f1951b35b681ab876",
          "sha1": "db6baa02fc430081e726d391f06357bad37fc6cc",
          "md5": "9da926e2bed977c66966787a79967f33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.10.jar",
          "url": "http-api-4.9.10.jar",
          "size": 158609,
          "sha512": "8e5a013f1d034badc2183788a9a0060bf33389f0ce2f637ba2704ca1da1ad4069eb5b4909b4e1b7db365f23c7060fc1be412606d1b7bbc2cca8e8170c49b24e6",
          "sha256": "d9d4429526cb3f1b945d9d5ca56028703699cf5992560f2f1951b35b681ab876",
          "sha1": "db6baa02fc430081e726d391f06357bad37fc6cc",
          "md5": "9da926e2bed977c66966787a79967f33"
        }
      ]
    }
  ]
}
