{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.3.jar",
          "url": "runescape-api-4.13.3.jar",
          "size": 143530,
          "sha512": "c97b3c8986c02de4582ccfc171bd8224a226cb6418ffe92feff6c8e4ffed442bfa258a01158c81399409597432554ad6579ffe90cf88e7239e942253a0ed7bf1",
          "sha256": "def75fb932dbf52f606ac695e0237e3ed3a66cba807e858efc3bf2f08585e6b0",
          "sha1": "06eb2395f2dc1177cb890c894a1975a8b4cd8dc5",
          "md5": "f9f53fc768e4fa407343eb0378a8b324"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.3.jar",
          "url": "runescape-api-4.13.3.jar",
          "size": 143530,
          "sha512": "c97b3c8986c02de4582ccfc171bd8224a226cb6418ffe92feff6c8e4ffed442bfa258a01158c81399409597432554ad6579ffe90cf88e7239e942253a0ed7bf1",
          "sha256": "def75fb932dbf52f606ac695e0237e3ed3a66cba807e858efc3bf2f08585e6b0",
          "sha1": "06eb2395f2dc1177cb890c894a1975a8b4cd8dc5",
          "md5": "f9f53fc768e4fa407343eb0378a8b324"
        }
      ]
    }
  ]
}
