{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.3.jar",
          "url": "runescape-api-4.13.3.jar",
          "size": 143530,
          "sha512": "1a24bd907377e6abc6ccaca1c0cbfecc312939c807000ba79cd43737c9374a54660337b29a85c69455162228bcc3ee7ddbd5db154171ffc62e54810e2472c23e",
          "sha256": "17b779d478d0b4ccbbb0d3b6d5b95ec040f3a851eb3dd7709f14b7df8fc2c56a",
          "sha1": "4ee43bab21fee8d2f4ba4c4ae7578fa998760fa3",
          "md5": "1e945fcb0cb2e4157630b9cf2527d1ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.3.jar",
          "url": "runescape-api-4.13.3.jar",
          "size": 143530,
          "sha512": "1a24bd907377e6abc6ccaca1c0cbfecc312939c807000ba79cd43737c9374a54660337b29a85c69455162228bcc3ee7ddbd5db154171ffc62e54810e2472c23e",
          "sha256": "17b779d478d0b4ccbbb0d3b6d5b95ec040f3a851eb3dd7709f14b7df8fc2c56a",
          "sha1": "4ee43bab21fee8d2f4ba4c4ae7578fa998760fa3",
          "md5": "1e945fcb0cb2e4157630b9cf2527d1ca"
        }
      ]
    }
  ]
}
