{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148377,
          "sha512": "c351f2f357aff09e0281c6cdb4de78b93b8748a758cdf7e1e10f6048ebb93b117a5734a8935078924e2b23c45c2ddf014b33ae19cdee2ef953f09f1542c7e2b3",
          "sha256": "b5582090bfd545e3118fd0bad508ee12007180db68fa2d579ff3d5e45c106b1c",
          "sha1": "009144116a513a27a17e0e9381579da8e123b4fb",
          "md5": "958916abd9fbdfaefd6c8af797a73101"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148377,
          "sha512": "c351f2f357aff09e0281c6cdb4de78b93b8748a758cdf7e1e10f6048ebb93b117a5734a8935078924e2b23c45c2ddf014b33ae19cdee2ef953f09f1542c7e2b3",
          "sha256": "b5582090bfd545e3118fd0bad508ee12007180db68fa2d579ff3d5e45c106b1c",
          "sha1": "009144116a513a27a17e0e9381579da8e123b4fb",
          "md5": "958916abd9fbdfaefd6c8af797a73101"
        }
      ]
    }
  ]
}
