{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148377,
          "sha512": "4961c5a5656702b7ce05e8316fddafeb7d0ef37452727f6b59c44b2ef6326aad043d8d12d64b5e13ac1d5da26f9520a9d78d60f449c59b3a83fc21713be617c4",
          "sha256": "c26b0e809659f86b4ed28703e278f8bb57a24ced1c847eb960adebf12a32802b",
          "sha1": "768573f5c94d3e9019324d6cae5cb288b956fd59",
          "md5": "3fbcee206cc6dd9043b77b19d9014f1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148377,
          "sha512": "4961c5a5656702b7ce05e8316fddafeb7d0ef37452727f6b59c44b2ef6326aad043d8d12d64b5e13ac1d5da26f9520a9d78d60f449c59b3a83fc21713be617c4",
          "sha256": "c26b0e809659f86b4ed28703e278f8bb57a24ced1c847eb960adebf12a32802b",
          "sha1": "768573f5c94d3e9019324d6cae5cb288b956fd59",
          "md5": "3fbcee206cc6dd9043b77b19d9014f1e"
        }
      ]
    }
  ]
}
