{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148390,
          "sha512": "2b8e45cf86858ee1b6a30a4916fe84510c6371d4236611e9c213c59b2ff3ccde42a5e0678ac3b6327468b32e5a0b6b4151b76eefa30705e5678c255e6fa97190",
          "sha256": "7ec0d11680575638330c337d36545d3ff291578d17b3c8a5b4f6a141e504b765",
          "sha1": "4d6de49a87de059df7c9817c886d287f7b645ff6",
          "md5": "f475d73ae48a8f95491a7157c56cbdfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148390,
          "sha512": "2b8e45cf86858ee1b6a30a4916fe84510c6371d4236611e9c213c59b2ff3ccde42a5e0678ac3b6327468b32e5a0b6b4151b76eefa30705e5678c255e6fa97190",
          "sha256": "7ec0d11680575638330c337d36545d3ff291578d17b3c8a5b4f6a141e504b765",
          "sha1": "4d6de49a87de059df7c9817c886d287f7b645ff6",
          "md5": "f475d73ae48a8f95491a7157c56cbdfc"
        }
      ]
    }
  ]
}
