{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.8.2.jar",
          "url": "runescape-api-4.8.2.jar",
          "size": 109433,
          "sha512": "c6fa088f6993729892700fb764800206cc2cba3771cbe039ffe5f60230dcbb3052225ab18b14c14ac7d9db4046b591eec684013cce8931e569f60dbea2363446",
          "sha256": "89432c44f72b4de83ed4251a29724108ee12fdb25f942cc1d6d4219234200ac9",
          "sha1": "cab24daa8ee3978cb6ab5cee1514cb9ceda81180",
          "md5": "6c939759979f14d9485e1b73fbb5c91b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.8.2.jar",
          "url": "runescape-api-4.8.2.jar",
          "size": 109433,
          "sha512": "c6fa088f6993729892700fb764800206cc2cba3771cbe039ffe5f60230dcbb3052225ab18b14c14ac7d9db4046b591eec684013cce8931e569f60dbea2363446",
          "sha256": "89432c44f72b4de83ed4251a29724108ee12fdb25f942cc1d6d4219234200ac9",
          "sha1": "cab24daa8ee3978cb6ab5cee1514cb9ceda81180",
          "md5": "6c939759979f14d9485e1b73fbb5c91b"
        }
      ]
    }
  ]
}
