{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "1bcac1ed3f811651273340d34fab2e8470348b1e12105db2837bf2d5f0007c0caa110c5e7941964c73dd6508cbfb4e3664e292a281db97a0e995c06bf0ce776a",
          "sha256": "8565d2b969a901ba600d4291516dd0cf151bf4d30b15557d8d85f8c31cdf4f02",
          "sha1": "9a2831c4788dcc771d87891e19c90a9c6e199e8a",
          "md5": "f5d0a398a7490836e44dcf13916a1d9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "1bcac1ed3f811651273340d34fab2e8470348b1e12105db2837bf2d5f0007c0caa110c5e7941964c73dd6508cbfb4e3664e292a281db97a0e995c06bf0ce776a",
          "sha256": "8565d2b969a901ba600d4291516dd0cf151bf4d30b15557d8d85f8c31cdf4f02",
          "sha1": "9a2831c4788dcc771d87891e19c90a9c6e199e8a",
          "md5": "f5d0a398a7490836e44dcf13916a1d9c"
        }
      ]
    }
  ]
}
