{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "d26dc5fdd18fc5a023cd8e339e405ed6bc26565e983d46cf0d1ae64d0969cdf922f1ae5095b3ed9acc45dc669ec6487db9e9e651160db2c379abe3cad6c120c1",
          "sha256": "bc598e518f51bc08aea217759df8207cea38dd167f2988a70cce2d45d880f44a",
          "sha1": "19897f223d38774ef92d268db15d47909728bb6f",
          "md5": "9f348719453b9de4a0e4a6753631b2be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "d26dc5fdd18fc5a023cd8e339e405ed6bc26565e983d46cf0d1ae64d0969cdf922f1ae5095b3ed9acc45dc669ec6487db9e9e651160db2c379abe3cad6c120c1",
          "sha256": "bc598e518f51bc08aea217759df8207cea38dd167f2988a70cce2d45d880f44a",
          "sha1": "19897f223d38774ef92d268db15d47909728bb6f",
          "md5": "9f348719453b9de4a0e4a6753631b2be"
        }
      ]
    }
  ]
}
