{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.12.1.jar",
          "url": "runelite-api-4.12.1.jar",
          "size": 1288509,
          "sha512": "c620b85d30566b14ba31fd48a48a3a340f18bc30b296cec5bc06e106efae72e8ecc25524bab0019ccdf37ae9bf9349da92cb0932b76dec3a81d1380574c18924",
          "sha256": "02ecc8d8fede25f055536a919f9db87550d194e799383a06fca68bfc23783964",
          "sha1": "dc1e987d7b963753298adf4ba2fd7013002c3551",
          "md5": "c98bcdd497c6f6210e11402b1ae3312d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.12.1.jar",
          "url": "runelite-api-4.12.1.jar",
          "size": 1288509,
          "sha512": "c620b85d30566b14ba31fd48a48a3a340f18bc30b296cec5bc06e106efae72e8ecc25524bab0019ccdf37ae9bf9349da92cb0932b76dec3a81d1380574c18924",
          "sha256": "02ecc8d8fede25f055536a919f9db87550d194e799383a06fca68bfc23783964",
          "sha1": "dc1e987d7b963753298adf4ba2fd7013002c3551",
          "md5": "c98bcdd497c6f6210e11402b1ae3312d"
        }
      ]
    }
  ]
}
