{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fmxxo5pnjfdldmkgdbsss773yi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.5.2.jar",
          "url": "injected-client-3.5.2.jar",
          "size": 2236288,
          "sha512": "453445448d7e9f71823dc7ed8ead925e205dcacd6e5a00999a7b94609fdb624c6e3cac66663edf0516fd7389fabade530a40a0d988ef49dcb6d513a918a92665",
          "sha256": "ee6f86e14bbcd6f7e1d9442223d6ddc17f098232ff557d51d18ecd18207c9e1c",
          "sha1": "ff9b99b3c159e9eccc468ef749c6f4790fbd978a",
          "md5": "6a2a1e33efed403a1bf4bd6d344c2044"
        }
      ]
    }
  ]
}
