{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "c1cf31350059266bfbda438ba01a7b5437ae38f3fcfc814efb036670143445b227606485a7169e05a2df13c068e642f54891d11eb6073915e5125a5ab0e05c0f",
          "sha256": "b8ce1aeb504ca70043d42e380427c94fbf1a0540ce2dde02ec1903a67eecdae3",
          "sha1": "685ad5e57054816e5dae49a75346c90bfe0aceb8",
          "md5": "4715af0bac00203bbc04d6367a02a7e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "c1cf31350059266bfbda438ba01a7b5437ae38f3fcfc814efb036670143445b227606485a7169e05a2df13c068e642f54891d11eb6073915e5125a5ab0e05c0f",
          "sha256": "b8ce1aeb504ca70043d42e380427c94fbf1a0540ce2dde02ec1903a67eecdae3",
          "sha1": "685ad5e57054816e5dae49a75346c90bfe0aceb8",
          "md5": "4715af0bac00203bbc04d6367a02a7e1"
        }
      ]
    }
  ]
}
