{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "c0d7849309650cd960886c541c2cb028e4a50d854dcff6b26c7091017f1e7b6ca9a0fdbb2bbc80b750de7f69387e9783bb339ac8dbcb94deb3f32034887599c1",
          "sha256": "5cbdf1da661945b116b463a733dd578ca41347d852fda810be07bde733926cd9",
          "sha1": "68b83cba99a25e204a89e7ff2580cf6254bb6821",
          "md5": "8680a7221a4695800445f8996b0eb881"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "c0d7849309650cd960886c541c2cb028e4a50d854dcff6b26c7091017f1e7b6ca9a0fdbb2bbc80b750de7f69387e9783bb339ac8dbcb94deb3f32034887599c1",
          "sha256": "5cbdf1da661945b116b463a733dd578ca41347d852fda810be07bde733926cd9",
          "sha1": "68b83cba99a25e204a89e7ff2580cf6254bb6821",
          "md5": "8680a7221a4695800445f8996b0eb881"
        }
      ]
    }
  ]
}
