{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "5f19be010752e1d1ea326d89db79da94d6ed404a177a90938a3a5a7f4a65609ed4278d9c9bc99cf118ca59d907ce138a947f59e1ae7adb810c3a10be86b5f034",
          "sha256": "8ac8c8d34812056d85fe1220c435b099a80aa045f908ccb06ef13c4d55e36fe1",
          "sha1": "3f2967698406c1485fd27244013e7b3eb9fcac8d",
          "md5": "5456fe79abc00ac819e7f6e315ab919e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "5f19be010752e1d1ea326d89db79da94d6ed404a177a90938a3a5a7f4a65609ed4278d9c9bc99cf118ca59d907ce138a947f59e1ae7adb810c3a10be86b5f034",
          "sha256": "8ac8c8d34812056d85fe1220c435b099a80aa045f908ccb06ef13c4d55e36fe1",
          "sha1": "3f2967698406c1485fd27244013e7b3eb9fcac8d",
          "md5": "5456fe79abc00ac819e7f6e315ab919e"
        }
      ]
    }
  ]
}
