{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "39c58d0d2f7eb65740a5ab68bddeb07752b072d47ebf44f3a6d9302edaad3d62e662d673c321c175b19b7180404ca4d568de599c4dabb947032435aec272f10e",
          "sha256": "a4fd4b3e561996bd0386fba5796424319e06dd3b4ba579e79e6aa92910a8ebc0",
          "sha1": "882e1cbeb15148df9a8852c9040a7b0df4a5f8b6",
          "md5": "0c56e98d5ccbe1004c581e5d2ea03a92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "39c58d0d2f7eb65740a5ab68bddeb07752b072d47ebf44f3a6d9302edaad3d62e662d673c321c175b19b7180404ca4d568de599c4dabb947032435aec272f10e",
          "sha256": "a4fd4b3e561996bd0386fba5796424319e06dd3b4ba579e79e6aa92910a8ebc0",
          "sha1": "882e1cbeb15148df9a8852c9040a7b0df4a5f8b6",
          "md5": "0c56e98d5ccbe1004c581e5d2ea03a92"
        }
      ]
    }
  ]
}
