{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "87e3cc9ecf058fc444ee9dffd56d95440f838edc12538765fd88f68b32759683af4178674d11c08c7cba949f3cfabf906fa49ee6d27ff84940968b1e5ae3236a",
          "sha256": "59cd6dd3ac41093568cba1762f2d1a11edcd21656580182f49b06446be40f44b",
          "sha1": "615f38f3f22a22bd0fc237bf8503f5d30729cf48",
          "md5": "847201f7582eb0244a91609be08eb7bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "87e3cc9ecf058fc444ee9dffd56d95440f838edc12538765fd88f68b32759683af4178674d11c08c7cba949f3cfabf906fa49ee6d27ff84940968b1e5ae3236a",
          "sha256": "59cd6dd3ac41093568cba1762f2d1a11edcd21656580182f49b06446be40f44b",
          "sha1": "615f38f3f22a22bd0fc237bf8503f5d30729cf48",
          "md5": "847201f7582eb0244a91609be08eb7bc"
        }
      ]
    }
  ]
}
