{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "6070323f4cda789e67869b70610759f6e09ee2f9ce84ba3b4042111d272d66f159eed525f034e6fb08c33c6f3bd97085f9258933f6642d976fbb24f3dd1f7c9e",
          "sha256": "8645c284171182be1125f446f8d772302a6616196f8e896d33764c2bd5b3dbc9",
          "sha1": "a76bc10015ee7e499b5a08430eaa4092f778ad83",
          "md5": "772db03bc37a08f9f2e0943992bd0970"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "6070323f4cda789e67869b70610759f6e09ee2f9ce84ba3b4042111d272d66f159eed525f034e6fb08c33c6f3bd97085f9258933f6642d976fbb24f3dd1f7c9e",
          "sha256": "8645c284171182be1125f446f8d772302a6616196f8e896d33764c2bd5b3dbc9",
          "sha1": "a76bc10015ee7e499b5a08430eaa4092f778ad83",
          "md5": "772db03bc37a08f9f2e0943992bd0970"
        }
      ]
    }
  ]
}
