{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "a9316a454635d723ce6b9e04fdb5af0c5a650e611fcd125079266172236eb7ef05bfb551e8d5220b9390e0b1e022eb41cc13a8c3ea8459f6440f0aa887f2f240",
          "sha256": "45222e12f64a5a59b74f7b840e991f4728356fa1d1ef6b87ccc1fce98fce592d",
          "sha1": "5dd36fb3ea7f2c6d0b1fe6b2f667a846775a46e4",
          "md5": "3d06636759a604af814202fb8a750a1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "a9316a454635d723ce6b9e04fdb5af0c5a650e611fcd125079266172236eb7ef05bfb551e8d5220b9390e0b1e022eb41cc13a8c3ea8459f6440f0aa887f2f240",
          "sha256": "45222e12f64a5a59b74f7b840e991f4728356fa1d1ef6b87ccc1fce98fce592d",
          "sha1": "5dd36fb3ea7f2c6d0b1fe6b2f667a846775a46e4",
          "md5": "3d06636759a604af814202fb8a750a1f"
        }
      ]
    }
  ]
}
