{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.0.jar",
          "url": "runelite-api-4.18.0.jar",
          "size": 1335313,
          "sha512": "82f26cf86fbea3100e3c59c5e4aa1e457b83f3494aaa43dbc5ceb5141bdc53c4b69bad0bdafdf3c816163f6493a23a8180b418f38ad0260c3bdbbca5cac21117",
          "sha256": "1e5d7e30507282c682269258b12f2f7c27316dadd54c2e77efe03109448a030a",
          "sha1": "b5b94d7edfc440b94e43ab8abe64d7e335f24a7d",
          "md5": "cfb9162300ac589808490d32d77ecc3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.0.jar",
          "url": "runelite-api-4.18.0.jar",
          "size": 1335313,
          "sha512": "82f26cf86fbea3100e3c59c5e4aa1e457b83f3494aaa43dbc5ceb5141bdc53c4b69bad0bdafdf3c816163f6493a23a8180b418f38ad0260c3bdbbca5cac21117",
          "sha256": "1e5d7e30507282c682269258b12f2f7c27316dadd54c2e77efe03109448a030a",
          "sha1": "b5b94d7edfc440b94e43ab8abe64d7e335f24a7d",
          "md5": "cfb9162300ac589808490d32d77ecc3d"
        }
      ]
    }
  ]
}
