{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.0.jar",
          "url": "runelite-api-4.18.0.jar",
          "size": 1335313,
          "sha512": "2634021a8169d4d9fd3b9f0deb058a7bb7889d7926620208c0118deb5a7e6ac43d424074169e9572cd1f9a52761864b7c98bf92f1fe6ad03ad1a842784c4297c",
          "sha256": "70a3a0a3c63a4bbb89185145d4de62b93337f50454504c5a58221fe26efa9f86",
          "sha1": "0f3a7c0695f0085df2315626c854085bb9f5cac3",
          "md5": "8a4173dac280115b8edac74a9e117ae5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.0.jar",
          "url": "runelite-api-4.18.0.jar",
          "size": 1335313,
          "sha512": "2634021a8169d4d9fd3b9f0deb058a7bb7889d7926620208c0118deb5a7e6ac43d424074169e9572cd1f9a52761864b7c98bf92f1fe6ad03ad1a842784c4297c",
          "sha256": "70a3a0a3c63a4bbb89185145d4de62b93337f50454504c5a58221fe26efa9f86",
          "sha1": "0f3a7c0695f0085df2315626c854085bb9f5cac3",
          "md5": "8a4173dac280115b8edac74a9e117ae5"
        }
      ]
    }
  ]
}
