{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.13.jar",
          "url": "runelite-api-4.9.13.jar",
          "size": 1282022,
          "sha512": "be880ed83d1739af3c2ee364d95fb41535c0d78793e3113612c6edd788fce5e71409170f7cff00172c6eae2cdb3159cfc07d20528a3c14fb899987ab92b5d463",
          "sha256": "ca73a7e2a51c2830618ad05b50ba20e9ca9378356092a6ff89f515af70508154",
          "sha1": "b93a9562d80703a8dd8994649eb6defb66f5a760",
          "md5": "3a5e951707843c7033856775f34bd990"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.13.jar",
          "url": "runelite-api-4.9.13.jar",
          "size": 1282022,
          "sha512": "be880ed83d1739af3c2ee364d95fb41535c0d78793e3113612c6edd788fce5e71409170f7cff00172c6eae2cdb3159cfc07d20528a3c14fb899987ab92b5d463",
          "sha256": "ca73a7e2a51c2830618ad05b50ba20e9ca9378356092a6ff89f515af70508154",
          "sha1": "b93a9562d80703a8dd8994649eb6defb66f5a760",
          "md5": "3a5e951707843c7033856775f34bd990"
        }
      ]
    }
  ]
}
