{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.1.jar",
          "url": "runelite-jshell-4.17.1.jar",
          "size": 26552,
          "sha512": "c6ae67d5cbe661db7e393d55f9fd5e6f4b6fcbb67ec8f9a55d23bbe7124d661404e8013060aee7611728b90a1592e9e650fecf0ceaee797f205da9ceaadda973",
          "sha256": "4add0aa9f6b28308bf7883be07a33a2851df42a7b6b30dbe1380cb2477a278c0",
          "sha1": "f03919dd6135059c578d6c1c66a076c6a564af8e",
          "md5": "ec94cb3c0b27171e2861bdf20fd50d63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.1.jar",
          "url": "runelite-jshell-4.17.1.jar",
          "size": 26552,
          "sha512": "c6ae67d5cbe661db7e393d55f9fd5e6f4b6fcbb67ec8f9a55d23bbe7124d661404e8013060aee7611728b90a1592e9e650fecf0ceaee797f205da9ceaadda973",
          "sha256": "4add0aa9f6b28308bf7883be07a33a2851df42a7b6b30dbe1380cb2477a278c0",
          "sha1": "f03919dd6135059c578d6c1c66a076c6a564af8e",
          "md5": "ec94cb3c0b27171e2861bdf20fd50d63"
        }
      ]
    }
  ]
}
