{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.1.jar",
          "url": "runelite-jshell-4.17.1.jar",
          "size": 26552,
          "sha512": "70898c59a7e413fde5bc1c4338c8d573103b611408f8175431b90ee5246c8d07ca1b371b5c1d0fad09d10cd352b9624bbf0fecbda12e779dc5ad3ed57889b1f5",
          "sha256": "a6f6749381286aea3710f9fe2dd13de4fd8f99e7f734870e5a2da9a8c1ee686c",
          "sha1": "4b2614ff6ad3eaa58b0e269626882452110a0fa7",
          "md5": "440fe44b7d94a58eec5e8da9ab133fc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.1.jar",
          "url": "runelite-jshell-4.17.1.jar",
          "size": 26552,
          "sha512": "70898c59a7e413fde5bc1c4338c8d573103b611408f8175431b90ee5246c8d07ca1b371b5c1d0fad09d10cd352b9624bbf0fecbda12e779dc5ad3ed57889b1f5",
          "sha256": "a6f6749381286aea3710f9fe2dd13de4fd8f99e7f734870e5a2da9a8c1ee686c",
          "sha1": "4b2614ff6ad3eaa58b0e269626882452110a0fa7",
          "md5": "440fe44b7d94a58eec5e8da9ab133fc2"
        }
      ]
    }
  ]
}
