{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.1.jar",
          "url": "runelite-jshell-4.17.1.jar",
          "size": 26552,
          "sha512": "303a49bf96f39ac8cc70b6c56c121ab1d39617afd8d5e70ddc6c0c8d859acc64f438daebedb51558b43fe410b5b4d397bcb467ee1f807cf39d6e2411cc1ca5f5",
          "sha256": "9a176092f6810f71cb61707867609ffacd46da896386f8f5ba375f92edad4aba",
          "sha1": "0c7d085c9a04bb45d91dae260e24c4c5c6022859",
          "md5": "f0883581446575213ae03026c0f13a9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.1.jar",
          "url": "runelite-jshell-4.17.1.jar",
          "size": 26552,
          "sha512": "303a49bf96f39ac8cc70b6c56c121ab1d39617afd8d5e70ddc6c0c8d859acc64f438daebedb51558b43fe410b5b4d397bcb467ee1f807cf39d6e2411cc1ca5f5",
          "sha256": "9a176092f6810f71cb61707867609ffacd46da896386f8f5ba375f92edad4aba",
          "sha1": "0c7d085c9a04bb45d91dae260e24c4c5c6022859",
          "md5": "f0883581446575213ae03026c0f13a9f"
        }
      ]
    }
  ]
}
