{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.2.jar",
          "url": "runescape-api-4.15.2.jar",
          "size": 143795,
          "sha512": "90ff303db17a938833c5c998c0cac5442335ec1bf578d27c994754587d8c15ea31f6809f249cb95e99cd9427253cb59a10a28a46e92f7df463bf95f18a2ffdd0",
          "sha256": "5106745e5c8612d0d7b3338c5b8af3ec37cf5e52bc2df3835161a63cef6242ab",
          "sha1": "d1a511419f3eae468720e1799a7fdf38f32f2f7c",
          "md5": "84bc2529a72e82b916804cf5a3db01ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.2.jar",
          "url": "runescape-api-4.15.2.jar",
          "size": 143795,
          "sha512": "90ff303db17a938833c5c998c0cac5442335ec1bf578d27c994754587d8c15ea31f6809f249cb95e99cd9427253cb59a10a28a46e92f7df463bf95f18a2ffdd0",
          "sha256": "5106745e5c8612d0d7b3338c5b8af3ec37cf5e52bc2df3835161a63cef6242ab",
          "sha1": "d1a511419f3eae468720e1799a7fdf38f32f2f7c",
          "md5": "84bc2529a72e82b916804cf5a3db01ee"
        }
      ]
    }
  ]
}
