{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.2.jar",
          "url": "runescape-api-4.15.2.jar",
          "size": 143795,
          "sha512": "baa44b338368c0fc0c8251f84b84e052c54370595bb218a6d371d3d619bd7c95ebf280f95b6a0b867a5376eafd155065b8c4126bb04d884b0091ab7fe0599dbb",
          "sha256": "cf5746111cde4affd4cf9fe2db3d4cc75823c7544458b88e87b0e2a77fa94ce3",
          "sha1": "55676b3a1158c4e3effdc9e1f133625b1f0a17d2",
          "md5": "a574894d08108e8a3821ddec7fe2a194"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.2.jar",
          "url": "runescape-api-4.15.2.jar",
          "size": 143795,
          "sha512": "baa44b338368c0fc0c8251f84b84e052c54370595bb218a6d371d3d619bd7c95ebf280f95b6a0b867a5376eafd155065b8c4126bb04d884b0091ab7fe0599dbb",
          "sha256": "cf5746111cde4affd4cf9fe2db3d4cc75823c7544458b88e87b0e2a77fa94ce3",
          "sha1": "55676b3a1158c4e3effdc9e1f133625b1f0a17d2",
          "md5": "a574894d08108e8a3821ddec7fe2a194"
        }
      ]
    }
  ]
}
