{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.2.jar",
          "url": "runescape-api-4.15.2.jar",
          "size": 143795,
          "sha512": "58b6a622f21d888ad63077f97805dcebd90f04170ef3d3b681104d97cab99807bfce56f7dafb28c3f274a822e4cf98d58957371ff645bf8dbd8c1e655e7d2176",
          "sha256": "65584697aac3e86c6a4c129901d2145b5ddcd57c51dc0009c845ccbf611362f1",
          "sha1": "b8e8e9c2fdf21a588eb2f7ef3968edb06b05d1dc",
          "md5": "15dbc3947be948ea11a334927f6a508b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.2.jar",
          "url": "runescape-api-4.15.2.jar",
          "size": 143795,
          "sha512": "58b6a622f21d888ad63077f97805dcebd90f04170ef3d3b681104d97cab99807bfce56f7dafb28c3f274a822e4cf98d58957371ff645bf8dbd8c1e655e7d2176",
          "sha256": "65584697aac3e86c6a4c129901d2145b5ddcd57c51dc0009c845ccbf611362f1",
          "sha1": "b8e8e9c2fdf21a588eb2f7ef3968edb06b05d1dc",
          "md5": "15dbc3947be948ea11a334927f6a508b"
        }
      ]
    }
  ]
}
