{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146551,
          "sha512": "ec9d2aacaeb15a4106da2c538e4944fa47111e9c402afe2343d72cc0e784b30481b81151c8d49fd452dae18507e4af1f85a570719ca7e0816b51555a66a09707",
          "sha256": "35cda7d9fce11c3841771a636c6c45915eacffa6792d91c11654f029bcfa696c",
          "sha1": "6c7b5f726eccc16b7a0e2811873c59572deffb05",
          "md5": "d54012a51e785db2d0d0f2cba73808a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146551,
          "sha512": "ec9d2aacaeb15a4106da2c538e4944fa47111e9c402afe2343d72cc0e784b30481b81151c8d49fd452dae18507e4af1f85a570719ca7e0816b51555a66a09707",
          "sha256": "35cda7d9fce11c3841771a636c6c45915eacffa6792d91c11654f029bcfa696c",
          "sha1": "6c7b5f726eccc16b7a0e2811873c59572deffb05",
          "md5": "d54012a51e785db2d0d0f2cba73808a7"
        }
      ]
    }
  ]
}
