{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.2.jar",
          "url": "http-api-4.17.2.jar",
          "size": 99203,
          "sha512": "123a18217c87102cc652f4a2a1918e69162323a353cc6076ea5d1d9cd141696e33a98e0d00b5b3569db3efb4645bae6c7d63074b0acda96de0edb112dd03dd7e",
          "sha256": "fc7073aab8d393eb721a8514befdc380034e5afd593e6b6753c0d688c8a146c3",
          "sha1": "0bcee5af9e0a63010f22aa8528b8476937455cad",
          "md5": "04915146f48c55b9e17d43476f17e373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.2.jar",
          "url": "http-api-4.17.2.jar",
          "size": 99203,
          "sha512": "123a18217c87102cc652f4a2a1918e69162323a353cc6076ea5d1d9cd141696e33a98e0d00b5b3569db3efb4645bae6c7d63074b0acda96de0edb112dd03dd7e",
          "sha256": "fc7073aab8d393eb721a8514befdc380034e5afd593e6b6753c0d688c8a146c3",
          "sha1": "0bcee5af9e0a63010f22aa8528b8476937455cad",
          "md5": "04915146f48c55b9e17d43476f17e373"
        }
      ]
    }
  ]
}
