{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.2.jar",
          "url": "http-api-4.17.2.jar",
          "size": 99210,
          "sha512": "7f56897dc329a79c6eb841e85cc473ef4143ac0ab66e44627062eedd8647e1bc2f1869e3746c8122fb6514ebd6c404981adb621b8795dcc4e24029ef5edf774d",
          "sha256": "f2f57d4d26a70e4a7999c00f35a01c276381cb2ba26d54a415062e0a6b755928",
          "sha1": "0695e5b169f38cbf8873c22743089a00d6c57a16",
          "md5": "f93f70d34202919fe856b5ded1a9403f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.2.jar",
          "url": "http-api-4.17.2.jar",
          "size": 99210,
          "sha512": "7f56897dc329a79c6eb841e85cc473ef4143ac0ab66e44627062eedd8647e1bc2f1869e3746c8122fb6514ebd6c404981adb621b8795dcc4e24029ef5edf774d",
          "sha256": "f2f57d4d26a70e4a7999c00f35a01c276381cb2ba26d54a415062e0a6b755928",
          "sha1": "0695e5b169f38cbf8873c22743089a00d6c57a16",
          "md5": "f93f70d34202919fe856b5ded1a9403f"
        }
      ]
    }
  ]
}
