{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.2.jar",
          "url": "http-api-4.17.2.jar",
          "size": 99203,
          "sha512": "a2a7083a35bd8eecfeea31a50e9afd23f7b6babd5f2fe916248eb659f52429a524a9d1c343d7164f4cd84c33aa4e712aa39583f71932a392ee49ba002c4a8ac1",
          "sha256": "8c98223861fa53a5ee9266f0fb4ec9e60000728eba8acaaf8df9a2fa58f0675a",
          "sha1": "73c5e2970d44d2d1d5c022dbfb950ede6c8548a8",
          "md5": "9d04d559ad52cbcd30f69303dddf83bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.2.jar",
          "url": "http-api-4.17.2.jar",
          "size": 99203,
          "sha512": "a2a7083a35bd8eecfeea31a50e9afd23f7b6babd5f2fe916248eb659f52429a524a9d1c343d7164f4cd84c33aa4e712aa39583f71932a392ee49ba002c4a8ac1",
          "sha256": "8c98223861fa53a5ee9266f0fb4ec9e60000728eba8acaaf8df9a2fa58f0675a",
          "sha1": "73c5e2970d44d2d1d5c022dbfb950ede6c8548a8",
          "md5": "9d04d559ad52cbcd30f69303dddf83bf"
        }
      ]
    }
  ]
}
