{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.0.jar",
          "url": "runelite-api-4.13.0.jar",
          "size": 1332566,
          "sha512": "a54f599ac37eb037d373b5dd5de575f691182ffd866cbb41049eff86a70fd3e9411066c642f034ff4c989d085031cd8ba98b78819b4b19bb6b6ed98cfeee0ef1",
          "sha256": "9cc28e9b9d307002c5c3bd7946fc2fd57768817fce4b4169c76c9d41a6b5897a",
          "sha1": "9a7fd25468aa305274f2627c3285b497763479fe",
          "md5": "07239879b9809320c38a643c2d0f2ee0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.0.jar",
          "url": "runelite-api-4.13.0.jar",
          "size": 1332566,
          "sha512": "a54f599ac37eb037d373b5dd5de575f691182ffd866cbb41049eff86a70fd3e9411066c642f034ff4c989d085031cd8ba98b78819b4b19bb6b6ed98cfeee0ef1",
          "sha256": "9cc28e9b9d307002c5c3bd7946fc2fd57768817fce4b4169c76c9d41a6b5897a",
          "sha1": "9a7fd25468aa305274f2627c3285b497763479fe",
          "md5": "07239879b9809320c38a643c2d0f2ee0"
        }
      ]
    }
  ]
}
