{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335004,
          "sha512": "230c1e4715335dd55360bd1d15f99f8b25b7e8db8bd3d4f0993a44267cd5cebd5b65d27e3332f92014446b77e253527cbbdfe6181810e47a46ae0b292dd3da38",
          "sha256": "d325e51aceb24b1aa89f794d90d7fcc9d622b3b24ad9c6a18060fc682030fb14",
          "sha1": "0bbb6b40aad728e54838fb3416bb662b686e6504",
          "md5": "dfc75f832fed788565e39608b580bf63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335004,
          "sha512": "230c1e4715335dd55360bd1d15f99f8b25b7e8db8bd3d4f0993a44267cd5cebd5b65d27e3332f92014446b77e253527cbbdfe6181810e47a46ae0b292dd3da38",
          "sha256": "d325e51aceb24b1aa89f794d90d7fcc9d622b3b24ad9c6a18060fc682030fb14",
          "sha1": "0bbb6b40aad728e54838fb3416bb662b686e6504",
          "md5": "dfc75f832fed788565e39608b580bf63"
        }
      ]
    }
  ]
}
