{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335036,
          "sha512": "4b90a8bb74da2de8d7d07535f58d243d6e217dd8c4390c3f1e4de5fc2c4eb3048f7f1204f8612132d497e88eb503986379f63687822928feaf22df62dd192e83",
          "sha256": "bcbde3fae3905f1dc7a766d4385ea70e9678240df448e24370ee2a9fd6ff069e",
          "sha1": "41fb11682d36810f945a5794d45dffac0442b0ab",
          "md5": "b6de36835fe350fd8ad4482fa5231724"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335036,
          "sha512": "4b90a8bb74da2de8d7d07535f58d243d6e217dd8c4390c3f1e4de5fc2c4eb3048f7f1204f8612132d497e88eb503986379f63687822928feaf22df62dd192e83",
          "sha256": "bcbde3fae3905f1dc7a766d4385ea70e9678240df448e24370ee2a9fd6ff069e",
          "sha1": "41fb11682d36810f945a5794d45dffac0442b0ab",
          "md5": "b6de36835fe350fd8ad4482fa5231724"
        }
      ]
    }
  ]
}
