{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335023,
          "sha512": "ccfdd023dd3becfe4a3d1e595069fba2a38c7026856bd9bcfa1b2dc4aef0c5202e0a52fd95e0f1cd59740dfaea21212134a48ae92c3649d5226f3986dedcf4c4",
          "sha256": "32f31d80fd1d92e32982cf9f6eec64f0d0bbb1aea6b97284cf61671e7a8fecaf",
          "sha1": "c1c5c6e6d416283e5ad47476cf39df1507eebe92",
          "md5": "cc606cdd621df711909f287c3ef0c8d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335023,
          "sha512": "ccfdd023dd3becfe4a3d1e595069fba2a38c7026856bd9bcfa1b2dc4aef0c5202e0a52fd95e0f1cd59740dfaea21212134a48ae92c3649d5226f3986dedcf4c4",
          "sha256": "32f31d80fd1d92e32982cf9f6eec64f0d0bbb1aea6b97284cf61671e7a8fecaf",
          "sha1": "c1c5c6e6d416283e5ad47476cf39df1507eebe92",
          "md5": "cc606cdd621df711909f287c3ef0c8d7"
        }
      ]
    }
  ]
}
