{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.22.0.jar",
          "url": "runelite-api-4.22.0.jar",
          "size": 1357236,
          "sha512": "e6f5078b2faf4bddcadf6747466fd73efbcb2a0e3dd474cfccc81b7cc0936cc6b0dcfea674933b618ebc2d3eba296ce1c26a4d77e3031dbca581142c2e411cb4",
          "sha256": "dfca150dde76cf3444be0ef74b27889dcd775724a9eb05d285a5dd5b3870e3bb",
          "sha1": "7011c2eef726090ca1f0077377144b9c9a2ba622",
          "md5": "38ab1f91d38d2e82e9b647cff5e30028"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.22.0.jar",
          "url": "runelite-api-4.22.0.jar",
          "size": 1357236,
          "sha512": "e6f5078b2faf4bddcadf6747466fd73efbcb2a0e3dd474cfccc81b7cc0936cc6b0dcfea674933b618ebc2d3eba296ce1c26a4d77e3031dbca581142c2e411cb4",
          "sha256": "dfca150dde76cf3444be0ef74b27889dcd775724a9eb05d285a5dd5b3870e3bb",
          "sha1": "7011c2eef726090ca1f0077377144b9c9a2ba622",
          "md5": "38ab1f91d38d2e82e9b647cff5e30028"
        }
      ]
    }
  ]
}
