{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.22.0.jar",
          "url": "runelite-api-4.22.0.jar",
          "size": 1357236,
          "sha512": "d2c9fc465225bec5e65baa0081ece482533044f9c472e865326fbbcf2e6a4b8151b6392e4b7686386042b5880b25f6c9b459d06d54f7cd74a95fc554e2deeb1f",
          "sha256": "ab8609ecfe8f79269f44ac800290252d0f5bea92794d1805c0a0c73d81eda589",
          "sha1": "2b2c9cee52cbad774f6ff14b6df603c7934122b9",
          "md5": "fbb32ebfffc0d24775d8f8c9ecd4b5b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.22.0.jar",
          "url": "runelite-api-4.22.0.jar",
          "size": 1357236,
          "sha512": "d2c9fc465225bec5e65baa0081ece482533044f9c472e865326fbbcf2e6a4b8151b6392e4b7686386042b5880b25f6c9b459d06d54f7cd74a95fc554e2deeb1f",
          "sha256": "ab8609ecfe8f79269f44ac800290252d0f5bea92794d1805c0a0c73d81eda589",
          "sha1": "2b2c9cee52cbad774f6ff14b6df603c7934122b9",
          "md5": "fbb32ebfffc0d24775d8f8c9ecd4b5b8"
        }
      ]
    }
  ]
}
