{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.22.0.jar",
          "url": "runelite-api-4.22.0.jar",
          "size": 1357236,
          "sha512": "bc3123fb3bcbefc43a0a86e4d58a7e3349f8c191d5443f364644569e3be5e5ea1d95fbe6fcc712c7a98218f51484ccfb9ce67b3710a4d1aa40bd0d977f2f5563",
          "sha256": "62b115a392c6ca883e864df3055a945c7953137524319eb7513c9a47c233c067",
          "sha1": "781595def05cb33e5fcfe996bd173ad79243166f",
          "md5": "85320f3b3d14aeee5182c9b026470e3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.22.0.jar",
          "url": "runelite-api-4.22.0.jar",
          "size": 1357236,
          "sha512": "bc3123fb3bcbefc43a0a86e4d58a7e3349f8c191d5443f364644569e3be5e5ea1d95fbe6fcc712c7a98218f51484ccfb9ce67b3710a4d1aa40bd0d977f2f5563",
          "sha256": "62b115a392c6ca883e864df3055a945c7953137524319eb7513c9a47c233c067",
          "sha1": "781595def05cb33e5fcfe996bd173ad79243166f",
          "md5": "85320f3b3d14aeee5182c9b026470e3d"
        }
      ]
    }
  ]
}
