{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.9.6.jar",
          "url": "runelite-jshell-4.9.6.jar",
          "size": 22948,
          "sha512": "9b471fbdaa8bef62c76cffe74e41d4ca862b683a8296973a043b50cd64e022fcaab5f268b1ab8f2e199b3216f4d0c7577079eb04147305869d91b04b10770d77",
          "sha256": "eaf5e6c19b8e08816c17156c4b0e8a874e8de211454c757cb9400b42e71a24a9",
          "sha1": "4547b5e7b127e784e29973737f4abb2b5a3c4f2f",
          "md5": "77466c023802bca00cb32a808b949355"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.9.6.jar",
          "url": "runelite-jshell-4.9.6.jar",
          "size": 22948,
          "sha512": "9b471fbdaa8bef62c76cffe74e41d4ca862b683a8296973a043b50cd64e022fcaab5f268b1ab8f2e199b3216f4d0c7577079eb04147305869d91b04b10770d77",
          "sha256": "eaf5e6c19b8e08816c17156c4b0e8a874e8de211454c757cb9400b42e71a24a9",
          "sha1": "4547b5e7b127e784e29973737f4abb2b5a3c4f2f",
          "md5": "77466c023802bca00cb32a808b949355"
        }
      ]
    }
  ]
}
