{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158715,
          "sha512": "972eb0a9177d76b26c3c6f08a83bde7b10a806806dd9ebc0138079f70481193ba850c76797bee23b3c4b60383c325bd563cfffcfb552fcace846cb683ba2de83",
          "sha256": "1db76dfd7136c511914a68f86982aae75f52bff49d55ec8a1133af08e0e09154",
          "sha1": "6223eb697e963ff15c737b0bc65434a46e5c33ae",
          "md5": "222b82ae93a35ba7d853c8589c8aebdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158715,
          "sha512": "972eb0a9177d76b26c3c6f08a83bde7b10a806806dd9ebc0138079f70481193ba850c76797bee23b3c4b60383c325bd563cfffcfb552fcace846cb683ba2de83",
          "sha256": "1db76dfd7136c511914a68f86982aae75f52bff49d55ec8a1133af08e0e09154",
          "sha1": "6223eb697e963ff15c737b0bc65434a46e5c33ae",
          "md5": "222b82ae93a35ba7d853c8589c8aebdc"
        }
      ]
    }
  ]
}
