{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158715,
          "sha512": "aa2e19a1c9ea4ce37f1dca2846e736a1cce2564a436c03da7c8c4b5b9a1d628908a02a685d17b45b65aa9eb0e368ca307bd4a7db1c4ba181b46886fb3f955f89",
          "sha256": "58f7a2cc42fc3f73ba11a8a0cc332bcb171e67ff7051358a1e5ca673ac968097",
          "sha1": "8fcb4937ee941cbd055a5d656bf94fa960a3f9ed",
          "md5": "b978911d4fe8a1a87ab4147ffa92e345"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158715,
          "sha512": "aa2e19a1c9ea4ce37f1dca2846e736a1cce2564a436c03da7c8c4b5b9a1d628908a02a685d17b45b65aa9eb0e368ca307bd4a7db1c4ba181b46886fb3f955f89",
          "sha256": "58f7a2cc42fc3f73ba11a8a0cc332bcb171e67ff7051358a1e5ca673ac968097",
          "sha1": "8fcb4937ee941cbd055a5d656bf94fa960a3f9ed",
          "md5": "b978911d4fe8a1a87ab4147ffa92e345"
        }
      ]
    }
  ]
}
