{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "bf98a56aa53e4ecd864f11d4530cb601a3e67e8e0b935a4e49b90225632f56aee0d30c3145e84460350d7a36fbae9603fc415ead39d34f182fe2e04a2e20b47b",
          "sha256": "7b2cada7d035c4b2675b4abf8518c14d4cb9c49fa4929226c451f537b67eec63",
          "sha1": "3c0099e87be016fdd919db64bad2e089a57e213f",
          "md5": "18e1bf1e64c1e0676258e011746cf2fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "bf98a56aa53e4ecd864f11d4530cb601a3e67e8e0b935a4e49b90225632f56aee0d30c3145e84460350d7a36fbae9603fc415ead39d34f182fe2e04a2e20b47b",
          "sha256": "7b2cada7d035c4b2675b4abf8518c14d4cb9c49fa4929226c451f537b67eec63",
          "sha1": "3c0099e87be016fdd919db64bad2e089a57e213f",
          "md5": "18e1bf1e64c1e0676258e011746cf2fe"
        }
      ]
    }
  ]
}
