{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "c11611867483ffd45747f012fb5e28c0df3cf08a4cf6bac87f9306d9045dd4c13ec9552626e2d7d2d1051898225d7082dcec12ae3e590a21b669db1317460a79",
          "sha256": "cc5e995a2de4aa56c55fc0520b7854a5835a06ccb1db99e3eed95c53f7d80a69",
          "sha1": "9098de1328a65e4d4a6bd719bf8f7b535e4a9b93",
          "md5": "a6fd2d9d6a1c78c9976f46fe1450755b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "c11611867483ffd45747f012fb5e28c0df3cf08a4cf6bac87f9306d9045dd4c13ec9552626e2d7d2d1051898225d7082dcec12ae3e590a21b669db1317460a79",
          "sha256": "cc5e995a2de4aa56c55fc0520b7854a5835a06ccb1db99e3eed95c53f7d80a69",
          "sha1": "9098de1328a65e4d4a6bd719bf8f7b535e4a9b93",
          "md5": "a6fd2d9d6a1c78c9976f46fe1450755b"
        }
      ]
    }
  ]
}
