{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "b8e73cda36f02b87123fe4363de57af4ca601516dc52c0eb9fe9c86b4669bd7ba94f66adab66c620fe63e05c9714a9e792139e0876b3c444211c938fd65934da",
          "sha256": "4a1beb7ecafee3959d416844451304b9ff72bfc56db3e591b5896fc8a36f57cc",
          "sha1": "864b1daece385d8ddd42e16ac1a809e2e779e747",
          "md5": "a8f11c83d9278662908e34f80bdc596e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "b8e73cda36f02b87123fe4363de57af4ca601516dc52c0eb9fe9c86b4669bd7ba94f66adab66c620fe63e05c9714a9e792139e0876b3c444211c938fd65934da",
          "sha256": "4a1beb7ecafee3959d416844451304b9ff72bfc56db3e591b5896fc8a36f57cc",
          "sha1": "864b1daece385d8ddd42e16ac1a809e2e779e747",
          "md5": "a8f11c83d9278662908e34f80bdc596e"
        }
      ]
    }
  ]
}
