{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "fdf035ef2143c346dda55903bc16abe5fa14ca89e4d7ce6b1000dea2fad70ffa11e124e9f011a108ccc02fb2aa83f45b77382a135d11db8b7d3a61330dbf57a5",
          "sha256": "c9df1000ad38c572525bf51fdab6f684ab3796e9fd179ac5413a4924f0e9400e",
          "sha1": "07d7377a2d533a1048bdee28b05f9f689b7f818f",
          "md5": "0499b2da802df9c84e8abf329a328e0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "fdf035ef2143c346dda55903bc16abe5fa14ca89e4d7ce6b1000dea2fad70ffa11e124e9f011a108ccc02fb2aa83f45b77382a135d11db8b7d3a61330dbf57a5",
          "sha256": "c9df1000ad38c572525bf51fdab6f684ab3796e9fd179ac5413a4924f0e9400e",
          "sha1": "07d7377a2d533a1048bdee28b05f9f689b7f818f",
          "md5": "0499b2da802df9c84e8abf329a328e0a"
        }
      ]
    }
  ]
}
