{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "b277c7415199781dff83a6f2d7b7bd3bd05b5e52ae31eb226d925769410c5c75a01cb21fad5e4f8cdad77448b40b0104064cacbac0d757a08d7298523818aebd",
          "sha256": "6ccfcd180c2d32e347b43e346ed06d2e7711ad8268b5686bd476e324c81da65c",
          "sha1": "6df22fc359261fed843f1fb3f826da8a4c6c932a",
          "md5": "4f5de0fddea2afb5ddbfb083a81291ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "b277c7415199781dff83a6f2d7b7bd3bd05b5e52ae31eb226d925769410c5c75a01cb21fad5e4f8cdad77448b40b0104064cacbac0d757a08d7298523818aebd",
          "sha256": "6ccfcd180c2d32e347b43e346ed06d2e7711ad8268b5686bd476e324c81da65c",
          "sha1": "6df22fc359261fed843f1fb3f826da8a4c6c932a",
          "md5": "4f5de0fddea2afb5ddbfb083a81291ee"
        }
      ]
    }
  ]
}
