{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "1da1b2e252cf1efb37d350a3566dc28ba3becfe7d5ebb0b8eb5a1628573fd73cb62ab8a30b72bebce5fa64119fe1350126797945f141f19d33d3aa2451f10074",
          "sha256": "f9d73e8b9193122dd239982ee30ae948a8dfa012dcc317edaa03112a16318e50",
          "sha1": "47105c15570732c483d164260a1a4cea1409f509",
          "md5": "387cceb7cd4d2d5318d0c44b0e750b61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "1da1b2e252cf1efb37d350a3566dc28ba3becfe7d5ebb0b8eb5a1628573fd73cb62ab8a30b72bebce5fa64119fe1350126797945f141f19d33d3aa2451f10074",
          "sha256": "f9d73e8b9193122dd239982ee30ae948a8dfa012dcc317edaa03112a16318e50",
          "sha1": "47105c15570732c483d164260a1a4cea1409f509",
          "md5": "387cceb7cd4d2d5318d0c44b0e750b61"
        }
      ]
    }
  ]
}
