{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.24.1.jar",
          "url": "runelite-api-4.24.1.jar",
          "size": 1346817,
          "sha512": "1160faaeca788057930293a9eeea05c873d8a2e227794772211706ef6f79d90325b081a548a692cc47392dc1dbbc4359100fffc767f90deaa82807bdad00b872",
          "sha256": "1ecf2e6287855e3d881598f22d38f09570bbebdb1f602f8c9bcb86d13f645176",
          "sha1": "557f920f8890629233c8f2bd3d37772e086aae7b",
          "md5": "7d77ad320db8c9864090466f247e29d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.24.1.jar",
          "url": "runelite-api-4.24.1.jar",
          "size": 1346817,
          "sha512": "1160faaeca788057930293a9eeea05c873d8a2e227794772211706ef6f79d90325b081a548a692cc47392dc1dbbc4359100fffc767f90deaa82807bdad00b872",
          "sha256": "1ecf2e6287855e3d881598f22d38f09570bbebdb1f602f8c9bcb86d13f645176",
          "sha1": "557f920f8890629233c8f2bd3d37772e086aae7b",
          "md5": "7d77ad320db8c9864090466f247e29d2"
        }
      ]
    }
  ]
}
