{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.24.1.jar",
          "url": "runelite-api-4.24.1.jar",
          "size": 1346781,
          "sha512": "79b18df7ae9fff74af697e5662fd83a75dcf02245e3a057e9ca291c46d181cb472e0d08af41bb96af0a81ab8f53020375243096f299fe6c4ae206fb2d4e77daf",
          "sha256": "daeda46a89cb067146804171c49b7b9e64344333e5026c1a87bd74de4500265b",
          "sha1": "facf39664e2b4cf802de9654158de93adb57a1a5",
          "md5": "26183b243bc2b6dbb7d04c44a49c0f4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.24.1.jar",
          "url": "runelite-api-4.24.1.jar",
          "size": 1346781,
          "sha512": "79b18df7ae9fff74af697e5662fd83a75dcf02245e3a057e9ca291c46d181cb472e0d08af41bb96af0a81ab8f53020375243096f299fe6c4ae206fb2d4e77daf",
          "sha256": "daeda46a89cb067146804171c49b7b9e64344333e5026c1a87bd74de4500265b",
          "sha1": "facf39664e2b4cf802de9654158de93adb57a1a5",
          "md5": "26183b243bc2b6dbb7d04c44a49c0f4b"
        }
      ]
    }
  ]
}
