{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "a3656ddb0c148de48bd002078e4fe9cb68c42b24cae838780b9f7b620d993a42167f86feaed427e786bb8a23b9ad2868a27456e66f708bbc8668da0438c5f1f2",
          "sha256": "b5a13fca771fb1562325f8710131a9e169c1adbb65a2dfcb3ab136c905be2d48",
          "sha1": "2e9c4c21f407b69f9aaf4be9b62d05392e311588",
          "md5": "772f2124a0b51862083aa8ea430444d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "a3656ddb0c148de48bd002078e4fe9cb68c42b24cae838780b9f7b620d993a42167f86feaed427e786bb8a23b9ad2868a27456e66f708bbc8668da0438c5f1f2",
          "sha256": "b5a13fca771fb1562325f8710131a9e169c1adbb65a2dfcb3ab136c905be2d48",
          "sha1": "2e9c4c21f407b69f9aaf4be9b62d05392e311588",
          "md5": "772f2124a0b51862083aa8ea430444d4"
        }
      ]
    }
  ]
}
