{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "aab524d5f32ea8e11a1c61553478ccb42f62eed84fb5a81a28c3235212442dada8366637a01d0f56bcf69b965fd4a6a5eea973fb8673415cd01d040058788718",
          "sha256": "1ec45a60dc899b39fcd3211167822c73d98f0a10622354e913ff0ab1247d5ae0",
          "sha1": "095c5d8908fd704f0a52185240543095ed6dadab",
          "md5": "cf8662cad3f7d9b03eef8bc70f658cd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "aab524d5f32ea8e11a1c61553478ccb42f62eed84fb5a81a28c3235212442dada8366637a01d0f56bcf69b965fd4a6a5eea973fb8673415cd01d040058788718",
          "sha256": "1ec45a60dc899b39fcd3211167822c73d98f0a10622354e913ff0ab1247d5ae0",
          "sha1": "095c5d8908fd704f0a52185240543095ed6dadab",
          "md5": "cf8662cad3f7d9b03eef8bc70f658cd2"
        }
      ]
    }
  ]
}
