{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "3e364a654d2b79da1d0b5687b5268b0dca967ad48ead1c77dae74182071b76af8e916fa4a8febc3b63e8239a837497da7bfa50be4796e73519e9af394cb4d186",
          "sha256": "3f56c3dfca2d848f4e77927219757c8f9d7cb32ab2b58e3efc1eb316c0dfe407",
          "sha1": "9e69597000f2a325ceec5c363084607861027c02",
          "md5": "4102ab113ac5d49c03d54b76e403c153"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "3e364a654d2b79da1d0b5687b5268b0dca967ad48ead1c77dae74182071b76af8e916fa4a8febc3b63e8239a837497da7bfa50be4796e73519e9af394cb4d186",
          "sha256": "3f56c3dfca2d848f4e77927219757c8f9d7cb32ab2b58e3efc1eb316c0dfe407",
          "sha1": "9e69597000f2a325ceec5c363084607861027c02",
          "md5": "4102ab113ac5d49c03d54b76e403c153"
        }
      ]
    }
  ]
}
