{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.4.jar",
          "url": "runelite-jshell-4.20.4.jar",
          "size": 26557,
          "sha512": "5b5b83a21b0af1813c1ce0f5ea2f58bde6c0691f5e2854b1a1495909cdd5dc395622bbd3d4560805de9fdb1ca098639a71f18b2ca330a03422960796d0ed4f80",
          "sha256": "4987b25fa0d09d7cf2ecfe38ca807081397736283b033a37136111ce0fc5fbc2",
          "sha1": "19263f0217acc1e8f8af84f582abf52a2fe76c1d",
          "md5": "5d81dad3415c16645179fda903dd0429"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.4.jar",
          "url": "runelite-jshell-4.20.4.jar",
          "size": 26557,
          "sha512": "5b5b83a21b0af1813c1ce0f5ea2f58bde6c0691f5e2854b1a1495909cdd5dc395622bbd3d4560805de9fdb1ca098639a71f18b2ca330a03422960796d0ed4f80",
          "sha256": "4987b25fa0d09d7cf2ecfe38ca807081397736283b033a37136111ce0fc5fbc2",
          "sha1": "19263f0217acc1e8f8af84f582abf52a2fe76c1d",
          "md5": "5d81dad3415c16645179fda903dd0429"
        }
      ]
    }
  ]
}
