{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.1.jar",
          "url": "runescape-api-4.15.1.jar",
          "size": 143795,
          "sha512": "3af1a4a7d3ddea5d8f05aacde4dda6dc7ff522d59634b7a2d6600daf9f7f077d1ea48c4a3cefe277a55fe5c35631b538e27a1590cef34390dab714afe2d560f4",
          "sha256": "0c46bcb4dd3f8f73ddbc5d2ea6a25c64197be22fd16b1c0a2f05458b659a9ff0",
          "sha1": "5eb468576cc6b03fa920a0e60f80da4c20ba8319",
          "md5": "f8f46349fe5b79d57c6d8df0897e215f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.1.jar",
          "url": "runescape-api-4.15.1.jar",
          "size": 143795,
          "sha512": "3af1a4a7d3ddea5d8f05aacde4dda6dc7ff522d59634b7a2d6600daf9f7f077d1ea48c4a3cefe277a55fe5c35631b538e27a1590cef34390dab714afe2d560f4",
          "sha256": "0c46bcb4dd3f8f73ddbc5d2ea6a25c64197be22fd16b1c0a2f05458b659a9ff0",
          "sha1": "5eb468576cc6b03fa920a0e60f80da4c20ba8319",
          "md5": "f8f46349fe5b79d57c6d8df0897e215f"
        }
      ]
    }
  ]
}
