{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.1.jar",
          "url": "runescape-api-4.15.1.jar",
          "size": 143795,
          "sha512": "0b51ab40b963feebcb7e58049defb748f70e62e75872a9175b7f9fe4016d11740efd0f0b7dbf2dbb40a864e290229016d9c091a4c20b567bde9404de9afce208",
          "sha256": "0ec0ed454b0bd91e326615d4d87a4f7b145fc45163ee345766abc5a740cdb17d",
          "sha1": "6a51ac05ae951e20b48f72750af2892fdcad4fbe",
          "md5": "11b6f1d01f9e784fc07fe3bed42c2bf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.1.jar",
          "url": "runescape-api-4.15.1.jar",
          "size": 143795,
          "sha512": "0b51ab40b963feebcb7e58049defb748f70e62e75872a9175b7f9fe4016d11740efd0f0b7dbf2dbb40a864e290229016d9c091a4c20b567bde9404de9afce208",
          "sha256": "0ec0ed454b0bd91e326615d4d87a4f7b145fc45163ee345766abc5a740cdb17d",
          "sha1": "6a51ac05ae951e20b48f72750af2892fdcad4fbe",
          "md5": "11b6f1d01f9e784fc07fe3bed42c2bf3"
        }
      ]
    }
  ]
}
