{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.1.jar",
          "url": "runescape-api-4.15.1.jar",
          "size": 143795,
          "sha512": "14b3ffe0a318dcc17f453921c9e97fa9273173e38a4b7210b234015ed540d1b3aaf1f102e6e68f009605d17620f7aab954561bf4add9aa01b555390018438ac8",
          "sha256": "be5519101b19f675d3879d4bb8780f00bdcdc839170d2453e87cbdb9d410fa16",
          "sha1": "51d298ab1ac9f04933227e1f0c668eb54c7ebf3a",
          "md5": "bbf828e53f5cd8f818e17c0d80d1e079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.1.jar",
          "url": "runescape-api-4.15.1.jar",
          "size": 143795,
          "sha512": "14b3ffe0a318dcc17f453921c9e97fa9273173e38a4b7210b234015ed540d1b3aaf1f102e6e68f009605d17620f7aab954561bf4add9aa01b555390018438ac8",
          "sha256": "be5519101b19f675d3879d4bb8780f00bdcdc839170d2453e87cbdb9d410fa16",
          "sha1": "51d298ab1ac9f04933227e1f0c668eb54c7ebf3a",
          "md5": "bbf828e53f5cd8f818e17c0d80d1e079"
        }
      ]
    }
  ]
}
