{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "l7dewzmt7vaftih4err3rq2aka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.2.0.jar",
          "url": "runelite-api-4.2.0.jar",
          "size": 1252986,
          "sha512": "312f1c36438a4655a1c61604cc38594444cbc6d14138e07b5f8e8805e50c299ad6663d70774184cf5604cc07fcc2b499e2c11f7a440da43571d2038beedeaec0",
          "sha256": "5b923e5730f8ca535f9474fb4c44ea73ffae7468f0a82b7b87fa7c66ae8a1ea9",
          "sha1": "6c85f3732bcd02b55e5f6068b8b7274fe925904a",
          "md5": "b22c664d2a8d50b59ef5be82fbf26ca6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.2.0.jar",
          "url": "runelite-api-4.2.0.jar",
          "size": 1252986,
          "sha512": "312f1c36438a4655a1c61604cc38594444cbc6d14138e07b5f8e8805e50c299ad6663d70774184cf5604cc07fcc2b499e2c11f7a440da43571d2038beedeaec0",
          "sha256": "5b923e5730f8ca535f9474fb4c44ea73ffae7468f0a82b7b87fa7c66ae8a1ea9",
          "sha1": "6c85f3732bcd02b55e5f6068b8b7274fe925904a",
          "md5": "b22c664d2a8d50b59ef5be82fbf26ca6"
        }
      ]
    }
  ]
}
