{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.4.jar",
          "url": "runelite-jshell-4.15.4.jar",
          "size": 26552,
          "sha512": "caca9addd1da5cad61826765b111ec213d1ecaaaa4f8f26cd9cbed81a2a6621f585cd880d22565627bda7cbd5c03c017df489d4301930e70a9c8a87d038dd888",
          "sha256": "f1530f4e704fe1721193a5dd35ea220e37ba076ae2d462cda35454396cf058b9",
          "sha1": "be574a28f97577b56b659e99b0d5e2f8304d5e73",
          "md5": "5f2391b5503db4f47b87f65004ec9730"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.4.jar",
          "url": "runelite-jshell-4.15.4.jar",
          "size": 26552,
          "sha512": "caca9addd1da5cad61826765b111ec213d1ecaaaa4f8f26cd9cbed81a2a6621f585cd880d22565627bda7cbd5c03c017df489d4301930e70a9c8a87d038dd888",
          "sha256": "f1530f4e704fe1721193a5dd35ea220e37ba076ae2d462cda35454396cf058b9",
          "sha1": "be574a28f97577b56b659e99b0d5e2f8304d5e73",
          "md5": "5f2391b5503db4f47b87f65004ec9730"
        }
      ]
    }
  ]
}
