{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.4.jar",
          "url": "runelite-jshell-4.15.4.jar",
          "size": 26552,
          "sha512": "e55be920b81a7d01d3cb40f1cc86970548da4bcac30123294b413182a54be79a8eef6a097fb62630235b5ccbcf24738d963247d991d100318527dd8afcd7200f",
          "sha256": "ed643d1bbe6a2b4cdec9ec690046e4ba91d1cbd4472ec0caa3dfbc277ac6823b",
          "sha1": "26b0ac086479fbf85732de4c8fe8f93db61aa513",
          "md5": "9fb69ce2addb816434ea72531ba089a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.4.jar",
          "url": "runelite-jshell-4.15.4.jar",
          "size": 26552,
          "sha512": "e55be920b81a7d01d3cb40f1cc86970548da4bcac30123294b413182a54be79a8eef6a097fb62630235b5ccbcf24738d963247d991d100318527dd8afcd7200f",
          "sha256": "ed643d1bbe6a2b4cdec9ec690046e4ba91d1cbd4472ec0caa3dfbc277ac6823b",
          "sha1": "26b0ac086479fbf85732de4c8fe8f93db61aa513",
          "md5": "9fb69ce2addb816434ea72531ba089a2"
        }
      ]
    }
  ]
}
