{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.4.jar",
          "url": "runelite-jshell-4.15.4.jar",
          "size": 26552,
          "sha512": "c53d5e0673feca1877063896295d0262c9f2732d3a170f23ef20413bf22769c1a2efa0f10bf982911ccbb1f8a23dec456353ca687abada3da275890c8053a539",
          "sha256": "494670cacc7b344ad38e127f05fdc640bc99589ce0353aabafdf957cce6df9cc",
          "sha1": "9a985f5623f295e53cb63b9d86d5af54a67967c4",
          "md5": "6b05f7dd0b1b1f7bf59a4f34ad04ad5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.4.jar",
          "url": "runelite-jshell-4.15.4.jar",
          "size": 26552,
          "sha512": "c53d5e0673feca1877063896295d0262c9f2732d3a170f23ef20413bf22769c1a2efa0f10bf982911ccbb1f8a23dec456353ca687abada3da275890c8053a539",
          "sha256": "494670cacc7b344ad38e127f05fdc640bc99589ce0353aabafdf957cce6df9cc",
          "sha1": "9a985f5623f295e53cb63b9d86d5af54a67967c4",
          "md5": "6b05f7dd0b1b1f7bf59a4f34ad04ad5f"
        }
      ]
    }
  ]
}
