{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149546,
          "sha512": "a421dc35f323cc4b54c8d59c80d6f5a88e5a3903ede24151029623fe9f66e60b88f359f672f2a8df69729eedcae93bc4ba35d24a7d1d82fe9548293db7ae59e6",
          "sha256": "9872c9835b008ad13bfc32ea7259721a12b3b9fbb70815d38658819f713ac3cb",
          "sha1": "85f8db2e9b57a309548abf2b93af062be0e4788f",
          "md5": "1384fa8aefe4028fed680f325b491799"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149546,
          "sha512": "a421dc35f323cc4b54c8d59c80d6f5a88e5a3903ede24151029623fe9f66e60b88f359f672f2a8df69729eedcae93bc4ba35d24a7d1d82fe9548293db7ae59e6",
          "sha256": "9872c9835b008ad13bfc32ea7259721a12b3b9fbb70815d38658819f713ac3cb",
          "sha1": "85f8db2e9b57a309548abf2b93af062be0e4788f",
          "md5": "1384fa8aefe4028fed680f325b491799"
        }
      ]
    }
  ]
}
