{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.2.jar",
          "url": "runescape-api-4.17.2.jar",
          "size": 146486,
          "sha512": "203820f1aa77e1a1fff5af52102afc6ec759e8b4f9868e616f557919cf503ab58b40dd6b19acdb184938e484b1c0902bc39fb2ce236a3165bba25e447a3d214f",
          "sha256": "d1107c74cef41aca397beb50c16ddb60a335751defb5ece62c5e19b1e21bebe7",
          "sha1": "131cf1c0143124ab2f84ce5d0561c5e2402454d8",
          "md5": "ecf710e328ab78e88736058041516bd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.2.jar",
          "url": "runescape-api-4.17.2.jar",
          "size": 146486,
          "sha512": "203820f1aa77e1a1fff5af52102afc6ec759e8b4f9868e616f557919cf503ab58b40dd6b19acdb184938e484b1c0902bc39fb2ce236a3165bba25e447a3d214f",
          "sha256": "d1107c74cef41aca397beb50c16ddb60a335751defb5ece62c5e19b1e21bebe7",
          "sha1": "131cf1c0143124ab2f84ce5d0561c5e2402454d8",
          "md5": "ecf710e328ab78e88736058041516bd8"
        }
      ]
    }
  ]
}
