{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.16.0.jar",
          "url": "runelite-jshell-4.16.0.jar",
          "size": 26552,
          "sha512": "5a4c87d640bea7647c18900080188df84bc0268a0e77fd2471cdc08b6343a2a11feb1acd6ef6997bed67ef2fb41fba30cde332b709cfcbd719a91c441ffe068e",
          "sha256": "90a1ce47de1d89a93ef736ffadcf1c641c0fc5d7e695e95683e3a24481e86940",
          "sha1": "e872c7ca4a12f733e4d9bf0638c7052782831937",
          "md5": "f012e8f98e3e9aae16c66b1b5e1f808d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.16.0.jar",
          "url": "runelite-jshell-4.16.0.jar",
          "size": 26552,
          "sha512": "5a4c87d640bea7647c18900080188df84bc0268a0e77fd2471cdc08b6343a2a11feb1acd6ef6997bed67ef2fb41fba30cde332b709cfcbd719a91c441ffe068e",
          "sha256": "90a1ce47de1d89a93ef736ffadcf1c641c0fc5d7e695e95683e3a24481e86940",
          "sha1": "e872c7ca4a12f733e4d9bf0638c7052782831937",
          "md5": "f012e8f98e3e9aae16c66b1b5e1f808d"
        }
      ]
    }
  ]
}
