{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.16.0.jar",
          "url": "runelite-jshell-4.16.0.jar",
          "size": 26552,
          "sha512": "948ed99868d356dc36432433c558071a011a47c7fcf35d3d10f0bfa22aa80082100a4a9d1f57420e44262e4df0ffc9e277d508dff115c3740b8fc823f05fbdc8",
          "sha256": "de97909f03164f7c0c95d1adb73124034dd948a15d14cc77d9ffa5c7c4e1cf2b",
          "sha1": "07b667604ce3d2ff78b38260976bf34b70a067de",
          "md5": "da2c01b0beb892ad3697bc5c190645b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.16.0.jar",
          "url": "runelite-jshell-4.16.0.jar",
          "size": 26552,
          "sha512": "948ed99868d356dc36432433c558071a011a47c7fcf35d3d10f0bfa22aa80082100a4a9d1f57420e44262e4df0ffc9e277d508dff115c3740b8fc823f05fbdc8",
          "sha256": "de97909f03164f7c0c95d1adb73124034dd948a15d14cc77d9ffa5c7c4e1cf2b",
          "sha1": "07b667604ce3d2ff78b38260976bf34b70a067de",
          "md5": "da2c01b0beb892ad3697bc5c190645b6"
        }
      ]
    }
  ]
}
