{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.14.0.jar",
          "url": "http-api-4.14.0.jar",
          "size": 172802,
          "sha512": "40831862b82686256c46761c1321d3946450710bd4fcf79c6981b2c370a9a29e5d10ee2f5a8287ef80747c6118e98d2ca2ad57c58df91bfaa8280728531982ce",
          "sha256": "7275aad66edb41a9afb78832e0c93d6f930dce0de0c1872dc70d4db8d12afd6f",
          "sha1": "7de4440fd8141554b610c6e0cc2e77b3a757ddc8",
          "md5": "e39e7f025303c33734c1dee7baf98f4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.14.0.jar",
          "url": "http-api-4.14.0.jar",
          "size": 172802,
          "sha512": "40831862b82686256c46761c1321d3946450710bd4fcf79c6981b2c370a9a29e5d10ee2f5a8287ef80747c6118e98d2ca2ad57c58df91bfaa8280728531982ce",
          "sha256": "7275aad66edb41a9afb78832e0c93d6f930dce0de0c1872dc70d4db8d12afd6f",
          "sha1": "7de4440fd8141554b610c6e0cc2e77b3a757ddc8",
          "md5": "e39e7f025303c33734c1dee7baf98f4f"
        }
      ]
    }
  ]
}
