{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.14.0.jar",
          "url": "http-api-4.14.0.jar",
          "size": 172791,
          "sha512": "184f60c8c4953328125f52f9aab7f30d5cc4560d33dd93b34917a04d55319ec25ae8a66dca4483e2f64b5e7465ccf035fa5455d9406fd5d27584dc8bab75efe5",
          "sha256": "f6d0f0e0cdfefdbc3ecfc30419898f10aec19a3d756b2d07784e301906c7ebe1",
          "sha1": "647d84f357068cf839a9ee2c684c0b5c7da58258",
          "md5": "6b6bd24ce1c04908e743a126c58abe12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.14.0.jar",
          "url": "http-api-4.14.0.jar",
          "size": 172791,
          "sha512": "184f60c8c4953328125f52f9aab7f30d5cc4560d33dd93b34917a04d55319ec25ae8a66dca4483e2f64b5e7465ccf035fa5455d9406fd5d27584dc8bab75efe5",
          "sha256": "f6d0f0e0cdfefdbc3ecfc30419898f10aec19a3d756b2d07784e301906c7ebe1",
          "sha1": "647d84f357068cf839a9ee2c684c0b5c7da58258",
          "md5": "6b6bd24ce1c04908e743a126c58abe12"
        }
      ]
    }
  ]
}
