{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.14.0.jar",
          "url": "http-api-4.14.0.jar",
          "size": 172802,
          "sha512": "db40e87363aa19911950385cc5fb4b89e489eed4357df2dce7546ae2ea4fd9ccdb878b856e2043eb1c4a0947490f5925ee8932798a85cee9d4db621f8318033b",
          "sha256": "9109d52f313678724e0d8b36e584c6d61c6802ddbdd18c324b6a18d54e4a9c12",
          "sha1": "c17073cdc2df96965a2a7f4f0847c188ecd1a6e2",
          "md5": "c99b952f7f7e0561d7627a0996ab8487"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.14.0.jar",
          "url": "http-api-4.14.0.jar",
          "size": 172802,
          "sha512": "db40e87363aa19911950385cc5fb4b89e489eed4357df2dce7546ae2ea4fd9ccdb878b856e2043eb1c4a0947490f5925ee8932798a85cee9d4db621f8318033b",
          "sha256": "9109d52f313678724e0d8b36e584c6d61c6802ddbdd18c324b6a18d54e4a9c12",
          "sha1": "c17073cdc2df96965a2a7f4f0847c188ecd1a6e2",
          "md5": "c99b952f7f7e0561d7627a0996ab8487"
        }
      ]
    }
  ]
}
