{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.4.jar",
          "url": "runelite-jshell-4.20.4.jar",
          "size": 26557,
          "sha512": "16f7b5b8c29e8eeee29ba4ad4f7af25fc872fe649e25fc2f4eeb3eaa5af1e6eb944e0d220d1fd269be92193b8ff483aa933982ebbacbf22a8983f2b300f5d71e",
          "sha256": "529f15b0d7ef1c679672ae357ac2e08a4398d7f90cf3be65f5e1143e9a4492b7",
          "sha1": "43e408bb78a43ca724c29a563554cce9d5c4b6c6",
          "md5": "512a694232e6fbfc531426c1b193fbf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.4.jar",
          "url": "runelite-jshell-4.20.4.jar",
          "size": 26557,
          "sha512": "16f7b5b8c29e8eeee29ba4ad4f7af25fc872fe649e25fc2f4eeb3eaa5af1e6eb944e0d220d1fd269be92193b8ff483aa933982ebbacbf22a8983f2b300f5d71e",
          "sha256": "529f15b0d7ef1c679672ae357ac2e08a4398d7f90cf3be65f5e1143e9a4492b7",
          "sha1": "43e408bb78a43ca724c29a563554cce9d5c4b6c6",
          "md5": "512a694232e6fbfc531426c1b193fbf8"
        }
      ]
    }
  ]
}
