{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "e78bd7f35c801bd0297ecb764a8fb7f358fa4cff887ea107e32443fa67ce8b0a55beb32fac60fc638495ce3ed8604bbb71e9e477f74e6ba5d6b508890dde41ff",
          "sha256": "d6da313354719fe950b739d2ac5feb26339f23d1eda07dc60fdd5a6de201347a",
          "sha1": "448fbe98a583a6e62d23ff932fb4b4dffcbb6f0d",
          "md5": "621e322997b78b910d83e27c33a05267"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "e78bd7f35c801bd0297ecb764a8fb7f358fa4cff887ea107e32443fa67ce8b0a55beb32fac60fc638495ce3ed8604bbb71e9e477f74e6ba5d6b508890dde41ff",
          "sha256": "d6da313354719fe950b739d2ac5feb26339f23d1eda07dc60fdd5a6de201347a",
          "sha1": "448fbe98a583a6e62d23ff932fb4b4dffcbb6f0d",
          "md5": "621e322997b78b910d83e27c33a05267"
        }
      ]
    }
  ]
}
