{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "09411c333a4aa2ecc8e0a5b96c096ec3f152567558aac4561a0da8dd1160ddafe2502ea13eaecf7a6854a9ca9994b5562b24bccd768560e116065dd68253cae6",
          "sha256": "4fe23f1f6dc57f7bb60cbec8bf5ed918ca05eca8017ed9b362e76726739b2bfd",
          "sha1": "f56e9805b68c57d053f831433fec58a5624ccb70",
          "md5": "f40ea28588d3db81e0d1e98e7ab0ad60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "09411c333a4aa2ecc8e0a5b96c096ec3f152567558aac4561a0da8dd1160ddafe2502ea13eaecf7a6854a9ca9994b5562b24bccd768560e116065dd68253cae6",
          "sha256": "4fe23f1f6dc57f7bb60cbec8bf5ed918ca05eca8017ed9b362e76726739b2bfd",
          "sha1": "f56e9805b68c57d053f831433fec58a5624ccb70",
          "md5": "f40ea28588d3db81e0d1e98e7ab0ad60"
        }
      ]
    }
  ]
}
