{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "928ff4a6426b99044fe7a2e965c749e59c44b286b2697cd253a7490f511e99793324969fa18489aa146bb93dd5398afe8d50c445a69289973f682d825897876d",
          "sha256": "76b304f5dff0295ad76d69c4f42b86d73c35ead981920b05b001d53aac7ce867",
          "sha1": "ef523caa6784e182239cd088eece215f48e889a0",
          "md5": "a67eb9faf8f521804b4f3bf33b201eb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "928ff4a6426b99044fe7a2e965c749e59c44b286b2697cd253a7490f511e99793324969fa18489aa146bb93dd5398afe8d50c445a69289973f682d825897876d",
          "sha256": "76b304f5dff0295ad76d69c4f42b86d73c35ead981920b05b001d53aac7ce867",
          "sha1": "ef523caa6784e182239cd088eece215f48e889a0",
          "md5": "a67eb9faf8f521804b4f3bf33b201eb5"
        }
      ]
    }
  ]
}
