{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "20a1024199a4894a798a2efd1339f5008fa7bd03aaf1a897631f5fb51a38aefbffb224aa3e173625e928cf24f5249fb8149f3edd782ee20c22558f3c12dcad3c",
          "sha256": "68bb47498ddbed5a66d60e38540379b980b027ab776d2f842647a91a7c9ca871",
          "sha1": "1580e99828df0fa0c6603c7769b26d67e953083f",
          "md5": "54dddc351e024dd3edebfe3e71126d78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "20a1024199a4894a798a2efd1339f5008fa7bd03aaf1a897631f5fb51a38aefbffb224aa3e173625e928cf24f5249fb8149f3edd782ee20c22558f3c12dcad3c",
          "sha256": "68bb47498ddbed5a66d60e38540379b980b027ab776d2f842647a91a7c9ca871",
          "sha1": "1580e99828df0fa0c6603c7769b26d67e953083f",
          "md5": "54dddc351e024dd3edebfe3e71126d78"
        }
      ]
    }
  ]
}
