{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "7b5a9011ac48407c746f748f5e7b07e962154996ab45e565a3ae51534432556f9bd87b9b1e38c376c39ac2f72e5a6c9be39f516f4ef9a47d9b8c95e933142da7",
          "sha256": "1b0ddbc574babd2d71d1f3c8d3a48f2475fb25ba4934b7c12949685af73d05c8",
          "sha1": "602ed406aca3a0d1a2811dcf3fb2f9c6720ccaf2",
          "md5": "b9fb659d521069b8180c60a5c9d36040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "7b5a9011ac48407c746f748f5e7b07e962154996ab45e565a3ae51534432556f9bd87b9b1e38c376c39ac2f72e5a6c9be39f516f4ef9a47d9b8c95e933142da7",
          "sha256": "1b0ddbc574babd2d71d1f3c8d3a48f2475fb25ba4934b7c12949685af73d05c8",
          "sha1": "602ed406aca3a0d1a2811dcf3fb2f9c6720ccaf2",
          "md5": "b9fb659d521069b8180c60a5c9d36040"
        }
      ]
    }
  ]
}
