{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.8.0.jar",
          "url": "runelite-api-4.8.0.jar",
          "size": 1269826,
          "sha512": "9fa1172f731bc4aa3807ca522cdb28d1270329891e9510c9217ee9b52b95df5f6ab839cb7d17e7b4a588287f904fd3797daf468e9ca26146a4f251a83d970018",
          "sha256": "e7d6259f4728211f1a63487ad9f37710535fe64b59bf706c888d046bff7138ce",
          "sha1": "8b3bee48173f03ee7cbf45b3ceea1546ef08b4fa",
          "md5": "40aafffeade2b1a8d2ea39bbb11c6743"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.8.0.jar",
          "url": "runelite-api-4.8.0.jar",
          "size": 1269826,
          "sha512": "9fa1172f731bc4aa3807ca522cdb28d1270329891e9510c9217ee9b52b95df5f6ab839cb7d17e7b4a588287f904fd3797daf468e9ca26146a4f251a83d970018",
          "sha256": "e7d6259f4728211f1a63487ad9f37710535fe64b59bf706c888d046bff7138ce",
          "sha1": "8b3bee48173f03ee7cbf45b3ceea1546ef08b4fa",
          "md5": "40aafffeade2b1a8d2ea39bbb11c6743"
        }
      ]
    }
  ]
}
