{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.10.0.jar",
          "url": "runescape-api-4.10.0.jar",
          "size": 111191,
          "sha512": "8fdb8570ea92dd814198b70805ce2cdd3db704c7dd1221124f75c5b54b23ee919eb9083dcb9a73da231b668687fd5dfe7f580bd8717fe3911d74c53897fc1c29",
          "sha256": "ea1ecedd4c0b548bcdfb7a392c64c212215337ced69e5b2053c371b9b9860949",
          "sha1": "8d3bc855fc1b90fe8dc1a3f539f83cd250b9f108",
          "md5": "eec5c3a02257429d670b65a8f18f5ef2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.10.0.jar",
          "url": "runescape-api-4.10.0.jar",
          "size": 111191,
          "sha512": "8fdb8570ea92dd814198b70805ce2cdd3db704c7dd1221124f75c5b54b23ee919eb9083dcb9a73da231b668687fd5dfe7f580bd8717fe3911d74c53897fc1c29",
          "sha256": "ea1ecedd4c0b548bcdfb7a392c64c212215337ced69e5b2053c371b9b9860949",
          "sha1": "8d3bc855fc1b90fe8dc1a3f539f83cd250b9f108",
          "md5": "eec5c3a02257429d670b65a8f18f5ef2"
        }
      ]
    }
  ]
}
