{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "6e619fbe5bf9e39967ddcc1369efda40333dd9320fccc3407d490308faf647795b421810bec893ff3a09791acf68d72975bfbfc4d9e52fe4d519b576bf0a7dad",
          "sha256": "2390db5a7152ec07126c8fe9e5655967b46f5a83cf46faae6c1d3657be2c9712",
          "sha1": "21be2ac5480be20e2f239fa76358f8827e13cbc3",
          "md5": "7d96988f4ab1c92f7123146f1007b938"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "6e619fbe5bf9e39967ddcc1369efda40333dd9320fccc3407d490308faf647795b421810bec893ff3a09791acf68d72975bfbfc4d9e52fe4d519b576bf0a7dad",
          "sha256": "2390db5a7152ec07126c8fe9e5655967b46f5a83cf46faae6c1d3657be2c9712",
          "sha1": "21be2ac5480be20e2f239fa76358f8827e13cbc3",
          "md5": "7d96988f4ab1c92f7123146f1007b938"
        }
      ]
    }
  ]
}
