{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "c67fa858e1c2d14d3a0bee5277d0d25899d555023b32d59e3777bf171acddc5f0adea9c0c3c25c7d78449471350e0caf957efa3661d01a4c350b7abe2218b669",
          "sha256": "41cfc6aa9b49cbaa0aee63ada4fe211a365a32d7678e9c7a9df1e28b44ad3aa5",
          "sha1": "b496670d4d2d67f099b487673ddd8da2ee362331",
          "md5": "ec1fd094935226841199100f1d469eb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "c67fa858e1c2d14d3a0bee5277d0d25899d555023b32d59e3777bf171acddc5f0adea9c0c3c25c7d78449471350e0caf957efa3661d01a4c350b7abe2218b669",
          "sha256": "41cfc6aa9b49cbaa0aee63ada4fe211a365a32d7678e9c7a9df1e28b44ad3aa5",
          "sha1": "b496670d4d2d67f099b487673ddd8da2ee362331",
          "md5": "ec1fd094935226841199100f1d469eb2"
        }
      ]
    }
  ]
}
