{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "2c763814c1ed0624c9190439e8e11d921261054c552809be7b8bffa5cac4d5eab03435f66ae194c3d21cfefd0782f40cbb91f31418a556c3958354133f6e5b4f",
          "sha256": "f7b432cee5911ec77c58364b85dc46a9495d18ea784f5a868bc6310582f39dac",
          "sha1": "ca75c0899732f7edbbd50cf154c381d0634bca24",
          "md5": "3cdf6dc7e14b07feff6e0c76d59d24f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "2c763814c1ed0624c9190439e8e11d921261054c552809be7b8bffa5cac4d5eab03435f66ae194c3d21cfefd0782f40cbb91f31418a556c3958354133f6e5b4f",
          "sha256": "f7b432cee5911ec77c58364b85dc46a9495d18ea784f5a868bc6310582f39dac",
          "sha1": "ca75c0899732f7edbbd50cf154c381d0634bca24",
          "md5": "3cdf6dc7e14b07feff6e0c76d59d24f0"
        }
      ]
    }
  ]
}
