{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.1.jar",
          "url": "runescape-api-4.16.1.jar",
          "size": 143805,
          "sha512": "9ec5e81d8e852e8ccbf8432a59a891ae282b4f967205caab03543642445179c0d024ea123038e73db6100e808dd456f8dcef315685ceb707f206570c7215e617",
          "sha256": "90dc2639a5dc13c2311cd76c4b1e493a2c06f13c019b71b0a52536199de7a5dd",
          "sha1": "699b87bc928193f5785f021ea5ffdcfe56663b19",
          "md5": "c5f33f4e6c452d015cdff68359ba377c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.1.jar",
          "url": "runescape-api-4.16.1.jar",
          "size": 143805,
          "sha512": "9ec5e81d8e852e8ccbf8432a59a891ae282b4f967205caab03543642445179c0d024ea123038e73db6100e808dd456f8dcef315685ceb707f206570c7215e617",
          "sha256": "90dc2639a5dc13c2311cd76c4b1e493a2c06f13c019b71b0a52536199de7a5dd",
          "sha1": "699b87bc928193f5785f021ea5ffdcfe56663b19",
          "md5": "c5f33f4e6c452d015cdff68359ba377c"
        }
      ]
    }
  ]
}
