{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 172795,
          "sha512": "4cac74ce6ae6a54ed916e43fdbecaa08d11287b0fc79ec396873d2f135f640fa9ff40866411a1dca7bbf2ab2df9312aa45f2293f01f4652cb6b87e3eb7662a0c",
          "sha256": "e8469aaf28c9c13e42cdc4258ca25e00f715ba09a73f518d35c921cbe576c5fb",
          "sha1": "357445b5c4c8ef5c97b55143bd8e75c95128a962",
          "md5": "22729bec43c2c59d4081275c4bac662e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 172795,
          "sha512": "4cac74ce6ae6a54ed916e43fdbecaa08d11287b0fc79ec396873d2f135f640fa9ff40866411a1dca7bbf2ab2df9312aa45f2293f01f4652cb6b87e3eb7662a0c",
          "sha256": "e8469aaf28c9c13e42cdc4258ca25e00f715ba09a73f518d35c921cbe576c5fb",
          "sha1": "357445b5c4c8ef5c97b55143bd8e75c95128a962",
          "md5": "22729bec43c2c59d4081275c4bac662e"
        }
      ]
    }
  ]
}
