{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 172800,
          "sha512": "495ce8a91e1675f912013f077265254c3d9b56dea979c1b61bdf029af1635ec9138bde7bcb5ede5596bbba9382bf0d7f4d93fc6e12e28d8aaeee3a57e8cc316c",
          "sha256": "605cd15316f3a9a74e354b04808e4dd3dad1689b55c4746f2b3e259bf930873e",
          "sha1": "2da5ac2a43b891cd0117b9fa38873eea9b3b160c",
          "md5": "12142d55ef540b4085ba349ea2ce0648"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 172800,
          "sha512": "495ce8a91e1675f912013f077265254c3d9b56dea979c1b61bdf029af1635ec9138bde7bcb5ede5596bbba9382bf0d7f4d93fc6e12e28d8aaeee3a57e8cc316c",
          "sha256": "605cd15316f3a9a74e354b04808e4dd3dad1689b55c4746f2b3e259bf930873e",
          "sha1": "2da5ac2a43b891cd0117b9fa38873eea9b3b160c",
          "md5": "12142d55ef540b4085ba349ea2ce0648"
        }
      ]
    }
  ]
}
