{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 172800,
          "sha512": "4e5fb334c092ebd12ddb77b6bee64b3f1ba3aaaefac2da4a57feb0818b16127edc93afac07afe050f230b422ad6d1ae23490a03dc6ebb61138b7c461f3a26501",
          "sha256": "146b6b4b3ac031b3ce14d79549a25267223361556ba4bf1f713d5118ca9a3dfa",
          "sha1": "4e48533f06d05311c3900d04487df190748f1750",
          "md5": "feac7b0db6b53bdf0a0560ba1de18f69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.8.jar",
          "url": "http-api-4.15.8.jar",
          "size": 172800,
          "sha512": "4e5fb334c092ebd12ddb77b6bee64b3f1ba3aaaefac2da4a57feb0818b16127edc93afac07afe050f230b422ad6d1ae23490a03dc6ebb61138b7c461f3a26501",
          "sha256": "146b6b4b3ac031b3ce14d79549a25267223361556ba4bf1f713d5118ca9a3dfa",
          "sha1": "4e48533f06d05311c3900d04487df190748f1750",
          "md5": "feac7b0db6b53bdf0a0560ba1de18f69"
        }
      ]
    }
  ]
}
