{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.0.jar",
          "url": "runescape-api-4.17.0.jar",
          "size": 145703,
          "sha512": "3acadf41d5077aeb82b21336e9930faa8a0ecf59e6d659f21b00d8bc312be867923da8a9b0ee286ab733e7541a3aeb9424c0dc4b61f53ee12a76f11d99fb59c3",
          "sha256": "40dcaaf472dc7f87cefd7a09a44150d4416b25021f4e8693767a1f652236daa5",
          "sha1": "1832adc706b75c11564b3157168b767b6c87d8ce",
          "md5": "2a024312b33b74eb414907bff3eda948"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.0.jar",
          "url": "runescape-api-4.17.0.jar",
          "size": 145703,
          "sha512": "3acadf41d5077aeb82b21336e9930faa8a0ecf59e6d659f21b00d8bc312be867923da8a9b0ee286ab733e7541a3aeb9424c0dc4b61f53ee12a76f11d99fb59c3",
          "sha256": "40dcaaf472dc7f87cefd7a09a44150d4416b25021f4e8693767a1f652236daa5",
          "sha1": "1832adc706b75c11564b3157168b767b6c87d8ce",
          "md5": "2a024312b33b74eb414907bff3eda948"
        }
      ]
    }
  ]
}
