{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "b18ffbb92969547267b596293004a378458394263232c310d01d6f0c02dc6e2839a6d0d07e20b80a68dbde760e64b6cf77432d5179fcebb754f4e6e098a847bd",
          "sha256": "e307796527b91bdaca7efdfd96288627b6ca36023e5b6683419122971cd05e26",
          "sha1": "abfb2c5e155e5d19968c8857dd9a4cdb32fe4a98",
          "md5": "28c6fc17e9c3b5684431619383cc4452"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "b18ffbb92969547267b596293004a378458394263232c310d01d6f0c02dc6e2839a6d0d07e20b80a68dbde760e64b6cf77432d5179fcebb754f4e6e098a847bd",
          "sha256": "e307796527b91bdaca7efdfd96288627b6ca36023e5b6683419122971cd05e26",
          "sha1": "abfb2c5e155e5d19968c8857dd9a4cdb32fe4a98",
          "md5": "28c6fc17e9c3b5684431619383cc4452"
        }
      ]
    }
  ]
}
