{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "85bb037496d609e07d8fc54eb7bd9142eed65b1dbd37e80ac35764f599dcf9583fc91cbc5994edf95d010c0997a4541b72f1f52b51974d35235d7fc7e336b593",
          "sha256": "65a89988a6fe640b9db29335af244f8a1ace19b6f47e9d6137a2936b43298c6d",
          "sha1": "693bdedcf37d2da0b7e2f84f8b98577c1a3e53b2",
          "md5": "93fc58915c7af9d3eb137404eb318ff5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "85bb037496d609e07d8fc54eb7bd9142eed65b1dbd37e80ac35764f599dcf9583fc91cbc5994edf95d010c0997a4541b72f1f52b51974d35235d7fc7e336b593",
          "sha256": "65a89988a6fe640b9db29335af244f8a1ace19b6f47e9d6137a2936b43298c6d",
          "sha1": "693bdedcf37d2da0b7e2f84f8b98577c1a3e53b2",
          "md5": "93fc58915c7af9d3eb137404eb318ff5"
        }
      ]
    }
  ]
}
