{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "d16c5c583d7f0812a3f2700bc1fb7a9860082a24faef530db207aa458c84178eccd25bf976d902d006b38598a8d0a412bc64531b28ef537331bdf13ecc49eca0",
          "sha256": "7b0ab46e6f3fe6d273e66888e109d140e14e3ef24407014a2936494be544b6c7",
          "sha1": "f463c95ffac5042361b8e61be43e6ae12d29e289",
          "md5": "61bc2e5134788d57d16d89ea4e491208"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "d16c5c583d7f0812a3f2700bc1fb7a9860082a24faef530db207aa458c84178eccd25bf976d902d006b38598a8d0a412bc64531b28ef537331bdf13ecc49eca0",
          "sha256": "7b0ab46e6f3fe6d273e66888e109d140e14e3ef24407014a2936494be544b6c7",
          "sha1": "f463c95ffac5042361b8e61be43e6ae12d29e289",
          "md5": "61bc2e5134788d57d16d89ea4e491208"
        }
      ]
    }
  ]
}
