{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.5.jar",
          "url": "runelite-api-4.15.5.jar",
          "size": 1331360,
          "sha512": "478e4410fa4e31438edadec5a4e90e33d73b0b6b2df3314dfd552bdcb4388afe7d52c8f216dc95610351bb973dfb1aa964b0735e2bf96a42f8c2882de587d0a3",
          "sha256": "0052f62a5c1b02cef9fccf6acd6ea5bb5c34265615718d47adb27789393edb31",
          "sha1": "4e8343b137fecb7ada92806ac10f391ce2208535",
          "md5": "05b57139873a20b4b6171ca235b329aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.5.jar",
          "url": "runelite-api-4.15.5.jar",
          "size": 1331360,
          "sha512": "478e4410fa4e31438edadec5a4e90e33d73b0b6b2df3314dfd552bdcb4388afe7d52c8f216dc95610351bb973dfb1aa964b0735e2bf96a42f8c2882de587d0a3",
          "sha256": "0052f62a5c1b02cef9fccf6acd6ea5bb5c34265615718d47adb27789393edb31",
          "sha1": "4e8343b137fecb7ada92806ac10f391ce2208535",
          "md5": "05b57139873a20b4b6171ca235b329aa"
        }
      ]
    }
  ]
}
