{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "c99a3c0c59419b21340329d7085bd5c1243fe798a53af7909edba32d97d15317c53369cd2701f737824ff81682d6579fc9cce53a56ae4034e59e2acef27a2ebd",
          "sha256": "225355d85f71aff07905a2ae55bf920f0906696022f9ce502797855b3ad30f88",
          "sha1": "6aa64fc19f17fcd9fbe687635e2bd01f31724a0a",
          "md5": "ccebf30cdc598538d9b10b8eda944ce9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "c99a3c0c59419b21340329d7085bd5c1243fe798a53af7909edba32d97d15317c53369cd2701f737824ff81682d6579fc9cce53a56ae4034e59e2acef27a2ebd",
          "sha256": "225355d85f71aff07905a2ae55bf920f0906696022f9ce502797855b3ad30f88",
          "sha1": "6aa64fc19f17fcd9fbe687635e2bd01f31724a0a",
          "md5": "ccebf30cdc598538d9b10b8eda944ce9"
        }
      ]
    }
  ]
}
