{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 99203,
          "sha512": "22e63f395910508d2396a90e7ca1ef5943e0585f7bdf98c3b836b31e05e4339e671f88cdfc7b44ff32fe0a1fd3e8001af4a72c45ece37c0691972777c3e61da3",
          "sha256": "d37a4235ea2da7ad11bf5fe21771f3452983609b817403165e0c4611cf210c77",
          "sha1": "e099a22b8629355862fea364c1c62bf2dd80ed69",
          "md5": "0e60d93cc195a1cdfb6ca882ef760182"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 99203,
          "sha512": "22e63f395910508d2396a90e7ca1ef5943e0585f7bdf98c3b836b31e05e4339e671f88cdfc7b44ff32fe0a1fd3e8001af4a72c45ece37c0691972777c3e61da3",
          "sha256": "d37a4235ea2da7ad11bf5fe21771f3452983609b817403165e0c4611cf210c77",
          "sha1": "e099a22b8629355862fea364c1c62bf2dd80ed69",
          "md5": "0e60d93cc195a1cdfb6ca882ef760182"
        }
      ]
    }
  ]
}
