{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "dyqmqj3g2rchnhjqhhiq5bbrta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.3.jar",
          "url": "http-api-3.5.3.jar",
          "size": 160389,
          "sha512": "86c1bc09a4cf6dd46668be907ca87dbe68485eae9c4cddfb4396296c6e1ea3a712a76af81ef15b983fe846d9c2c425754cfbd3cd30866004c5208fa20bbcfc4e",
          "sha256": "8816898b5172b9defc543f0df49cd987809b710f2279a626cdd8f8d0b0dffc2f",
          "sha1": "22609e99cbbe7ce9a7fdf6b62dc8aab4c64ea96e",
          "md5": "bc286dd7b9231a399e2e11a343fc9c8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.3.jar",
          "url": "http-api-3.5.3.jar",
          "size": 160389,
          "sha512": "86c1bc09a4cf6dd46668be907ca87dbe68485eae9c4cddfb4396296c6e1ea3a712a76af81ef15b983fe846d9c2c425754cfbd3cd30866004c5208fa20bbcfc4e",
          "sha256": "8816898b5172b9defc543f0df49cd987809b710f2279a626cdd8f8d0b0dffc2f",
          "sha1": "22609e99cbbe7ce9a7fdf6b62dc8aab4c64ea96e",
          "md5": "bc286dd7b9231a399e2e11a343fc9c8a"
        }
      ]
    }
  ]
}
