{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.5.jar",
          "url": "runelite-jshell-4.15.5.jar",
          "size": 26552,
          "sha512": "9b726011289132d750fd4cc505250f56c8b5a4aca5a15a36134dad0e0380cf752677c6ee49a2a911d66419469ae2ffd09b60813e20082075b7781d008bbbc4b1",
          "sha256": "9e55780b5f17ca4f5df14b36172852a234965e688d8ba927e3117ebacac68820",
          "sha1": "3b408d04f213a0feb5fbfe162e6e1f621e4bb165",
          "md5": "8cdac6a0d9d5b5b1ed3c58c3f69185ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.5.jar",
          "url": "runelite-jshell-4.15.5.jar",
          "size": 26552,
          "sha512": "9b726011289132d750fd4cc505250f56c8b5a4aca5a15a36134dad0e0380cf752677c6ee49a2a911d66419469ae2ffd09b60813e20082075b7781d008bbbc4b1",
          "sha256": "9e55780b5f17ca4f5df14b36172852a234965e688d8ba927e3117ebacac68820",
          "sha1": "3b408d04f213a0feb5fbfe162e6e1f621e4bb165",
          "md5": "8cdac6a0d9d5b5b1ed3c58c3f69185ea"
        }
      ]
    }
  ]
}
