{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.13.1.jar",
          "url": "runelite-jshell-4.13.1.jar",
          "size": 26552,
          "sha512": "51893ac5be172d4518cedf6433d03813ca5a92eca73098ae605f10ff110a642c011a5b47540248f168e9a8d82a8d582862be1d3f618268017c01b63203f56e86",
          "sha256": "30c0874b7680fb1ea66808b1681b8337f4a1aa6d165157f526e761b23139aabb",
          "sha1": "e26dc9cbfade35ca37d0a449e82c99e7317434d6",
          "md5": "a6ac9a5bc6e5c3e7ff9b49f990b2c08d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.13.1.jar",
          "url": "runelite-jshell-4.13.1.jar",
          "size": 26552,
          "sha512": "51893ac5be172d4518cedf6433d03813ca5a92eca73098ae605f10ff110a642c011a5b47540248f168e9a8d82a8d582862be1d3f618268017c01b63203f56e86",
          "sha256": "30c0874b7680fb1ea66808b1681b8337f4a1aa6d165157f526e761b23139aabb",
          "sha1": "e26dc9cbfade35ca37d0a449e82c99e7317434d6",
          "md5": "a6ac9a5bc6e5c3e7ff9b49f990b2c08d"
        }
      ]
    }
  ]
}
