{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.29.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.29.0.jar",
          "url": "runescape-api-4.29.0.jar",
          "size": 150296,
          "sha512": "d1378abced88c9e05b41b30ae50506d35078600bc264da8e7778b1183186f210adabfa135e8b7980ed0d877cb035792fd0509025a1493071418bc2cf0af82819",
          "sha256": "b757c353c0fb79fb0f6efd99f43df76524ec7feab007f6b304bcc10af4ffb865",
          "sha1": "4bab45cfcb8275dd012c499241c3c0cbaa7ccd57",
          "md5": "9ef5ef1c003b28eda952c91e01b3970b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.29.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.29.0.jar",
          "url": "runescape-api-4.29.0.jar",
          "size": 150296,
          "sha512": "d1378abced88c9e05b41b30ae50506d35078600bc264da8e7778b1183186f210adabfa135e8b7980ed0d877cb035792fd0509025a1493071418bc2cf0af82819",
          "sha256": "b757c353c0fb79fb0f6efd99f43df76524ec7feab007f6b304bcc10af4ffb865",
          "sha1": "4bab45cfcb8275dd012c499241c3c0cbaa7ccd57",
          "md5": "9ef5ef1c003b28eda952c91e01b3970b"
        }
      ]
    }
  ]
}
