{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.6.0.jar",
          "url": "runelite-api-4.6.0.jar",
          "size": 1258864,
          "sha512": "8372e20e29ccca407f6c48f8b16bda358dce1ca4efe1cdce4d9e224afbe6187e9e16383d826b8c419cd9a04648b7ac78622ba3fc9b1cf891ad27eeec354d5c13",
          "sha256": "ab6046fb5399f9f2acd538c6fc5d0e3533f33f9382e502918fc7f78cbe43ed4c",
          "sha1": "251cb63cf13e4fbf023bfde983a380314c756f59",
          "md5": "3f2e2c596607a7332f2fefd5da7593af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.6.0.jar",
          "url": "runelite-api-4.6.0.jar",
          "size": 1258864,
          "sha512": "8372e20e29ccca407f6c48f8b16bda358dce1ca4efe1cdce4d9e224afbe6187e9e16383d826b8c419cd9a04648b7ac78622ba3fc9b1cf891ad27eeec354d5c13",
          "sha256": "ab6046fb5399f9f2acd538c6fc5d0e3533f33f9382e502918fc7f78cbe43ed4c",
          "sha1": "251cb63cf13e4fbf023bfde983a380314c756f59",
          "md5": "3f2e2c596607a7332f2fefd5da7593af"
        }
      ]
    }
  ]
}
