{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.0.jar",
          "url": "runelite-api-4.18.0.jar",
          "size": 1335313,
          "sha512": "0ba231ec18f10247428e108f02ead40af48887fc174f050c3b6d3fa1b71e8eee708873a0c77aa3736c17f831c85b996d1a5824853fcbb646c31498ddb630f2f5",
          "sha256": "b47eeb825609c11ec8e48231aa4b1f32c0fe55d7513a3ec89c4e13833c8e4a5a",
          "sha1": "fb2fd11789605677fce5532f5d7e82400c917f14",
          "md5": "4e2b5df84f4aa24aef2f329fbe7b12ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.0.jar",
          "url": "runelite-api-4.18.0.jar",
          "size": 1335313,
          "sha512": "0ba231ec18f10247428e108f02ead40af48887fc174f050c3b6d3fa1b71e8eee708873a0c77aa3736c17f831c85b996d1a5824853fcbb646c31498ddb630f2f5",
          "sha256": "b47eeb825609c11ec8e48231aa4b1f32c0fe55d7513a3ec89c4e13833c8e4a5a",
          "sha1": "fb2fd11789605677fce5532f5d7e82400c917f14",
          "md5": "4e2b5df84f4aa24aef2f329fbe7b12ac"
        }
      ]
    }
  ]
}
