{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.6.jar",
          "url": "runelite-api-4.15.6.jar",
          "size": 1331360,
          "sha512": "38baffb532bb1e7e8230d1151473b6606caaddfd7eb722cd3a1cbed3562acedf3da8d395ba60f8b15925f7c91965cd5e4b99c1d3ca35025868edb7ef9c433425",
          "sha256": "a80278bfedb7feb13e3dab1c4d0cc12e0ddb6e01082bd8a4209c1bc71d1ee13c",
          "sha1": "360d06a0c907d89d78fbd8055effaec34b39f305",
          "md5": "4fdbb0978c1ecee3b8aaf1015a1efb3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.6.jar",
          "url": "runelite-api-4.15.6.jar",
          "size": 1331360,
          "sha512": "38baffb532bb1e7e8230d1151473b6606caaddfd7eb722cd3a1cbed3562acedf3da8d395ba60f8b15925f7c91965cd5e4b99c1d3ca35025868edb7ef9c433425",
          "sha256": "a80278bfedb7feb13e3dab1c4d0cc12e0ddb6e01082bd8a4209c1bc71d1ee13c",
          "sha1": "360d06a0c907d89d78fbd8055effaec34b39f305",
          "md5": "4fdbb0978c1ecee3b8aaf1015a1efb3f"
        }
      ]
    }
  ]
}
