{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.5.jar",
          "url": "runelite-jshell-4.20.5.jar",
          "size": 26557,
          "sha512": "242e895e5898a66c9f6b2e47db26125ac1dcb91199fe635f338683742ad90bd8442bba92abc4e8aaa2d682f6e07a3066c635bd7a39cc46f3f8c2ff5803346303",
          "sha256": "0dbaa2540b7b9ca846551a5ae29d670f8ebd1b18334f644a3f06e8e5f6aae4db",
          "sha1": "7911d0296093e86a7123962d75f42de2db2c3880",
          "md5": "6fa31d8d03a6bd736a34626f3f52b444"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.5.jar",
          "url": "runelite-jshell-4.20.5.jar",
          "size": 26557,
          "sha512": "242e895e5898a66c9f6b2e47db26125ac1dcb91199fe635f338683742ad90bd8442bba92abc4e8aaa2d682f6e07a3066c635bd7a39cc46f3f8c2ff5803346303",
          "sha256": "0dbaa2540b7b9ca846551a5ae29d670f8ebd1b18334f644a3f06e8e5f6aae4db",
          "sha1": "7911d0296093e86a7123962d75f42de2db2c3880",
          "md5": "6fa31d8d03a6bd736a34626f3f52b444"
        }
      ]
    }
  ]
}
