{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.5.jar",
          "url": "runelite-jshell-4.20.5.jar",
          "size": 26557,
          "sha512": "8d6642721fe4d42e8fdf46292bc556dd5abdc32f18a439fbd06b6260d3e249f0a780616deef4d251809d334eff6c59e2239b2292c5de9d92c87b86131ca9d06b",
          "sha256": "f2be72b820249e916b46e0f52b97ea833612709374bbeca411db22eb80afdb38",
          "sha1": "0e3ea09a038ada3468bbfadf5910e73e620eb597",
          "md5": "c05339ce9b81d044ef038cc58ae41bbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.5.jar",
          "url": "runelite-jshell-4.20.5.jar",
          "size": 26557,
          "sha512": "8d6642721fe4d42e8fdf46292bc556dd5abdc32f18a439fbd06b6260d3e249f0a780616deef4d251809d334eff6c59e2239b2292c5de9d92c87b86131ca9d06b",
          "sha256": "f2be72b820249e916b46e0f52b97ea833612709374bbeca411db22eb80afdb38",
          "sha1": "0e3ea09a038ada3468bbfadf5910e73e620eb597",
          "md5": "c05339ce9b81d044ef038cc58ae41bbe"
        }
      ]
    }
  ]
}
