{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 135435,
          "sha512": "f337fc74efd206c638f78965d9008371d2117e3c31a6c8d994964104e2f27fbdd5ee39d32dea03f0cf1cbeed88b7cff31b224465c991b0400b40d165cccecfaf",
          "sha256": "9af54c8c919f8cd3299e7c603f033306d6c1cc7b8f293ada45ed2c46c568469a",
          "sha1": "df5ec85cae0d7f044534558475693b62632602f1",
          "md5": "9a789886aa07cf190709f23a0e9af5aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 135435,
          "sha512": "f337fc74efd206c638f78965d9008371d2117e3c31a6c8d994964104e2f27fbdd5ee39d32dea03f0cf1cbeed88b7cff31b224465c991b0400b40d165cccecfaf",
          "sha256": "9af54c8c919f8cd3299e7c603f033306d6c1cc7b8f293ada45ed2c46c568469a",
          "sha1": "df5ec85cae0d7f044534558475693b62632602f1",
          "md5": "9a789886aa07cf190709f23a0e9af5aa"
        }
      ]
    }
  ]
}
