{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 135448,
          "sha512": "06dd0d680314ab532e8dc49cd4f294788943ff2f0d43b5b784a7d79d1b356f0ba31b589d732e7a436b3dc0b8f6405f317ffd0ff1d7a60f05f6d18444f19c0e8d",
          "sha256": "e2c3257f9ee631086fc512072361f5bea78e0b9573b9d4c79787340a546b2315",
          "sha1": "eb117117f9048e29b9f02f8759fbc37ef91daaf3",
          "md5": "a32d350b507436dd6f68e2d55efc467e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 135448,
          "sha512": "06dd0d680314ab532e8dc49cd4f294788943ff2f0d43b5b784a7d79d1b356f0ba31b589d732e7a436b3dc0b8f6405f317ffd0ff1d7a60f05f6d18444f19c0e8d",
          "sha256": "e2c3257f9ee631086fc512072361f5bea78e0b9573b9d4c79787340a546b2315",
          "sha1": "eb117117f9048e29b9f02f8759fbc37ef91daaf3",
          "md5": "a32d350b507436dd6f68e2d55efc467e"
        }
      ]
    }
  ]
}
