{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 136348,
          "sha512": "32bcc01a6d178b7ef1cf409c2e510f76c4aef158f0f86d753857a3b91a9aa4c8ebcf037753585807b9686564536573834e87690601d7e5ccf8791d69af20c2e7",
          "sha256": "d77f41cbee737a64bd46e9b8a88899536d7265120df6b3ef18f415bbc381c2ca",
          "sha1": "58ac9586601bf2890ffd9a5584db56044fa6a22c",
          "md5": "f9cb4e7432ac9b01f801fcadd3cf7916"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.17.1.jar",
          "url": "http-api-4.17.1.jar",
          "size": 136348,
          "sha512": "32bcc01a6d178b7ef1cf409c2e510f76c4aef158f0f86d753857a3b91a9aa4c8ebcf037753585807b9686564536573834e87690601d7e5ccf8791d69af20c2e7",
          "sha256": "d77f41cbee737a64bd46e9b8a88899536d7265120df6b3ef18f415bbc381c2ca",
          "sha1": "58ac9586601bf2890ffd9a5584db56044fa6a22c",
          "md5": "f9cb4e7432ac9b01f801fcadd3cf7916"
        }
      ]
    }
  ]
}
