{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "2c64efe7a0ccf533b486a1ffe3601dd88db438ed191801225d1195fe4f619c3fbe484aef434ff113147c83d57ab1707fe2e7070c5447defdb72bb0fa150fc084",
          "sha256": "1582a4865403555c8ba8a4bb8d37bc4714687f2cc5a5e42b0cbd561b6ffc5121",
          "sha1": "68dadeea8e616638fdaabf9cabf0131591a98e7f",
          "md5": "10a5d37162257251d61c82bede34614f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "2c64efe7a0ccf533b486a1ffe3601dd88db438ed191801225d1195fe4f619c3fbe484aef434ff113147c83d57ab1707fe2e7070c5447defdb72bb0fa150fc084",
          "sha256": "1582a4865403555c8ba8a4bb8d37bc4714687f2cc5a5e42b0cbd561b6ffc5121",
          "sha1": "68dadeea8e616638fdaabf9cabf0131591a98e7f",
          "md5": "10a5d37162257251d61c82bede34614f"
        }
      ]
    }
  ]
}
