{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "41fdbfef0a5e592c574fb5775768207c241c7ddb0002d3716a56b31878ab8b81a8937672c026bf293c3fba641bc66c9c8b24eb04e8a2d0991197d5f3673db6d1",
          "sha256": "027a0da27ecaf9f78b81ae53936e67a51bf8148a94b46f7f8b916327f1c57ed2",
          "sha1": "9df61936488251ecf9df9e9250a6f1feded4c81f",
          "md5": "4346ac38591baca7dccf54700dfb9b19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "41fdbfef0a5e592c574fb5775768207c241c7ddb0002d3716a56b31878ab8b81a8937672c026bf293c3fba641bc66c9c8b24eb04e8a2d0991197d5f3673db6d1",
          "sha256": "027a0da27ecaf9f78b81ae53936e67a51bf8148a94b46f7f8b916327f1c57ed2",
          "sha1": "9df61936488251ecf9df9e9250a6f1feded4c81f",
          "md5": "4346ac38591baca7dccf54700dfb9b19"
        }
      ]
    }
  ]
}
