{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "4ef212ce315a6948b7400749b53b1a57dbe5e837cefa55962cac9c6d0c1abc46cbcdf3cca7dda92bfcb24c2727df6248a1131669219a011f4f756f91b606b3e3",
          "sha256": "4e2134f2ed5340003c7603b54ab8aa0ec0d1f696cd072662e5cc3ea50bee8974",
          "sha1": "d7e68edca31abb1d1b9ae8e79bfdc10baa4216ce",
          "md5": "a26ed48fd440c0cfada6193aaba18415"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "4ef212ce315a6948b7400749b53b1a57dbe5e837cefa55962cac9c6d0c1abc46cbcdf3cca7dda92bfcb24c2727df6248a1131669219a011f4f756f91b606b3e3",
          "sha256": "4e2134f2ed5340003c7603b54ab8aa0ec0d1f696cd072662e5cc3ea50bee8974",
          "sha1": "d7e68edca31abb1d1b9ae8e79bfdc10baa4216ce",
          "md5": "a26ed48fd440c0cfada6193aaba18415"
        }
      ]
    }
  ]
}
