{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99208,
          "sha512": "0c5182fe437380c095efaeb785b1d93178d19787e310f232fd89da1c74221c3021cf3c636dde0a99bde22450eab608f4c70b50be4be9a5d290f05eb8fccf328f",
          "sha256": "95ef3feac21b3d36fedecd84cc182a112c3127c36379327f2241213dfda3948a",
          "sha1": "d91e47f8eddf5abb815ee612b8a6442b661fd233",
          "md5": "c6dd63d3d64f47af73bd4792a35f4d96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99208,
          "sha512": "0c5182fe437380c095efaeb785b1d93178d19787e310f232fd89da1c74221c3021cf3c636dde0a99bde22450eab608f4c70b50be4be9a5d290f05eb8fccf328f",
          "sha256": "95ef3feac21b3d36fedecd84cc182a112c3127c36379327f2241213dfda3948a",
          "sha1": "d91e47f8eddf5abb815ee612b8a6442b661fd233",
          "md5": "c6dd63d3d64f47af73bd4792a35f4d96"
        }
      ]
    }
  ]
}
