{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99205,
          "sha512": "d185359fa562e181d8b048e0d3567e3ea8eae2664ec7e7cdd23e82af0e08432c33e9781136fa41fd17029e4222127421589db4bf244e84e5bb81053aeeb1133e",
          "sha256": "23dfe5176f02621e688b30003b8c475a7ea3f1ae29331da06a490453b3c9558f",
          "sha1": "19b09c148eca841965cb01cce44c0d9f3002aba1",
          "md5": "3838bcdb36acfd188a39119bbeaf626c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99205,
          "sha512": "d185359fa562e181d8b048e0d3567e3ea8eae2664ec7e7cdd23e82af0e08432c33e9781136fa41fd17029e4222127421589db4bf244e84e5bb81053aeeb1133e",
          "sha256": "23dfe5176f02621e688b30003b8c475a7ea3f1ae29331da06a490453b3c9558f",
          "sha1": "19b09c148eca841965cb01cce44c0d9f3002aba1",
          "md5": "3838bcdb36acfd188a39119bbeaf626c"
        }
      ]
    }
  ]
}
