{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99206,
          "sha512": "8200ff82f0f1f9aa45c39b451e76ac610086cf993ff2b3e929f872466759aaa83de0fa9a7c023cdfb8f2e6b75be793b69a31c7fb1c16d159dcd1705c73cfd05f",
          "sha256": "f6405bd7f4a2076df47b5510bc9c109797f3117f512ef8b0ad1a7a1ee14b8c72",
          "sha1": "68e27406cba1a30df987d701789d3f038cbeb8f9",
          "md5": "a4a4c1af47cea35f1355151f27a4037d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99206,
          "sha512": "8200ff82f0f1f9aa45c39b451e76ac610086cf993ff2b3e929f872466759aaa83de0fa9a7c023cdfb8f2e6b75be793b69a31c7fb1c16d159dcd1705c73cfd05f",
          "sha256": "f6405bd7f4a2076df47b5510bc9c109797f3117f512ef8b0ad1a7a1ee14b8c72",
          "sha1": "68e27406cba1a30df987d701789d3f038cbeb8f9",
          "md5": "a4a4c1af47cea35f1355151f27a4037d"
        }
      ]
    }
  ]
}
