{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "64cd044d24e17a8dd612aca1eaef6c491229ce158e442e7abeb0b5342d9d82c35679729e949883e7f08a95fb1a846a72903b47864f562b56206080f754f66dbe",
          "sha256": "448394d02e3b3a69b4b039fa224987610f78d536181a065ce58dc1f389393ac8",
          "sha1": "eda6c0fac183900e8daf0b048f60b54f55a1066e",
          "md5": "27d80b876735923b4f275b8c09f4de28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "64cd044d24e17a8dd612aca1eaef6c491229ce158e442e7abeb0b5342d9d82c35679729e949883e7f08a95fb1a846a72903b47864f562b56206080f754f66dbe",
          "sha256": "448394d02e3b3a69b4b039fa224987610f78d536181a065ce58dc1f389393ac8",
          "sha1": "eda6c0fac183900e8daf0b048f60b54f55a1066e",
          "md5": "27d80b876735923b4f275b8c09f4de28"
        }
      ]
    }
  ]
}
