{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "94d55b0c990e108d8b1acc008cbbe44491890b6ca92edd5988e703fab88423d6213cf8567385a048953ae9d2e78d8b06c38c0a56bdca716361275320a715233d",
          "sha256": "588cc2f80d10eb62b79e34b2b2f00a5d2d8ce2f6c8f57b32b2fd25c09b8718ad",
          "sha1": "37a0a82c3a8a402f755b5d6b266dea503b4fcef4",
          "md5": "c5558073f063e6bea8eb2fa4fb21a3e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "94d55b0c990e108d8b1acc008cbbe44491890b6ca92edd5988e703fab88423d6213cf8567385a048953ae9d2e78d8b06c38c0a56bdca716361275320a715233d",
          "sha256": "588cc2f80d10eb62b79e34b2b2f00a5d2d8ce2f6c8f57b32b2fd25c09b8718ad",
          "sha1": "37a0a82c3a8a402f755b5d6b266dea503b4fcef4",
          "md5": "c5558073f063e6bea8eb2fa4fb21a3e2"
        }
      ]
    }
  ]
}
