{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "ddbb4b52750a442da95604001817cf2638f10ceb8ea8e9002d9781695e3f2a8c84efafe19f7a98c4c8e8dd51f79a6d2c73bf9405641f48cfd241e413eba42136",
          "sha256": "bc777bebcfe2559aa727bbd8a34b7778d978a5618c47c77fa3c05bf28c5aa08a",
          "sha1": "1404943e54d6a5714cb650b61ef7182d23de2b52",
          "md5": "ae859aaa8583441cfefcf7eb8a7f2f3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "ddbb4b52750a442da95604001817cf2638f10ceb8ea8e9002d9781695e3f2a8c84efafe19f7a98c4c8e8dd51f79a6d2c73bf9405641f48cfd241e413eba42136",
          "sha256": "bc777bebcfe2559aa727bbd8a34b7778d978a5618c47c77fa3c05bf28c5aa08a",
          "sha1": "1404943e54d6a5714cb650b61ef7182d23de2b52",
          "md5": "ae859aaa8583441cfefcf7eb8a7f2f3a"
        }
      ]
    }
  ]
}
