{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3d447txjbvamvg6xnz3c32gz34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.4.0.jar",
          "url": "http-api-4.4.0.jar",
          "size": 159718,
          "sha512": "cae9435e8c7b26cf7a563d39f8a365b3e5dad1f568097f834f43dbc133c087bdf0fa0bb3f7b5030706ca0f931d0149cb73a5c0a184ea7ac9aa7ee6f0f00b9a2a",
          "sha256": "b745ea10ff69bef2944984b358fccbdb85f1c4aa901fb4c0a2d9178fd1daa275",
          "sha1": "f6e8c70d07f47060f82127cb4881a59c3c5eeb73",
          "md5": "a9bb5723597266f297e48a539ff0dca6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.4.0.jar",
          "url": "http-api-4.4.0.jar",
          "size": 159718,
          "sha512": "cae9435e8c7b26cf7a563d39f8a365b3e5dad1f568097f834f43dbc133c087bdf0fa0bb3f7b5030706ca0f931d0149cb73a5c0a184ea7ac9aa7ee6f0f00b9a2a",
          "sha256": "b745ea10ff69bef2944984b358fccbdb85f1c4aa901fb4c0a2d9178fd1daa275",
          "sha1": "f6e8c70d07f47060f82127cb4881a59c3c5eeb73",
          "md5": "a9bb5723597266f297e48a539ff0dca6"
        }
      ]
    }
  ]
}
