{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.16.1.jar",
          "url": "runelite-jshell-4.16.1.jar",
          "size": 26552,
          "sha512": "3333f5fe3324c21b331ad5e279c8387bb33bf848d01f6d04ecf48845e5ec5025bf494d5740356151dc5d7faef49ab4e064d044107a7450bb2900ea3bdc84f7b6",
          "sha256": "f3c994fbffaaaadf15d62e6072b2862d4248bfb208f9ca8082e461ac1d0f4cde",
          "sha1": "fad14b8ced70fcf2624ab6d7a2c34322a6e663c8",
          "md5": "35f625d60cfb0e4ead018b3285e22f40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.16.1.jar",
          "url": "runelite-jshell-4.16.1.jar",
          "size": 26552,
          "sha512": "3333f5fe3324c21b331ad5e279c8387bb33bf848d01f6d04ecf48845e5ec5025bf494d5740356151dc5d7faef49ab4e064d044107a7450bb2900ea3bdc84f7b6",
          "sha256": "f3c994fbffaaaadf15d62e6072b2862d4248bfb208f9ca8082e461ac1d0f4cde",
          "sha1": "fad14b8ced70fcf2624ab6d7a2c34322a6e663c8",
          "md5": "35f625d60cfb0e4ead018b3285e22f40"
        }
      ]
    }
  ]
}
