{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "8209b063b66781322c828e39cbfbb7924ffe9c6fd8dafd3581e510c5bda598c7c75d707941abee223ce9e77455ee5291944da0f98bf85c26726a3bd0f2e96459",
          "sha256": "3f74f921665927ed3566a067a82275b571f0f2db3cdd452752048797cef77027",
          "sha1": "159c180b7f055016338cf5b02546d4ebe4e7044d",
          "md5": "99cd30a0d1a1826b849bea343c975c67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "8209b063b66781322c828e39cbfbb7924ffe9c6fd8dafd3581e510c5bda598c7c75d707941abee223ce9e77455ee5291944da0f98bf85c26726a3bd0f2e96459",
          "sha256": "3f74f921665927ed3566a067a82275b571f0f2db3cdd452752048797cef77027",
          "sha1": "159c180b7f055016338cf5b02546d4ebe4e7044d",
          "md5": "99cd30a0d1a1826b849bea343c975c67"
        }
      ]
    }
  ]
}
