{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "baad8cc49ce1e261f4de9a661aa092ac58bd0b0898f2761f40276003fadae06db78d0adf02b1b766e2ad9997274a928579728dc4d0931a9cba4f87445af1140e",
          "sha256": "59e08c6a712fe88bd903a09cb826a51c3523fc34103a42953899ba188613eb41",
          "sha1": "f7fc9f8a49bc283905b6bc5478e49f0aa1e2fa12",
          "md5": "c7f571ce7cc7040279f7f00d8d3a937d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "baad8cc49ce1e261f4de9a661aa092ac58bd0b0898f2761f40276003fadae06db78d0adf02b1b766e2ad9997274a928579728dc4d0931a9cba4f87445af1140e",
          "sha256": "59e08c6a712fe88bd903a09cb826a51c3523fc34103a42953899ba188613eb41",
          "sha1": "f7fc9f8a49bc283905b6bc5478e49f0aa1e2fa12",
          "md5": "c7f571ce7cc7040279f7f00d8d3a937d"
        }
      ]
    }
  ]
}
