{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "f97829247348690cf7473d1c3b39ee3f05ccc06cd0827ac1811f7fc649acc137ae70604831ceedc6cbf3de91809f95cd818eaa760ce1506f30de11bb38e1332b",
          "sha256": "f92dab91e3b804bd0b9f93271dc12bd0913ace1059ae00acf91e4d331c8e5a37",
          "sha1": "d00cda5e3659d5415890ea72c83a3e37789f02d9",
          "md5": "e38cf7e038bd0199de30523bc2c9a9c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "f97829247348690cf7473d1c3b39ee3f05ccc06cd0827ac1811f7fc649acc137ae70604831ceedc6cbf3de91809f95cd818eaa760ce1506f30de11bb38e1332b",
          "sha256": "f92dab91e3b804bd0b9f93271dc12bd0913ace1059ae00acf91e4d331c8e5a37",
          "sha1": "d00cda5e3659d5415890ea72c83a3e37789f02d9",
          "md5": "e38cf7e038bd0199de30523bc2c9a9c6"
        }
      ]
    }
  ]
}
