{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "1b14aa3825b02360872c6af18ea127cf56a9a9c205f5b42a8416dc4fb67f2ecc9295000ea70ceb5583942e5bfcfd73162e89ee9354790cc61089111b107c487f",
          "sha256": "d687af0a1f76a42a620b2d2c517ee3490921e12cdf0331e7b0787173807d1285",
          "sha1": "d53e49fdc617e5e725d2908e6eb73a4583c2818e",
          "md5": "62431c76193c9ef04fd50dee9369fa16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "1b14aa3825b02360872c6af18ea127cf56a9a9c205f5b42a8416dc4fb67f2ecc9295000ea70ceb5583942e5bfcfd73162e89ee9354790cc61089111b107c487f",
          "sha256": "d687af0a1f76a42a620b2d2c517ee3490921e12cdf0331e7b0787173807d1285",
          "sha1": "d53e49fdc617e5e725d2908e6eb73a4583c2818e",
          "md5": "62431c76193c9ef04fd50dee9369fa16"
        }
      ]
    }
  ]
}
