{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "94ea975a246613b0cf49e6a8c9eb24b3cc1290c080055dee23b7cb1521f26dbf5ae1bb7424f647c5e631f0b03a7f2f6a673db8cd91beb9e7ea7a1db0928cc290",
          "sha256": "63e315b5141afb45dd343a2ff51fbe99890ec51a072dc061889fb46347bd8c59",
          "sha1": "be81a4b0d0b281f238770a5774b2c2ae60440e31",
          "md5": "88b50ad47494a2e326011e78a11254c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "94ea975a246613b0cf49e6a8c9eb24b3cc1290c080055dee23b7cb1521f26dbf5ae1bb7424f647c5e631f0b03a7f2f6a673db8cd91beb9e7ea7a1db0928cc290",
          "sha256": "63e315b5141afb45dd343a2ff51fbe99890ec51a072dc061889fb46347bd8c59",
          "sha1": "be81a4b0d0b281f238770a5774b2c2ae60440e31",
          "md5": "88b50ad47494a2e326011e78a11254c8"
        }
      ]
    }
  ]
}
