{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.1.jar",
          "url": "runescape-api-4.16.1.jar",
          "size": 143805,
          "sha512": "a7c4f3b128d5f26f9905d4a3ad8366dac6aff0ade623f8e570c21962339c4edaf368e311edd93a375969458121a8b49beb65e2bf94a8636d4c2efd5e41dd4b19",
          "sha256": "c51ccedecfeb5cf42f55afa90d0efeb4dd33f0623394fc80bc67928ed0e4d0ca",
          "sha1": "34fe69be0dff3e36d443fd1d6d6437eb9174b58e",
          "md5": "82662af755783ab053c7dd671b5b75d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.1.jar",
          "url": "runescape-api-4.16.1.jar",
          "size": 143805,
          "sha512": "a7c4f3b128d5f26f9905d4a3ad8366dac6aff0ade623f8e570c21962339c4edaf368e311edd93a375969458121a8b49beb65e2bf94a8636d4c2efd5e41dd4b19",
          "sha256": "c51ccedecfeb5cf42f55afa90d0efeb4dd33f0623394fc80bc67928ed0e4d0ca",
          "sha1": "34fe69be0dff3e36d443fd1d6d6437eb9174b58e",
          "md5": "82662af755783ab053c7dd671b5b75d7"
        }
      ]
    }
  ]
}
