{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.5.jar",
          "url": "runescape-api-4.9.5.jar",
          "size": 109469,
          "sha512": "2a77511f8af7b49738ad62df634e47b0e28b8fe4d4b6dc705941f2b9dd0e3fbff037cc7e9317caa9fb10e08a16018cbf9a980a4fb3406eedde60b5a6074d159e",
          "sha256": "08a1633213a11ee642f45051e72959d369c2e88c2e584240a54539ba0d984f3d",
          "sha1": "15ace77107aa708f292981dcc55368a8e74bdbea",
          "md5": "7ccb8cd0c861ef9a095a857a8d766e51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.5.jar",
          "url": "runescape-api-4.9.5.jar",
          "size": 109469,
          "sha512": "2a77511f8af7b49738ad62df634e47b0e28b8fe4d4b6dc705941f2b9dd0e3fbff037cc7e9317caa9fb10e08a16018cbf9a980a4fb3406eedde60b5a6074d159e",
          "sha256": "08a1633213a11ee642f45051e72959d369c2e88c2e584240a54539ba0d984f3d",
          "sha1": "15ace77107aa708f292981dcc55368a8e74bdbea",
          "md5": "7ccb8cd0c861ef9a095a857a8d766e51"
        }
      ]
    }
  ]
}
