{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.5.jar",
          "url": "runelite-api-4.15.5.jar",
          "size": 1331360,
          "sha512": "f486338a12151f4a465eabc418a0a47818f053b68dd1d890b0f8752cbbac89df794688728513b6b6533e4781d55fdf85aeb136356d55908e38a74f0bb7e2b465",
          "sha256": "e3873e94a2451a0449486d0b602633258af71e0b1819812a5bb141afc7d85e85",
          "sha1": "16784cc64a0b48e36d5bac1a11c2f37ac18ac136",
          "md5": "f7099ded39ff0625858c21c4e9f403c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.5.jar",
          "url": "runelite-api-4.15.5.jar",
          "size": 1331360,
          "sha512": "f486338a12151f4a465eabc418a0a47818f053b68dd1d890b0f8752cbbac89df794688728513b6b6533e4781d55fdf85aeb136356d55908e38a74f0bb7e2b465",
          "sha256": "e3873e94a2451a0449486d0b602633258af71e0b1819812a5bb141afc7d85e85",
          "sha1": "16784cc64a0b48e36d5bac1a11c2f37ac18ac136",
          "md5": "f7099ded39ff0625858c21c4e9f403c4"
        }
      ]
    }
  ]
}
