{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.5.jar",
          "url": "runelite-api-4.15.5.jar",
          "size": 1331360,
          "sha512": "b24a009acec5598551e26f962ae4581a22f93f4bf6d8fd99f108e8912468a1f6f1ea34abdb506d0225dd64fe5ac8bd414994408b86c6cb6574937c4cc86f193a",
          "sha256": "b14bb626cd961b3b0fa2e7cd97ddf60953d8e291b92b6f2ee787d662ed30351f",
          "sha1": "b031beeabcdb6ee93b33a0557581aa16632a6972",
          "md5": "9b053a5b2bf03a2ff4f48ace8ac8b2e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.5.jar",
          "url": "runelite-api-4.15.5.jar",
          "size": 1331360,
          "sha512": "b24a009acec5598551e26f962ae4581a22f93f4bf6d8fd99f108e8912468a1f6f1ea34abdb506d0225dd64fe5ac8bd414994408b86c6cb6574937c4cc86f193a",
          "sha256": "b14bb626cd961b3b0fa2e7cd97ddf60953d8e291b92b6f2ee787d662ed30351f",
          "sha1": "b031beeabcdb6ee93b33a0557581aa16632a6972",
          "md5": "9b053a5b2bf03a2ff4f48ace8ac8b2e3"
        }
      ]
    }
  ]
}
