{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.8.jar",
          "url": "runelite-api-4.15.8.jar",
          "size": 1331360,
          "sha512": "c496a3d77b20d59a96c758db84d86cf6faa2268eb75cdc8bdee9dfe17a9c3e310d3b51e716ce39ccffb55a8bf36c96e41a13e24ca34da81a49879e782abfec82",
          "sha256": "028ac1e4107b3d287b14ba281733246b2d3fa913010097391b969ab71594f46d",
          "sha1": "003149557042c12fb2bf30e81e4ecb273a4753ea",
          "md5": "946aa2c861c52023d6203db8fcaaecab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.8.jar",
          "url": "runelite-api-4.15.8.jar",
          "size": 1331360,
          "sha512": "c496a3d77b20d59a96c758db84d86cf6faa2268eb75cdc8bdee9dfe17a9c3e310d3b51e716ce39ccffb55a8bf36c96e41a13e24ca34da81a49879e782abfec82",
          "sha256": "028ac1e4107b3d287b14ba281733246b2d3fa913010097391b969ab71594f46d",
          "sha1": "003149557042c12fb2bf30e81e4ecb273a4753ea",
          "md5": "946aa2c861c52023d6203db8fcaaecab"
        }
      ]
    }
  ]
}
