{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.8.jar",
          "url": "runelite-api-4.15.8.jar",
          "size": 1331408,
          "sha512": "228ce761da3ff4bf9f2c0c57d36c3acc1366b3f515ad94274cbffb463bdd962cff9724f1f855776da237e055f556b91aaf7cf31beca68f89d153e58981b12053",
          "sha256": "6b6e40c979df99bd1f07e4a61616df27fb9182aeab06abfc007bfd1547551b1a",
          "sha1": "cd5fc7223d6133aaecd447fadf09dc60f803ca70",
          "md5": "b6ac8f8ddc9f1bd854669e5219c0b33e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.8.jar",
          "url": "runelite-api-4.15.8.jar",
          "size": 1331408,
          "sha512": "228ce761da3ff4bf9f2c0c57d36c3acc1366b3f515ad94274cbffb463bdd962cff9724f1f855776da237e055f556b91aaf7cf31beca68f89d153e58981b12053",
          "sha256": "6b6e40c979df99bd1f07e4a61616df27fb9182aeab06abfc007bfd1547551b1a",
          "sha1": "cd5fc7223d6133aaecd447fadf09dc60f803ca70",
          "md5": "b6ac8f8ddc9f1bd854669e5219c0b33e"
        }
      ]
    }
  ]
}
