{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99200,
          "sha512": "dbaa6cbc3c2dc6ac5e3ed1d5d67535ff5c9330dc5072eb701108fc70cb2b795fb08bc37cd0e76db2cfe8239a4087b05279fcc8037702f235715f8e465d994844",
          "sha256": "710559d038fca6b162e628bc384db4d3314490ee95528ca62c22ab901dd4573a",
          "sha1": "d977d43e6b80c9994e3697bd00200d7535a499a4",
          "md5": "f0084ff8a8d51a0e4d6cb27c363a4873"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99200,
          "sha512": "dbaa6cbc3c2dc6ac5e3ed1d5d67535ff5c9330dc5072eb701108fc70cb2b795fb08bc37cd0e76db2cfe8239a4087b05279fcc8037702f235715f8e465d994844",
          "sha256": "710559d038fca6b162e628bc384db4d3314490ee95528ca62c22ab901dd4573a",
          "sha1": "d977d43e6b80c9994e3697bd00200d7535a499a4",
          "md5": "f0084ff8a8d51a0e4d6cb27c363a4873"
        }
      ]
    }
  ]
}
