{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99200,
          "sha512": "c5b09fd7b3f3f1a5175b94159b33459e7eeda67689df91f6c3f8698cdfa94ff3510bfbb4bb753edcdceb3b674634ca883ceca924af8a4ff919fdb327d60809b4",
          "sha256": "b553703cb15ca87b76d077478ad4614ec11225689faae5c9e8c8ae9b86ae6e2a",
          "sha1": "5e2bb7a1b19951112187ac68590e3a53529bbde4",
          "md5": "4709bf31abb0efa7b89d9509ec7cf2f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99200,
          "sha512": "c5b09fd7b3f3f1a5175b94159b33459e7eeda67689df91f6c3f8698cdfa94ff3510bfbb4bb753edcdceb3b674634ca883ceca924af8a4ff919fdb327d60809b4",
          "sha256": "b553703cb15ca87b76d077478ad4614ec11225689faae5c9e8c8ae9b86ae6e2a",
          "sha1": "5e2bb7a1b19951112187ac68590e3a53529bbde4",
          "md5": "4709bf31abb0efa7b89d9509ec7cf2f5"
        }
      ]
    }
  ]
}
