{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "f6881fc75e859803491d4507b700e12a1799fb2f1f76fe850945de103641d7f46b546daf14bf61289e6580dbec421822fff85a2be6653b9ca6a827d09f8507db",
          "sha256": "cc34503d9be80d418c3b403ac4f0921da0b10f1bc953974592033cb225fb4bcc",
          "sha1": "05b464c852d1eb3568d0111d6f98a625277530d5",
          "md5": "963a9afc5cb9ddbb35537ec0d5901f02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.19.0.jar",
          "url": "http-api-4.19.0.jar",
          "size": 99206,
          "sha512": "f6881fc75e859803491d4507b700e12a1799fb2f1f76fe850945de103641d7f46b546daf14bf61289e6580dbec421822fff85a2be6653b9ca6a827d09f8507db",
          "sha256": "cc34503d9be80d418c3b403ac4f0921da0b10f1bc953974592033cb225fb4bcc",
          "sha1": "05b464c852d1eb3568d0111d6f98a625277530d5",
          "md5": "963a9afc5cb9ddbb35537ec0d5901f02"
        }
      ]
    }
  ]
}
