{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.12.1.jar",
          "url": "http-api-4.12.1.jar",
          "size": 158715,
          "sha512": "633f11f579c5ce69663b7c6b218f97b16468d0e4bf3b419bce5b74044d7c3bfecf9472537d12294f636f368595cb8ec6ebd4c2007c3c1d438c71afe54bdb2785",
          "sha256": "759bd61a6de093b703c61b26b5d83bf423c6e53a398e062a39ce84b4cf0a09c5",
          "sha1": "c0cec6ba1ce8fd94ca5200236566debef841246b",
          "md5": "0da8f20f754591f54a904b71d8d82a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.12.1.jar",
          "url": "http-api-4.12.1.jar",
          "size": 158715,
          "sha512": "633f11f579c5ce69663b7c6b218f97b16468d0e4bf3b419bce5b74044d7c3bfecf9472537d12294f636f368595cb8ec6ebd4c2007c3c1d438c71afe54bdb2785",
          "sha256": "759bd61a6de093b703c61b26b5d83bf423c6e53a398e062a39ce84b4cf0a09c5",
          "sha1": "c0cec6ba1ce8fd94ca5200236566debef841246b",
          "md5": "0da8f20f754591f54a904b71d8d82a0b"
        }
      ]
    }
  ]
}
