{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "ec78ac9f61a2307996784ec8e1675935faf365abb107f4025c9a885e2f45ec04a9c27e6aaea646045d06a58f96f2312da5591ebb27b97e6abd88a27df5b5bd90",
          "sha256": "8e3715d52d43fd99a5f39acee396d3b26dea81e421ecee06077081e3ac64ae64",
          "sha1": "ba6279469172e789a210efc6fc8376e692811bff",
          "md5": "3a0b951e597e299c363003788194f2a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "ec78ac9f61a2307996784ec8e1675935faf365abb107f4025c9a885e2f45ec04a9c27e6aaea646045d06a58f96f2312da5591ebb27b97e6abd88a27df5b5bd90",
          "sha256": "8e3715d52d43fd99a5f39acee396d3b26dea81e421ecee06077081e3ac64ae64",
          "sha1": "ba6279469172e789a210efc6fc8376e692811bff",
          "md5": "3a0b951e597e299c363003788194f2a8"
        }
      ]
    }
  ]
}
