{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "ec4f15f1d4ef0643f2144042985fa1e07e4429fbacc447a1c84118948081b2df72f65269086fe8263b1ad8972f6bf3124238de9feb06be26764b647b6dca27b2",
          "sha256": "4c3ba5ac4d1d0b669dd2025754a37ba73d290f55bb40d1a9710f2171ada860ac",
          "sha1": "928161dda68c46e74f6385fa3665bd346f232a3b",
          "md5": "3e05dcd981b0aa4d17d448614e608419"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "ec4f15f1d4ef0643f2144042985fa1e07e4429fbacc447a1c84118948081b2df72f65269086fe8263b1ad8972f6bf3124238de9feb06be26764b647b6dca27b2",
          "sha256": "4c3ba5ac4d1d0b669dd2025754a37ba73d290f55bb40d1a9710f2171ada860ac",
          "sha1": "928161dda68c46e74f6385fa3665bd346f232a3b",
          "md5": "3e05dcd981b0aa4d17d448614e608419"
        }
      ]
    }
  ]
}
