{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "9504d512a57e2810fcef08a8a1b5e3d1a3b7b85246d3b2c225db9e84db5a82792ee9e34cc8a7f2b6d3ce1e9e72e5ce5fe7d8fabe5a795df281eb721a1fc41e9e",
          "sha256": "08378db81bba10c42a11235de4e8fd1ad3e1495d93a2045154a4eb6ff006bbe6",
          "sha1": "0d55e5a0fd14592e8ee73728161f6f3d10914a56",
          "md5": "a4666f7bd51e306e45bfe96a5c84818d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "9504d512a57e2810fcef08a8a1b5e3d1a3b7b85246d3b2c225db9e84db5a82792ee9e34cc8a7f2b6d3ce1e9e72e5ce5fe7d8fabe5a795df281eb721a1fc41e9e",
          "sha256": "08378db81bba10c42a11235de4e8fd1ad3e1495d93a2045154a4eb6ff006bbe6",
          "sha1": "0d55e5a0fd14592e8ee73728161f6f3d10914a56",
          "md5": "a4666f7bd51e306e45bfe96a5c84818d"
        }
      ]
    }
  ]
}
