{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "c91d725c079a9e2838d4da14fa05a5c09e4dc53543215dce191629d5418abb5fa7e8f4f0c8ac9b9afbd00d3a40ccff11e2d642daed1c7bb91b115b79ee0b5620",
          "sha256": "5fba1e2f370bfba058546b5dabeeba1e56aaf942206f7dd21921eae46f473b58",
          "sha1": "0693070ec0996eecdcff8058590c0c8fd6a8f83b",
          "md5": "7cb251aa47a771c5c8469bafb27b9ebb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 150281,
          "sha512": "c91d725c079a9e2838d4da14fa05a5c09e4dc53543215dce191629d5418abb5fa7e8f4f0c8ac9b9afbd00d3a40ccff11e2d642daed1c7bb91b115b79ee0b5620",
          "sha256": "5fba1e2f370bfba058546b5dabeeba1e56aaf942206f7dd21921eae46f473b58",
          "sha1": "0693070ec0996eecdcff8058590c0c8fd6a8f83b",
          "md5": "7cb251aa47a771c5c8469bafb27b9ebb"
        }
      ]
    }
  ]
}
