{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "9e1e91d78954bc977895110c45051d98787db1c8e24cbc847c1fedf37393bbd974c90d6fd709db8c5ab5e8c2a7b8314b82ede8ddf78124a12afc8ab14ab3880d",
          "sha256": "18dce28c774f2674ad030d27b8f952c1aae75c51bf7868ed46013b996793c269",
          "sha1": "744a57fce1fff70e09f5edb9c1f6ea7882b9944e",
          "md5": "f1c50ab949bcf7714fbfa43d411c9856"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "9e1e91d78954bc977895110c45051d98787db1c8e24cbc847c1fedf37393bbd974c90d6fd709db8c5ab5e8c2a7b8314b82ede8ddf78124a12afc8ab14ab3880d",
          "sha256": "18dce28c774f2674ad030d27b8f952c1aae75c51bf7868ed46013b996793c269",
          "sha1": "744a57fce1fff70e09f5edb9c1f6ea7882b9944e",
          "md5": "f1c50ab949bcf7714fbfa43d411c9856"
        }
      ]
    }
  ]
}
