{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "f6a8e7fbefec3f9b64f7e39d9d503f81bace38630462aa7c2212d0f7d504ede2b85c08cf1e9d61bd51801142ba6e46a9d34ceff3d2436b4ae220a8e313cf1665",
          "sha256": "610ba321764a52d1e63164bffc53c643f6e8027a0b73f38cf5112fbb93fb3949",
          "sha1": "4344beae20fdd6767a3766eb72b3b7de5522d24a",
          "md5": "1ed706eb6f7bc3d50048fd379ecdb888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.1.jar",
          "url": "http-api-4.18.1.jar",
          "size": 99210,
          "sha512": "f6a8e7fbefec3f9b64f7e39d9d503f81bace38630462aa7c2212d0f7d504ede2b85c08cf1e9d61bd51801142ba6e46a9d34ceff3d2436b4ae220a8e313cf1665",
          "sha256": "610ba321764a52d1e63164bffc53c643f6e8027a0b73f38cf5112fbb93fb3949",
          "sha1": "4344beae20fdd6767a3766eb72b3b7de5522d24a",
          "md5": "1ed706eb6f7bc3d50048fd379ecdb888"
        }
      ]
    }
  ]
}
