{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "cea6453ae3944f532d682e33e362549d8af45c93f4c79039a7006c2de0a0481703f20f9c301a385435904dd8cf87bd9233000349d84d1e824b63ee07b74c2cbe",
          "sha256": "d3433b882aa41c18e1d1b7f9066f5c5a37f947b4310d7c6dedfe73825f310c11",
          "sha1": "b75828ec160c8f5c5980c8694aebe4aa2a4f5617",
          "md5": "de59e15c0c7afadf8cce7514be8b119f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "cea6453ae3944f532d682e33e362549d8af45c93f4c79039a7006c2de0a0481703f20f9c301a385435904dd8cf87bd9233000349d84d1e824b63ee07b74c2cbe",
          "sha256": "d3433b882aa41c18e1d1b7f9066f5c5a37f947b4310d7c6dedfe73825f310c11",
          "sha1": "b75828ec160c8f5c5980c8694aebe4aa2a4f5617",
          "md5": "de59e15c0c7afadf8cce7514be8b119f"
        }
      ]
    }
  ]
}
