{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "74ecf7f25bdefe2f1357554152979c7c1465944d75088c3868c0a13fff42bcf141e0fa0ae52ef8fa1bccc57c0c137aa8ede9800d763f0b84da246b919e4cac9a",
          "sha256": "b7f9ad873873577dfe3fb891f7b09c95f3b4b12efa8b2a07bb92819e14f23479",
          "sha1": "8a5d8f9c5948ee23a57e106b82ef065237d12546",
          "md5": "f7b678670bf48c45739f50ee4c170412"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "74ecf7f25bdefe2f1357554152979c7c1465944d75088c3868c0a13fff42bcf141e0fa0ae52ef8fa1bccc57c0c137aa8ede9800d763f0b84da246b919e4cac9a",
          "sha256": "b7f9ad873873577dfe3fb891f7b09c95f3b4b12efa8b2a07bb92819e14f23479",
          "sha1": "8a5d8f9c5948ee23a57e106b82ef065237d12546",
          "md5": "f7b678670bf48c45739f50ee4c170412"
        }
      ]
    }
  ]
}
