{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "5ff3eb2604dabedfc737ec22aac8c73254177c51bf660c12e9b87ca7a24189ddabe6f3056e69eb6fe5314bea61b2ab1d523bf5f1e35f8afdc603a47df4a39e16",
          "sha256": "bcf60ae054e9f8576e2a919984433ca5a7e715556367756dab57d95339ea6ec2",
          "sha1": "36ced1b1836b3c73d1c4bdbdd1683f65995c73a2",
          "md5": "1e91ccba246dd29d47792872067ff57f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "5ff3eb2604dabedfc737ec22aac8c73254177c51bf660c12e9b87ca7a24189ddabe6f3056e69eb6fe5314bea61b2ab1d523bf5f1e35f8afdc603a47df4a39e16",
          "sha256": "bcf60ae054e9f8576e2a919984433ca5a7e715556367756dab57d95339ea6ec2",
          "sha1": "36ced1b1836b3c73d1c4bdbdd1683f65995c73a2",
          "md5": "1e91ccba246dd29d47792872067ff57f"
        }
      ]
    }
  ]
}
