{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.0.jar",
          "url": "http-api-4.31.0.jar",
          "size": 99211,
          "sha512": "0c9d8b4a9b6fb71af9601632a63dd11e47d6bae45c5c4f8d79b8d6af4e319b95f205360501587e3225b89d118bad7813eb35d48741603db988b032204b016415",
          "sha256": "7da58803a29ee132e0b490f9549261f4d84444c4787c23c15c88b743f8302ece",
          "sha1": "59270d3d57004d1f75a15b83a50ed0f20a6e1e6c",
          "md5": "1c9e9b210b1c35eb15cc34a4af766dc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.0.jar",
          "url": "http-api-4.31.0.jar",
          "size": 99211,
          "sha512": "0c9d8b4a9b6fb71af9601632a63dd11e47d6bae45c5c4f8d79b8d6af4e319b95f205360501587e3225b89d118bad7813eb35d48741603db988b032204b016415",
          "sha256": "7da58803a29ee132e0b490f9549261f4d84444c4787c23c15c88b743f8302ece",
          "sha1": "59270d3d57004d1f75a15b83a50ed0f20a6e1e6c",
          "md5": "1c9e9b210b1c35eb15cc34a4af766dc9"
        }
      ]
    }
  ]
}
