{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.0.jar",
          "url": "http-api-4.31.0.jar",
          "size": 99208,
          "sha512": "ce8650f898f81fa207064524019c30cfd3e08dbad064a52677df8520551f89293549ad6ec61020f7316256f17ba41d12758ec076eeff224f58775468f330ff56",
          "sha256": "4a0104f55d5c03080f6e1a200719815dd6a2be2b4dd4d6730fd6e7518895d329",
          "sha1": "a974d2d5c1e34cf82a648f24a2ef209720142e71",
          "md5": "b89ce58e9f1d457333eac3be99dd7e68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.0.jar",
          "url": "http-api-4.31.0.jar",
          "size": 99208,
          "sha512": "ce8650f898f81fa207064524019c30cfd3e08dbad064a52677df8520551f89293549ad6ec61020f7316256f17ba41d12758ec076eeff224f58775468f330ff56",
          "sha256": "4a0104f55d5c03080f6e1a200719815dd6a2be2b4dd4d6730fd6e7518895d329",
          "sha1": "a974d2d5c1e34cf82a648f24a2ef209720142e71",
          "md5": "b89ce58e9f1d457333eac3be99dd7e68"
        }
      ]
    }
  ]
}
