{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.8.1.jar",
          "url": "runescape-api-4.8.1.jar",
          "size": 109392,
          "sha512": "43a5bda67b89051ae64f806eef956302a4a27811237ffabc13e83d582182fe3ab8d30ed5d5c2ca0f14792cd7df92238fbd16b8f99455eb53a0ae0a23cf8bcfba",
          "sha256": "8f81948938623c8c8b7b6d088eb52c77ae52c25db1b874b4325d37f15abcf750",
          "sha1": "88119c698fb0eabe49489b546ba7cb394bdc713c",
          "md5": "812a9dafc90d0eb3dc02fcd73245c86d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.8.1.jar",
          "url": "runescape-api-4.8.1.jar",
          "size": 109392,
          "sha512": "43a5bda67b89051ae64f806eef956302a4a27811237ffabc13e83d582182fe3ab8d30ed5d5c2ca0f14792cd7df92238fbd16b8f99455eb53a0ae0a23cf8bcfba",
          "sha256": "8f81948938623c8c8b7b6d088eb52c77ae52c25db1b874b4325d37f15abcf750",
          "sha1": "88119c698fb0eabe49489b546ba7cb394bdc713c",
          "md5": "812a9dafc90d0eb3dc02fcd73245c86d"
        }
      ]
    }
  ]
}
