{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.8.1.jar",
          "url": "runescape-api-4.8.1.jar",
          "size": 109406,
          "sha512": "fbddea06224ad20f133e28c334ffcf799b7e071fdc35c3442c4824a1db5befd77619b38cbadc30ce026461c1477c2e37f089b66228dee9bbc445313e9cc6faae",
          "sha256": "a023d5777ff91bc8276c414e2188d91fbfd69a1e17099c2cbbf2c656428d98ab",
          "sha1": "e84da08c1aaccebeb7e5589ff5f20f9477031df8",
          "md5": "a83c584d09566b3962ed87e970eb3385"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.8.1.jar",
          "url": "runescape-api-4.8.1.jar",
          "size": 109406,
          "sha512": "fbddea06224ad20f133e28c334ffcf799b7e071fdc35c3442c4824a1db5befd77619b38cbadc30ce026461c1477c2e37f089b66228dee9bbc445313e9cc6faae",
          "sha256": "a023d5777ff91bc8276c414e2188d91fbfd69a1e17099c2cbbf2c656428d98ab",
          "sha1": "e84da08c1aaccebeb7e5589ff5f20f9477031df8",
          "md5": "a83c584d09566b3962ed87e970eb3385"
        }
      ]
    }
  ]
}
