{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.2.jar",
          "url": "runelite-api-4.9.2.jar",
          "size": 1273733,
          "sha512": "1e8f104f957ace916834337755b9815245541d1d9e2e0c0874227aadafa95579edaa43e8b7cd8861286c99eeb72fc3c3adfc211784ec37950e9733b6cdf2ba48",
          "sha256": "bccf7de27721d56d2b61f2ec3ffd00a87d44fa24ffefd8eb66b2a21a7dc89f30",
          "sha1": "ae852664381a2bd3f57b53a1128287121ba10e85",
          "md5": "e1457be64988597af8d5b6079c6e4fb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.2.jar",
          "url": "runelite-api-4.9.2.jar",
          "size": 1273733,
          "sha512": "1e8f104f957ace916834337755b9815245541d1d9e2e0c0874227aadafa95579edaa43e8b7cd8861286c99eeb72fc3c3adfc211784ec37950e9733b6cdf2ba48",
          "sha256": "bccf7de27721d56d2b61f2ec3ffd00a87d44fa24ffefd8eb66b2a21a7dc89f30",
          "sha1": "ae852664381a2bd3f57b53a1128287121ba10e85",
          "md5": "e1457be64988597af8d5b6079c6e4fb2"
        }
      ]
    }
  ]
}
