{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "e01bfadc8fec3012f3ffe6a5fea034606dd13b343cec146088b112b953ae538d9d52023f443eb7400d244f318d8c0b613369beb7a44e9a44a88ce67229b82ec2",
          "sha256": "6d7120730b0a50c6cc829a41215f321d7177066e12cce7639330d3f55b89d232",
          "sha1": "e25ef2504f1e09e126869e98e204b9cc8bffff03",
          "md5": "c132cd7b942d7ddcea4d79cab189fa67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "e01bfadc8fec3012f3ffe6a5fea034606dd13b343cec146088b112b953ae538d9d52023f443eb7400d244f318d8c0b613369beb7a44e9a44a88ce67229b82ec2",
          "sha256": "6d7120730b0a50c6cc829a41215f321d7177066e12cce7639330d3f55b89d232",
          "sha1": "e25ef2504f1e09e126869e98e204b9cc8bffff03",
          "md5": "c132cd7b942d7ddcea4d79cab189fa67"
        }
      ]
    }
  ]
}
