{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "d0b520d51f4acb087589e2a1c4dccd361941232a26bee4e8b424d31ee9f3d657f53024d693b34bb686ad0b647641d90f714c9ab3ec03c14f3e0e5e08a8c13162",
          "sha256": "a6cc26ab60e7ebe7937c5b28eb558f5929f6f5bfb7df0a20b5af5d0c156f456a",
          "sha1": "214230c350672640138944884a5e495a2bfd8085",
          "md5": "8d3a71de0f03d109b0676e5c8e27241c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "d0b520d51f4acb087589e2a1c4dccd361941232a26bee4e8b424d31ee9f3d657f53024d693b34bb686ad0b647641d90f714c9ab3ec03c14f3e0e5e08a8c13162",
          "sha256": "a6cc26ab60e7ebe7937c5b28eb558f5929f6f5bfb7df0a20b5af5d0c156f456a",
          "sha1": "214230c350672640138944884a5e495a2bfd8085",
          "md5": "8d3a71de0f03d109b0676e5c8e27241c"
        }
      ]
    }
  ]
}
