{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "59d718cc037db4357153ec1d512181d7917675e200827bcfafe0254172a1450304d29b490355e304a02728a5eb9f4d6059f4300852f4f0d1d474457f317a7024",
          "sha256": "974ad9e098e439413cefaddefad15db1df0464bec491edd741c372b12fceb4e3",
          "sha1": "79138358b22eb59de6177e476125bb4eb85e7707",
          "md5": "0743c2bbfaf1cd607363a14b45d7b8a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "59d718cc037db4357153ec1d512181d7917675e200827bcfafe0254172a1450304d29b490355e304a02728a5eb9f4d6059f4300852f4f0d1d474457f317a7024",
          "sha256": "974ad9e098e439413cefaddefad15db1df0464bec491edd741c372b12fceb4e3",
          "sha1": "79138358b22eb59de6177e476125bb4eb85e7707",
          "md5": "0743c2bbfaf1cd607363a14b45d7b8a5"
        }
      ]
    }
  ]
}
