{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.4.jar",
          "url": "http-api-4.9.4.jar",
          "size": 157568,
          "sha512": "aef70df24c8de9f966a2f05dd51e6e65cdb41c731ea21bd77fd04e2abcad296d108c188621394c5cc340a831bb3672f9d35cb66c5daefa36a00932d511595f6d",
          "sha256": "95f9e86f82799982da44f0e4e96a58b8520aec188860a55d055bd4201638c915",
          "sha1": "33622bf890acdfd1f1b478504deb427a332e47aa",
          "md5": "400f85b33dd8b4fe3a0f33e8d7dc7c5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.4.jar",
          "url": "http-api-4.9.4.jar",
          "size": 157568,
          "sha512": "aef70df24c8de9f966a2f05dd51e6e65cdb41c731ea21bd77fd04e2abcad296d108c188621394c5cc340a831bb3672f9d35cb66c5daefa36a00932d511595f6d",
          "sha256": "95f9e86f82799982da44f0e4e96a58b8520aec188860a55d055bd4201638c915",
          "sha1": "33622bf890acdfd1f1b478504deb427a332e47aa",
          "md5": "400f85b33dd8b4fe3a0f33e8d7dc7c5e"
        }
      ]
    }
  ]
}
