{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346817,
          "sha512": "f926f7b1af0c0bc031674d8b74d43f7dfdf2205839c2b9149b27f818abb3387f50a835d7d4b77f1447f3c400d4f634bc2e05b0fbadafefaa20c674f855ac6ae8",
          "sha256": "f5e1b958b4fb9de7e0b39fb311ace1016f8b27c929b30db6d847ea3e8489e89b",
          "sha1": "cf6800c2bb545b036c7a48776a1115879e883449",
          "md5": "6d854707fd4c45e6f2964d9e89a4890e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346817,
          "sha512": "f926f7b1af0c0bc031674d8b74d43f7dfdf2205839c2b9149b27f818abb3387f50a835d7d4b77f1447f3c400d4f634bc2e05b0fbadafefaa20c674f855ac6ae8",
          "sha256": "f5e1b958b4fb9de7e0b39fb311ace1016f8b27c929b30db6d847ea3e8489e89b",
          "sha1": "cf6800c2bb545b036c7a48776a1115879e883449",
          "md5": "6d854707fd4c45e6f2964d9e89a4890e"
        }
      ]
    }
  ]
}
