{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346825,
          "sha512": "fe87fd73ee38339124f875f8e46ab772f9ea15f705a68274a197713c01d3d8de9b7c40796c604be1beb3adfb504bd6cc531be797949fc1763eb428bc689831d5",
          "sha256": "5f40046a5555b28665260e1d6a899278a2337a32a5efd0d9830bc766ef10b346",
          "sha1": "e45eea653ca4afb1cc18b852ab83824dc081db12",
          "md5": "ee9a34a743be0b2aa645a130e07815ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346825,
          "sha512": "fe87fd73ee38339124f875f8e46ab772f9ea15f705a68274a197713c01d3d8de9b7c40796c604be1beb3adfb504bd6cc531be797949fc1763eb428bc689831d5",
          "sha256": "5f40046a5555b28665260e1d6a899278a2337a32a5efd0d9830bc766ef10b346",
          "sha1": "e45eea653ca4afb1cc18b852ab83824dc081db12",
          "md5": "ee9a34a743be0b2aa645a130e07815ae"
        }
      ]
    }
  ]
}
