{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346825,
          "sha512": "52d04888f140fa72cc96edfe9435fe18bbd5eafd1fc863398c8b214d8a70298d0c94ed196283bdc6fc6497e3d267b21629f5cc11a79b2160ee509d05e389b1c5",
          "sha256": "63955bb00aed8ca071f55ccdffb54bfc2fde8b1db7a0d38d0216828202193e0a",
          "sha1": "6c271abbeb127b3b04dd3f582efc5ce9888a213c",
          "md5": "28bcab2d51bb3d2dfa11a03eb1913765"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346825,
          "sha512": "52d04888f140fa72cc96edfe9435fe18bbd5eafd1fc863398c8b214d8a70298d0c94ed196283bdc6fc6497e3d267b21629f5cc11a79b2160ee509d05e389b1c5",
          "sha256": "63955bb00aed8ca071f55ccdffb54bfc2fde8b1db7a0d38d0216828202193e0a",
          "sha1": "6c271abbeb127b3b04dd3f582efc5ce9888a213c",
          "md5": "28bcab2d51bb3d2dfa11a03eb1913765"
        }
      ]
    }
  ]
}
