{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.6.0.jar",
          "url": "http-api-4.6.0.jar",
          "size": 159717,
          "sha512": "0336a909b8e15ab4b1344735cdfb37a2afebe6d1b3cd13c5dd24b6ecd10a7dde9d7710704995f7ac4c8972f84910ce391d9436528213b1e371d3adb364707bbf",
          "sha256": "87fe2d11473bd2910ba7c52e4bf24596fef8d44fbc5427567567ed348d90d4af",
          "sha1": "c0bafeabf7e5aa5391f3f6e1bc0e10a13074e54f",
          "md5": "6e9d7dadf1f4d02abdb005966cd9091b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.6.0.jar",
          "url": "http-api-4.6.0.jar",
          "size": 159717,
          "sha512": "0336a909b8e15ab4b1344735cdfb37a2afebe6d1b3cd13c5dd24b6ecd10a7dde9d7710704995f7ac4c8972f84910ce391d9436528213b1e371d3adb364707bbf",
          "sha256": "87fe2d11473bd2910ba7c52e4bf24596fef8d44fbc5427567567ed348d90d4af",
          "sha1": "c0bafeabf7e5aa5391f3f6e1bc0e10a13074e54f",
          "md5": "6e9d7dadf1f4d02abdb005966cd9091b"
        }
      ]
    }
  ]
}
