{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.6.0.jar",
          "url": "http-api-4.6.0.jar",
          "size": 159717,
          "sha512": "dcbfc091769430e0cc3ac7babb4ee59595912d135ecf667f219f76d9747333b3c6c6b497a22d266e1a3f39602a94456b53990a5482bb1228abe39df90298d667",
          "sha256": "7a7984d66cb49ed4c2fe41280123ca13ecfa780d306a1164562409e651f25c2f",
          "sha1": "a83617770347391a0c5dfa0b2695c163d5ecf9b1",
          "md5": "906dbacd798601d45eda8a1995909325"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.6.0.jar",
          "url": "http-api-4.6.0.jar",
          "size": 159717,
          "sha512": "dcbfc091769430e0cc3ac7babb4ee59595912d135ecf667f219f76d9747333b3c6c6b497a22d266e1a3f39602a94456b53990a5482bb1228abe39df90298d667",
          "sha256": "7a7984d66cb49ed4c2fe41280123ca13ecfa780d306a1164562409e651f25c2f",
          "sha1": "a83617770347391a0c5dfa0b2695c163d5ecf9b1",
          "md5": "906dbacd798601d45eda8a1995909325"
        }
      ]
    }
  ]
}
