{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "c4o2hasjxndfzfrfcst6yo6fd4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.2.jar",
          "url": "runelite-api-3.5.2.jar",
          "size": 1236458,
          "sha512": "2b7b09d1e2c9658710b02ac41ee948be4dcacc13f522a44260afc34383639dd1e96076e8902059fd33570a1d09e95c8663d2efbbcc16b89a9e4253a9153aa9de",
          "sha256": "576dd6bee30b9f38a0a094b946e945ecc345dc660d3d780664ce39e468dec1cc",
          "sha1": "8c4e1d1a7ed568a5757d893c9e5817e310803904",
          "md5": "779eb3b58200dd7339c03621d79b9b80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.2.jar",
          "url": "runelite-api-3.5.2.jar",
          "size": 1236458,
          "sha512": "2b7b09d1e2c9658710b02ac41ee948be4dcacc13f522a44260afc34383639dd1e96076e8902059fd33570a1d09e95c8663d2efbbcc16b89a9e4253a9153aa9de",
          "sha256": "576dd6bee30b9f38a0a094b946e945ecc345dc660d3d780664ce39e468dec1cc",
          "sha1": "8c4e1d1a7ed568a5757d893c9e5817e310803904",
          "md5": "779eb3b58200dd7339c03621d79b9b80"
        }
      ]
    }
  ]
}
