{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vnqfelpitvb7tb7mmkrzbtnnue"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 136867,
          "sha512": "0707844d4949da2afa48de075874076f98ad40eec640bf8d90701c86a5ef445b3add419cf8591e1b7dd42aa01b59a150077d021d3f47502b3f7885e0d76af02b",
          "sha256": "551161cb80bca21bc196435464bf28171236e7c97701b3d4c9b2954e6580b35d",
          "sha1": "b064feb8712c177d95253756be9e821174dbca2e",
          "md5": "81284747f71b498464e0be20f9778398"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 136867,
          "sha512": "0707844d4949da2afa48de075874076f98ad40eec640bf8d90701c86a5ef445b3add419cf8591e1b7dd42aa01b59a150077d021d3f47502b3f7885e0d76af02b",
          "sha256": "551161cb80bca21bc196435464bf28171236e7c97701b3d4c9b2954e6580b35d",
          "sha1": "b064feb8712c177d95253756be9e821174dbca2e",
          "md5": "81284747f71b498464e0be20f9778398"
        }
      ]
    }
  ]
}
