{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.1.jar",
          "url": "runescape-api-4.20.1.jar",
          "size": 148390,
          "sha512": "81bc2e98848686ccf90b8241c6b7fd4d8611be5f9c39ff4a83f00e43fe1087ccb040a6ffe2abc06035c07a8d6f19ab290e0ecb9104a9834b64571880b3d919fe",
          "sha256": "b2c68f39feb7b0303f8ce56a721bfb42de8057343cd32f74ccae304b132d878a",
          "sha1": "776e83f58d6aa05b32b9c1b5dff8c4d8f4e5ae67",
          "md5": "13a5aaa2a876689d94baf1e2a285bb00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.1.jar",
          "url": "runescape-api-4.20.1.jar",
          "size": 148390,
          "sha512": "81bc2e98848686ccf90b8241c6b7fd4d8611be5f9c39ff4a83f00e43fe1087ccb040a6ffe2abc06035c07a8d6f19ab290e0ecb9104a9834b64571880b3d919fe",
          "sha256": "b2c68f39feb7b0303f8ce56a721bfb42de8057343cd32f74ccae304b132d878a",
          "sha1": "776e83f58d6aa05b32b9c1b5dff8c4d8f4e5ae67",
          "md5": "13a5aaa2a876689d94baf1e2a285bb00"
        }
      ]
    }
  ]
}
