{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "750d23cea5e9c90b32d0e4e4466f9b8aa3b2ce95d8d482b5999c5708052c31e82ec665c9157083dea155de3f25b6b83f0a4b4f864006cc423d3a15230e100f5d",
          "sha256": "607cb1e3f8e430589368247c7092889fa1edfc28faec05aad38657ac52dd47e7",
          "sha1": "70f8ef9c2aa52d8cc05d34d0ac267962a04a1b22",
          "md5": "bee55ae2935d42ba42ec17e2947485f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "750d23cea5e9c90b32d0e4e4466f9b8aa3b2ce95d8d482b5999c5708052c31e82ec665c9157083dea155de3f25b6b83f0a4b4f864006cc423d3a15230e100f5d",
          "sha256": "607cb1e3f8e430589368247c7092889fa1edfc28faec05aad38657ac52dd47e7",
          "sha1": "70f8ef9c2aa52d8cc05d34d0ac267962a04a1b22",
          "md5": "bee55ae2935d42ba42ec17e2947485f6"
        }
      ]
    }
  ]
}
