{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "3e5f1d548f7bcd89ae11aa1ac5ec96f01471e7ed364ff778d5a9ae9da89990f3d6197a00a7c4b99d43bf305fc4d0292db0b6413f5930b50101bf7bfbbe2cb17b",
          "sha256": "efb473b3f3ed632f48c5a250a700321ba3ab03d96352c8f5b04ac5974ab7a47f",
          "sha1": "cbacf0e680c11d62cee0f3fbfda7e604127af45b",
          "md5": "87b0d5e7205f2b6eb137c8655bceedfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "3e5f1d548f7bcd89ae11aa1ac5ec96f01471e7ed364ff778d5a9ae9da89990f3d6197a00a7c4b99d43bf305fc4d0292db0b6413f5930b50101bf7bfbbe2cb17b",
          "sha256": "efb473b3f3ed632f48c5a250a700321ba3ab03d96352c8f5b04ac5974ab7a47f",
          "sha1": "cbacf0e680c11d62cee0f3fbfda7e604127af45b",
          "md5": "87b0d5e7205f2b6eb137c8655bceedfc"
        }
      ]
    }
  ]
}
