{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "fda63297914f7f78da953971b577f561851f40c0f9b8163c944061492d42c63649139ac93e4a33074d24f8ae42e79faf40deda1dd7f06d63493410c2976d0538",
          "sha256": "930836a066365faeae830860118a91cdf5037b0dadd37a9333d9a730a0c2d6e4",
          "sha1": "599e52387ac757080312168d206107b075609f63",
          "md5": "a3e818d19235f1ecc19695cf5f9c7821"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "fda63297914f7f78da953971b577f561851f40c0f9b8163c944061492d42c63649139ac93e4a33074d24f8ae42e79faf40deda1dd7f06d63493410c2976d0538",
          "sha256": "930836a066365faeae830860118a91cdf5037b0dadd37a9333d9a730a0c2d6e4",
          "sha1": "599e52387ac757080312168d206107b075609f63",
          "md5": "a3e818d19235f1ecc19695cf5f9c7821"
        }
      ]
    }
  ]
}
