{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "7fd8e426e722f8b95963929c0712759286dc4dcdf6dd792718f8a75d4dcc9cf9e02e2384ebf9bf93b47f28629d9d68496797dbc2205c4bf9310757de2a4eefac",
          "sha256": "e77a6c9329ec24aead86e116c0edc0df66bbebb55478e2bb45a97c77fd6f801b",
          "sha1": "095b1ea8996b0563aa4419cd208f4215d9fc62b1",
          "md5": "fb2d147e908c1b60817c537461936867"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.2.jar",
          "url": "runescape-api-4.20.2.jar",
          "size": 149157,
          "sha512": "7fd8e426e722f8b95963929c0712759286dc4dcdf6dd792718f8a75d4dcc9cf9e02e2384ebf9bf93b47f28629d9d68496797dbc2205c4bf9310757de2a4eefac",
          "sha256": "e77a6c9329ec24aead86e116c0edc0df66bbebb55478e2bb45a97c77fd6f801b",
          "sha1": "095b1ea8996b0563aa4419cd208f4215d9fc62b1",
          "md5": "fb2d147e908c1b60817c537461936867"
        }
      ]
    }
  ]
}
