{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "38ab18e10448ba1046a122179aab5ec5fbf60bc09947246955eb456ea7668ba1fcb2c01c6e79be602feebe7c0233b4915ff02213f3a259bba03cad154ba6b764",
          "sha256": "53b228512124b0cb292e7b8236814a88bf72e05d9a6e6e3f1fcd4e380d6cd477",
          "sha1": "baee57a1b8350b27b6e23f34dc76e214b99d679f",
          "md5": "a23052eda6b0d8a6ae0d1eeccd956e36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "38ab18e10448ba1046a122179aab5ec5fbf60bc09947246955eb456ea7668ba1fcb2c01c6e79be602feebe7c0233b4915ff02213f3a259bba03cad154ba6b764",
          "sha256": "53b228512124b0cb292e7b8236814a88bf72e05d9a6e6e3f1fcd4e380d6cd477",
          "sha1": "baee57a1b8350b27b6e23f34dc76e214b99d679f",
          "md5": "a23052eda6b0d8a6ae0d1eeccd956e36"
        }
      ]
    }
  ]
}
