{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "c3fced69b873ae9092c6965c1162d644cdb43cf5f1eb9c8fdbafa483e9a272c6b878ea69726e39dd83976dfa003ff09e2c6d22f8ed2d74dca3e3947135eaca6d",
          "sha256": "0dde6a3a3edafbbd9a7923424dc7218d11d32ce612d94dd536b6c3672d3962a9",
          "sha1": "cbefc31d9dc17129c66333a79e2943711f0370c7",
          "md5": "75eaad3a2bba62bb5a0ee3a3ca1b8bae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "c3fced69b873ae9092c6965c1162d644cdb43cf5f1eb9c8fdbafa483e9a272c6b878ea69726e39dd83976dfa003ff09e2c6d22f8ed2d74dca3e3947135eaca6d",
          "sha256": "0dde6a3a3edafbbd9a7923424dc7218d11d32ce612d94dd536b6c3672d3962a9",
          "sha1": "cbefc31d9dc17129c66333a79e2943711f0370c7",
          "md5": "75eaad3a2bba62bb5a0ee3a3ca1b8bae"
        }
      ]
    }
  ]
}
