{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "77aff4f8f37301d92a5ef08a4ec9cc9f0e52aae85257abb15dd2bd858c93e74e7805291cee7f3d3d7e67af67a2597951a83eafbc40bab77ea3cc8b9a13b02b22",
          "sha256": "a18ead3d81ec29126d910a217a9b35b5da00b0b6eafcbce5d52511e7d920c3d9",
          "sha1": "229e24ea007c94022902b434b01712171aa9f1a3",
          "md5": "362bc85043c440c71ceb8c97ad02139d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.19.0.jar",
          "url": "runelite-api-4.19.0.jar",
          "size": 1340677,
          "sha512": "77aff4f8f37301d92a5ef08a4ec9cc9f0e52aae85257abb15dd2bd858c93e74e7805291cee7f3d3d7e67af67a2597951a83eafbc40bab77ea3cc8b9a13b02b22",
          "sha256": "a18ead3d81ec29126d910a217a9b35b5da00b0b6eafcbce5d52511e7d920c3d9",
          "sha1": "229e24ea007c94022902b434b01712171aa9f1a3",
          "md5": "362bc85043c440c71ceb8c97ad02139d"
        }
      ]
    }
  ]
}
