{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.1.jar",
          "url": "http-api-4.31.1.jar",
          "size": 99199,
          "sha512": "d7a93b4c5f8f40b269b2dc961d65616f133c401230192cde7e50d96f9ba172755464da96dc7d47195cd90a9fc2c088536333629fe35bfaa2d4db461b726c10b2",
          "sha256": "ed0e157c6d6b7fcd3cb7acb46c1ebac6158d60eaf02320ee41f04b17ca48aca3",
          "sha1": "fcb920850f30b2e5ff28534c4cd713b9d1d7629d",
          "md5": "4e8581bae27c3d555bcecd216b3e8c23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.1.jar",
          "url": "http-api-4.31.1.jar",
          "size": 99199,
          "sha512": "d7a93b4c5f8f40b269b2dc961d65616f133c401230192cde7e50d96f9ba172755464da96dc7d47195cd90a9fc2c088536333629fe35bfaa2d4db461b726c10b2",
          "sha256": "ed0e157c6d6b7fcd3cb7acb46c1ebac6158d60eaf02320ee41f04b17ca48aca3",
          "sha1": "fcb920850f30b2e5ff28534c4cd713b9d1d7629d",
          "md5": "4e8581bae27c3d555bcecd216b3e8c23"
        }
      ]
    }
  ]
}
