{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 99212,
          "sha512": "8a0c9b1e88dbfe1fb214b4a93e26e82f9cf185b57fb747aeeeb0c5e16e0e6d8672b34ad738c8ef02aa5e0325d636ccb9a04e78fb6ee099900fe3b8a3bee56f58",
          "sha256": "0afdd757dfdc2c6f9270978fbb01f9b0b50941001dae98e79de2909e005d351d",
          "sha1": "d5da01f024478c8a525c2e031dfcf3e7a3238a9d",
          "md5": "795b3149f2430477cfd8107f5a3764e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 99212,
          "sha512": "8a0c9b1e88dbfe1fb214b4a93e26e82f9cf185b57fb747aeeeb0c5e16e0e6d8672b34ad738c8ef02aa5e0325d636ccb9a04e78fb6ee099900fe3b8a3bee56f58",
          "sha256": "0afdd757dfdc2c6f9270978fbb01f9b0b50941001dae98e79de2909e005d351d",
          "sha1": "d5da01f024478c8a525c2e031dfcf3e7a3238a9d",
          "md5": "795b3149f2430477cfd8107f5a3764e7"
        }
      ]
    }
  ]
}
