{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 99212,
          "sha512": "b14113ecdaaeb0fff04547db10696432b11f308d6b1f7c70f7c955a68afa1337cd1777baf5c462f8eb472aba4ff953c643750d9b080783bf23b93a21058537cb",
          "sha256": "f28338e539836a4c76faadee6cf957098c8955477b00aee0a1a45e88c615708b",
          "sha1": "a7d4f4d75b4d66201806d3e6708a4549f42416ff",
          "md5": "047280dd1daf8ab167783688c56bdfb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 99212,
          "sha512": "b14113ecdaaeb0fff04547db10696432b11f308d6b1f7c70f7c955a68afa1337cd1777baf5c462f8eb472aba4ff953c643750d9b080783bf23b93a21058537cb",
          "sha256": "f28338e539836a4c76faadee6cf957098c8955477b00aee0a1a45e88c615708b",
          "sha1": "a7d4f4d75b4d66201806d3e6708a4549f42416ff",
          "md5": "047280dd1daf8ab167783688c56bdfb8"
        }
      ]
    }
  ]
}
