{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "e7c632848963899dee8d6ced4a57e95a75153d20bbad9002c6b37001c17c0bb28ddc47b6dfea71d44783c17786e6836607919e7c33b15a506b294b3db28499a7",
          "sha256": "a116a4f186f2b6b3db073461515bf1edd627aff910f90768e3def33a36073282",
          "sha1": "4fb65540cc3563be84847bc359e18ce1bbce303c",
          "md5": "37d5a8d86a0981e360582633271dc36f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "e7c632848963899dee8d6ced4a57e95a75153d20bbad9002c6b37001c17c0bb28ddc47b6dfea71d44783c17786e6836607919e7c33b15a506b294b3db28499a7",
          "sha256": "a116a4f186f2b6b3db073461515bf1edd627aff910f90768e3def33a36073282",
          "sha1": "4fb65540cc3563be84847bc359e18ce1bbce303c",
          "md5": "37d5a8d86a0981e360582633271dc36f"
        }
      ]
    }
  ]
}
