{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "b0238b18d3303b21cccfe48c8527fcc5d09f0b34d5a9b18537a82e7873b0f67e9f92563c6d0e30f6d5fb34600f66773459254ba3c4a4bef4247df9e4a76c5ea6",
          "sha256": "75a353a41ce596e5a5d9de13d4dd869f36b48e3fde3b13488dfc6876270ec610",
          "sha1": "ad8dc6ef199df37ab1ed6e8e660539489a3311f0",
          "md5": "68761e25b4d12875bc2cfba1cd74c31f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "b0238b18d3303b21cccfe48c8527fcc5d09f0b34d5a9b18537a82e7873b0f67e9f92563c6d0e30f6d5fb34600f66773459254ba3c4a4bef4247df9e4a76c5ea6",
          "sha256": "75a353a41ce596e5a5d9de13d4dd869f36b48e3fde3b13488dfc6876270ec610",
          "sha1": "ad8dc6ef199df37ab1ed6e8e660539489a3311f0",
          "md5": "68761e25b4d12875bc2cfba1cd74c31f"
        }
      ]
    }
  ]
}
