{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "d6cd6432435c96360a1aef09263018ccc57a5186dcb63ba7822e1a577e2d34fda803eeedd9b0707b6df47442972ce9d8e658d6209f1811bef82ffe5e65ccea41",
          "sha256": "4579077d3bdf62fe007b65dc84f82b537db42a3d8067cfaed23f05de2dcf10e0",
          "sha1": "a3c6ec8fc41d7970bc1682f2762b043413e6367c",
          "md5": "70a3f81b90fcb01b818d887f210e1dd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.24.1.jar",
          "url": "runelite-jshell-4.24.1.jar",
          "size": 26557,
          "sha512": "d6cd6432435c96360a1aef09263018ccc57a5186dcb63ba7822e1a577e2d34fda803eeedd9b0707b6df47442972ce9d8e658d6209f1811bef82ffe5e65ccea41",
          "sha256": "4579077d3bdf62fe007b65dc84f82b537db42a3d8067cfaed23f05de2dcf10e0",
          "sha1": "a3c6ec8fc41d7970bc1682f2762b043413e6367c",
          "md5": "70a3f81b90fcb01b818d887f210e1dd2"
        }
      ]
    }
  ]
}
