{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.6.jar",
          "url": "runelite-api-4.9.6.jar",
          "size": 1278158,
          "sha512": "8bcbf6870ab5f56a7863d105cb9ede5b3a8275af90ba2284ca752f939cd69ca8ada051d1e3ef0e485f57b72d17130b2f9fa2f8b6862f5aa29acfca855750da15",
          "sha256": "7d95af661bbd96773eab222e40e5e00edf401c4597b011fbfc60767fc796f508",
          "sha1": "98a2f5935a2a49f7ac2a645c377f8dd336956dc2",
          "md5": "b1f4816ac8fb68ff56b952bef37a3b49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.6.jar",
          "url": "runelite-api-4.9.6.jar",
          "size": 1278158,
          "sha512": "8bcbf6870ab5f56a7863d105cb9ede5b3a8275af90ba2284ca752f939cd69ca8ada051d1e3ef0e485f57b72d17130b2f9fa2f8b6862f5aa29acfca855750da15",
          "sha256": "7d95af661bbd96773eab222e40e5e00edf401c4597b011fbfc60767fc796f508",
          "sha1": "98a2f5935a2a49f7ac2a645c377f8dd336956dc2",
          "md5": "b1f4816ac8fb68ff56b952bef37a3b49"
        }
      ]
    }
  ]
}
