{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99202,
          "sha512": "bfc9ea510bd391ee8cb7d36dafaae1f3e50a4b553a679953b28527068d23ee28a46bb436333e542637f8c6bccf8423e9f4f526f8588cc3b6286ed08df392189f",
          "sha256": "746746836b403ab0c0dcee0b9406f0024bae50edae009e9c1da14d2c326ed9b0",
          "sha1": "baf120f5fe3eacea882fdd505dcd4253b614a365",
          "md5": "22ed21b9c280dbff1378a796f01a46db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99202,
          "sha512": "bfc9ea510bd391ee8cb7d36dafaae1f3e50a4b553a679953b28527068d23ee28a46bb436333e542637f8c6bccf8423e9f4f526f8588cc3b6286ed08df392189f",
          "sha256": "746746836b403ab0c0dcee0b9406f0024bae50edae009e9c1da14d2c326ed9b0",
          "sha1": "baf120f5fe3eacea882fdd505dcd4253b614a365",
          "md5": "22ed21b9c280dbff1378a796f01a46db"
        }
      ]
    }
  ]
}
