{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99205,
          "sha512": "cd31dfc0a569068696463e457d4deae3d9efb353308ce6ec54329c57792249177823e1241d6fbc0e9ad9df219083c2d85fa9d47dd98fb47fe13d472b9be65704",
          "sha256": "715f1f9210116f085c807f8c37c3694c0fc8d439521c4d9b7a8c884f0993ad21",
          "sha1": "17fb871133393279ef4762d1cba66ce329a03ccd",
          "md5": "688640d0da93a31b60f650e2566c48cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99205,
          "sha512": "cd31dfc0a569068696463e457d4deae3d9efb353308ce6ec54329c57792249177823e1241d6fbc0e9ad9df219083c2d85fa9d47dd98fb47fe13d472b9be65704",
          "sha256": "715f1f9210116f085c807f8c37c3694c0fc8d439521c4d9b7a8c884f0993ad21",
          "sha1": "17fb871133393279ef4762d1cba66ce329a03ccd",
          "md5": "688640d0da93a31b60f650e2566c48cd"
        }
      ]
    }
  ]
}
