{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99202,
          "sha512": "6189794f9f772867d874370d94f427ae6536002b625488e85f6908ac8f4c44cede365e2329d3c0c36d421ded3f906bcce1120fffc37a8f82dd69ea06636e045c",
          "sha256": "561b6a0d424cde5a8ed3585272f97c205d0b77687c75b52cd16a855f3370fe7a",
          "sha1": "da7b83e7e2e0e687a2e17bf1ff77c7df2b1f1c26",
          "md5": "58a8264cbe43e4e6a67dfbe2d8c8ae53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99202,
          "sha512": "6189794f9f772867d874370d94f427ae6536002b625488e85f6908ac8f4c44cede365e2329d3c0c36d421ded3f906bcce1120fffc37a8f82dd69ea06636e045c",
          "sha256": "561b6a0d424cde5a8ed3585272f97c205d0b77687c75b52cd16a855f3370fe7a",
          "sha1": "da7b83e7e2e0e687a2e17bf1ff77c7df2b1f1c26",
          "md5": "58a8264cbe43e4e6a67dfbe2d8c8ae53"
        }
      ]
    }
  ]
}
