{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.1.jar",
          "url": "http-api-4.20.1.jar",
          "size": 99206,
          "sha512": "7a58135292207389a61aa25bee0528159def712862a8ec39102c0a307f45dbd38bca72ea0ce00ee6b02899275f19d3d821354d2c0012d2e9c7579e16bcaa1514",
          "sha256": "db84e51fbd9cd96320fd1b7bc92e36e5a24594e0ba1710f878ff80b7a49337a6",
          "sha1": "52403c82fbc9fc8e7fb173c1a7692b2307d7e974",
          "md5": "26818d2438edddff85013beb5b4693b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.1.jar",
          "url": "http-api-4.20.1.jar",
          "size": 99206,
          "sha512": "7a58135292207389a61aa25bee0528159def712862a8ec39102c0a307f45dbd38bca72ea0ce00ee6b02899275f19d3d821354d2c0012d2e9c7579e16bcaa1514",
          "sha256": "db84e51fbd9cd96320fd1b7bc92e36e5a24594e0ba1710f878ff80b7a49337a6",
          "sha1": "52403c82fbc9fc8e7fb173c1a7692b2307d7e974",
          "md5": "26818d2438edddff85013beb5b4693b3"
        }
      ]
    }
  ]
}
