{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159717,
          "sha512": "eee4bc746ab25d4ddac4348ff69f2acf097ca6dff47d9b58c931bfbf342a94ea0845fa5e232b51937d0e2f6737da777250e8edeb683cde5b355434cfe429abc7",
          "sha256": "78f50a77d62d42b8aecc37e80e77043a3dca41c775600c221dd32bcc6a99c44e",
          "sha1": "63314fcf565708adfe46bb80d5975956c9d8c135",
          "md5": "3b3c6bf0a9fdd677689d8987c3466061"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159717,
          "sha512": "eee4bc746ab25d4ddac4348ff69f2acf097ca6dff47d9b58c931bfbf342a94ea0845fa5e232b51937d0e2f6737da777250e8edeb683cde5b355434cfe429abc7",
          "sha256": "78f50a77d62d42b8aecc37e80e77043a3dca41c775600c221dd32bcc6a99c44e",
          "sha1": "63314fcf565708adfe46bb80d5975956c9d8c135",
          "md5": "3b3c6bf0a9fdd677689d8987c3466061"
        }
      ]
    }
  ]
}
