{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "acfc53a3f5668451465d13aac434f7ad5f1a6e91a7f91c6e09423671e134872210daea3c0dff03c37bd972d861e902f14078cd9f5ab4ab3d1b7cbcbe3e581dcf",
          "sha256": "51c1cac8d73f64f81044685cd33794d38363b5b855440e2e3450dcb5205b46ef",
          "sha1": "cd3104fc3453a3678b6fdb331660522ef66b6c56",
          "md5": "61f41a669eb32daa8cae651a98012b7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "acfc53a3f5668451465d13aac434f7ad5f1a6e91a7f91c6e09423671e134872210daea3c0dff03c37bd972d861e902f14078cd9f5ab4ab3d1b7cbcbe3e581dcf",
          "sha256": "51c1cac8d73f64f81044685cd33794d38363b5b855440e2e3450dcb5205b46ef",
          "sha1": "cd3104fc3453a3678b6fdb331660522ef66b6c56",
          "md5": "61f41a669eb32daa8cae651a98012b7c"
        }
      ]
    }
  ]
}
