{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "938f8b0693463ec058459fcd2918fbe576c7798c0946dc910daadad748d7b10b0ea35b8d9f8871d9f0415bee76332511c381a53d690f5bf5e539fd34a99da10d",
          "sha256": "f0e30ed25191272c809b7fec8d2f76918bd85c4ac95fc9119048d88d9c41a766",
          "sha1": "d8394b3600c26ff180862fd297b0c246db6e126e",
          "md5": "3a9e436f7a14b0d9425da90be2b3a218"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "938f8b0693463ec058459fcd2918fbe576c7798c0946dc910daadad748d7b10b0ea35b8d9f8871d9f0415bee76332511c381a53d690f5bf5e539fd34a99da10d",
          "sha256": "f0e30ed25191272c809b7fec8d2f76918bd85c4ac95fc9119048d88d9c41a766",
          "sha1": "d8394b3600c26ff180862fd297b0c246db6e126e",
          "md5": "3a9e436f7a14b0d9425da90be2b3a218"
        }
      ]
    }
  ]
}
