{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "9de9749af328b3535b39e5aa4b452a9664f358f47562dc15e626d278f38452ad29e7579400e7a51e8f5adf716c2ad58c654e15837c444af12b3e3e63186d81dd",
          "sha256": "a4ef2f0140479a0da2e3fb168a7eda7fc18f3f870ced114beb91cfccb762201b",
          "sha1": "68d14f0bcdc805f09be43867871108f66440f8f8",
          "md5": "a1d8b887cde906b8a7cca91ab60ce9fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "9de9749af328b3535b39e5aa4b452a9664f358f47562dc15e626d278f38452ad29e7579400e7a51e8f5adf716c2ad58c654e15837c444af12b3e3e63186d81dd",
          "sha256": "a4ef2f0140479a0da2e3fb168a7eda7fc18f3f870ced114beb91cfccb762201b",
          "sha1": "68d14f0bcdc805f09be43867871108f66440f8f8",
          "md5": "a1d8b887cde906b8a7cca91ab60ce9fe"
        }
      ]
    }
  ]
}
