{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "5991c096451a2233def8d6d218f6c8394af6e06063812cb29574f934f79f35906d9e14316919c4b882781349738fdb7978683b9c44f2ea578d949eb5930c702e",
          "sha256": "5f15d51ca9e0996444d772c3af9d1213ff704bb2813608389db32dedf0755eef",
          "sha1": "6abccc56abb31b67707a9a03157ee7faa2e88f10",
          "md5": "ab981b0598fb065ab4f6c2ab61a1e480"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "5991c096451a2233def8d6d218f6c8394af6e06063812cb29574f934f79f35906d9e14316919c4b882781349738fdb7978683b9c44f2ea578d949eb5930c702e",
          "sha256": "5f15d51ca9e0996444d772c3af9d1213ff704bb2813608389db32dedf0755eef",
          "sha1": "6abccc56abb31b67707a9a03157ee7faa2e88f10",
          "md5": "ab981b0598fb065ab4f6c2ab61a1e480"
        }
      ]
    }
  ]
}
