{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "c1ffe197d8d218d5c4150e6976cca3489d2c5cf72372b4c6966b3be4e9b5ffa41be8223570a380b748b3cdcbd3b32399728d1364ce9e93c638f7f7936e63236f",
          "sha256": "a6dc0ac34c62cc9c374db8b58af170e6faabff3503522ee5790dcb7cd2438349",
          "sha1": "f78a77455a44a31ee26efbde7dfab24ef416cff7",
          "md5": "a17eed659b9906dce343c6480a4c630b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "c1ffe197d8d218d5c4150e6976cca3489d2c5cf72372b4c6966b3be4e9b5ffa41be8223570a380b748b3cdcbd3b32399728d1364ce9e93c638f7f7936e63236f",
          "sha256": "a6dc0ac34c62cc9c374db8b58af170e6faabff3503522ee5790dcb7cd2438349",
          "sha1": "f78a77455a44a31ee26efbde7dfab24ef416cff7",
          "md5": "a17eed659b9906dce343c6480a4c630b"
        }
      ]
    }
  ]
}
