{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "5957bed59fa5a9dde818decf98184d31e92dae7cec2a328696b6b2c6bd4ee2bfd0843e0c3bc5ff0c2f6ab31bb9a657f9fe6931a65092a8bfd2c31170c9514a18",
          "sha256": "45a49aca103aa3c06d41f6da8de1c481081c5b320d47e937e1aabaef35af8e0a",
          "sha1": "e026a8c5e7cc8ffae6320e51781e3dafb174a706",
          "md5": "c473f658c32570e613225cf709ce3376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "5957bed59fa5a9dde818decf98184d31e92dae7cec2a328696b6b2c6bd4ee2bfd0843e0c3bc5ff0c2f6ab31bb9a657f9fe6931a65092a8bfd2c31170c9514a18",
          "sha256": "45a49aca103aa3c06d41f6da8de1c481081c5b320d47e937e1aabaef35af8e0a",
          "sha1": "e026a8c5e7cc8ffae6320e51781e3dafb174a706",
          "md5": "c473f658c32570e613225cf709ce3376"
        }
      ]
    }
  ]
}
