{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "b5a7f1df5abdf9875ed71a40cc62fa69affff3c2377d6004beea1c6602052e4974a668bc34572fd0318790c77ef75b1b103491d319906a9ab411073371fcd08c",
          "sha256": "b6957494c5008a2ee261500e4ef0f2f5052025be14e32ce68ae14966bb18281d",
          "sha1": "0b864df922d4299c2223e6e495c1840036caa5f1",
          "md5": "e4666a513961b3373ecf46708282de15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "b5a7f1df5abdf9875ed71a40cc62fa69affff3c2377d6004beea1c6602052e4974a668bc34572fd0318790c77ef75b1b103491d319906a9ab411073371fcd08c",
          "sha256": "b6957494c5008a2ee261500e4ef0f2f5052025be14e32ce68ae14966bb18281d",
          "sha1": "0b864df922d4299c2223e6e495c1840036caa5f1",
          "md5": "e4666a513961b3373ecf46708282de15"
        }
      ]
    }
  ]
}
