{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1356979,
          "sha512": "5bec824db82f6f378de7214bb03ebd21404e5a239af07d34bcb3bebd962558c8867380fa7a4baeac9a00a717db251777e6de34f70b9836065a731814fcc8d793",
          "sha256": "d4424f79583e6ad198ad2d6999b91048d013d8447ca9279a86c63a22ab3f016a",
          "sha1": "e0292f1574f2554d6f9b2e0ed58099c03a28f20b",
          "md5": "fed1611087aaad5c4acd2738dcc8d638"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1356979,
          "sha512": "5bec824db82f6f378de7214bb03ebd21404e5a239af07d34bcb3bebd962558c8867380fa7a4baeac9a00a717db251777e6de34f70b9836065a731814fcc8d793",
          "sha256": "d4424f79583e6ad198ad2d6999b91048d013d8447ca9279a86c63a22ab3f016a",
          "sha1": "e0292f1574f2554d6f9b2e0ed58099c03a28f20b",
          "md5": "fed1611087aaad5c4acd2738dcc8d638"
        }
      ]
    }
  ]
}
