{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1356958,
          "sha512": "73fa60cfd33ac4f898886f2da743e72e11938f97288fc69b9076cbf6bd1d8aed10a03875789b2552fa4b67a15847853b2bd2337b2651b7dc42907458ebf7fa06",
          "sha256": "a4cd242949e5fb60a496b02ced94932c8eb4864c5244dad8b75eb0560ebaa983",
          "sha1": "c4188a03c2413d0814dec9945d18eff022385bab",
          "md5": "9509744c7bb14f307f9db38a2c5b7275"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1356958,
          "sha512": "73fa60cfd33ac4f898886f2da743e72e11938f97288fc69b9076cbf6bd1d8aed10a03875789b2552fa4b67a15847853b2bd2337b2651b7dc42907458ebf7fa06",
          "sha256": "a4cd242949e5fb60a496b02ced94932c8eb4864c5244dad8b75eb0560ebaa983",
          "sha1": "c4188a03c2413d0814dec9945d18eff022385bab",
          "md5": "9509744c7bb14f307f9db38a2c5b7275"
        }
      ]
    }
  ]
}
