{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "dc9a10df17b701e00787202024dc6be33c960dd17ee406261e9ae0ce4be89cdf4f3ad07f594de909bd2fb9709800963e507658806c7b0887f34b8e80e2b792ce",
          "sha256": "fa9bf67b29e1e7fdb3249f3ab1e46cd4beaef4f7930dd70759ae6ae11a6953d9",
          "sha1": "64d6dc426e18abb7de753a3aff78168709fdd442",
          "md5": "1ce0cd2554d17b9c2d2962f280bf9a0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "dc9a10df17b701e00787202024dc6be33c960dd17ee406261e9ae0ce4be89cdf4f3ad07f594de909bd2fb9709800963e507658806c7b0887f34b8e80e2b792ce",
          "sha256": "fa9bf67b29e1e7fdb3249f3ab1e46cd4beaef4f7930dd70759ae6ae11a6953d9",
          "sha1": "64d6dc426e18abb7de753a3aff78168709fdd442",
          "md5": "1ce0cd2554d17b9c2d2962f280bf9a0a"
        }
      ]
    }
  ]
}
