{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "7dd9d99a3f12ae18c339f9c0032f1898187c9a09769671b1a973bc1e10284bccd4eacd4bf5dd5ce60196551e8860c0ba3eaa0f7eac90cf9af85aaec341c9459f",
          "sha256": "caacfcd38541d63829e51cd2598f75e903c48c2f1468f55f134f114f5682bf2d",
          "sha1": "2755cb11889ce19e718344eabb91fc19c28f5d5b",
          "md5": "510d83c17b2f65da651a9193b36935ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "7dd9d99a3f12ae18c339f9c0032f1898187c9a09769671b1a973bc1e10284bccd4eacd4bf5dd5ce60196551e8860c0ba3eaa0f7eac90cf9af85aaec341c9459f",
          "sha256": "caacfcd38541d63829e51cd2598f75e903c48c2f1468f55f134f114f5682bf2d",
          "sha1": "2755cb11889ce19e718344eabb91fc19c28f5d5b",
          "md5": "510d83c17b2f65da651a9193b36935ca"
        }
      ]
    }
  ]
}
