{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "dbcd8107a8e83420edbba4a471c3afb89d75b5f1efc60dad58d815c17c38ba16ad4652e81f40f0a923aed829dca59d8668ac075c1b08b1c4f4593fbe780c29c4",
          "sha256": "ad2b476618f5288c69fc131aea41d92da631ad8580a9fb966b82a150da125abc",
          "sha1": "ba06c04c12eab7592d898f13ccad6dcc8119ee6d",
          "md5": "f042932fb8a8d5026ac0cee6c3316f14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "dbcd8107a8e83420edbba4a471c3afb89d75b5f1efc60dad58d815c17c38ba16ad4652e81f40f0a923aed829dca59d8668ac075c1b08b1c4f4593fbe780c29c4",
          "sha256": "ad2b476618f5288c69fc131aea41d92da631ad8580a9fb966b82a150da125abc",
          "sha1": "ba06c04c12eab7592d898f13ccad6dcc8119ee6d",
          "md5": "f042932fb8a8d5026ac0cee6c3316f14"
        }
      ]
    }
  ]
}
