{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.0.jar",
          "url": "runescape-api-4.13.0.jar",
          "size": 143482,
          "sha512": "4ae6862a16fc60e08fc7ca535d195235f425f03e33ef33c9e6c2a22dae0712c80f959d424e2ad5aa58d4f9a3d7353523064bc8250c88829ecf1a444d0fe4e658",
          "sha256": "b15e3f9d7bee79584d52b0c8116f7fb7bccbc31f4987883a531504c43527a3c5",
          "sha1": "c64551af60f7344a3901340c28162e75df0138d4",
          "md5": "d1cda22c1958e65ecfaaee7ec9b524f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.0.jar",
          "url": "runescape-api-4.13.0.jar",
          "size": 143482,
          "sha512": "4ae6862a16fc60e08fc7ca535d195235f425f03e33ef33c9e6c2a22dae0712c80f959d424e2ad5aa58d4f9a3d7353523064bc8250c88829ecf1a444d0fe4e658",
          "sha256": "b15e3f9d7bee79584d52b0c8116f7fb7bccbc31f4987883a531504c43527a3c5",
          "sha1": "c64551af60f7344a3901340c28162e75df0138d4",
          "md5": "d1cda22c1958e65ecfaaee7ec9b524f4"
        }
      ]
    }
  ]
}
