{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "msb2ujb6obbs3dd2zibqzdxt7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159146,
          "sha512": "3272c62135aec3546a7bd180e9ad80e0dd83bb3a9be3776582e9d99fcad211810efb7a88bf31d96b47f92855b8e16a0a0d535f948656b3c040079a04e2a6e270",
          "sha256": "cc2a5b47e4c625f1ab0881f8efa1d9d1f5659b42e91baec9e59ab8c5f474e9bd",
          "sha1": "be2c15141d32dce73a0d10b46d6b73f4c03ee65c",
          "md5": "d7552198319e4a41c1f49f329ba870e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159146,
          "sha512": "3272c62135aec3546a7bd180e9ad80e0dd83bb3a9be3776582e9d99fcad211810efb7a88bf31d96b47f92855b8e16a0a0d535f948656b3c040079a04e2a6e270",
          "sha256": "cc2a5b47e4c625f1ab0881f8efa1d9d1f5659b42e91baec9e59ab8c5f474e9bd",
          "sha1": "be2c15141d32dce73a0d10b46d6b73f4c03ee65c",
          "md5": "d7552198319e4a41c1f49f329ba870e8"
        }
      ]
    }
  ]
}
