{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nqnphptwrvdqdo2z2fvc5u3h2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159127,
          "sha512": "7df71b4a8cf7418094afa42d8e6ca3755855be4ea63c4610dc20da1c4800fc594c8a9b792e60c6ec498688024fc7f3b9aa502d1d4d884b13e55641744a6ef550",
          "sha256": "8cef5f552f4d17176e8a0c190eea748c4e502e6d32cd6d559d562a684778eb17",
          "sha1": "acfe55ec7ac618c0f52fa29a19b56e8227cc033d",
          "md5": "8222533d650d522d6d5f169d00490cf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159127,
          "sha512": "7df71b4a8cf7418094afa42d8e6ca3755855be4ea63c4610dc20da1c4800fc594c8a9b792e60c6ec498688024fc7f3b9aa502d1d4d884b13e55641744a6ef550",
          "sha256": "8cef5f552f4d17176e8a0c190eea748c4e502e6d32cd6d559d562a684778eb17",
          "sha1": "acfe55ec7ac618c0f52fa29a19b56e8227cc033d",
          "md5": "8222533d650d522d6d5f169d00490cf8"
        }
      ]
    }
  ]
}
