{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "519b8228af8a20130bb828b013c1a0419eefbada3fc0c6e4f689b5c54f19ee15a3ced65338d587db407d9350bbcd2316aa114588e88ebca46c322435c998fd53",
          "sha256": "13e3aaac9e18005dff3c7440bc75485f612eec505dd94b90450a8a980df28141",
          "sha1": "d936e5a238b3e9d80c9d4fd10d43b780ab13d53e",
          "md5": "2d1ec1b3bcd6240356a0f8decea20569"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "519b8228af8a20130bb828b013c1a0419eefbada3fc0c6e4f689b5c54f19ee15a3ced65338d587db407d9350bbcd2316aa114588e88ebca46c322435c998fd53",
          "sha256": "13e3aaac9e18005dff3c7440bc75485f612eec505dd94b90450a8a980df28141",
          "sha1": "d936e5a238b3e9d80c9d4fd10d43b780ab13d53e",
          "md5": "2d1ec1b3bcd6240356a0f8decea20569"
        }
      ]
    }
  ]
}
