{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "32eb842357075c5a3859c3387e66cf7ce2d91e20ad458226a68b6b1512e8fe2d14a69d93486075f86edebc58fbe1705c8426ac7de961b6b7b3ea6ba9deb7f29b",
          "sha256": "219075a2dcc60d362a4aaea68c8e6cef8bd7f1f13dabecdf4e12a66ad7342b17",
          "sha1": "92f6ca8a89777802ff2f9d4174d18a4c3e5b300c",
          "md5": "6b94313eb3aaaa636992bac8d7eb6cba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "32eb842357075c5a3859c3387e66cf7ce2d91e20ad458226a68b6b1512e8fe2d14a69d93486075f86edebc58fbe1705c8426ac7de961b6b7b3ea6ba9deb7f29b",
          "sha256": "219075a2dcc60d362a4aaea68c8e6cef8bd7f1f13dabecdf4e12a66ad7342b17",
          "sha1": "92f6ca8a89777802ff2f9d4174d18a4c3e5b300c",
          "md5": "6b94313eb3aaaa636992bac8d7eb6cba"
        }
      ]
    }
  ]
}
