{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "6e8145b3c9bb510e851886cf08654db6d8e3a726a18105a74c42f6dc00b6d7730b243f8f0c3d17c510ff52e4f3682c5a9067465140ffab40e9c20d0d322cf3b7",
          "sha256": "9d31d525c7086411829346777c1f5b4f2254b5a8a094589c44a21152c7480325",
          "sha1": "1043f502c4b5a763e4e9705240c0359c154271b3",
          "md5": "31e20856cf2a271d51782197b7b8c806"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "6e8145b3c9bb510e851886cf08654db6d8e3a726a18105a74c42f6dc00b6d7730b243f8f0c3d17c510ff52e4f3682c5a9067465140ffab40e9c20d0d322cf3b7",
          "sha256": "9d31d525c7086411829346777c1f5b4f2254b5a8a094589c44a21152c7480325",
          "sha1": "1043f502c4b5a763e4e9705240c0359c154271b3",
          "md5": "31e20856cf2a271d51782197b7b8c806"
        }
      ]
    }
  ]
}
