{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.13.1.jar",
          "url": "http-api-4.13.1.jar",
          "size": 172794,
          "sha512": "d76b67f946acd825fa8a776a2614c145c60486da2b63570f9e5221ba9e7ba447427a628abce9c7a6be64d07eae527aff29d2a19a3e100605bd46a5bf0a803ff2",
          "sha256": "9db5c06f392bda39ce5763a2c8e049ea40659c3294985d928f58d735130dcae7",
          "sha1": "b090a72a6b925745374d28b15f0e2fe0e3233556",
          "md5": "816aafbbd496fd1deb6e7de964ae1152"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.13.1.jar",
          "url": "http-api-4.13.1.jar",
          "size": 172794,
          "sha512": "d76b67f946acd825fa8a776a2614c145c60486da2b63570f9e5221ba9e7ba447427a628abce9c7a6be64d07eae527aff29d2a19a3e100605bd46a5bf0a803ff2",
          "sha256": "9db5c06f392bda39ce5763a2c8e049ea40659c3294985d928f58d735130dcae7",
          "sha1": "b090a72a6b925745374d28b15f0e2fe0e3233556",
          "md5": "816aafbbd496fd1deb6e7de964ae1152"
        }
      ]
    }
  ]
}
