{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "59f9d651e3240781c66acf1ec84eff227778283a44d5214d0495b48fa632e95c2238fd12c2d795f91390a8bec007faa795bda065e07d32958ed6dad508011704",
          "sha256": "3b2753ceff152367f3a15e211c4f9e61fae69e3747647dab5beacc41bb435e8c",
          "sha1": "39259d5faa5e4c842dc17868d03eb49f26a8a1ca",
          "md5": "50be671cc4edc024bb829e8fbd5928f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "59f9d651e3240781c66acf1ec84eff227778283a44d5214d0495b48fa632e95c2238fd12c2d795f91390a8bec007faa795bda065e07d32958ed6dad508011704",
          "sha256": "3b2753ceff152367f3a15e211c4f9e61fae69e3747647dab5beacc41bb435e8c",
          "sha1": "39259d5faa5e4c842dc17868d03eb49f26a8a1ca",
          "md5": "50be671cc4edc024bb829e8fbd5928f8"
        }
      ]
    }
  ]
}
