{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "cab96a4d227e63fd7f86a331bbd5630ac51ee7f4310f5692d7ef8de9a16a7988a8cdc6094d024e73a0e97117ff889516afa5f9b9d8380d2c6a2a1f4686bca279",
          "sha256": "512e0814f7b3ce7a03f01d0507fcc535789578e61eb6a3dbcfa665e3a1c461c2",
          "sha1": "680a5f93a653c77ed917e9ccfaec58ccf059922e",
          "md5": "fd863153a2bd8c5b2bc29c486f110020"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "cab96a4d227e63fd7f86a331bbd5630ac51ee7f4310f5692d7ef8de9a16a7988a8cdc6094d024e73a0e97117ff889516afa5f9b9d8380d2c6a2a1f4686bca279",
          "sha256": "512e0814f7b3ce7a03f01d0507fcc535789578e61eb6a3dbcfa665e3a1c461c2",
          "sha1": "680a5f93a653c77ed917e9ccfaec58ccf059922e",
          "md5": "fd863153a2bd8c5b2bc29c486f110020"
        }
      ]
    }
  ]
}
