{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "fff991612f5b30849345233d1c3089b4657b2fdddc9ff8b6ff6988f05bf518448595b9fcb49dd3618d4a6ac5d5ad88d9e68b650619b61b3102b02b226f19ccda",
          "sha256": "49484bb8ea020102b4cf51fe30c00f5ce0b9b9b538eb4a4b8e53c604a8220469",
          "sha1": "ab08fcf884549454802cdc5c3f79959f22463d81",
          "md5": "c3f1ed3e8ce638e7fb5e034ca01ff0e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "fff991612f5b30849345233d1c3089b4657b2fdddc9ff8b6ff6988f05bf518448595b9fcb49dd3618d4a6ac5d5ad88d9e68b650619b61b3102b02b226f19ccda",
          "sha256": "49484bb8ea020102b4cf51fe30c00f5ce0b9b9b538eb4a4b8e53c604a8220469",
          "sha1": "ab08fcf884549454802cdc5c3f79959f22463d81",
          "md5": "c3f1ed3e8ce638e7fb5e034ca01ff0e4"
        }
      ]
    }
  ]
}
