{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "e36c721c958c23339ce261a04f8c36c9f11852b2f41b239a3001f8df631d830fca7fa24eb981cc35af5028ea4a0fb8ce58bb96279886a64133a0627bc5886a16",
          "sha256": "aa936b87cfe460fb29924abeca8a01aed5bcb6bcdb8f84cb189d816f71eef8e8",
          "sha1": "8a35a955b9016c89e2e7c77f9f3651b2f222af48",
          "md5": "9d6809215aec108552cf270fa9d05143"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "e36c721c958c23339ce261a04f8c36c9f11852b2f41b239a3001f8df631d830fca7fa24eb981cc35af5028ea4a0fb8ce58bb96279886a64133a0627bc5886a16",
          "sha256": "aa936b87cfe460fb29924abeca8a01aed5bcb6bcdb8f84cb189d816f71eef8e8",
          "sha1": "8a35a955b9016c89e2e7c77f9f3651b2f222af48",
          "md5": "9d6809215aec108552cf270fa9d05143"
        }
      ]
    }
  ]
}
