{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "38e6dbcc185ec4c0e678dd2099a683698cae163f3c7b793dd9796aaa80a92cd8f4376968cf341a2588cadd5faf047abd76289e6175c59fa1f3c37f180c81f45f",
          "sha256": "71d856ee43302d009e88afe9174aa67437b3c4c3f59fa144e93e0773ca1f4fed",
          "sha1": "3daa8decc72f55dc98be5d967fa2bbf7f9eac672",
          "md5": "a26da423504a29cef0a0944908c73ebe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "38e6dbcc185ec4c0e678dd2099a683698cae163f3c7b793dd9796aaa80a92cd8f4376968cf341a2588cadd5faf047abd76289e6175c59fa1f3c37f180c81f45f",
          "sha256": "71d856ee43302d009e88afe9174aa67437b3c4c3f59fa144e93e0773ca1f4fed",
          "sha1": "3daa8decc72f55dc98be5d967fa2bbf7f9eac672",
          "md5": "a26da423504a29cef0a0944908c73ebe"
        }
      ]
    }
  ]
}
