{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1331264,
          "sha512": "5c082983e0410f67bc95adb8303065fdd3f88e1ef3dee91569868770f63882ee59863a4b1e084d9c56774568c6d371fc52a0c710447dddfef5726c9ee55742d6",
          "sha256": "8f698472c44d33cfffaadd16a68e5bb6fde2368e7745db4a64e757d50574507b",
          "sha1": "dfe26128c7b7e4a5d81f4b7863d28b21d220d760",
          "md5": "43585b4b23ba0cbe361ad4caffc08e9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1331264,
          "sha512": "5c082983e0410f67bc95adb8303065fdd3f88e1ef3dee91569868770f63882ee59863a4b1e084d9c56774568c6d371fc52a0c710447dddfef5726c9ee55742d6",
          "sha256": "8f698472c44d33cfffaadd16a68e5bb6fde2368e7745db4a64e757d50574507b",
          "sha1": "dfe26128c7b7e4a5d81f4b7863d28b21d220d760",
          "md5": "43585b4b23ba0cbe361ad4caffc08e9b"
        }
      ]
    }
  ]
}
