{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1331264,
          "sha512": "c0bbc0feb3e27a6e41ed3c5679f20355ccc75f95b6707e5a43fa2b187a1a04c90c15fef4d91dc604cf245b6e06ac35dc94703ac70f14fdc577ecef45e8d6f9c0",
          "sha256": "1ba29eae28fd9ca3b706d01cdba0cae859c1f053386f514436225e84c3f79165",
          "sha1": "d7e155b4747450158ee72b1cd962820cbfff0e4d",
          "md5": "29570ff172e43546e24b3b39ab54228b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1331264,
          "sha512": "c0bbc0feb3e27a6e41ed3c5679f20355ccc75f95b6707e5a43fa2b187a1a04c90c15fef4d91dc604cf245b6e06ac35dc94703ac70f14fdc577ecef45e8d6f9c0",
          "sha256": "1ba29eae28fd9ca3b706d01cdba0cae859c1f053386f514436225e84c3f79165",
          "sha1": "d7e155b4747450158ee72b1cd962820cbfff0e4d",
          "md5": "29570ff172e43546e24b3b39ab54228b"
        }
      ]
    }
  ]
}
