{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1331264,
          "sha512": "3786dac381237cbeeac22fe731b37a8b63d9a3cc7f81116d95bc1fc1df582d9b24af8454cbb8ba79a79c5162062b5aebb5347e31e64a40b82cf76d3aa610eec1",
          "sha256": "6035de4909e213eac6306954468865ccbe14f0590786f96307af469ce2ca91f3",
          "sha1": "404463458246bb6489bb64f9d8a021a6f12cd094",
          "md5": "b9b3e0a83cfb76f52c0551ddc09381a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.4.jar",
          "url": "runelite-api-4.15.4.jar",
          "size": 1331264,
          "sha512": "3786dac381237cbeeac22fe731b37a8b63d9a3cc7f81116d95bc1fc1df582d9b24af8454cbb8ba79a79c5162062b5aebb5347e31e64a40b82cf76d3aa610eec1",
          "sha256": "6035de4909e213eac6306954468865ccbe14f0590786f96307af469ce2ca91f3",
          "sha1": "404463458246bb6489bb64f9d8a021a6f12cd094",
          "md5": "b9b3e0a83cfb76f52c0551ddc09381a2"
        }
      ]
    }
  ]
}
