{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7vshtkvopbb7pgfvonsytem7ni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.3.0.jar",
          "url": "http-api-4.3.0.jar",
          "size": 159711,
          "sha512": "d0b9d9b320434630554de830ebe7df7c6e136702630b533ed94021907de4a67b4fe980885c88c39e6195f5c818355297ae513a96ac1597b8dcbd26a7e468b256",
          "sha256": "1d7820f3af5e820e3d919c1ed95016f1de8ec692e81c54bafb2fd12c1661dcb6",
          "sha1": "71eaa88f664f6eac9f2a830bc0e9be2d750fff0c",
          "md5": "777a376050bed7a5cf22df3ccc0d4495"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.3.0.jar",
          "url": "http-api-4.3.0.jar",
          "size": 159711,
          "sha512": "d0b9d9b320434630554de830ebe7df7c6e136702630b533ed94021907de4a67b4fe980885c88c39e6195f5c818355297ae513a96ac1597b8dcbd26a7e468b256",
          "sha256": "1d7820f3af5e820e3d919c1ed95016f1de8ec692e81c54bafb2fd12c1661dcb6",
          "sha1": "71eaa88f664f6eac9f2a830bc0e9be2d750fff0c",
          "md5": "777a376050bed7a5cf22df3ccc0d4495"
        }
      ]
    }
  ]
}
