{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.8.1.jar",
          "url": "runelite-api-4.8.1.jar",
          "size": 1272517,
          "sha512": "044e98c333d45be37deeb659a2abd81d8599cf0a715b0526bf2684b9c045460e75f9afdc485fdcec8637828dc874a48780a358064efc53fb22a8d2057c240d6d",
          "sha256": "ef66f833fc5a1c28b97c561690b357fc8d356576535e28c1112a42c119a5e4fb",
          "sha1": "d03a1d82786581b57ffdacc49a795b6737bf9a17",
          "md5": "cf3f08566e82d86d182feeca238b5430"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.8.1.jar",
          "url": "runelite-api-4.8.1.jar",
          "size": 1272517,
          "sha512": "044e98c333d45be37deeb659a2abd81d8599cf0a715b0526bf2684b9c045460e75f9afdc485fdcec8637828dc874a48780a358064efc53fb22a8d2057c240d6d",
          "sha256": "ef66f833fc5a1c28b97c561690b357fc8d356576535e28c1112a42c119a5e4fb",
          "sha1": "d03a1d82786581b57ffdacc49a795b6737bf9a17",
          "md5": "cf3f08566e82d86d182feeca238b5430"
        }
      ]
    }
  ]
}
