{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "69a20344acbb43817e5d940af4870d9801d9974696e5da2dc50916337059dcf7b6dea6a1eabca3508a8946837633778ed84ef2116918638fba5f4035f4ba62ad",
          "sha256": "eef8e38b3b7d0da5850c1f6a45305877ef92f6414f70e004233d378e9c393d9f",
          "sha1": "28550023b572fabb34a6b7e29f6b888b5cc9e624",
          "md5": "887ae160c5ee8a81c31afe60732eb435"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "69a20344acbb43817e5d940af4870d9801d9974696e5da2dc50916337059dcf7b6dea6a1eabca3508a8946837633778ed84ef2116918638fba5f4035f4ba62ad",
          "sha256": "eef8e38b3b7d0da5850c1f6a45305877ef92f6414f70e004233d378e9c393d9f",
          "sha1": "28550023b572fabb34a6b7e29f6b888b5cc9e624",
          "md5": "887ae160c5ee8a81c31afe60732eb435"
        }
      ]
    }
  ]
}
