{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.4.jar",
          "url": "runelite-api-4.9.4.jar",
          "size": 1274446,
          "sha512": "138a69e71fce995e82ac424057c8734166fa19ec361fcaaa211b52b610eb24df32e7f8806c7c6dbd5cbeab8a404244222c6554dcbcdba6e8cff3029cd1257ad9",
          "sha256": "73d71ab9193db8687b7d1e78e5509705b52184440647e7f5d91cce5db98a0340",
          "sha1": "7f4b94c0aaafc604e9245896f8b76bc574236eb8",
          "md5": "0e5821f7b833fffe78f44a35b11f3f45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.4.jar",
          "url": "runelite-api-4.9.4.jar",
          "size": 1274446,
          "sha512": "138a69e71fce995e82ac424057c8734166fa19ec361fcaaa211b52b610eb24df32e7f8806c7c6dbd5cbeab8a404244222c6554dcbcdba6e8cff3029cd1257ad9",
          "sha256": "73d71ab9193db8687b7d1e78e5509705b52184440647e7f5d91cce5db98a0340",
          "sha1": "7f4b94c0aaafc604e9245896f8b76bc574236eb8",
          "md5": "0e5821f7b833fffe78f44a35b11f3f45"
        }
      ]
    }
  ]
}
