{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0.jar",
          "url": "runescape-api-4.27.0.jar",
          "size": 150217,
          "sha512": "f620ba4872f07b1a6c2b52f5d1741824490e25c662ae7f66c6717347031f009c5a81ab982041f6c8eafeab666642c0fd5ea4bdfc9de03341fa4f5d7b84f5ce58",
          "sha256": "44ec429bc568434c7139667e494f29cac3856855a1073d83c1383e5d19b21abb",
          "sha1": "7c550fefe41b3d44d8702ef9423cde3264348418",
          "md5": "27ec5b243759fe4e0d174000e9ead34b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0.jar",
          "url": "runescape-api-4.27.0.jar",
          "size": 150217,
          "sha512": "f620ba4872f07b1a6c2b52f5d1741824490e25c662ae7f66c6717347031f009c5a81ab982041f6c8eafeab666642c0fd5ea4bdfc9de03341fa4f5d7b84f5ce58",
          "sha256": "44ec429bc568434c7139667e494f29cac3856855a1073d83c1383e5d19b21abb",
          "sha1": "7c550fefe41b3d44d8702ef9423cde3264348418",
          "md5": "27ec5b243759fe4e0d174000e9ead34b"
        }
      ]
    }
  ]
}
