{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0.jar",
          "url": "runescape-api-4.27.0.jar",
          "size": 150217,
          "sha512": "e96b41d306c453943a8bdccff4cbecc8ccf5783be43ca09611a92066903ad41673d0f7dcd847ffa7b4ac26c35366f1162ce59ae8f209ffc1ac4a50e7db1a1f21",
          "sha256": "36b77c1c6ca4750ab32fcb0071a903edeba6ed3689e445bd24f97dd86e5160fb",
          "sha1": "c33d239260efaf829fd64dce4e46c6b3152739ab",
          "md5": "35a165f31f0f6162af8951565c837d71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0.jar",
          "url": "runescape-api-4.27.0.jar",
          "size": 150217,
          "sha512": "e96b41d306c453943a8bdccff4cbecc8ccf5783be43ca09611a92066903ad41673d0f7dcd847ffa7b4ac26c35366f1162ce59ae8f209ffc1ac4a50e7db1a1f21",
          "sha256": "36b77c1c6ca4750ab32fcb0071a903edeba6ed3689e445bd24f97dd86e5160fb",
          "sha1": "c33d239260efaf829fd64dce4e46c6b3152739ab",
          "md5": "35a165f31f0f6162af8951565c837d71"
        }
      ]
    }
  ]
}
