{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.1.jar",
          "url": "runelite-api-4.20.1.jar",
          "size": 1346200,
          "sha512": "a28096500594fb23572411c980806f68951bed90dffec9b5a5053c85df705a2662d70ed006b05def182d0c94ebdbf102860411e9d454b669b8831740bbe90a17",
          "sha256": "61ce61c40f47fb126263da250341f211690027fddd33441fe831df28a2137d27",
          "sha1": "eade8786a23e713a3a1d6f4cfc041236271bcd54",
          "md5": "4fd2f1108746933e8c409df7c0d819aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.1.jar",
          "url": "runelite-api-4.20.1.jar",
          "size": 1346200,
          "sha512": "a28096500594fb23572411c980806f68951bed90dffec9b5a5053c85df705a2662d70ed006b05def182d0c94ebdbf102860411e9d454b669b8831740bbe90a17",
          "sha256": "61ce61c40f47fb126263da250341f211690027fddd33441fe831df28a2137d27",
          "sha1": "eade8786a23e713a3a1d6f4cfc041236271bcd54",
          "md5": "4fd2f1108746933e8c409df7c0d819aa"
        }
      ]
    }
  ]
}
