{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.1.jar",
          "url": "runelite-api-4.20.1.jar",
          "size": 1346200,
          "sha512": "7800587f058d96164e04a8842f8d0b0193d568492004233ae29b5e05ff95e9495753284be80b78b9fb54e0e2ba8bcb0b55ac912de1c0ed1470e89601e157d07c",
          "sha256": "8e66d62bc459aec1cef074fb538eca3ea3cf6a3d82a843df122f8330c50db465",
          "sha1": "679a5e1271c7488933c02120a3f8c2d2ed37931b",
          "md5": "2f58c404e3819a73a7d6c06a46ebf07a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.1.jar",
          "url": "runelite-api-4.20.1.jar",
          "size": 1346200,
          "sha512": "7800587f058d96164e04a8842f8d0b0193d568492004233ae29b5e05ff95e9495753284be80b78b9fb54e0e2ba8bcb0b55ac912de1c0ed1470e89601e157d07c",
          "sha256": "8e66d62bc459aec1cef074fb538eca3ea3cf6a3d82a843df122f8330c50db465",
          "sha1": "679a5e1271c7488933c02120a3f8c2d2ed37931b",
          "md5": "2f58c404e3819a73a7d6c06a46ebf07a"
        }
      ]
    }
  ]
}
