{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.1.jar",
          "url": "runelite-api-4.20.1.jar",
          "size": 1346200,
          "sha512": "852942ddf1a4a4d2cfe65cffc3da03e423a549b17b84cbede60c8656537fef28565295c1593edf1d9d7f9815d827ffc442c88388b045d4477ded971e4b6fec60",
          "sha256": "7b9137f924fedab5c867a0898c2111b6343656b9977db164fefa77222b8f6cf2",
          "sha1": "af2078ab8e10de123544be58f7a9aa3931ac2f3e",
          "md5": "51209a5db66ce2889e39883dafad5370"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.1.jar",
          "url": "runelite-api-4.20.1.jar",
          "size": 1346200,
          "sha512": "852942ddf1a4a4d2cfe65cffc3da03e423a549b17b84cbede60c8656537fef28565295c1593edf1d9d7f9815d827ffc442c88388b045d4477ded971e4b6fec60",
          "sha256": "7b9137f924fedab5c867a0898c2111b6343656b9977db164fefa77222b8f6cf2",
          "sha1": "af2078ab8e10de123544be58f7a9aa3931ac2f3e",
          "md5": "51209a5db66ce2889e39883dafad5370"
        }
      ]
    }
  ]
}
