{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.1.jar",
          "url": "runelite-api-4.13.1.jar",
          "size": 1332566,
          "sha512": "f1c2de4015924f71d063ba6de716c0c9c6c85a4e4b4d3c156bbc3bd5643e44422d1d5d6a1d8355da0289ce2a101b158a7de454bd6f9503561fe95fe85eeffb17",
          "sha256": "226a0ec3e88c43382ae9accac9c0beabc1384aa91e2d00e23c112a4a46c3d5d1",
          "sha1": "1d472298bdc084c8adefd6372862f7fa08d7528c",
          "md5": "64bd2f275d07352fa40811bee72d40c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.1.jar",
          "url": "runelite-api-4.13.1.jar",
          "size": 1332566,
          "sha512": "f1c2de4015924f71d063ba6de716c0c9c6c85a4e4b4d3c156bbc3bd5643e44422d1d5d6a1d8355da0289ce2a101b158a7de454bd6f9503561fe95fe85eeffb17",
          "sha256": "226a0ec3e88c43382ae9accac9c0beabc1384aa91e2d00e23c112a4a46c3d5d1",
          "sha1": "1d472298bdc084c8adefd6372862f7fa08d7528c",
          "md5": "64bd2f275d07352fa40811bee72d40c0"
        }
      ]
    }
  ]
}
