{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "b52zjzvrcrgw7fp7hwtctbb7oe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.1.0.jar",
          "url": "runelite-api-4.1.0.jar",
          "size": 1249343,
          "sha512": "b73c6c12346db9f293ea3092e0ff3bab49d6f390d15d94c9ad762126d024fec048b47c948fe70e97d8789d36df57dc61022ae19403018babedec1736359e9c5d",
          "sha256": "a3cc346fc58f7393143cd9ab4e55234c1c7c65952b9269b5fcfbceabd05c9ada",
          "sha1": "20daca1448daf7cd5a9b64add4b67f3172c6eb4c",
          "md5": "3db0e70666f67f1731c7dfe6fed13ce6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.1.0.jar",
          "url": "runelite-api-4.1.0.jar",
          "size": 1249343,
          "sha512": "b73c6c12346db9f293ea3092e0ff3bab49d6f390d15d94c9ad762126d024fec048b47c948fe70e97d8789d36df57dc61022ae19403018babedec1736359e9c5d",
          "sha256": "a3cc346fc58f7393143cd9ab4e55234c1c7c65952b9269b5fcfbceabd05c9ada",
          "sha1": "20daca1448daf7cd5a9b64add4b67f3172c6eb4c",
          "md5": "3db0e70666f67f1731c7dfe6fed13ce6"
        }
      ]
    }
  ]
}
