{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359379,
          "sha512": "72dc15af8e64d77680adf59202df96baaa02395e453e669c3084f30386a701ea110211b6b3df34be05583da284100191ac0ecae9c7ea799f821b2942477de57f",
          "sha256": "5f81724258123acd5089c0a71e65b479323bd365a53858c9f8a2ac362bb54bd5",
          "sha1": "d4a740859d92c5bfc692149341c8c9bb1667d3f7",
          "md5": "07e5440a4e83f0fa0aab71c7ad75a1af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359379,
          "sha512": "72dc15af8e64d77680adf59202df96baaa02395e453e669c3084f30386a701ea110211b6b3df34be05583da284100191ac0ecae9c7ea799f821b2942477de57f",
          "sha256": "5f81724258123acd5089c0a71e65b479323bd365a53858c9f8a2ac362bb54bd5",
          "sha1": "d4a740859d92c5bfc692149341c8c9bb1667d3f7",
          "md5": "07e5440a4e83f0fa0aab71c7ad75a1af"
        }
      ]
    }
  ]
}
