{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359379,
          "sha512": "d006458e387d92f2430709ae793e8ae3bc379d73ac8212810b1bf5477a158da30b4f211ba4a9deaa4351335bee1ae97345af471978db8dd9714f5981f79d3eee",
          "sha256": "c1825fec2594aa8c2d243688d02540dd3a622b81a8f0f027791102b19f57fd4e",
          "sha1": "2e12c5b436141e37f3ed3cc85eed32882f06ae20",
          "md5": "d33f65abc12452bec8097eb07f25dd13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359379,
          "sha512": "d006458e387d92f2430709ae793e8ae3bc379d73ac8212810b1bf5477a158da30b4f211ba4a9deaa4351335bee1ae97345af471978db8dd9714f5981f79d3eee",
          "sha256": "c1825fec2594aa8c2d243688d02540dd3a622b81a8f0f027791102b19f57fd4e",
          "sha1": "2e12c5b436141e37f3ed3cc85eed32882f06ae20",
          "md5": "d33f65abc12452bec8097eb07f25dd13"
        }
      ]
    }
  ]
}
