{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "r3odwks7urb6pm4fjwa4ovc4je"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.0.1.jar",
          "url": "http-api-4.0.1.jar",
          "size": 159145,
          "sha512": "a465cb4588ea1fea70a8ab93d2abb4c6bf121a3dd14b8ea734811a74d9097ddbab17f755c1c01527f6d47dccdbcb6ef319e258c4168516ba7297e71c061bf670",
          "sha256": "68a11fc2d4f6516f8ee889b029210128df31b9f15769e0a42ad272e41a2f2890",
          "sha1": "80bd8f7d62d34cbb5bf0e2744d7f6e5fc663f217",
          "md5": "da248a040dbae9e510a6077d0aca8730"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.0.1.jar",
          "url": "http-api-4.0.1.jar",
          "size": 159145,
          "sha512": "a465cb4588ea1fea70a8ab93d2abb4c6bf121a3dd14b8ea734811a74d9097ddbab17f755c1c01527f6d47dccdbcb6ef319e258c4168516ba7297e71c061bf670",
          "sha256": "68a11fc2d4f6516f8ee889b029210128df31b9f15769e0a42ad272e41a2f2890",
          "sha1": "80bd8f7d62d34cbb5bf0e2744d7f6e5fc663f217",
          "md5": "da248a040dbae9e510a6077d0aca8730"
        }
      ]
    }
  ]
}
