{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99205,
          "sha512": "3f260fabc5275584b4d5d13a32157b51306be3bb5543ff777553b5659b3ab52040fb47d2a31b26cac03413d85ae42bd7ccb9de2b734070a1cb38989236dd7ee8",
          "sha256": "dd23c22a4d68bc1604ce315876a5ff822282f559ff76014aa2f7c6dd81fa2cc8",
          "sha1": "7a164848c842607fd2a8b639de027a931808d10c",
          "md5": "0356dbf958c8f9a86b62c6beb5a5477b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99205,
          "sha512": "3f260fabc5275584b4d5d13a32157b51306be3bb5543ff777553b5659b3ab52040fb47d2a31b26cac03413d85ae42bd7ccb9de2b734070a1cb38989236dd7ee8",
          "sha256": "dd23c22a4d68bc1604ce315876a5ff822282f559ff76014aa2f7c6dd81fa2cc8",
          "sha1": "7a164848c842607fd2a8b639de027a931808d10c",
          "md5": "0356dbf958c8f9a86b62c6beb5a5477b"
        }
      ]
    }
  ]
}
