{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.12.2.jar",
          "url": "runelite-api-4.12.2.jar",
          "size": 1332895,
          "sha512": "4d16a2a52f6feae228c83ab23cafdee9851cd57092fe1c2f0d10325bae19f76783e1d308dd8485d142c7ba7353009dd9462dab3b7627f12dc58d02d54c6730c1",
          "sha256": "74751d773c62baf77219dff501ea9b204496b95b56dee68b3a33a3c4bf0464f8",
          "sha1": "a088fe393463572cb886c97eca2f333dc513e960",
          "md5": "7cf29277d81c4a55ad45b28c9a3bacb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.12.2.jar",
          "url": "runelite-api-4.12.2.jar",
          "size": 1332895,
          "sha512": "4d16a2a52f6feae228c83ab23cafdee9851cd57092fe1c2f0d10325bae19f76783e1d308dd8485d142c7ba7353009dd9462dab3b7627f12dc58d02d54c6730c1",
          "sha256": "74751d773c62baf77219dff501ea9b204496b95b56dee68b3a33a3c4bf0464f8",
          "sha1": "a088fe393463572cb886c97eca2f333dc513e960",
          "md5": "7cf29277d81c4a55ad45b28c9a3bacb1"
        }
      ]
    }
  ]
}
