{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99210,
          "sha512": "bee90be8868c2f7c7a6e80a762cc4bdf4f9ee5f32b70e6de9e37387443716410b426701a841cca84adb9d9bf2c64528545aaab59ba8bafc32b68a132a2d9cdb2",
          "sha256": "d7e0044562bccde48ca83cfb1df49026746466c655320b0a149fe82b999ecb19",
          "sha1": "ae03f551caf4043c7542f58c1d1d967329ff49d0",
          "md5": "be363803a6e32389e55f7b4e1ee7ff92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99210,
          "sha512": "bee90be8868c2f7c7a6e80a762cc4bdf4f9ee5f32b70e6de9e37387443716410b426701a841cca84adb9d9bf2c64528545aaab59ba8bafc32b68a132a2d9cdb2",
          "sha256": "d7e0044562bccde48ca83cfb1df49026746466c655320b0a149fe82b999ecb19",
          "sha1": "ae03f551caf4043c7542f58c1d1d967329ff49d0",
          "md5": "be363803a6e32389e55f7b4e1ee7ff92"
        }
      ]
    }
  ]
}
