{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "c54tolov35d4db3gruahceiebq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160388,
          "sha512": "513e963abb00775401bfec441d636998ce13f53b73e647de98fc472352a639f8f232e50971c187fb50acb44f7ecc764b0e461bf0397172a27d70544daad4d194",
          "sha256": "cef3300a7f593f0db1fb556a63d42a37629d845ef09057dec03d9a86a0bf31d5",
          "sha1": "1aae16ef7cae6a2cb21b6cd978c1a3ce0d7537ce",
          "md5": "c8874ff68a717d98dec8cbf69a122fb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160388,
          "sha512": "513e963abb00775401bfec441d636998ce13f53b73e647de98fc472352a639f8f232e50971c187fb50acb44f7ecc764b0e461bf0397172a27d70544daad4d194",
          "sha256": "cef3300a7f593f0db1fb556a63d42a37629d845ef09057dec03d9a86a0bf31d5",
          "sha1": "1aae16ef7cae6a2cb21b6cd978c1a3ce0d7537ce",
          "md5": "c8874ff68a717d98dec8cbf69a122fb3"
        }
      ]
    }
  ]
}
