{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wbvjpqczgvc3lcvsu2vwykmczm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160645,
          "sha512": "e36a90fca4eeae3ff2be6529084ad25d22c1b940077b831139045831717ea1197b5edcb45126ddf05ef2f95a3b0f57296e3703c208eb5b07699adfcf2e716839",
          "sha256": "174697a8e2071170263c19eb59de6926c70cc813fb5900a7777fc89e90848fcb",
          "sha1": "514d25d6e5b191465afd2f4dba29f2cfdd79f219",
          "md5": "7416c0d271bdba4a2d9dce113a06888b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160645,
          "sha512": "e36a90fca4eeae3ff2be6529084ad25d22c1b940077b831139045831717ea1197b5edcb45126ddf05ef2f95a3b0f57296e3703c208eb5b07699adfcf2e716839",
          "sha256": "174697a8e2071170263c19eb59de6926c70cc813fb5900a7777fc89e90848fcb",
          "sha1": "514d25d6e5b191465afd2f4dba29f2cfdd79f219",
          "md5": "7416c0d271bdba4a2d9dce113a06888b"
        }
      ]
    }
  ]
}
