{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "32d2fb5b58a7d78a5445f2719e4b1de88fcfff1ad3ea87be4de50da1baaf1d2d205fd5af1b646f49736cb534d77d54ea5152637231a842e8fdd2f5b0a5d324c3",
          "sha256": "40b2e0de402c5b15912ba9e8ee2877032c3777e773e93a9823347a3f07580aa7",
          "sha1": "c995ac2b6c9444ca01cc98d492a80cadba88cd4a",
          "md5": "926dd17e67c504f1c1c81819c6eb0e99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "32d2fb5b58a7d78a5445f2719e4b1de88fcfff1ad3ea87be4de50da1baaf1d2d205fd5af1b646f49736cb534d77d54ea5152637231a842e8fdd2f5b0a5d324c3",
          "sha256": "40b2e0de402c5b15912ba9e8ee2877032c3777e773e93a9823347a3f07580aa7",
          "sha1": "c995ac2b6c9444ca01cc98d492a80cadba88cd4a",
          "md5": "926dd17e67c504f1c1c81819c6eb0e99"
        }
      ]
    }
  ]
}
