{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "de5905f2693621c45866674a85127b3ed7c7fe752f39fdae5f3eb438e2d343f666e9b60415b0ac99801be0f3695495fb9c402d90642b0dd67e5446fdc108eb93",
          "sha256": "8fb3825482a6716b8c5145a47dd4b6a666a2879aa8ca8e82ad4a8ea420ee8e77",
          "sha1": "d9e9fbb94f3571435142192139f4941b13e35e13",
          "md5": "9a8ac3d2afa18760ef50b7bd79ecfd1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "de5905f2693621c45866674a85127b3ed7c7fe752f39fdae5f3eb438e2d343f666e9b60415b0ac99801be0f3695495fb9c402d90642b0dd67e5446fdc108eb93",
          "sha256": "8fb3825482a6716b8c5145a47dd4b6a666a2879aa8ca8e82ad4a8ea420ee8e77",
          "sha1": "d9e9fbb94f3571435142192139f4941b13e35e13",
          "md5": "9a8ac3d2afa18760ef50b7bd79ecfd1a"
        }
      ]
    }
  ]
}
