{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.2.jar",
          "url": "http-api-4.15.2.jar",
          "size": 172790,
          "sha512": "b9394ba430754148d7c68e579d53fa2b8a09fa3770f80bdb47523548322b3b6bd89749a32306ef8172173b20bb725447b96a73f35909e32f7b5b1ceed7ccbb85",
          "sha256": "c7b96cef624ad141f57305977eb7b2658dc9c17e260b7f0736660c1a5656bb32",
          "sha1": "3dae9a7339b224bbe9230f74dd96e6ccd46533a2",
          "md5": "ad2e5d5860e2e18a4f43e06c924d27cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.2.jar",
          "url": "http-api-4.15.2.jar",
          "size": 172790,
          "sha512": "b9394ba430754148d7c68e579d53fa2b8a09fa3770f80bdb47523548322b3b6bd89749a32306ef8172173b20bb725447b96a73f35909e32f7b5b1ceed7ccbb85",
          "sha256": "c7b96cef624ad141f57305977eb7b2658dc9c17e260b7f0736660c1a5656bb32",
          "sha1": "3dae9a7339b224bbe9230f74dd96e6ccd46533a2",
          "md5": "ad2e5d5860e2e18a4f43e06c924d27cd"
        }
      ]
    }
  ]
}
