{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.2.jar",
          "url": "http-api-4.15.2.jar",
          "size": 172790,
          "sha512": "13085ec0655dc7d6ca7259c100dcfa63271825b4d43a4328599ba0c8a172fc53b5a68771ec0ffd2a3b0557006c134904e86f055e688375ceb82001eb99b0ad5c",
          "sha256": "666623e5da68dcf425e186256511fedc195ad8e1be8edad8673ca9569ebbfee2",
          "sha1": "eb5be84166e68eea25934c587560970bcb9d2ead",
          "md5": "d882d26ee9c1b22d1bf7f9eabfcc71b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.2.jar",
          "url": "http-api-4.15.2.jar",
          "size": 172790,
          "sha512": "13085ec0655dc7d6ca7259c100dcfa63271825b4d43a4328599ba0c8a172fc53b5a68771ec0ffd2a3b0557006c134904e86f055e688375ceb82001eb99b0ad5c",
          "sha256": "666623e5da68dcf425e186256511fedc195ad8e1be8edad8673ca9569ebbfee2",
          "sha1": "eb5be84166e68eea25934c587560970bcb9d2ead",
          "md5": "d882d26ee9c1b22d1bf7f9eabfcc71b9"
        }
      ]
    }
  ]
}
