{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "242a9fb871e80f355db941570aa22aa43195ded5014e131998bc69a3b4b66d31aa236f9eeda622b71eddcd3bd3d19165f16be1092e5122fcc7bb9afe1fc3d5c3",
          "sha256": "7d4cf7ef4ccdbaacf92aca08ed14ad8d1314faca098e3d7e9dd4eacdf6bd293e",
          "sha1": "e9e8896a68e37641ade2ed589d1f3c553e74e6fb",
          "md5": "e7e9f678a984b7f569f6d859937dc3fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "242a9fb871e80f355db941570aa22aa43195ded5014e131998bc69a3b4b66d31aa236f9eeda622b71eddcd3bd3d19165f16be1092e5122fcc7bb9afe1fc3d5c3",
          "sha256": "7d4cf7ef4ccdbaacf92aca08ed14ad8d1314faca098e3d7e9dd4eacdf6bd293e",
          "sha1": "e9e8896a68e37641ade2ed589d1f3c553e74e6fb",
          "md5": "e7e9f678a984b7f569f6d859937dc3fd"
        }
      ]
    }
  ]
}
