{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "9d56aa0e3647f11a9ff760dc540087d585a34442658589e01e408c57774a864eafa0886467325d546c5c0b4a683f9c42c1e0098851d84b908a3eb3837f9c1d0a",
          "sha256": "674a9747aa3636c93585c7b2a4421ba5cd2def3d3161df77cbdb44412bf54b85",
          "sha1": "1ad4ae13502f28b99c1bec7fad0564e46c59a281",
          "md5": "d931b840aae8e8f193a4bac02ccffd85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "9d56aa0e3647f11a9ff760dc540087d585a34442658589e01e408c57774a864eafa0886467325d546c5c0b4a683f9c42c1e0098851d84b908a3eb3837f9c1d0a",
          "sha256": "674a9747aa3636c93585c7b2a4421ba5cd2def3d3161df77cbdb44412bf54b85",
          "sha1": "1ad4ae13502f28b99c1bec7fad0564e46c59a281",
          "md5": "d931b840aae8e8f193a4bac02ccffd85"
        }
      ]
    }
  ]
}
