{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "b8392db189c99a58df4683382cf9124c78e0e35cdce75f53f25752098d6a2da325b2d093c1c3bf40933ee42f78bda156ab39d3ad5e2795753ea443ffc33cf25e",
          "sha256": "732dfb78e0675d4edbaea3c7225cd26582e35da272d87cf68fe66c9fa1951371",
          "sha1": "35036a3b3b327e5e1cb72b665e1c331e1df693f9",
          "md5": "06489fa24962d89f0381063ede77c3ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "b8392db189c99a58df4683382cf9124c78e0e35cdce75f53f25752098d6a2da325b2d093c1c3bf40933ee42f78bda156ab39d3ad5e2795753ea443ffc33cf25e",
          "sha256": "732dfb78e0675d4edbaea3c7225cd26582e35da272d87cf68fe66c9fa1951371",
          "sha1": "35036a3b3b327e5e1cb72b665e1c331e1df693f9",
          "md5": "06489fa24962d89f0381063ede77c3ed"
        }
      ]
    }
  ]
}
