{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.5.jar",
          "url": "runescape-api-4.15.5.jar",
          "size": 143805,
          "sha512": "e00e1eca2880b5d0d6c35db7b005a58008b7bec815b3b969ee3e5dc96f3f655cd1a872d9f1b2c86d781e3d30e7771f970571810318ad5795ef2efeb45b859479",
          "sha256": "941743d2a7973918d72d18005bd93cfe1df367f29adaf0efbbe18674ef1e961b",
          "sha1": "5344262b0e68ec6d397cbf3f055046a1c42143c2",
          "md5": "7128e7549408d67def3e56e87daad3fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.5.jar",
          "url": "runescape-api-4.15.5.jar",
          "size": 143805,
          "sha512": "e00e1eca2880b5d0d6c35db7b005a58008b7bec815b3b969ee3e5dc96f3f655cd1a872d9f1b2c86d781e3d30e7771f970571810318ad5795ef2efeb45b859479",
          "sha256": "941743d2a7973918d72d18005bd93cfe1df367f29adaf0efbbe18674ef1e961b",
          "sha1": "5344262b0e68ec6d397cbf3f055046a1c42143c2",
          "md5": "7128e7549408d67def3e56e87daad3fe"
        }
      ]
    }
  ]
}
