{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.5.jar",
          "url": "runescape-api-4.15.5.jar",
          "size": 143805,
          "sha512": "d79073c1c97dd1c2431a60be34c56685e3341af0c5a5afc49f5e20a6dd2ef936222f9232b767994cf65db86316f78e0a8ccb4db3fe89241eb629a22db94291f8",
          "sha256": "1c209be63a6928c9d1dbb4231353acfa731e13507ea77819bf4a08a7a4211a9b",
          "sha1": "ba7c798b7999170278c95f57e8bbec1f88369413",
          "md5": "9322cccf04fbdd8d551f9c8fc6825573"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.5.jar",
          "url": "runescape-api-4.15.5.jar",
          "size": 143805,
          "sha512": "d79073c1c97dd1c2431a60be34c56685e3341af0c5a5afc49f5e20a6dd2ef936222f9232b767994cf65db86316f78e0a8ccb4db3fe89241eb629a22db94291f8",
          "sha256": "1c209be63a6928c9d1dbb4231353acfa731e13507ea77819bf4a08a7a4211a9b",
          "sha1": "ba7c798b7999170278c95f57e8bbec1f88369413",
          "md5": "9322cccf04fbdd8d551f9c8fc6825573"
        }
      ]
    }
  ]
}
