{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146551,
          "sha512": "5914c1451648a0b9c92fc7742ffede9e0ebdf6d8bda3b0eb461c4be3044c8c23d46394ac5241eb43cf8b34b6c176a50c4d5ad62605e5b4598a6fe955cbf0119f",
          "sha256": "e2668724ac40ebf74cbdf44bc4f0d118eff21640cf3ddd0724f8767c22c700d9",
          "sha1": "68c4b19b54216fd7c0596dc804fea1a196439dfe",
          "md5": "a74d33c8a850be1b81ff7bfbfd0d01c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146551,
          "sha512": "5914c1451648a0b9c92fc7742ffede9e0ebdf6d8bda3b0eb461c4be3044c8c23d46394ac5241eb43cf8b34b6c176a50c4d5ad62605e5b4598a6fe955cbf0119f",
          "sha256": "e2668724ac40ebf74cbdf44bc4f0d118eff21640cf3ddd0724f8767c22c700d9",
          "sha1": "68c4b19b54216fd7c0596dc804fea1a196439dfe",
          "md5": "a74d33c8a850be1b81ff7bfbfd0d01c9"
        }
      ]
    }
  ]
}
