{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146551,
          "sha512": "6cffc4c312188bb20ef35e2a630e7e68b746ff0f90ed9d45ee8b44a98ac0a7be57d9fc1673855d8e34e0b6a0c1cc331205ca2c65251cfa94136ad14d71a2b424",
          "sha256": "52742d954a3092edeee8497fa727ea69e288c4ce40e51c500c289e007057ad21",
          "sha1": "47d0446252006eea6c66c5cff0915eb52df1572e",
          "md5": "63dc89dcb68563c52361819d65b2f821"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146551,
          "sha512": "6cffc4c312188bb20ef35e2a630e7e68b746ff0f90ed9d45ee8b44a98ac0a7be57d9fc1673855d8e34e0b6a0c1cc331205ca2c65251cfa94136ad14d71a2b424",
          "sha256": "52742d954a3092edeee8497fa727ea69e288c4ce40e51c500c289e007057ad21",
          "sha1": "47d0446252006eea6c66c5cff0915eb52df1572e",
          "md5": "63dc89dcb68563c52361819d65b2f821"
        }
      ]
    }
  ]
}
