{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146573,
          "sha512": "76a093bac363058c59e6118d1305c45371a044f51347e7713f458197d3451200eb8cc65f43ff981b91a20d5b16750301deaf59aad69c69d68281b10ce208c73f",
          "sha256": "94c26815bef6d1d492f2bcc648ffc5acf20d7ae01c917ec79cbebf61dcf146f8",
          "sha1": "8d91e71426da7f92df1291321630fc95a199b745",
          "md5": "b77b62e2a7113b607f40ab5bbc7f07fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.1.jar",
          "url": "runescape-api-4.18.1.jar",
          "size": 146573,
          "sha512": "76a093bac363058c59e6118d1305c45371a044f51347e7713f458197d3451200eb8cc65f43ff981b91a20d5b16750301deaf59aad69c69d68281b10ce208c73f",
          "sha256": "94c26815bef6d1d492f2bcc648ffc5acf20d7ae01c917ec79cbebf61dcf146f8",
          "sha1": "8d91e71426da7f92df1291321630fc95a199b745",
          "md5": "b77b62e2a7113b607f40ab5bbc7f07fd"
        }
      ]
    }
  ]
}
