{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "ac43d96d17f767b4ed9c785b7bc86e82e9d37e0bebd8d10df6447e24d3d1bb155d325d77a58e01c4bc453132887b3bb4f59c141d396d71e576c3f885d7bf706a",
          "sha256": "298865758a223533bcdbfd14ca1d6cac6a5221ea06eac7cdf3b173123b2a9bd4",
          "sha1": "1c5e3014807662e10fbe05a5ae91d1bb92d72687",
          "md5": "18ad3dad848e7e53f524e4e0417084d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "ac43d96d17f767b4ed9c785b7bc86e82e9d37e0bebd8d10df6447e24d3d1bb155d325d77a58e01c4bc453132887b3bb4f59c141d396d71e576c3f885d7bf706a",
          "sha256": "298865758a223533bcdbfd14ca1d6cac6a5221ea06eac7cdf3b173123b2a9bd4",
          "sha1": "1c5e3014807662e10fbe05a5ae91d1bb92d72687",
          "md5": "18ad3dad848e7e53f524e4e0417084d1"
        }
      ]
    }
  ]
}
