{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "ce5f0e94a50110c96cfe06e203d06117a310309effbf2f345c8d8fa0d6c802e7eb61455b937cae8c79bb0b4b24a7c325923afefa5451616d29a4b636e97a5f60",
          "sha256": "f55fcce97c530831d7a9ee1131b3ab4d3bcc143dd52476ad04524ae0048c31b0",
          "sha1": "74080797c6afa37bea6f79f72eb334b64e10cf12",
          "md5": "14b292139ab367493dbad1b1091f928d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "ce5f0e94a50110c96cfe06e203d06117a310309effbf2f345c8d8fa0d6c802e7eb61455b937cae8c79bb0b4b24a7c325923afefa5451616d29a4b636e97a5f60",
          "sha256": "f55fcce97c530831d7a9ee1131b3ab4d3bcc143dd52476ad04524ae0048c31b0",
          "sha1": "74080797c6afa37bea6f79f72eb334b64e10cf12",
          "md5": "14b292139ab367493dbad1b1091f928d"
        }
      ]
    }
  ]
}
