{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "23cafd71a054851dd115971e4e634e369b63dfa12a4a485e44db639d6caeb69ec362ee04c2bdc811305d938a3a9f20a9812e0f813ee9874ff657085c1f79b856",
          "sha256": "989c322530d44d3f191468812e15dafa1f3516765122b6ad79eb42556d511769",
          "sha1": "de226dd311c80e84b7ab8cf935799d70fdef0d9c",
          "md5": "14ce4db218f6eecb9eb60d975902ccb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "23cafd71a054851dd115971e4e634e369b63dfa12a4a485e44db639d6caeb69ec362ee04c2bdc811305d938a3a9f20a9812e0f813ee9874ff657085c1f79b856",
          "sha256": "989c322530d44d3f191468812e15dafa1f3516765122b6ad79eb42556d511769",
          "sha1": "de226dd311c80e84b7ab8cf935799d70fdef0d9c",
          "md5": "14ce4db218f6eecb9eb60d975902ccb9"
        }
      ]
    }
  ]
}
