{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "dyqmqj3g2rchnhjqhhiq5bbrta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.3.jar",
          "url": "runescape-api-3.5.3.jar",
          "size": 104610,
          "sha512": "842e2be950e8c7eef704e4dd4115ae681e3ee3bae80c0b36c683fef830d739ed90125f87e3d94791d00869ffac9972f2c181f6749d5bdc6cf511a8e183d90a0b",
          "sha256": "70a69aae05173892db7e8db719436657a5af4c00b6041c2af18343093dad2cb6",
          "sha1": "e5963927a5338b1d784ed73b509ee934c461181e",
          "md5": "04e4ee244d59e3f8f1d50e111ddd0470"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.3.jar",
          "url": "runescape-api-3.5.3.jar",
          "size": 104610,
          "sha512": "842e2be950e8c7eef704e4dd4115ae681e3ee3bae80c0b36c683fef830d739ed90125f87e3d94791d00869ffac9972f2c181f6749d5bdc6cf511a8e183d90a0b",
          "sha256": "70a69aae05173892db7e8db719436657a5af4c00b6041c2af18343093dad2cb6",
          "sha1": "e5963927a5338b1d784ed73b509ee934c461181e",
          "md5": "04e4ee244d59e3f8f1d50e111ddd0470"
        }
      ]
    }
  ]
}
