{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.14.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.14.0.jar",
          "url": "runescape-api-4.14.0.jar",
          "size": 143543,
          "sha512": "13e0bebe539c8dca3499d96ee20c33aea0ece13743eab29d9b203e52ed35324414656367a72531d305bf41fa84020798edcaae473354433299d1d738afb38574",
          "sha256": "d67d0361f80f8b8c5c444d4598ff184749f95ccec49aae7076cfe842a725db12",
          "sha1": "1c5079d2faa6ed0ccb02474628b13ccc06ccc5a7",
          "md5": "84862ac65b61e514326bed3742e65d47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.14.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.14.0.jar",
          "url": "runescape-api-4.14.0.jar",
          "size": 143543,
          "sha512": "13e0bebe539c8dca3499d96ee20c33aea0ece13743eab29d9b203e52ed35324414656367a72531d305bf41fa84020798edcaae473354433299d1d738afb38574",
          "sha256": "d67d0361f80f8b8c5c444d4598ff184749f95ccec49aae7076cfe842a725db12",
          "sha1": "1c5079d2faa6ed0ccb02474628b13ccc06ccc5a7",
          "md5": "84862ac65b61e514326bed3742e65d47"
        }
      ]
    }
  ]
}
