{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.14.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.14.0.jar",
          "url": "runescape-api-4.14.0.jar",
          "size": 143543,
          "sha512": "8c6e1ba08a4ccd65ec7d26dcaab141bd2ed0de0e58da39f5898651da2af61b2499e857573930b41fdadfdb10b1d5b95f24573b9a73e83119cc88ac3209c8f439",
          "sha256": "384e2e00294c9962a43629e5209b27d31724ac04344e4cfd5f5566195991982f",
          "sha1": "0c0da710e8285d785dd689c5ffe3d664287e914a",
          "md5": "d03c6d07679d40c88015391ac17b659b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.14.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.14.0.jar",
          "url": "runescape-api-4.14.0.jar",
          "size": 143543,
          "sha512": "8c6e1ba08a4ccd65ec7d26dcaab141bd2ed0de0e58da39f5898651da2af61b2499e857573930b41fdadfdb10b1d5b95f24573b9a73e83119cc88ac3209c8f439",
          "sha256": "384e2e00294c9962a43629e5209b27d31724ac04344e4cfd5f5566195991982f",
          "sha1": "0c0da710e8285d785dd689c5ffe3d664287e914a",
          "md5": "d03c6d07679d40c88015391ac17b659b"
        }
      ]
    }
  ]
}
