{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "q2idj2wxcvb2llf3ln7kb23cxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.3.0.jar",
          "url": "runelite-api-4.3.0.jar",
          "size": 1255289,
          "sha512": "202873c02cbe6dbad9309ea7c4622710432b08854d744618a40a6e195cdc7fa8e012492cf9bdb2067863ecf12e6b4b553a9855807a904a2b46fa25e8768820f1",
          "sha256": "ad469727de9245d41101cfdc4cc62f72c20176e936429a88d27955a63d7906b0",
          "sha1": "49a9b60930fbdb8a8ec1028a85582a6982bd0520",
          "md5": "261a2cd8ea7a43a47d85e92c91421cb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.3.0.jar",
          "url": "runelite-api-4.3.0.jar",
          "size": 1255289,
          "sha512": "202873c02cbe6dbad9309ea7c4622710432b08854d744618a40a6e195cdc7fa8e012492cf9bdb2067863ecf12e6b4b553a9855807a904a2b46fa25e8768820f1",
          "sha256": "ad469727de9245d41101cfdc4cc62f72c20176e936429a88d27955a63d7906b0",
          "sha1": "49a9b60930fbdb8a8ec1028a85582a6982bd0520",
          "md5": "261a2cd8ea7a43a47d85e92c91421cb4"
        }
      ]
    }
  ]
}
