{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.24.1.jar",
          "url": "http-api-4.24.1.jar",
          "size": 99204,
          "sha512": "039ca549000bc8b303612a2140adb398b83b6a89a83c1215ddb2ae50f435a16b583ca8730e17840913db7461233218a6e6b1fea404e0ec919a4bf0a082c361f1",
          "sha256": "0ad07d347a28014bfed308613e7d26886b83054cec1fcfb749dfdbb0b4b44014",
          "sha1": "9910e1fa00d36853ad4d6535d73b2c93ef990b03",
          "md5": "4baf286850e74bd8fc7295ae4dbf4562"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.24.1.jar",
          "url": "http-api-4.24.1.jar",
          "size": 99204,
          "sha512": "039ca549000bc8b303612a2140adb398b83b6a89a83c1215ddb2ae50f435a16b583ca8730e17840913db7461233218a6e6b1fea404e0ec919a4bf0a082c361f1",
          "sha256": "0ad07d347a28014bfed308613e7d26886b83054cec1fcfb749dfdbb0b4b44014",
          "sha1": "9910e1fa00d36853ad4d6535d73b2c93ef990b03",
          "md5": "4baf286850e74bd8fc7295ae4dbf4562"
        }
      ]
    }
  ]
}
