{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.24.1.jar",
          "url": "http-api-4.24.1.jar",
          "size": 99208,
          "sha512": "7468444bd1fe4ca8174afaa135ae954306806c0c75b56410510cad11301bf2dc4ff4fc04cc96a0921953411f3d43f16da9fa9501e79ff63449f8b52a96458a8a",
          "sha256": "5ffc2a5451700478999f4a44659f85d127bb9e5d65939723a6c946c0b59db57f",
          "sha1": "24d1b3ca48bf683a23975a7af6588f99a48216a5",
          "md5": "39fd057a9fcbfd6a4d19cafe5f43796f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.24.1.jar",
          "url": "http-api-4.24.1.jar",
          "size": 99208,
          "sha512": "7468444bd1fe4ca8174afaa135ae954306806c0c75b56410510cad11301bf2dc4ff4fc04cc96a0921953411f3d43f16da9fa9501e79ff63449f8b52a96458a8a",
          "sha256": "5ffc2a5451700478999f4a44659f85d127bb9e5d65939723a6c946c0b59db57f",
          "sha1": "24d1b3ca48bf683a23975a7af6588f99a48216a5",
          "md5": "39fd057a9fcbfd6a4d19cafe5f43796f"
        }
      ]
    }
  ]
}
