{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 172792,
          "sha512": "c0c0dfe0b9e5e3af375bdf14a7946a6913aaa928c31f0b6dacfe89b1ef7693a9c80330c22d2484f3bbaf77b1b51fd1337486da8696d12e3bbd84f0c033c87426",
          "sha256": "956444dde2a1254430f459bb3bbf658fb4897851d5906684560316f69c53781e",
          "sha1": "de689acd7df7aef87b663eee01d21cfbc05853b7",
          "md5": "63298124fb75547ed0d338f3190c4cc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 172792,
          "sha512": "c0c0dfe0b9e5e3af375bdf14a7946a6913aaa928c31f0b6dacfe89b1ef7693a9c80330c22d2484f3bbaf77b1b51fd1337486da8696d12e3bbd84f0c033c87426",
          "sha256": "956444dde2a1254430f459bb3bbf658fb4897851d5906684560316f69c53781e",
          "sha1": "de689acd7df7aef87b663eee01d21cfbc05853b7",
          "md5": "63298124fb75547ed0d338f3190c4cc2"
        }
      ]
    }
  ]
}
