{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 172798,
          "sha512": "34a74860884b1e9218c80b1175645bb12c277fa1e2d512127cd7c0fdb1d1a3f15c95611a466d38fe02e72df1f09c0e575df4689bc0205d3b4bafe737e8040543",
          "sha256": "0fd02926c09d7061403eaacf776297dc3940e05007f4f342a99ee114343b56a6",
          "sha1": "b0231b8a993078e21080f28912b0be1c2fbcb725",
          "md5": "ffb9a0ef983d5000b24505e3f3778902"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 172798,
          "sha512": "34a74860884b1e9218c80b1175645bb12c277fa1e2d512127cd7c0fdb1d1a3f15c95611a466d38fe02e72df1f09c0e575df4689bc0205d3b4bafe737e8040543",
          "sha256": "0fd02926c09d7061403eaacf776297dc3940e05007f4f342a99ee114343b56a6",
          "sha1": "b0231b8a993078e21080f28912b0be1c2fbcb725",
          "md5": "ffb9a0ef983d5000b24505e3f3778902"
        }
      ]
    }
  ]
}
