{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 172798,
          "sha512": "374c4ac7769a6fafbecfcf72b58a32d22582202bf9257e9a14a6f9b66153cb824da9c960f9cf70b2dc7ace23704361f07e8143296eb4a5ab5b421e31f39fd70a",
          "sha256": "1939cd62af50d6affc90c0769182cb1c1c4b2553ffbe8541582e3be07e006e1d",
          "sha1": "e8ea8ddbe3671fb736cd00f1f7e5a0aff1eb77f5",
          "md5": "85658332c93fb9954393f0bdfe8154b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.4.jar",
          "url": "http-api-4.15.4.jar",
          "size": 172798,
          "sha512": "374c4ac7769a6fafbecfcf72b58a32d22582202bf9257e9a14a6f9b66153cb824da9c960f9cf70b2dc7ace23704361f07e8143296eb4a5ab5b421e31f39fd70a",
          "sha256": "1939cd62af50d6affc90c0769182cb1c1c4b2553ffbe8541582e3be07e006e1d",
          "sha1": "e8ea8ddbe3671fb736cd00f1f7e5a0aff1eb77f5",
          "md5": "85658332c93fb9954393f0bdfe8154b3"
        }
      ]
    }
  ]
}
