{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.2.jar",
          "url": "runescape-api-4.13.2.jar",
          "size": 143530,
          "sha512": "e581c9c3003a085b33eb30b20f44115ba8bd09f02edb5609fe261f47d39340541ccccab4a2cc0efc95c4aa80eca90cc02bacc0bc7de54c52c8c3025c65da22da",
          "sha256": "81e2657158e3f7a4b9a0c8d70dd7703b44c59d0affbbd6111996f5b841696c3f",
          "sha1": "5fa28d7f49358f96bcad96326df95f79fa444af6",
          "md5": "86a809d2a05fb516ad770935155509c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.13.2.jar",
          "url": "runescape-api-4.13.2.jar",
          "size": 143530,
          "sha512": "e581c9c3003a085b33eb30b20f44115ba8bd09f02edb5609fe261f47d39340541ccccab4a2cc0efc95c4aa80eca90cc02bacc0bc7de54c52c8c3025c65da22da",
          "sha256": "81e2657158e3f7a4b9a0c8d70dd7703b44c59d0affbbd6111996f5b841696c3f",
          "sha1": "5fa28d7f49358f96bcad96326df95f79fa444af6",
          "md5": "86a809d2a05fb516ad770935155509c8"
        }
      ]
    }
  ]
}
