{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "37d1f6299525e9bc922f79838edc582d3c840ab89bea48ad33d96d70bba50bc8991479d3e46d954ddc1d7e3ba2da71f4c775d20c03cc9aa3cf51bae7fa0068a4",
          "sha256": "c96b8560d8bbdecd58f274e54ef9c997b611b9c9e71365b814e75bef5b9cc508",
          "sha1": "6ab005ead0c9f8569eff604935d427a81f41696a",
          "md5": "635be16ad1a0090a55f1d4a053ad10a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "37d1f6299525e9bc922f79838edc582d3c840ab89bea48ad33d96d70bba50bc8991479d3e46d954ddc1d7e3ba2da71f4c775d20c03cc9aa3cf51bae7fa0068a4",
          "sha256": "c96b8560d8bbdecd58f274e54ef9c997b611b9c9e71365b814e75bef5b9cc508",
          "sha1": "6ab005ead0c9f8569eff604935d427a81f41696a",
          "md5": "635be16ad1a0090a55f1d4a053ad10a2"
        }
      ]
    }
  ]
}
