{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "f1f7318cc0e9740f38072bdad86f528a9b1844d403875a18de66968502ce3aaaac30505e80e8d83204365df0707647c11c9e7dd0a36b2db42475b8076b41f76d",
          "sha256": "96b1133d5d17a9e65ed6030308c8e2f982d1a51da1c1d62394a8da43dabe5fc7",
          "sha1": "380c5558173add515fe8d7691fd07b9d7b6fe33d",
          "md5": "3853de2a5d69d29b64ca494d1c5c3ebc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "f1f7318cc0e9740f38072bdad86f528a9b1844d403875a18de66968502ce3aaaac30505e80e8d83204365df0707647c11c9e7dd0a36b2db42475b8076b41f76d",
          "sha256": "96b1133d5d17a9e65ed6030308c8e2f982d1a51da1c1d62394a8da43dabe5fc7",
          "sha1": "380c5558173add515fe8d7691fd07b9d7b6fe33d",
          "md5": "3853de2a5d69d29b64ca494d1c5c3ebc"
        }
      ]
    }
  ]
}
