{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "b77767affbe823d4fe37d2aa7e515cc1e9c7a5f96aa4d4d3b76e0b182c614b95c5105dc52d5ddec8901e5c6ce34209a65dbf1a66bb6459fd6d810304afea526c",
          "sha256": "8d45632e98981dd04b0352da998badecc369e8d57d3feb33189a7998b0bcbb12",
          "sha1": "2db282433c02ae370c0bd56e0abcc5281b8144f2",
          "md5": "be1035eed3ffa3b3cfec4b0af91e8660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "b77767affbe823d4fe37d2aa7e515cc1e9c7a5f96aa4d4d3b76e0b182c614b95c5105dc52d5ddec8901e5c6ce34209a65dbf1a66bb6459fd6d810304afea526c",
          "sha256": "8d45632e98981dd04b0352da998badecc369e8d57d3feb33189a7998b0bcbb12",
          "sha1": "2db282433c02ae370c0bd56e0abcc5281b8144f2",
          "md5": "be1035eed3ffa3b3cfec4b0af91e8660"
        }
      ]
    }
  ]
}
