{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "046db761eb62c17488fb8a669f3c9614ade8b6f32b8232ad75d36ae0401715d465039161edb0fb4c4323fa6a6fca0405fac156d5a74be21d7563b0567bbd4278",
          "sha256": "a1aa2ed14e7f57bddc4979ba2b9779a5e2ee2f1e4b5671a952f5024e33e6e7a0",
          "sha1": "101d683a906325aad90d686e48d5e9397573b6b1",
          "md5": "e4539d9628346511b4a5758f1f59f531"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.2.jar",
          "url": "runelite-jshell-4.31.2.jar",
          "size": 26557,
          "sha512": "046db761eb62c17488fb8a669f3c9614ade8b6f32b8232ad75d36ae0401715d465039161edb0fb4c4323fa6a6fca0405fac156d5a74be21d7563b0567bbd4278",
          "sha256": "a1aa2ed14e7f57bddc4979ba2b9779a5e2ee2f1e4b5671a952f5024e33e6e7a0",
          "sha1": "101d683a906325aad90d686e48d5e9397573b6b1",
          "md5": "e4539d9628346511b4a5758f1f59f531"
        }
      ]
    }
  ]
}
