{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.24.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.24.1.jar",
          "url": "runescape-api-4.24.1.jar",
          "size": 149638,
          "sha512": "2ff6f101b4cd627fcde6b908f19ecc13bec4d7fb2c87e52357df36ac73a3be732488233033a389fb22a586ab491024bce4f26132b7cd73d63c187b9bb1ee079b",
          "sha256": "31b9402a54b6985fc11b62203dc810ffd0f0b8459c6d5c0cf97f08def98efdcd",
          "sha1": "58fcd78ac3cd55539bfaf24c22ab9acfbd554a95",
          "md5": "7734d098f5a941c265886a8fb57c604a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.24.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.24.1.jar",
          "url": "runescape-api-4.24.1.jar",
          "size": 149638,
          "sha512": "2ff6f101b4cd627fcde6b908f19ecc13bec4d7fb2c87e52357df36ac73a3be732488233033a389fb22a586ab491024bce4f26132b7cd73d63c187b9bb1ee079b",
          "sha256": "31b9402a54b6985fc11b62203dc810ffd0f0b8459c6d5c0cf97f08def98efdcd",
          "sha1": "58fcd78ac3cd55539bfaf24c22ab9acfbd554a95",
          "md5": "7734d098f5a941c265886a8fb57c604a"
        }
      ]
    }
  ]
}
