{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.24.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.24.1.jar",
          "url": "runescape-api-4.24.1.jar",
          "size": 149656,
          "sha512": "f6310aa33275cbff88fa94c18d27d025c82dd06ddf345dd1dd7cd792bc0cf1a3c690e9cc1023babc9bf1924af9afcff6ca0cffa675338a3dcaaced19defba353",
          "sha256": "0df29be77a4bebeafd466778fcbf2e08a079ffe91cff05e3e564e05f456ebf09",
          "sha1": "9fcb5a6d9a934f1580dc05059be40383b222fb0a",
          "md5": "a227a48f7005c459393b0ef39333d7c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.24.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.24.1.jar",
          "url": "runescape-api-4.24.1.jar",
          "size": 149656,
          "sha512": "f6310aa33275cbff88fa94c18d27d025c82dd06ddf345dd1dd7cd792bc0cf1a3c690e9cc1023babc9bf1924af9afcff6ca0cffa675338a3dcaaced19defba353",
          "sha256": "0df29be77a4bebeafd466778fcbf2e08a079ffe91cff05e3e564e05f456ebf09",
          "sha1": "9fcb5a6d9a934f1580dc05059be40383b222fb0a",
          "md5": "a227a48f7005c459393b0ef39333d7c1"
        }
      ]
    }
  ]
}
