{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.8.2.jar",
          "url": "http-api-4.8.2.jar",
          "size": 157340,
          "sha512": "797fbe6ee8a926fa94b585c03b0aff80125120a8851b8f5dfe5cce82dd1728ff99b1627773bf1351b7bb12ccc4e4a807012ac9053c07663a814d419d2a0214da",
          "sha256": "201dbf9111a4b193cf6a98583186de02178741a161d71edb34ad1def649f6e2c",
          "sha1": "526f9502ca427ea551eb5295219cc59fd0e845c6",
          "md5": "29138776608d12a189e49fd01f2ab3ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.8.2.jar",
          "url": "http-api-4.8.2.jar",
          "size": 157340,
          "sha512": "797fbe6ee8a926fa94b585c03b0aff80125120a8851b8f5dfe5cce82dd1728ff99b1627773bf1351b7bb12ccc4e4a807012ac9053c07663a814d419d2a0214da",
          "sha256": "201dbf9111a4b193cf6a98583186de02178741a161d71edb34ad1def649f6e2c",
          "sha1": "526f9502ca427ea551eb5295219cc59fd0e845c6",
          "md5": "29138776608d12a189e49fd01f2ab3ba"
        }
      ]
    }
  ]
}
