{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.8.2.jar",
          "url": "http-api-4.8.2.jar",
          "size": 157341,
          "sha512": "e81980ff95e765aaa061200eae04212dda6068bcd6ca0d9445c8f883008fd5ed3840a5a8505e6692c27615245e0b03a493a4f6b66f5aa53079a6d512412c3e94",
          "sha256": "a26d62bb1574c792290f57ec1cc59cfb1aa44efb2fd94c5dbded436700d4653d",
          "sha1": "8be4d2ad002c4548e7894f845dd465e9e39519a6",
          "md5": "acf94841b9db9dc571cd9ae70bf35eed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.8.2.jar",
          "url": "http-api-4.8.2.jar",
          "size": 157341,
          "sha512": "e81980ff95e765aaa061200eae04212dda6068bcd6ca0d9445c8f883008fd5ed3840a5a8505e6692c27615245e0b03a493a4f6b66f5aa53079a6d512412c3e94",
          "sha256": "a26d62bb1574c792290f57ec1cc59cfb1aa44efb2fd94c5dbded436700d4653d",
          "sha1": "8be4d2ad002c4548e7894f845dd465e9e39519a6",
          "md5": "acf94841b9db9dc571cd9ae70bf35eed"
        }
      ]
    }
  ]
}
