{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.6.jar",
          "url": "runelite-jshell-4.15.6.jar",
          "size": 26552,
          "sha512": "9805b5d909600ecb50e1f3bb2fdf547c3cc8a3d1744b91ab97d8b59f956aeac62d070f08fe555774f58e9115dba4b5362c0b02fd3855e0eb9f4d2113b41ba0b9",
          "sha256": "ed2f5261eaafe59c7e595cf6fad0a0df8cafd73c6a1ceee8fc59efb25ebf4f36",
          "sha1": "49606e31c0e6622c606f3afeb396d66133abc3a1",
          "md5": "ac81355316874c735050ee901358a7a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.6.jar",
          "url": "runelite-jshell-4.15.6.jar",
          "size": 26552,
          "sha512": "9805b5d909600ecb50e1f3bb2fdf547c3cc8a3d1744b91ab97d8b59f956aeac62d070f08fe555774f58e9115dba4b5362c0b02fd3855e0eb9f4d2113b41ba0b9",
          "sha256": "ed2f5261eaafe59c7e595cf6fad0a0df8cafd73c6a1ceee8fc59efb25ebf4f36",
          "sha1": "49606e31c0e6622c606f3afeb396d66133abc3a1",
          "md5": "ac81355316874c735050ee901358a7a7"
        }
      ]
    }
  ]
}
