{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "d521145d651f8a54f531653743ca43838428abe4c72bffcef17d530b62d9252be79269d01c24ce4b6fc37a4e148f7c69efebae0b8debc485f29d5261e950e15a",
          "sha256": "5a09cf9ad94e30dc979c587b3aa08737cdf393c0b06474d1f7a7057b89194a2f",
          "sha1": "a1bb96719d8bb78b5b3a4fbc2eb9eff5fbf15136",
          "md5": "be4f4c81d97ccc46f439544cc67ca0ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "d521145d651f8a54f531653743ca43838428abe4c72bffcef17d530b62d9252be79269d01c24ce4b6fc37a4e148f7c69efebae0b8debc485f29d5261e950e15a",
          "sha256": "5a09cf9ad94e30dc979c587b3aa08737cdf393c0b06474d1f7a7057b89194a2f",
          "sha1": "a1bb96719d8bb78b5b3a4fbc2eb9eff5fbf15136",
          "md5": "be4f4c81d97ccc46f439544cc67ca0ab"
        }
      ]
    }
  ]
}
