{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "d5f7d71b98e871ce9f1102781ef1be0582303c9357f4cd8e51d94579aa6d2322af60c177ad0e7dc97f6990c249aa7490165f824e09a30ba546ebe87ff8a2e678",
          "sha256": "c6ef1a326e50c0e1f0a83f776f273cf3fde685631bc83e8dd3fcad824f8cceea",
          "sha1": "3ec9171b424c89d725b5477628f2a53ec888b7a0",
          "md5": "b08104fc8aa5576891672c481dfb9f25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "d5f7d71b98e871ce9f1102781ef1be0582303c9357f4cd8e51d94579aa6d2322af60c177ad0e7dc97f6990c249aa7490165f824e09a30ba546ebe87ff8a2e678",
          "sha256": "c6ef1a326e50c0e1f0a83f776f273cf3fde685631bc83e8dd3fcad824f8cceea",
          "sha1": "3ec9171b424c89d725b5477628f2a53ec888b7a0",
          "md5": "b08104fc8aa5576891672c481dfb9f25"
        }
      ]
    }
  ]
}
