{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "22b0bd45a5b120f717f98ac94e483a28e86225ff5428eec5bfc2012c3097ef12a29dd4a8d7b3cf0c4cd54b15f85e5e93f6858d5092c6ba57e6b9b1bfd2155897",
          "sha256": "adcdb53a17778df32fd3ed4d8231fa90d1c0729d6d3307a977b7d0a073f6ce0b",
          "sha1": "210d2873a48f2556eda1a0dde08a1c1e45a86845",
          "md5": "d183ac0adf8d35617646609f08a5adc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "22b0bd45a5b120f717f98ac94e483a28e86225ff5428eec5bfc2012c3097ef12a29dd4a8d7b3cf0c4cd54b15f85e5e93f6858d5092c6ba57e6b9b1bfd2155897",
          "sha256": "adcdb53a17778df32fd3ed4d8231fa90d1c0729d6d3307a977b7d0a073f6ce0b",
          "sha1": "210d2873a48f2556eda1a0dde08a1c1e45a86845",
          "md5": "d183ac0adf8d35617646609f08a5adc1"
        }
      ]
    }
  ]
}
