{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "1bbb4512384d43e2df723e6ab0ca7c3a2a91901152824a00891b028d9f1b67681e049421920c7301fb589d247e87e650632010b7b6a3723467c55877338daad7",
          "sha256": "9ec468690aafd06bb018c1e36fff2eb8dd3dbd9d0e5461a57bdd9e87af16ed01",
          "sha1": "62955d476c9bb9117be8e6d25020c82f76851cef",
          "md5": "b2ffda4e58b1a7c1cf4786736d17a4d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.5.6.jar",
          "url": "http-api-4.5.6.jar",
          "size": 159718,
          "sha512": "1bbb4512384d43e2df723e6ab0ca7c3a2a91901152824a00891b028d9f1b67681e049421920c7301fb589d247e87e650632010b7b6a3723467c55877338daad7",
          "sha256": "9ec468690aafd06bb018c1e36fff2eb8dd3dbd9d0e5461a57bdd9e87af16ed01",
          "sha1": "62955d476c9bb9117be8e6d25020c82f76851cef",
          "md5": "b2ffda4e58b1a7c1cf4786736d17a4d3"
        }
      ]
    }
  ]
}
