{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.2.jar",
          "url": "runelite-jshell-4.18.2.jar",
          "size": 26552,
          "sha512": "b7c75afd8fa3c4b080d6a0847693177f04fbad8f427aef007fa577b689e7ea3df4e93aef347db8872b023e189af03ed748ce384ecba02a4c0a082007283138ee",
          "sha256": "6af27f49698ace9333bc5e8eadc74ff29ac95b7bb3c6a2c201e0e3646871c955",
          "sha1": "98d0dc81df2f00abeeaeab3cf4e03722f6f07923",
          "md5": "841d26a2964b46f73e2e9554f045b08b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.2.jar",
          "url": "runelite-jshell-4.18.2.jar",
          "size": 26552,
          "sha512": "b7c75afd8fa3c4b080d6a0847693177f04fbad8f427aef007fa577b689e7ea3df4e93aef347db8872b023e189af03ed748ce384ecba02a4c0a082007283138ee",
          "sha256": "6af27f49698ace9333bc5e8eadc74ff29ac95b7bb3c6a2c201e0e3646871c955",
          "sha1": "98d0dc81df2f00abeeaeab3cf4e03722f6f07923",
          "md5": "841d26a2964b46f73e2e9554f045b08b"
        }
      ]
    }
  ]
}
