{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pqy6y2uizfg63lf5utwwbewlba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.4.jar",
          "url": "runescape-api-3.5.4.jar",
          "size": 106519,
          "sha512": "80a66f9eb088a88882a53433cbf8314e6b786b75615e3c48d38dc49b3e08aa30716bb9281641ec4543e7ba9b2e355713fa8492ae8b241386a08c0d4ad10c7579",
          "sha256": "28971575d6c29ef59babc109534eb1010d1463d4ef0222e9c895a1bd5adbe58e",
          "sha1": "c1445e4501f91401ae24f65934434286aa666f56",
          "md5": "9cd0ac90cbfd8086fea9f10af7ad84bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.4.jar",
          "url": "runescape-api-3.5.4.jar",
          "size": 106519,
          "sha512": "80a66f9eb088a88882a53433cbf8314e6b786b75615e3c48d38dc49b3e08aa30716bb9281641ec4543e7ba9b2e355713fa8492ae8b241386a08c0d4ad10c7579",
          "sha256": "28971575d6c29ef59babc109534eb1010d1463d4ef0222e9c895a1bd5adbe58e",
          "sha1": "c1445e4501f91401ae24f65934434286aa666f56",
          "md5": "9cd0ac90cbfd8086fea9f10af7ad84bd"
        }
      ]
    }
  ]
}
