{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.2.jar",
          "url": "runelite-api-4.13.2.jar",
          "size": 1332566,
          "sha512": "1bac891b1314cfc40d5c6930288b970239859a639ddd496c0c7492d8bf3aa2820d00b7ab74b61ae996d680476bc1b0e5cdc3c5f443ade425308c425e934f50c8",
          "sha256": "0010a2296fd2491bf0a16af1252e47074d10f0ee14f4990dfd954d9641ed5d5e",
          "sha1": "b4f2eb6909d94471eadc51f2a3963a69a7a12f6b",
          "md5": "f97f22c86de1243672549ab7e8a182fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.2.jar",
          "url": "runelite-api-4.13.2.jar",
          "size": 1332566,
          "sha512": "1bac891b1314cfc40d5c6930288b970239859a639ddd496c0c7492d8bf3aa2820d00b7ab74b61ae996d680476bc1b0e5cdc3c5f443ade425308c425e934f50c8",
          "sha256": "0010a2296fd2491bf0a16af1252e47074d10f0ee14f4990dfd954d9641ed5d5e",
          "sha1": "b4f2eb6909d94471eadc51f2a3963a69a7a12f6b",
          "md5": "f97f22c86de1243672549ab7e8a182fc"
        }
      ]
    }
  ]
}
