{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "a6147652b45343a8a3c38acd76e3863fa852b60be17d21f23dccb149ebe4f5e6b014756ea6d506d0172989eed09d1f40b171bc63d9759e23924afe063c82557a",
          "sha256": "151d26e76f67c1754dadabe96818d5b98fb0efc74aeb7efb42a676e7bcf861b1",
          "sha1": "bd451221f741ca12b436a97435105332d77b760f",
          "md5": "db484ecdcc0c7d0df37e8f127ce7b6ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "a6147652b45343a8a3c38acd76e3863fa852b60be17d21f23dccb149ebe4f5e6b014756ea6d506d0172989eed09d1f40b171bc63d9759e23924afe063c82557a",
          "sha256": "151d26e76f67c1754dadabe96818d5b98fb0efc74aeb7efb42a676e7bcf861b1",
          "sha1": "bd451221f741ca12b436a97435105332d77b760f",
          "md5": "db484ecdcc0c7d0df37e8f127ce7b6ce"
        }
      ]
    }
  ]
}
