{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "530a94594dc845192ba1e95eef2368fd2fe854af832c38a14dc438739e06ffaaf01a3e1faa0165e7b4be7f02bc6c6fc8f50bc53fd27793fb363fe9b4c61cf565",
          "sha256": "749306414f389c80feae84f50c52d43245adeb7fa2491b5c56abd6ec9b984eb4",
          "sha1": "33c200caf226e023f19d3eb0fd9374ffd2757509",
          "md5": "4722bc99f8180f8fb505405c58fe46db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "530a94594dc845192ba1e95eef2368fd2fe854af832c38a14dc438739e06ffaaf01a3e1faa0165e7b4be7f02bc6c6fc8f50bc53fd27793fb363fe9b4c61cf565",
          "sha256": "749306414f389c80feae84f50c52d43245adeb7fa2491b5c56abd6ec9b984eb4",
          "sha1": "33c200caf226e023f19d3eb0fd9374ffd2757509",
          "md5": "4722bc99f8180f8fb505405c58fe46db"
        }
      ]
    }
  ]
}
