{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "3f6beb086e8b11f2cb87a83d2e76fdf5255065ec4b450f03f7953a0f8a8f750b39dd2f265690209c0304ded80378242c13aea2c50717969a47e1bf786f55ca5b",
          "sha256": "97d4f60c503dc7b02a2954004d0ab82787b6de9f2770798aff94d349fbcbd8c7",
          "sha1": "2ffc607378f425c5deba057ef87ac4afa7737153",
          "md5": "0ec824799b71d128afb57aab308ad301"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.3.jar",
          "url": "runelite-api-4.20.3.jar",
          "size": 1347482,
          "sha512": "3f6beb086e8b11f2cb87a83d2e76fdf5255065ec4b450f03f7953a0f8a8f750b39dd2f265690209c0304ded80378242c13aea2c50717969a47e1bf786f55ca5b",
          "sha256": "97d4f60c503dc7b02a2954004d0ab82787b6de9f2770798aff94d349fbcbd8c7",
          "sha1": "2ffc607378f425c5deba057ef87ac4afa7737153",
          "md5": "0ec824799b71d128afb57aab308ad301"
        }
      ]
    }
  ]
}
