{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.5.6.jar",
          "url": "runelite-api-4.5.6.jar",
          "size": 1258543,
          "sha512": "69d375d12a8e7069ce27c4515301137655223a8db89c50388134607b292f931b4f9408049cda6dacb8a75752a75e21ee878b6dee968d606fc8afee86e2afe104",
          "sha256": "072e7bf2842375c05e25e434527c58c508562938a3975c37d761b69cc6965eb2",
          "sha1": "2083d0ea7e7e78b064643d1afb147148f4d78719",
          "md5": "fdbfd94baab2b0bc51ee43c2d86d3126"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.5.6.jar",
          "url": "runelite-api-4.5.6.jar",
          "size": 1258543,
          "sha512": "69d375d12a8e7069ce27c4515301137655223a8db89c50388134607b292f931b4f9408049cda6dacb8a75752a75e21ee878b6dee968d606fc8afee86e2afe104",
          "sha256": "072e7bf2842375c05e25e434527c58c508562938a3975c37d761b69cc6965eb2",
          "sha1": "2083d0ea7e7e78b064643d1afb147148f4d78719",
          "md5": "fdbfd94baab2b0bc51ee43c2d86d3126"
        }
      ]
    }
  ]
}
