{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "ca564e997824586651121414ba7fbc583216595d65f83299b0dc7fb5e232f187131c5315adf26ec2b14cc897bf966f971e084ee1e94ce87ede40a3bf9ca387c2",
          "sha256": "e581a7144b9dd5992bf075fa5fd151e4cf353cc6fff8be856a387f07812ec028",
          "sha1": "49f3e3b771275d03ad87f692eb26796ffc2eeab6",
          "md5": "8ae577c688d0c8c2fd0fb766fbd26270"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "ca564e997824586651121414ba7fbc583216595d65f83299b0dc7fb5e232f187131c5315adf26ec2b14cc897bf966f971e084ee1e94ce87ede40a3bf9ca387c2",
          "sha256": "e581a7144b9dd5992bf075fa5fd151e4cf353cc6fff8be856a387f07812ec028",
          "sha1": "49f3e3b771275d03ad87f692eb26796ffc2eeab6",
          "md5": "8ae577c688d0c8c2fd0fb766fbd26270"
        }
      ]
    }
  ]
}
