{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "40f347b64f4d4fadd14b6e012cb4b633ec82be769e034969cd2be47d7f28e1fd9d46d3757307c07faec51507624ecddf584644ba88f1c79d34c5adc643d3880f",
          "sha256": "a94fc4bb0021d667622d6d6be6a88f76e16ff94024a6da8eb1aa3babb46dfdd7",
          "sha1": "c0fd93a5984af080d2d9ffd10b6db8089f258682",
          "md5": "32bdc8d282d34a85a41af1c2ed3b143c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "40f347b64f4d4fadd14b6e012cb4b633ec82be769e034969cd2be47d7f28e1fd9d46d3757307c07faec51507624ecddf584644ba88f1c79d34c5adc643d3880f",
          "sha256": "a94fc4bb0021d667622d6d6be6a88f76e16ff94024a6da8eb1aa3babb46dfdd7",
          "sha1": "c0fd93a5984af080d2d9ffd10b6db8089f258682",
          "md5": "32bdc8d282d34a85a41af1c2ed3b143c"
        }
      ]
    }
  ]
}
