{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "d5aaba9c05315236fec3b9ddbae1177e8b1eabc350b3b3546956bef89b5d703e85e1d9c58dccb95fed848c263e1ce1d35f02df7bd04b01fc4cc46715003504ba",
          "sha256": "2c3ee162f9d5a15edddbbcbff66e6d326d83da77adba72be388b870c34d3e313",
          "sha1": "ebbd65e72922481d0f53eff91187840badf5de26",
          "md5": "1cca8890fa6197fdad749ec3fef3e050"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "d5aaba9c05315236fec3b9ddbae1177e8b1eabc350b3b3546956bef89b5d703e85e1d9c58dccb95fed848c263e1ce1d35f02df7bd04b01fc4cc46715003504ba",
          "sha256": "2c3ee162f9d5a15edddbbcbff66e6d326d83da77adba72be388b870c34d3e313",
          "sha1": "ebbd65e72922481d0f53eff91187840badf5de26",
          "md5": "1cca8890fa6197fdad749ec3fef3e050"
        }
      ]
    }
  ]
}
