{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99205,
          "sha512": "8ececb47923ff5c559462c1d8b28aeebcf2c9d31076d76384f722177f3f44283683d565c1131f8459048637c2d6c174e6cae303e322b9eb03604faab679a9e99",
          "sha256": "addf7002443da8ed306abbbf395cc9ac618579f6e67df48b5d541d5e6d762d37",
          "sha1": "ef341e6aaca48489b1a16ec8bbafb6002c36828b",
          "md5": "389e45f90280d61d5e23fbb9adbd1d61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99205,
          "sha512": "8ececb47923ff5c559462c1d8b28aeebcf2c9d31076d76384f722177f3f44283683d565c1131f8459048637c2d6c174e6cae303e322b9eb03604faab679a9e99",
          "sha256": "addf7002443da8ed306abbbf395cc9ac618579f6e67df48b5d541d5e6d762d37",
          "sha1": "ef341e6aaca48489b1a16ec8bbafb6002c36828b",
          "md5": "389e45f90280d61d5e23fbb9adbd1d61"
        }
      ]
    }
  ]
}
