{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346888,
          "sha512": "b3837c3613830d3820d81e9a86384815bd11a16e839234cdbdf410c4883582e2cd8972aba1c13bad84c001bcefc04122e2ac85e74c8a0ef29f609e5618b608d8",
          "sha256": "4e349b0c1b5f9f0f3bf3502e1d9cf13af48dd4136ed18a924109b85f2c3e304c",
          "sha1": "5d25c1f733ca17abcba3534d74f6a415e9969e18",
          "md5": "e2c90b52fb45f6296fea6ed481a597ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346888,
          "sha512": "b3837c3613830d3820d81e9a86384815bd11a16e839234cdbdf410c4883582e2cd8972aba1c13bad84c001bcefc04122e2ac85e74c8a0ef29f609e5618b608d8",
          "sha256": "4e349b0c1b5f9f0f3bf3502e1d9cf13af48dd4136ed18a924109b85f2c3e304c",
          "sha1": "5d25c1f733ca17abcba3534d74f6a415e9969e18",
          "md5": "e2c90b52fb45f6296fea6ed481a597ff"
        }
      ]
    }
  ]
}
