{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346888,
          "sha512": "7521fa9fa362da1251cfcfa447b5846d1489441d16d665cd462149fe1951787e386c811257ca221fd60ecf6a2cbc47819a7b37955c8f711e669f7bdd3aa0bc77",
          "sha256": "bfb66acfef33cb7d6c98587f5cb92f0edd5fb328c6c39d556b6e50db0c311559",
          "sha1": "9bef17601bf72e20f7cfe7b1e104e88778286d0e",
          "md5": "ff068349a3a85725b690cd41bfc0575e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.0.jar",
          "url": "runelite-api-4.25.0.jar",
          "size": 1346888,
          "sha512": "7521fa9fa362da1251cfcfa447b5846d1489441d16d665cd462149fe1951787e386c811257ca221fd60ecf6a2cbc47819a7b37955c8f711e669f7bdd3aa0bc77",
          "sha256": "bfb66acfef33cb7d6c98587f5cb92f0edd5fb328c6c39d556b6e50db0c311559",
          "sha1": "9bef17601bf72e20f7cfe7b1e104e88778286d0e",
          "md5": "ff068349a3a85725b690cd41bfc0575e"
        }
      ]
    }
  ]
}
