{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.13.jar",
          "url": "runelite-api-4.9.13.jar",
          "size": 1281992,
          "sha512": "39325fe9ce4b44e2e833855c96a9450192eef949323df924717ed5d71b4a5ed63c2100f1589292732b71f81af17ac73fa6e5ed0ed7f6d5c3c13a693f69e77204",
          "sha256": "e76668cd386ec9671cadd3fea163bdef749e3f0a97cf8456c35b74f79f4f8794",
          "sha1": "aafc48723617927a62963811c1c3c800819ed2be",
          "md5": "ef7aad944745c603704bcb857c81f1d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.13.jar",
          "url": "runelite-api-4.9.13.jar",
          "size": 1281992,
          "sha512": "39325fe9ce4b44e2e833855c96a9450192eef949323df924717ed5d71b4a5ed63c2100f1589292732b71f81af17ac73fa6e5ed0ed7f6d5c3c13a693f69e77204",
          "sha256": "e76668cd386ec9671cadd3fea163bdef749e3f0a97cf8456c35b74f79f4f8794",
          "sha1": "aafc48723617927a62963811c1c3c800819ed2be",
          "md5": "ef7aad944745c603704bcb857c81f1d1"
        }
      ]
    }
  ]
}
