{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159719,
          "sha512": "929662966c2f619a1ab898dd26dc0fc0f040b9d52d8ba1cad177537df164c5d8465df35d5db4d4a700f809cd0aa0c481a842f418d46dbeb483b5e13e4ed8e8b1",
          "sha256": "e5ab02d919da2244ad49284343b7f4ed1fe871316afa5e6d923ef60bbb1c1690",
          "sha1": "345d2aa2b2c725b702335cc11c7bada47a3a2d70",
          "md5": "93a4a8f545ace5ce7693d4b167111e10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159719,
          "sha512": "929662966c2f619a1ab898dd26dc0fc0f040b9d52d8ba1cad177537df164c5d8465df35d5db4d4a700f809cd0aa0c481a842f418d46dbeb483b5e13e4ed8e8b1",
          "sha256": "e5ab02d919da2244ad49284343b7f4ed1fe871316afa5e6d923ef60bbb1c1690",
          "sha1": "345d2aa2b2c725b702335cc11c7bada47a3a2d70",
          "md5": "93a4a8f545ace5ce7693d4b167111e10"
        }
      ]
    }
  ]
}
