{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159718,
          "sha512": "45109164b684c53e03aa154838dcc5bf41211da6ec983dcdd265f5ac38ce9014e5a41f6e51f6e4804d5ec7530511625145d3a591d52fc71caa7f2cb957181ea8",
          "sha256": "4521676ce0fd807a47361afd7818ea0d5d0ff6181afd88d180de2d2a535339c0",
          "sha1": "60a05a3f831db9c7d0d8823b84d54e3711dbff1f",
          "md5": "a31cd374af0f38c8524915c8b6bb87c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159718,
          "sha512": "45109164b684c53e03aa154838dcc5bf41211da6ec983dcdd265f5ac38ce9014e5a41f6e51f6e4804d5ec7530511625145d3a591d52fc71caa7f2cb957181ea8",
          "sha256": "4521676ce0fd807a47361afd7818ea0d5d0ff6181afd88d180de2d2a535339c0",
          "sha1": "60a05a3f831db9c7d0d8823b84d54e3711dbff1f",
          "md5": "a31cd374af0f38c8524915c8b6bb87c6"
        }
      ]
    }
  ]
}
