{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.5.6.jar",
          "url": "runelite-api-4.5.6.jar",
          "size": 1258159,
          "sha512": "27273f8b709195accc68f48af722ab06715276703f30726805ae972854520817189c993f4e46890f019cfb16180e83059d4f9600a06d890702578c78a002e01d",
          "sha256": "e2c291fe1d01cca9117d7ae682680e31615ae99492879d17a3f70a1528d87c46",
          "sha1": "1597bf5f37d80d56ac5f98c3558c4e9a0e6eb2d2",
          "md5": "d3136b6be0c18e29ff05e2a0d0003d80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.5.6.jar",
          "url": "runelite-api-4.5.6.jar",
          "size": 1258159,
          "sha512": "27273f8b709195accc68f48af722ab06715276703f30726805ae972854520817189c993f4e46890f019cfb16180e83059d4f9600a06d890702578c78a002e01d",
          "sha256": "e2c291fe1d01cca9117d7ae682680e31615ae99492879d17a3f70a1528d87c46",
          "sha1": "1597bf5f37d80d56ac5f98c3558c4e9a0e6eb2d2",
          "md5": "d3136b6be0c18e29ff05e2a0d0003d80"
        }
      ]
    }
  ]
}
