{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "brzvkswalbd6bo3kp2pt735iqm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1272621,
          "sha512": "483e71ecbc01afa8b87632abf6b22b87cc8dd1519cbd51ba5f376308cb8f9a693d865f6eed95e91fa1c197cae2e6eccb1ab0107b32c7cd5cb04713afe4b1780f",
          "sha256": "4357a42d1183cad956add0c73ead6863cb30aad9300a48a100118f17420f5352",
          "sha1": "5121f4872a6ddeafa4d342fd6e3b450f2d13832f",
          "md5": "384fa6d160c53d6a58fb9810fb89dafe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1272621,
          "sha512": "483e71ecbc01afa8b87632abf6b22b87cc8dd1519cbd51ba5f376308cb8f9a693d865f6eed95e91fa1c197cae2e6eccb1ab0107b32c7cd5cb04713afe4b1780f",
          "sha256": "4357a42d1183cad956add0c73ead6863cb30aad9300a48a100118f17420f5352",
          "sha1": "5121f4872a6ddeafa4d342fd6e3b450f2d13832f",
          "md5": "384fa6d160c53d6a58fb9810fb89dafe"
        }
      ]
    }
  ]
}
