{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "o6tlvy7o2fcqvhljp5fituawzm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1272587,
          "sha512": "ef8cc752e8c6e75d7914754928997553eeb28513b880a9c4b9989d07f235ee7bef40315bbf2a08a2c5d8137b799b93521d6f164f8937507d080ee7c01948c189",
          "sha256": "19e103e8d518dfcb18d02e33df8eddd7d5ca312cca7aae2b38c2e94a861237f7",
          "sha1": "2c5b85804cfb2731d590c469835b996941754583",
          "md5": "f70a5a9b00ad2b9f57b53da713f36fee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1272587,
          "sha512": "ef8cc752e8c6e75d7914754928997553eeb28513b880a9c4b9989d07f235ee7bef40315bbf2a08a2c5d8137b799b93521d6f164f8937507d080ee7c01948c189",
          "sha256": "19e103e8d518dfcb18d02e33df8eddd7d5ca312cca7aae2b38c2e94a861237f7",
          "sha1": "2c5b85804cfb2731d590c469835b996941754583",
          "md5": "f70a5a9b00ad2b9f57b53da713f36fee"
        }
      ]
    }
  ]
}
