{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "d7322y27dvgvrg6qrrbfg6kba4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1272124,
          "sha512": "8e8ba12a0faf94e5276411f208070b6b1020cef7bfdd309b973fbff0386ffa66146316dbead0b515c4b16a5435dc1be5ffe1e860dcbf38a25bace2bc93d784e4",
          "sha256": "ac4127f82b5dc3adaba3069e62145177ed3d463dd07b3fa1468df1bed57e67d2",
          "sha1": "15c58aba1683ddf7d8b998e9f32e63313a090357",
          "md5": "1e3c917caed526fd1fd0ed4fdee50ad2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1272124,
          "sha512": "8e8ba12a0faf94e5276411f208070b6b1020cef7bfdd309b973fbff0386ffa66146316dbead0b515c4b16a5435dc1be5ffe1e860dcbf38a25bace2bc93d784e4",
          "sha256": "ac4127f82b5dc3adaba3069e62145177ed3d463dd07b3fa1468df1bed57e67d2",
          "sha1": "15c58aba1683ddf7d8b998e9f32e63313a090357",
          "md5": "1e3c917caed526fd1fd0ed4fdee50ad2"
        }
      ]
    }
  ]
}
