{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.9.jar",
          "url": "runelite-api-4.9.9.jar",
          "size": 1281891,
          "sha512": "cee429216fc6840298d8b45eff909ac8c5401e821ab1261b9090dcc700199b37a818c25e2abdcf7a7f5453ac15e9796fa3c2a9641a6293a937a4278e2d7e03da",
          "sha256": "81b9215bba9934c9d9c26328940d630286d9935f01b6725d4367789b08365404",
          "sha1": "e8c5df85fc733581e0b9a8113d767c494a465e6a",
          "md5": "6447fbb3d32e3525116cb3e9f572c277"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.9.jar",
          "url": "runelite-api-4.9.9.jar",
          "size": 1281891,
          "sha512": "cee429216fc6840298d8b45eff909ac8c5401e821ab1261b9090dcc700199b37a818c25e2abdcf7a7f5453ac15e9796fa3c2a9641a6293a937a4278e2d7e03da",
          "sha256": "81b9215bba9934c9d9c26328940d630286d9935f01b6725d4367789b08365404",
          "sha1": "e8c5df85fc733581e0b9a8113d767c494a465e6a",
          "md5": "6447fbb3d32e3525116cb3e9f572c277"
        }
      ]
    }
  ]
}
