{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 172791,
          "sha512": "33c80e9caa9031ab7752af4dbcb1e2fec986bbe92b089f91fad5e20bc329e8ebeb2ed18a86b43de8fba64370275189346e30401c9ef0afff6836fd8a1b97c247",
          "sha256": "87f92645a0e609b9fb5ecad849668f6dfc2a0acdb54bc352944801ec5ce3841e",
          "sha1": "2af47f7bc700e2a9c931188fb7e26ed2c7ac402a",
          "md5": "e4182ff5a6c47a8115b3d1d8df756b62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 172791,
          "sha512": "33c80e9caa9031ab7752af4dbcb1e2fec986bbe92b089f91fad5e20bc329e8ebeb2ed18a86b43de8fba64370275189346e30401c9ef0afff6836fd8a1b97c247",
          "sha256": "87f92645a0e609b9fb5ecad849668f6dfc2a0acdb54bc352944801ec5ce3841e",
          "sha1": "2af47f7bc700e2a9c931188fb7e26ed2c7ac402a",
          "md5": "e4182ff5a6c47a8115b3d1d8df756b62"
        }
      ]
    }
  ]
}
