{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.8.jar",
          "url": "runescape-api-4.15.8.jar",
          "size": 143805,
          "sha512": "b45cf758fedec30d64a6d95c12656591149a99356d23d314f7e6b789a15e924abb01b1c9059b492f074e01d82d2d9be3748439fbb38105240f0ad74a1a7e634c",
          "sha256": "3a55768d8acc6e4f29e80dfcb51ee4999ab31ca1bda8b91523d4c62cc68ca903",
          "sha1": "dd44b06f4fc19215343fb680d65bf4c7e8429068",
          "md5": "25f08f63aef61c46189964b27c4775f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.8.jar",
          "url": "runescape-api-4.15.8.jar",
          "size": 143805,
          "sha512": "b45cf758fedec30d64a6d95c12656591149a99356d23d314f7e6b789a15e924abb01b1c9059b492f074e01d82d2d9be3748439fbb38105240f0ad74a1a7e634c",
          "sha256": "3a55768d8acc6e4f29e80dfcb51ee4999ab31ca1bda8b91523d4c62cc68ca903",
          "sha1": "dd44b06f4fc19215343fb680d65bf4c7e8429068",
          "md5": "25f08f63aef61c46189964b27c4775f1"
        }
      ]
    }
  ]
}
