{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.8.jar",
          "url": "runescape-api-4.15.8.jar",
          "size": 143805,
          "sha512": "fde1962fcb83824abe04339de2df7998eb509ad4531a87689791a468f532648fd6ef0d6f2bdf530e0378e1e609d8f442e7b3be80b13d72ccc6b1a73fc912fae4",
          "sha256": "fb030d692beac61f6a0ade6c54076c31ed5f5a6ad7169a89546f1acf46800b84",
          "sha1": "1ebc0b531e828063293d39991886c223666fc566",
          "md5": "ca34766d588cc616374873350a8a0eec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.8.jar",
          "url": "runescape-api-4.15.8.jar",
          "size": 143805,
          "sha512": "fde1962fcb83824abe04339de2df7998eb509ad4531a87689791a468f532648fd6ef0d6f2bdf530e0378e1e609d8f442e7b3be80b13d72ccc6b1a73fc912fae4",
          "sha256": "fb030d692beac61f6a0ade6c54076c31ed5f5a6ad7169a89546f1acf46800b84",
          "sha1": "1ebc0b531e828063293d39991886c223666fc566",
          "md5": "ca34766d588cc616374873350a8a0eec"
        }
      ]
    }
  ]
}
