{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.8.jar",
          "url": "runescape-api-4.15.8.jar",
          "size": 143805,
          "sha512": "b21dd05afa68135fa7080125195690e635b49eac8e61bd48dafb39e94f877b758597bb350f0f18da66d4f55c8a33a6db8884f2f7e46e0f3f861847db166fda14",
          "sha256": "1e141151900a18e4c11c3cd432376d0344afe96c29efbfe2ccf5a896eda0ef43",
          "sha1": "ae250ed0d2b4b5dab14a1dfa1fcf7aa7073186c3",
          "md5": "e66ec3fd1f731846d3802925e1069c51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.8.jar",
          "url": "runescape-api-4.15.8.jar",
          "size": 143805,
          "sha512": "b21dd05afa68135fa7080125195690e635b49eac8e61bd48dafb39e94f877b758597bb350f0f18da66d4f55c8a33a6db8884f2f7e46e0f3f861847db166fda14",
          "sha256": "1e141151900a18e4c11c3cd432376d0344afe96c29efbfe2ccf5a896eda0ef43",
          "sha1": "ae250ed0d2b4b5dab14a1dfa1fcf7aa7073186c3",
          "md5": "e66ec3fd1f731846d3802925e1069c51"
        }
      ]
    }
  ]
}
