{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.0.jar",
          "url": "runelite-api-4.15.0.jar",
          "size": 1331666,
          "sha512": "e9ce7b71d52756eba694c68b6357f2ff7988a90663a28c8039559637f971b320f99266007161bcd7ddc288cae1eb5c5f0d94c48ec693162f24be0fffdb136ad5",
          "sha256": "beac5ce852ae9c27fd4df9684ea3fb91e4314a644c5fd9964bbc653a17427bcc",
          "sha1": "c09a62f50309996b3a046ec3fad0d987717844ef",
          "md5": "475e07dbdc3d9e0b634696fb4c2e8fdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.0.jar",
          "url": "runelite-api-4.15.0.jar",
          "size": 1331666,
          "sha512": "e9ce7b71d52756eba694c68b6357f2ff7988a90663a28c8039559637f971b320f99266007161bcd7ddc288cae1eb5c5f0d94c48ec693162f24be0fffdb136ad5",
          "sha256": "beac5ce852ae9c27fd4df9684ea3fb91e4314a644c5fd9964bbc653a17427bcc",
          "sha1": "c09a62f50309996b3a046ec3fad0d987717844ef",
          "md5": "475e07dbdc3d9e0b634696fb4c2e8fdb"
        }
      ]
    }
  ]
}
