{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.0.jar",
          "url": "runelite-api-4.15.0.jar",
          "size": 1331666,
          "sha512": "2021b3dac0ef7e9a2d505b5c4e24f9fbcd24c6c796fe8281b0c8cbd12fe19e4bb32f83b46a86eee39e30588a55899b345f1524a5b89ede6b0bfb79bbe387bc11",
          "sha256": "7108de7befffa6061a43fcfc48dbe855b86217e43a83b4dd1f08c9a9dcf490b2",
          "sha1": "7420e9b26a5382901f3d857032e5efb9f17b95ca",
          "md5": "e9c72b9e4f2b5c2ce19ae3a49848fc23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.0.jar",
          "url": "runelite-api-4.15.0.jar",
          "size": 1331666,
          "sha512": "2021b3dac0ef7e9a2d505b5c4e24f9fbcd24c6c796fe8281b0c8cbd12fe19e4bb32f83b46a86eee39e30588a55899b345f1524a5b89ede6b0bfb79bbe387bc11",
          "sha256": "7108de7befffa6061a43fcfc48dbe855b86217e43a83b4dd1f08c9a9dcf490b2",
          "sha1": "7420e9b26a5382901f3d857032e5efb9f17b95ca",
          "md5": "e9c72b9e4f2b5c2ce19ae3a49848fc23"
        }
      ]
    }
  ]
}
