{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.7.1.jar",
          "url": "http-api-4.7.1.jar",
          "size": 159717,
          "sha512": "814a1c6ec79270efb1bdd1906f62ec1484b739b6f5407395e8fd799412d9c15c25689e5b919380d0301925244e257e4aa20ab49cb644882f16a7d995a6bad5ab",
          "sha256": "1a5c675bf3655938c68d1dc9b297e8ae24637f58d3499b107a0e6bf2d60cf458",
          "sha1": "377fc206927398daf531340821ceb1b7c4b3d71d",
          "md5": "9bdc82930cc1c203a4745ba4b731cb79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.7.1.jar",
          "url": "http-api-4.7.1.jar",
          "size": 159717,
          "sha512": "814a1c6ec79270efb1bdd1906f62ec1484b739b6f5407395e8fd799412d9c15c25689e5b919380d0301925244e257e4aa20ab49cb644882f16a7d995a6bad5ab",
          "sha256": "1a5c675bf3655938c68d1dc9b297e8ae24637f58d3499b107a0e6bf2d60cf458",
          "sha1": "377fc206927398daf531340821ceb1b7c4b3d71d",
          "md5": "9bdc82930cc1c203a4745ba4b731cb79"
        }
      ]
    }
  ]
}
