{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.11.jar",
          "url": "http-api-4.9.11.jar",
          "size": 158533,
          "sha512": "2d1c501deb9488b165414cc27db80e8795bbedc08a89c1d26c7e895c07896e9c12b321bb2ce452010a2931fe78f18a430d5d35f3c8e13ad38fd5cdbb9e0521a7",
          "sha256": "0437642c5250d129479200a7a1f30a484e8b93d33e35669a8705292427a1b223",
          "sha1": "258d46aa6711278e79ff3a768f0464a8e67baf5b",
          "md5": "debf778b555aee4721a45f3ff6cc0c74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.11"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.11.jar",
          "url": "http-api-4.9.11.jar",
          "size": 158533,
          "sha512": "2d1c501deb9488b165414cc27db80e8795bbedc08a89c1d26c7e895c07896e9c12b321bb2ce452010a2931fe78f18a430d5d35f3c8e13ad38fd5cdbb9e0521a7",
          "sha256": "0437642c5250d129479200a7a1f30a484e8b93d33e35669a8705292427a1b223",
          "sha1": "258d46aa6711278e79ff3a768f0464a8e67baf5b",
          "md5": "debf778b555aee4721a45f3ff6cc0c74"
        }
      ]
    }
  ]
}
