{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nqnphptwrvdqdo2z2fvc5u3h2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.0.0.jar",
          "url": "runelite-api-4.0.0.jar",
          "size": 1253667,
          "sha512": "477a290c492cf261e562534aa277f5c0b84b55a15e7197201f00d1325e79b209dcdabb5cf42f73bb3a24a1a58d4213507def2801e0c234a649f1238989ccde53",
          "sha256": "147986c17bcfb496b55023e2b4215e2ce70ae5b761a270e7d041652f38811673",
          "sha1": "8b4e3a1ada2e60a4c628201c629ac95bfdedb217",
          "md5": "d895e7f20952c2a6412c0a6a0f64b0da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.0.0.jar",
          "url": "runelite-api-4.0.0.jar",
          "size": 1253667,
          "sha512": "477a290c492cf261e562534aa277f5c0b84b55a15e7197201f00d1325e79b209dcdabb5cf42f73bb3a24a1a58d4213507def2801e0c234a649f1238989ccde53",
          "sha256": "147986c17bcfb496b55023e2b4215e2ce70ae5b761a270e7d041652f38811673",
          "sha1": "8b4e3a1ada2e60a4c628201c629ac95bfdedb217",
          "md5": "d895e7f20952c2a6412c0a6a0f64b0da"
        }
      ]
    }
  ]
}
