{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "05e5816a37d445df91222a174709dc7fbe824994e6706c2e5536bbc03dd81fc88a1d59285f0333f3371e65529eef2aee32a21f74ff7fe6331c06efd70419e1ea",
          "sha256": "7aa0b103115fb2f9038b79dbe9ac2a882bb7bfa658e3846d900222f57952ec92",
          "sha1": "c0ac31a2c11b1c3efd5902b0b9152e123f83c662",
          "md5": "e5b06c920b2808489c5d190b8b31bfa8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "05e5816a37d445df91222a174709dc7fbe824994e6706c2e5536bbc03dd81fc88a1d59285f0333f3371e65529eef2aee32a21f74ff7fe6331c06efd70419e1ea",
          "sha256": "7aa0b103115fb2f9038b79dbe9ac2a882bb7bfa658e3846d900222f57952ec92",
          "sha1": "c0ac31a2c11b1c3efd5902b0b9152e123f83c662",
          "md5": "e5b06c920b2808489c5d190b8b31bfa8"
        }
      ]
    }
  ]
}
