{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "a129aa14d9a4d618c5e98fedcbfbe3b30ce0ebf34627c0b3b0e55145d77737c7cc18add6e85fe223183835475c87829fa482df6e989f2ab2017cf5c85fa0a16a",
          "sha256": "a2e64718d8f6ae89ebe098ca87ac1a8e247bbfd8eb0dec6127bf7e98707963f3",
          "sha1": "595b58bca2ad337fae8acc5dd8c895cdc2cdfd61",
          "md5": "3a9e125f61569f9f68628eb1d0c66a2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "a129aa14d9a4d618c5e98fedcbfbe3b30ce0ebf34627c0b3b0e55145d77737c7cc18add6e85fe223183835475c87829fa482df6e989f2ab2017cf5c85fa0a16a",
          "sha256": "a2e64718d8f6ae89ebe098ca87ac1a8e247bbfd8eb0dec6127bf7e98707963f3",
          "sha1": "595b58bca2ad337fae8acc5dd8c895cdc2cdfd61",
          "md5": "3a9e125f61569f9f68628eb1d0c66a2e"
        }
      ]
    }
  ]
}
