{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "51c66804a3e5438d1657275629dc6ab7b2607e0cf69fd69a73dac39f3692b6f01ddda9e3d158b92bdf18038de6244d4afa8d3931017304195ee0fbd2e7e36b6f",
          "sha256": "91ce609d5d45e13c056e505fb7d30d680fd034466442db268073734f8ff32350",
          "sha1": "d21b2f0ae2d62da260b62fb2f1bf5dd8ac8c2c44",
          "md5": "3e51ae3bdda7d28a10904f872ab9d544"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.2.jar",
          "url": "runelite-api-4.31.2.jar",
          "size": 1362971,
          "sha512": "51c66804a3e5438d1657275629dc6ab7b2607e0cf69fd69a73dac39f3692b6f01ddda9e3d158b92bdf18038de6244d4afa8d3931017304195ee0fbd2e7e36b6f",
          "sha256": "91ce609d5d45e13c056e505fb7d30d680fd034466442db268073734f8ff32350",
          "sha1": "d21b2f0ae2d62da260b62fb2f1bf5dd8ac8c2c44",
          "md5": "3e51ae3bdda7d28a10904f872ab9d544"
        }
      ]
    }
  ]
}
