{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6rheulyot5fpnai4ze32orumlu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.2.1.jar",
          "url": "runelite-api-4.2.1.jar",
          "size": 1253540,
          "sha512": "0a02dc9122bb8c70c6ebab245d0c99878e2bc524a3fefb83e3648eeebb158c3187d4a8fe74e8dfca09b813cbb8d6c86f570b367d0cece9b87eccba3f55fc2ce1",
          "sha256": "3be19c20370e62d6d1ad765857a6dfc8c678e9dd5918fe4df3e3b4dd7ba3ef90",
          "sha1": "4f6a1fd25aec77af9ad3a1cc5de7d57167c76f3f",
          "md5": "990c1b30a4915eaac12e7d4554dc3f57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.2.1.jar",
          "url": "runelite-api-4.2.1.jar",
          "size": 1253540,
          "sha512": "0a02dc9122bb8c70c6ebab245d0c99878e2bc524a3fefb83e3648eeebb158c3187d4a8fe74e8dfca09b813cbb8d6c86f570b367d0cece9b87eccba3f55fc2ce1",
          "sha256": "3be19c20370e62d6d1ad765857a6dfc8c678e9dd5918fe4df3e3b4dd7ba3ef90",
          "sha1": "4f6a1fd25aec77af9ad3a1cc5de7d57167c76f3f",
          "md5": "990c1b30a4915eaac12e7d4554dc3f57"
        }
      ]
    }
  ]
}
