{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.24.1.jar",
          "url": "http-api-4.24.1.jar",
          "size": 99208,
          "sha512": "1e04489f9f34ee71413f7efd4df76f3f4a46ccda735648704956336413723b5708420e71ee1164cf825b58223507676092a7be8d0860d97027bc5145cee353f9",
          "sha256": "987ea0e9a79815ed2cf27aa58ca3e34162adab970ea199b91a7c4cbeb6aaff14",
          "sha1": "4e48f18edd335ce76031aef13c34f6cee5fd5b86",
          "md5": "ebe30e57b4b0d425a0d6c1919f889729"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.24.1.jar",
          "url": "http-api-4.24.1.jar",
          "size": 99208,
          "sha512": "1e04489f9f34ee71413f7efd4df76f3f4a46ccda735648704956336413723b5708420e71ee1164cf825b58223507676092a7be8d0860d97027bc5145cee353f9",
          "sha256": "987ea0e9a79815ed2cf27aa58ca3e34162adab970ea199b91a7c4cbeb6aaff14",
          "sha1": "4e48f18edd335ce76031aef13c34f6cee5fd5b86",
          "md5": "ebe30e57b4b0d425a0d6c1919f889729"
        }
      ]
    }
  ]
}
