{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.16.0.jar",
          "url": "runelite-api-4.16.0.jar",
          "size": 1331364,
          "sha512": "54993ea4f0c5bc5d721af6d0fb9f207016d0656ac4b3f5d67bfa43d424a8ec9b2603c9dd0d59dadf9add24ebb60bc32ffb33e82739555507b2e1d76424620e52",
          "sha256": "838232d2b14bea83ce64c380e386203d9bdd8c7b4d2c4111dc73b7698de2fff9",
          "sha1": "6f0ed83ae35b36fb2473643874aa056c3f59fed4",
          "md5": "f6050f94b55e4164a1ef36dea0e9a86c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.16.0.jar",
          "url": "runelite-api-4.16.0.jar",
          "size": 1331364,
          "sha512": "54993ea4f0c5bc5d721af6d0fb9f207016d0656ac4b3f5d67bfa43d424a8ec9b2603c9dd0d59dadf9add24ebb60bc32ffb33e82739555507b2e1d76424620e52",
          "sha256": "838232d2b14bea83ce64c380e386203d9bdd8c7b4d2c4111dc73b7698de2fff9",
          "sha1": "6f0ed83ae35b36fb2473643874aa056c3f59fed4",
          "md5": "f6050f94b55e4164a1ef36dea0e9a86c"
        }
      ]
    }
  ]
}
