{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99202,
          "sha512": "4e5fb3a58790ba6e085a12cc01b3deb3b6149754d978f8ab3f28baf6407c0dd0841137633579a2bb4ebabca74cd42370146100c3d691bf307a4b96550b5c31bd",
          "sha256": "8d54f7a557d8994bfa518d076f1f51b65f1ff7ea3ca0ce6020ac281fe5afb603",
          "sha1": "6cafbada3bc000b48069d1c9eee52caf072a87ed",
          "md5": "aacd7dac2e2df7ecd6c191d020ffcdd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99202,
          "sha512": "4e5fb3a58790ba6e085a12cc01b3deb3b6149754d978f8ab3f28baf6407c0dd0841137633579a2bb4ebabca74cd42370146100c3d691bf307a4b96550b5c31bd",
          "sha256": "8d54f7a557d8994bfa518d076f1f51b65f1ff7ea3ca0ce6020ac281fe5afb603",
          "sha1": "6cafbada3bc000b48069d1c9eee52caf072a87ed",
          "md5": "aacd7dac2e2df7ecd6c191d020ffcdd8"
        }
      ]
    }
  ]
}
