{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99210,
          "sha512": "8863e6f14df9734f650561319926a8a6132b8fdb42a630c42cd921510c20a11964c81ab9db0a8affdb951567f0c7a76983deb02667808e4fd4bd25784b6e8150",
          "sha256": "c3187fe2ada3be7e4bd16f611ae460ebcc426f7dd476d13cec040eb1bba25b56",
          "sha1": "8931b04670592851ece3d37a381a7443c8400ce6",
          "md5": "d31f452219f57d3b605b7802d851184d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99210,
          "sha512": "8863e6f14df9734f650561319926a8a6132b8fdb42a630c42cd921510c20a11964c81ab9db0a8affdb951567f0c7a76983deb02667808e4fd4bd25784b6e8150",
          "sha256": "c3187fe2ada3be7e4bd16f611ae460ebcc426f7dd476d13cec040eb1bba25b56",
          "sha1": "8931b04670592851ece3d37a381a7443c8400ce6",
          "md5": "d31f452219f57d3b605b7802d851184d"
        }
      ]
    }
  ]
}
