{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99206,
          "sha512": "d0ecc3f897e9e96214bf57709eac0c318688995481b97c20d719c13ccf01b9c57acb95e70c76aab60f2d6e0690d7fd400a842c0987649758eae169eb23e0c927",
          "sha256": "079b0663a0a460bb073bf6404ef429a1bd37fc3015461b9d76168f31ab095a08",
          "sha1": "f5483f5d3e19717712f0ff4d5bf406ecf3d40b92",
          "md5": "4ec7612672648b46e235b4b76727c553"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.0.jar",
          "url": "http-api-4.25.0.jar",
          "size": 99206,
          "sha512": "d0ecc3f897e9e96214bf57709eac0c318688995481b97c20d719c13ccf01b9c57acb95e70c76aab60f2d6e0690d7fd400a842c0987649758eae169eb23e0c927",
          "sha256": "079b0663a0a460bb073bf6404ef429a1bd37fc3015461b9d76168f31ab095a08",
          "sha1": "f5483f5d3e19717712f0ff4d5bf406ecf3d40b92",
          "md5": "4ec7612672648b46e235b4b76727c553"
        }
      ]
    }
  ]
}
