{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.13.2.jar",
          "url": "http-api-4.13.2.jar",
          "size": 172794,
          "sha512": "51c482bbf7985bee16936cc41164796dbe5a9501bade8ba3391027e21c43eb6dcd3864ad8a9e89b09a39a684136cde86f6f4d6aaf7e2d08d0371b2a352699ea5",
          "sha256": "747467996a014c0b6c1a8b8bab8259da3451a11e09fc8e37e6933d368f75df4a",
          "sha1": "93bd744b00f5301634996542cd1bd0e06924a46d",
          "md5": "2e41fbd7e1a1902f2c0558228f6d9fc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.13.2.jar",
          "url": "http-api-4.13.2.jar",
          "size": 172794,
          "sha512": "51c482bbf7985bee16936cc41164796dbe5a9501bade8ba3391027e21c43eb6dcd3864ad8a9e89b09a39a684136cde86f6f4d6aaf7e2d08d0371b2a352699ea5",
          "sha256": "747467996a014c0b6c1a8b8bab8259da3451a11e09fc8e37e6933d368f75df4a",
          "sha1": "93bd744b00f5301634996542cd1bd0e06924a46d",
          "md5": "2e41fbd7e1a1902f2c0558228f6d9fc6"
        }
      ]
    }
  ]
}
