{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.13.3.jar",
          "url": "runelite-api-4.13.3.jar",
          "size": 1332566,
          "sha512": "30793e562277bacd8740b6c4f68db7da756ff6a7acde26350c363b44488635f1ef4b4d21cc1f17f1d5a63a76e1831a33c6b84065fc05185ba24f495d7409a597",
          "sha256": "7573aa38efb4458141ab6e99c6c86b317ecf1247ee2790a0426b469188006429",
          "sha1": "4012fee7923566974f495aaae5133eebf71955de",
          "md5": "8b11922127d766e83ed365f5ac93e8bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.3.jar",
          "url": "runelite-api-4.13.3.jar",
          "size": 1332566,
          "sha512": "30793e562277bacd8740b6c4f68db7da756ff6a7acde26350c363b44488635f1ef4b4d21cc1f17f1d5a63a76e1831a33c6b84065fc05185ba24f495d7409a597",
          "sha256": "7573aa38efb4458141ab6e99c6c86b317ecf1247ee2790a0426b469188006429",
          "sha1": "4012fee7923566974f495aaae5133eebf71955de",
          "md5": "8b11922127d766e83ed365f5ac93e8bd"
        }
      ]
    }
  ]
}
