{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vnqfelpitvb7tb7mmkrzbtnnue"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.0.0.jar",
          "url": "runelite-api-4.0.0.jar",
          "size": 1250096,
          "sha512": "a8cebb201e54e0b00a47a027fb595f05dd7253c20ff376faf5a37f75f2af553404c6721496d307fd74a54ca57789b0ffea237578784a3f828a5e1bb2a91afdff",
          "sha256": "ecc490fb8d6dc9bc2795469e70f09f949da16b8f78c46407300c5e64e84efef1",
          "sha1": "c9e02f716948fa89c8ef71c3939e3b5eeba968f7",
          "md5": "ae45507b3fa08e9d73668e48b7e3f9d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.0.0.jar",
          "url": "runelite-api-4.0.0.jar",
          "size": 1250096,
          "sha512": "a8cebb201e54e0b00a47a027fb595f05dd7253c20ff376faf5a37f75f2af553404c6721496d307fd74a54ca57789b0ffea237578784a3f828a5e1bb2a91afdff",
          "sha256": "ecc490fb8d6dc9bc2795469e70f09f949da16b8f78c46407300c5e64e84efef1",
          "sha1": "c9e02f716948fa89c8ef71c3939e3b5eeba968f7",
          "md5": "ae45507b3fa08e9d73668e48b7e3f9d4"
        }
      ]
    }
  ]
}
