{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "42bc06f516cd293a0205ae4329ca140b563b1a6076f7a191f34c0d72931031ac36a7b54316a143d6c2205aba7828a3dfb1621810731baba51cb93c7e4391bda5",
          "sha256": "887f49802970fbc4b9a267dfbd280abff78ce6ad08b5488a3e8ed6710d484794",
          "sha1": "4f819da29c89540e67c94756572179528b0a574a",
          "md5": "cd30781c7dfb028366b838a49acce6f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "42bc06f516cd293a0205ae4329ca140b563b1a6076f7a191f34c0d72931031ac36a7b54316a143d6c2205aba7828a3dfb1621810731baba51cb93c7e4391bda5",
          "sha256": "887f49802970fbc4b9a267dfbd280abff78ce6ad08b5488a3e8ed6710d484794",
          "sha1": "4f819da29c89540e67c94756572179528b0a574a",
          "md5": "cd30781c7dfb028366b838a49acce6f4"
        }
      ]
    }
  ]
}
