{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "48454ba22ff07b33642da8701c5ceeccf62f688bc6181740c54a3ac9026b72ee0ed1e1de0e21650b812c65e943b8f892baa720b053e10470edcf2d0b15d17ac0",
          "sha256": "31f72b4ce0bc8e49a91e9f61af8ae2b37ad45d144e735559794f1cc29c3dcdcf",
          "sha1": "4912d55c15511d5dc3a486107a9748946fd2d19a",
          "md5": "49e3aca32aa71db96376f342705d385a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "48454ba22ff07b33642da8701c5ceeccf62f688bc6181740c54a3ac9026b72ee0ed1e1de0e21650b812c65e943b8f892baa720b053e10470edcf2d0b15d17ac0",
          "sha256": "31f72b4ce0bc8e49a91e9f61af8ae2b37ad45d144e735559794f1cc29c3dcdcf",
          "sha1": "4912d55c15511d5dc3a486107a9748946fd2d19a",
          "md5": "49e3aca32aa71db96376f342705d385a"
        }
      ]
    }
  ]
}
