{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "a548d8dbe90f2917da01c8973fb579fdf8add0f54dd27565ee3fc007d09b5687a6f36dd6760784daae44e8013c9fb2b19fc8d16363789b4947ba30bb51153226",
          "sha256": "b096de458647749e15c5b33bd28099bdc97bf04a385185341d9e3652a23e63e0",
          "sha1": "9130d5a2e5671516f3b267b6faf3e9d16cb51b2a",
          "md5": "046ec20a195094d06ec7b6dadf99e0c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.23.0.jar",
          "url": "runelite-api-4.23.0.jar",
          "size": 1347517,
          "sha512": "a548d8dbe90f2917da01c8973fb579fdf8add0f54dd27565ee3fc007d09b5687a6f36dd6760784daae44e8013c9fb2b19fc8d16363789b4947ba30bb51153226",
          "sha256": "b096de458647749e15c5b33bd28099bdc97bf04a385185341d9e3652a23e63e0",
          "sha1": "9130d5a2e5671516f3b267b6faf3e9d16cb51b2a",
          "md5": "046ec20a195094d06ec7b6dadf99e0c6"
        }
      ]
    }
  ]
}
