{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.8.jar",
          "url": "runescape-api-4.9.8.jar",
          "size": 109472,
          "sha512": "0eff0d8c80887a0af1c4a772f914b2625ae892341679c4cc025454fe6423a091cb2c5bbcd70c2e32dda9390d495d1eb50662c7a950d66686a682db5bee222b39",
          "sha256": "33f2c514538f4205574c3571b30e50603e700f4956423ef42e85b5247703df03",
          "sha1": "bba173cb9e425463915baebf20ab446fca5818d7",
          "md5": "8ac1f99e5881d1ffe7240949d125bc14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.8"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.8.jar",
          "url": "runescape-api-4.9.8.jar",
          "size": 109472,
          "sha512": "0eff0d8c80887a0af1c4a772f914b2625ae892341679c4cc025454fe6423a091cb2c5bbcd70c2e32dda9390d495d1eb50662c7a950d66686a682db5bee222b39",
          "sha256": "33f2c514538f4205574c3571b30e50603e700f4956423ef42e85b5247703df03",
          "sha1": "bba173cb9e425463915baebf20ab446fca5818d7",
          "md5": "8ac1f99e5881d1ffe7240949d125bc14"
        }
      ]
    }
  ]
}
