{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.13.3.jar",
          "url": "runelite-jshell-4.13.3.jar",
          "size": 26552,
          "sha512": "e1d35f8d772a7e1340b781d22249e1b15a787a5ac6c7d5be4ad115176e39138135c2eb17d447a67a9f712fb7054c7953a7c40ad6729ecb9fc0fd1b4499376162",
          "sha256": "5f92fa4bfeaf508b4d22e13107566ea1fb8618e578166b7b39ed0116fa9b0579",
          "sha1": "7cf8487bc2122b8e905504652c09a33738220094",
          "md5": "765e317997f43f8b51d359528882388d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.13.3.jar",
          "url": "runelite-jshell-4.13.3.jar",
          "size": 26552,
          "sha512": "e1d35f8d772a7e1340b781d22249e1b15a787a5ac6c7d5be4ad115176e39138135c2eb17d447a67a9f712fb7054c7953a7c40ad6729ecb9fc0fd1b4499376162",
          "sha256": "5f92fa4bfeaf508b4d22e13107566ea1fb8618e578166b7b39ed0116fa9b0579",
          "sha1": "7cf8487bc2122b8e905504652c09a33738220094",
          "md5": "765e317997f43f8b51d359528882388d"
        }
      ]
    }
  ]
}
