{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.13.3.jar",
          "url": "runelite-jshell-4.13.3.jar",
          "size": 26552,
          "sha512": "eb07016e09fb3f802ca3216dd817792ce65fe2188d9a6cf8d597297b1162bbf8c6029adc70c87ddc5d2f40bb6276b54fbc4d59053279c5152c3530815c6a6ca6",
          "sha256": "8339be9b99006f4f4cba94ad1e6a6f53ff8b98ffd6476dac6ce1b792c42ef6e2",
          "sha1": "1753acdfddcdd5a449e8397380d8226401c1d171",
          "md5": "a6fb3fc4c570264928b658e3a61b347d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.13.3.jar",
          "url": "runelite-jshell-4.13.3.jar",
          "size": 26552,
          "sha512": "eb07016e09fb3f802ca3216dd817792ce65fe2188d9a6cf8d597297b1162bbf8c6029adc70c87ddc5d2f40bb6276b54fbc4d59053279c5152c3530815c6a6ca6",
          "sha256": "8339be9b99006f4f4cba94ad1e6a6f53ff8b98ffd6476dac6ce1b792c42ef6e2",
          "sha1": "1753acdfddcdd5a449e8397380d8226401c1d171",
          "md5": "a6fb3fc4c570264928b658e3a61b347d"
        }
      ]
    }
  ]
}
