{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.5.jar",
          "url": "runelite-api-4.20.5.jar",
          "size": 1347756,
          "sha512": "cd8c484a47afb8415d1f3c3e8d0a30c18645c0c139a4b4f96db74d36059fa67b94f9b29ea3df79e702ac926dbbfb328e9d7066a963eada51430a233ac2e2909d",
          "sha256": "b16df0985eddd6884c9ef9caa5684de94e7e00aa7c086403816c3d9906454fd2",
          "sha1": "a34cb918c141949dbbee62c9dbeca7b020b1610e",
          "md5": "303da5433f3d3e7e5d012c489b68e4a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.5.jar",
          "url": "runelite-api-4.20.5.jar",
          "size": 1347756,
          "sha512": "cd8c484a47afb8415d1f3c3e8d0a30c18645c0c139a4b4f96db74d36059fa67b94f9b29ea3df79e702ac926dbbfb328e9d7066a963eada51430a233ac2e2909d",
          "sha256": "b16df0985eddd6884c9ef9caa5684de94e7e00aa7c086403816c3d9906454fd2",
          "sha1": "a34cb918c141949dbbee62c9dbeca7b020b1610e",
          "md5": "303da5433f3d3e7e5d012c489b68e4a3"
        }
      ]
    }
  ]
}
