{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.5.jar",
          "url": "runelite-api-4.20.5.jar",
          "size": 1347756,
          "sha512": "53d8eb6602ccf4b3f195ab58f8e84cefd27c5af7f3f4f499ff61516a5ede426b376ddaa0d4d5d7f87fc3546171e0296abe9a86c9c9dbcfdfa0cd1338f1149524",
          "sha256": "0fc19135825505692a61e49b3b13a4a91f08a3ceca6a353f7911a8c7d7fa2648",
          "sha1": "883cebd13256f0e88da35075217e98756684ffa6",
          "md5": "cd3df5f21a589d41b14cb46f72a3d507"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.5.jar",
          "url": "runelite-api-4.20.5.jar",
          "size": 1347756,
          "sha512": "53d8eb6602ccf4b3f195ab58f8e84cefd27c5af7f3f4f499ff61516a5ede426b376ddaa0d4d5d7f87fc3546171e0296abe9a86c9c9dbcfdfa0cd1338f1149524",
          "sha256": "0fc19135825505692a61e49b3b13a4a91f08a3ceca6a353f7911a8c7d7fa2648",
          "sha1": "883cebd13256f0e88da35075217e98756684ffa6",
          "md5": "cd3df5f21a589d41b14cb46f72a3d507"
        }
      ]
    }
  ]
}
