{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.5.jar",
          "url": "runelite-api-4.20.5.jar",
          "size": 1347756,
          "sha512": "478fc85d2704ce2f52f241da9f68052a1a1046fc47826d7c51b1bb2ad6ca6fd9a53ad830e9ca3de1116f56582563a4420bfbb879b69a6f962b399297667902b0",
          "sha256": "bdfdc0feea162347939d5d40485a2e6de985bd70c0653ae580876153fd7e17e5",
          "sha1": "d8e79e30e31670cef646ba83fa08f65b20b5c9b7",
          "md5": "7cb52cd74bc107ba6bc827c7745ed1ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.5.jar",
          "url": "runelite-api-4.20.5.jar",
          "size": 1347756,
          "sha512": "478fc85d2704ce2f52f241da9f68052a1a1046fc47826d7c51b1bb2ad6ca6fd9a53ad830e9ca3de1116f56582563a4420bfbb879b69a6f962b399297667902b0",
          "sha256": "bdfdc0feea162347939d5d40485a2e6de985bd70c0653ae580876153fd7e17e5",
          "sha1": "d8e79e30e31670cef646ba83fa08f65b20b5c9b7",
          "md5": "7cb52cd74bc107ba6bc827c7745ed1ab"
        }
      ]
    }
  ]
}
