{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6x6rdqdr2feqdhliowtuawqwqe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.3.0.jar",
          "url": "http-api-4.3.0.jar",
          "size": 159710,
          "sha512": "07547c0516b5a236e739809b9690ae794e6db87a84ada6a556e027c6b14f18c40f3054e0398625a99f8c06675e40234d51647e703e79074f5c57d3693b638041",
          "sha256": "239655df65d435d01be09bed72aaab0a1d1e46874e8f780f888b89ac6ca90c45",
          "sha1": "99c729929e165873667a89692c90a04eeab8ae1c",
          "md5": "76a16b863ea985e8b561e1d4f9ec654b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.3.0.jar",
          "url": "http-api-4.3.0.jar",
          "size": 159710,
          "sha512": "07547c0516b5a236e739809b9690ae794e6db87a84ada6a556e027c6b14f18c40f3054e0398625a99f8c06675e40234d51647e703e79074f5c57d3693b638041",
          "sha256": "239655df65d435d01be09bed72aaab0a1d1e46874e8f780f888b89ac6ca90c45",
          "sha1": "99c729929e165873667a89692c90a04eeab8ae1c",
          "md5": "76a16b863ea985e8b561e1d4f9ec654b"
        }
      ]
    }
  ]
}
