{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.1.jar",
          "url": "http-api-4.15.1.jar",
          "size": 172794,
          "sha512": "710969aa2fbde28521b90f242d80b04268a4bcfc820b5e7584d2e406ef4fdc9f8201dc20869acff3e317f01e346ccd56779c6fe2cddaa3f75964fe0b6807114d",
          "sha256": "654763b22e377fa480e56c723d862a9b6759a3a5b5f1d02696ee373645fba3e2",
          "sha1": "fdbf0a23db0a04eef696f21ae724aa8abe5672ca",
          "md5": "1c2acecd76bd20565fa01de68232204a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.1.jar",
          "url": "http-api-4.15.1.jar",
          "size": 172794,
          "sha512": "710969aa2fbde28521b90f242d80b04268a4bcfc820b5e7584d2e406ef4fdc9f8201dc20869acff3e317f01e346ccd56779c6fe2cddaa3f75964fe0b6807114d",
          "sha256": "654763b22e377fa480e56c723d862a9b6759a3a5b5f1d02696ee373645fba3e2",
          "sha1": "fdbf0a23db0a04eef696f21ae724aa8abe5672ca",
          "md5": "1c2acecd76bd20565fa01de68232204a"
        }
      ]
    }
  ]
}
