{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.1.jar",
          "url": "http-api-4.15.1.jar",
          "size": 172794,
          "sha512": "c6e5fd7c78019038d260cf951c3db2e14ce17b8d18ade8913770a34f0359681c35765f1adf3a0671c02b5f83daced45e17953fc95bd17fdd9575041c95741084",
          "sha256": "533144ca7440b0b2c886a4240a3827408dde7c440b3dddfc180932917630b8e5",
          "sha1": "3e041a56634b9b5fe1f78264b9657892d0b165de",
          "md5": "de11ee5ffeac7a8e45ee4bb4da076a7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.1.jar",
          "url": "http-api-4.15.1.jar",
          "size": 172794,
          "sha512": "c6e5fd7c78019038d260cf951c3db2e14ce17b8d18ade8913770a34f0359681c35765f1adf3a0671c02b5f83daced45e17953fc95bd17fdd9575041c95741084",
          "sha256": "533144ca7440b0b2c886a4240a3827408dde7c440b3dddfc180932917630b8e5",
          "sha1": "3e041a56634b9b5fe1f78264b9657892d0b165de",
          "md5": "de11ee5ffeac7a8e45ee4bb4da076a7b"
        }
      ]
    }
  ]
}
