{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rktcpl45hnbmpe4o3j6ndsbf5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159127,
          "sha512": "45681174a5ecc73a706802162e160e615e9b3c61e6a1cbe649d5973a5831737cdc20dac4bdc28b6b14401c2e3917a75062fab4e6e1cab39a8d300c593b3bc5c2",
          "sha256": "28e04d5bc7a60c7418b8c96d90c61b7bcbe750d42e3e3305f5ae3bb781a8ea46",
          "sha1": "cd9d410f6bdae7a582c0b3725a9cd2c5fdc5a8f1",
          "md5": "eb56b6152fc414b4613b8b00402b1377"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159127,
          "sha512": "45681174a5ecc73a706802162e160e615e9b3c61e6a1cbe649d5973a5831737cdc20dac4bdc28b6b14401c2e3917a75062fab4e6e1cab39a8d300c593b3bc5c2",
          "sha256": "28e04d5bc7a60c7418b8c96d90c61b7bcbe750d42e3e3305f5ae3bb781a8ea46",
          "sha1": "cd9d410f6bdae7a582c0b3725a9cd2c5fdc5a8f1",
          "md5": "eb56b6152fc414b4613b8b00402b1377"
        }
      ]
    }
  ]
}
