{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2lfibgsgnfggncblcbpuuj2vie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159127,
          "sha512": "ed6510451de6098b3b39aabe9d8babd7f0532ddc275708a9702b7f37c980f4a1d8cabfd2042ac6020a30a26e3afe4c12a863677dcba27bd4c0686bf4ef725944",
          "sha256": "388bae376cade8fdb556833479799fcfd66e86a4a168c428f685c74bc0b2a242",
          "sha1": "3372f757f0b6b488ca80b86898dd7bfda65f370e",
          "md5": "4e47cb701a5066b8e7c733f2f1d6af78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.0.0.jar",
          "url": "http-api-4.0.0.jar",
          "size": 159127,
          "sha512": "ed6510451de6098b3b39aabe9d8babd7f0532ddc275708a9702b7f37c980f4a1d8cabfd2042ac6020a30a26e3afe4c12a863677dcba27bd4c0686bf4ef725944",
          "sha256": "388bae376cade8fdb556833479799fcfd66e86a4a168c428f685c74bc0b2a242",
          "sha1": "3372f757f0b6b488ca80b86898dd7bfda65f370e",
          "md5": "4e47cb701a5066b8e7c733f2f1d6af78"
        }
      ]
    }
  ]
}
