{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dv5bgqpcubbhthfmk422afayva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.4.0.jar",
          "url": "runelite-api-4.4.0.jar",
          "size": 1255603,
          "sha512": "c8704423a7db1ac996c766fe24b0a4e1173cbc039d6585f5ab88008fc284d2981bcaa459a08846c76c2c9460de9f9ae57570edfbabe18009ca616c6c70da130c",
          "sha256": "cc50ec6642fd50555f462ace5bd56711cf7fd545e47d017a2d3fde967a3479ad",
          "sha1": "9aacc156e298527ea0ddc7b67b7795f7a2034462",
          "md5": "43ccd4974481b5677ba1f471ef251f29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.4.0.jar",
          "url": "runelite-api-4.4.0.jar",
          "size": 1255603,
          "sha512": "c8704423a7db1ac996c766fe24b0a4e1173cbc039d6585f5ab88008fc284d2981bcaa459a08846c76c2c9460de9f9ae57570edfbabe18009ca616c6c70da130c",
          "sha256": "cc50ec6642fd50555f462ace5bd56711cf7fd545e47d017a2d3fde967a3479ad",
          "sha1": "9aacc156e298527ea0ddc7b67b7795f7a2034462",
          "md5": "43ccd4974481b5677ba1f471ef251f29"
        }
      ]
    }
  ]
}
