{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "n34drkg3ynf23inmqqc3nx447e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160388,
          "sha512": "7bbd2dce4d3a0c2354c8e3be8da4bf957a0fdb647ded2b3af539e4c90c149c8da5f4606e1eaccd6ce2a424690122c49c0a9dd41d00cb50b8719c41a8a2e516d7",
          "sha256": "b1a82efe44a341268e53bd3cf5a52e47409ab57d5a9877cc35b7620a5d8b2e20",
          "sha1": "4b27ad753c7fce0d828b12cd5df28854a5a7cde6",
          "md5": "6630d0441e7a906f4455a2441d581805"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160388,
          "sha512": "7bbd2dce4d3a0c2354c8e3be8da4bf957a0fdb647ded2b3af539e4c90c149c8da5f4606e1eaccd6ce2a424690122c49c0a9dd41d00cb50b8719c41a8a2e516d7",
          "sha256": "b1a82efe44a341268e53bd3cf5a52e47409ab57d5a9877cc35b7620a5d8b2e20",
          "sha1": "4b27ad753c7fce0d828b12cd5df28854a5a7cde6",
          "md5": "6630d0441e7a906f4455a2441d581805"
        }
      ]
    }
  ]
}
