{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "jwumkx2yajcspe3s2djnmp5tuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160388,
          "sha512": "55cfe73a4fd60d01cebee4723406367eebe11f05aa5db21f1051ab6b57a780413960947be330401a39cf8fa7cbc1b0305f54a62a6ba6646cc4cbd28838ed552c",
          "sha256": "8d8f068239fab6e666f841791e79b57b1a841eb997c61a981fb5d6978dab7223",
          "sha1": "2be3edc247686f896eb0a526508d0943c8aaa32e",
          "md5": "14074e21493dadd17108b1bb924ea293"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160388,
          "sha512": "55cfe73a4fd60d01cebee4723406367eebe11f05aa5db21f1051ab6b57a780413960947be330401a39cf8fa7cbc1b0305f54a62a6ba6646cc4cbd28838ed552c",
          "sha256": "8d8f068239fab6e666f841791e79b57b1a841eb997c61a981fb5d6978dab7223",
          "sha1": "2be3edc247686f896eb0a526508d0943c8aaa32e",
          "md5": "14074e21493dadd17108b1bb924ea293"
        }
      ]
    }
  ]
}
