{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "lx5k4na37fhkzdqw3bv72mpj7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160353,
          "sha512": "2047695a6a888b25efcbd274bde05158fd6d11ff167582614a2ee765a9bd947b7312e1d820ab34741c0deb1a86c0c9ae7919cd4e7bccdbbc95d0200ccddf5b1e",
          "sha256": "915b914ea923c586fbd524b648751ad49e39f7ed7e76e5f6838ce65dafe1bd0c",
          "sha1": "6d5ed691650063137d23c26376304c92dbb44459",
          "md5": "76698728eb43f17fd95200d8b84d678d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160353,
          "sha512": "2047695a6a888b25efcbd274bde05158fd6d11ff167582614a2ee765a9bd947b7312e1d820ab34741c0deb1a86c0c9ae7919cd4e7bccdbbc95d0200ccddf5b1e",
          "sha256": "915b914ea923c586fbd524b648751ad49e39f7ed7e76e5f6838ce65dafe1bd0c",
          "sha1": "6d5ed691650063137d23c26376304c92dbb44459",
          "md5": "76698728eb43f17fd95200d8b84d678d"
        }
      ]
    }
  ]
}
