{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.5.6.jar",
          "url": "runelite-jshell-4.5.6.jar",
          "size": 22730,
          "sha512": "f4f1bd1eac4b4180fe27f6b9467c9756f122d3f6d2d01b0a3fe610bd449038c9b5b845c45534121aa2433d3cef5d273e119955085bcb830f9cc7841afe2d85ea",
          "sha256": "de2c07a068a5fc67bf8fcebd2afd42eb11d9c71790f5d17e6719cb8d9818bb17",
          "sha1": "7d0b0431cb9264a0da4c1cfcc90eb389a90fa090",
          "md5": "17e79f391783c18ca252205b8d178915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.5.6.jar",
          "url": "runelite-jshell-4.5.6.jar",
          "size": 22730,
          "sha512": "f4f1bd1eac4b4180fe27f6b9467c9756f122d3f6d2d01b0a3fe610bd449038c9b5b845c45534121aa2433d3cef5d273e119955085bcb830f9cc7841afe2d85ea",
          "sha256": "de2c07a068a5fc67bf8fcebd2afd42eb11d9c71790f5d17e6719cb8d9818bb17",
          "sha1": "7d0b0431cb9264a0da4c1cfcc90eb389a90fa090",
          "md5": "17e79f391783c18ca252205b8d178915"
        }
      ]
    }
  ]
}
