{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.0.jar",
          "url": "http-api-4.18.0.jar",
          "size": 99211,
          "sha512": "8b4e16ed44b3304af1efcb7a10bb8d202f72eb0e0aceb3bf8f39018eb7f17adb36ad0a8468eae99a773096d3aa169c723b0593dc5e24a720e111436d41324da2",
          "sha256": "5921949f1f7532d7de3640348767de5411a6e0f7ba929775322dc63c88979fb6",
          "sha1": "02e66da28a449f7d9d1a2366d3b92b422f8efce6",
          "md5": "239b5e10c24943b8d9d7bb1553944693"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.0.jar",
          "url": "http-api-4.18.0.jar",
          "size": 99211,
          "sha512": "8b4e16ed44b3304af1efcb7a10bb8d202f72eb0e0aceb3bf8f39018eb7f17adb36ad0a8468eae99a773096d3aa169c723b0593dc5e24a720e111436d41324da2",
          "sha256": "5921949f1f7532d7de3640348767de5411a6e0f7ba929775322dc63c88979fb6",
          "sha1": "02e66da28a449f7d9d1a2366d3b92b422f8efce6",
          "md5": "239b5e10c24943b8d9d7bb1553944693"
        }
      ]
    }
  ]
}
