{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.0.jar",
          "url": "http-api-4.18.0.jar",
          "size": 99211,
          "sha512": "3b54559013bdfe2c0e7be09bdcae32eff46bd72f1626347f53d6d02b1534679dc292a16d81b6bc17882a2b7007ba2b48ea214fb291c1db404383b929e1a8ffe5",
          "sha256": "b3535926f4b67e77a3464fdb30362b7c9d0ff969ea53ef9b2e6496632fabe810",
          "sha1": "dc3d0f2f43dc754d97d8334e262570842aa3605f",
          "md5": "1713f950d17db07e8dabeb2a37b0134e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.0.jar",
          "url": "http-api-4.18.0.jar",
          "size": 99211,
          "sha512": "3b54559013bdfe2c0e7be09bdcae32eff46bd72f1626347f53d6d02b1534679dc292a16d81b6bc17882a2b7007ba2b48ea214fb291c1db404383b929e1a8ffe5",
          "sha256": "b3535926f4b67e77a3464fdb30362b7c9d0ff969ea53ef9b2e6496632fabe810",
          "sha1": "dc3d0f2f43dc754d97d8334e262570842aa3605f",
          "md5": "1713f950d17db07e8dabeb2a37b0134e"
        }
      ]
    }
  ]
}
