{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99208,
          "sha512": "402a5c35caedc09048a2e26475d512b98904a2068dd39a2d9f99eb2d639449b18a46c2afea9f28be96390cdada4cf9017f4b81ffc15f97aaa783ed5b9741188a",
          "sha256": "5b8470a9e182eef665eb0d01d6e2b7a24936ce916c27fc204e015fe1a92d0d63",
          "sha1": "f0617d2bc2ca31c2b32154c110c8b3b298250438",
          "md5": "00db0096814efba6c8adf3d02c3de129"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99208,
          "sha512": "402a5c35caedc09048a2e26475d512b98904a2068dd39a2d9f99eb2d639449b18a46c2afea9f28be96390cdada4cf9017f4b81ffc15f97aaa783ed5b9741188a",
          "sha256": "5b8470a9e182eef665eb0d01d6e2b7a24936ce916c27fc204e015fe1a92d0d63",
          "sha1": "f0617d2bc2ca31c2b32154c110c8b3b298250438",
          "md5": "00db0096814efba6c8adf3d02c3de129"
        }
      ]
    }
  ]
}
