{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99208,
          "sha512": "b11cb34a660f4f61027a9505c606d5c4ba2474eefea85dfbda7407bd911829e45ac856479db67d2bc5148249325f0fa227baad50e1cc61be690c48015c2bada2",
          "sha256": "91082dfdc067356404176fd37e733f8ab1aed26724c3adf7d8e1212a3ec56453",
          "sha1": "b537d849ed68f01a2a9ab8498362658bbf4cb4d2",
          "md5": "f2acbb5d338d7d79d2cda2169ffd1c23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99208,
          "sha512": "b11cb34a660f4f61027a9505c606d5c4ba2474eefea85dfbda7407bd911829e45ac856479db67d2bc5148249325f0fa227baad50e1cc61be690c48015c2bada2",
          "sha256": "91082dfdc067356404176fd37e733f8ab1aed26724c3adf7d8e1212a3ec56453",
          "sha1": "b537d849ed68f01a2a9ab8498362658bbf4cb4d2",
          "md5": "f2acbb5d338d7d79d2cda2169ffd1c23"
        }
      ]
    }
  ]
}
