{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99204,
          "sha512": "9d97d3e5f00689bbebc391813957f085d545b1b2ce05e859b55620b751be2574629f06d6b189aa4708494c4200eeaf58f9194124e8bbf0bcd80bb57cd9b85d88",
          "sha256": "37b3db525fcd9d828e055e6983a8a25739efaa8682fe08d8c88ad040f2f1a48a",
          "sha1": "cc03364830db168b3fb70f30bc12b007ce187b76",
          "md5": "37858cdd327bf7d5d2aeccf8f4b7d6fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2.jar",
          "url": "http-api-4.25.2.jar",
          "size": 99204,
          "sha512": "9d97d3e5f00689bbebc391813957f085d545b1b2ce05e859b55620b751be2574629f06d6b189aa4708494c4200eeaf58f9194124e8bbf0bcd80bb57cd9b85d88",
          "sha256": "37b3db525fcd9d828e055e6983a8a25739efaa8682fe08d8c88ad040f2f1a48a",
          "sha1": "cc03364830db168b3fb70f30bc12b007ce187b76",
          "md5": "37858cdd327bf7d5d2aeccf8f4b7d6fd"
        }
      ]
    }
  ]
}
