{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99205,
          "sha512": "4d484133688d85287051ce93705aa386f461c92048e4a5748514c73f45be2879751ebf76e05cc7f1aa9c6da3a6f283f138228cf3def4c609416908368f0b0e1d",
          "sha256": "df0d6e21c33c1e25133af637d091bc4a355609bb7898b9bf0938ad8ba5df8bb4",
          "sha1": "e588ff6329e8955e393a8aa378f8ddc9a9147ab3",
          "md5": "00d1fe5e3d0d273cb54beef1e0ecab41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99205,
          "sha512": "4d484133688d85287051ce93705aa386f461c92048e4a5748514c73f45be2879751ebf76e05cc7f1aa9c6da3a6f283f138228cf3def4c609416908368f0b0e1d",
          "sha256": "df0d6e21c33c1e25133af637d091bc4a355609bb7898b9bf0938ad8ba5df8bb4",
          "sha1": "e588ff6329e8955e393a8aa378f8ddc9a9147ab3",
          "md5": "00d1fe5e3d0d273cb54beef1e0ecab41"
        }
      ]
    }
  ]
}
