{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99206,
          "sha512": "d6ad6ea72c26a1b5c13c87346bfa776c3863aa4d27e68429292bfeb34fdda4910e400e43c444d5aa5606b8620abcebbdbf075380623a063ea4cc143992afa218",
          "sha256": "88ea2a420991d712cb9cbc3a1fdaf35b9abdf4b48133a619659363207f243aaf",
          "sha1": "ee89f167441b08ac6f5efc1ae17282f43b34acfd",
          "md5": "b81de7a67aa5ed5da075cbb2e24fec01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99206,
          "sha512": "d6ad6ea72c26a1b5c13c87346bfa776c3863aa4d27e68429292bfeb34fdda4910e400e43c444d5aa5606b8620abcebbdbf075380623a063ea4cc143992afa218",
          "sha256": "88ea2a420991d712cb9cbc3a1fdaf35b9abdf4b48133a619659363207f243aaf",
          "sha1": "ee89f167441b08ac6f5efc1ae17282f43b34acfd",
          "md5": "b81de7a67aa5ed5da075cbb2e24fec01"
        }
      ]
    }
  ]
}
