{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99205,
          "sha512": "246a43fdd97b5f569fa3290f95928dd8e426216b0fbe1b78bd08004fea542c53e4f320cff0eeb433b7a5dc4ee980d59a86a56c056cbf8e729862aec10716d828",
          "sha256": "333bf98302c597a3ae4c99be502222069b777349e091db994ecaa1a4556aa045",
          "sha1": "0a79428a93641f0f0879a6a036a696a70e0158d9",
          "md5": "2f6fb4b30f7c35d21debac862801a167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99205,
          "sha512": "246a43fdd97b5f569fa3290f95928dd8e426216b0fbe1b78bd08004fea542c53e4f320cff0eeb433b7a5dc4ee980d59a86a56c056cbf8e729862aec10716d828",
          "sha256": "333bf98302c597a3ae4c99be502222069b777349e091db994ecaa1a4556aa045",
          "sha1": "0a79428a93641f0f0879a6a036a696a70e0158d9",
          "md5": "2f6fb4b30f7c35d21debac862801a167"
        }
      ]
    }
  ]
}
