{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346200,
          "sha512": "6d6a13d0972d5e1a2e25b35e0ea97e746c87ff17c4aac534bad5a631930b550f7b6dc9923d0c842e19ba2d3888fee9e3855306fd0aca3208a0124fc027faf09b",
          "sha256": "471d206e916f9e1f3040f332fd2060bfffe9086da92df354dd39905e5bdc9ee1",
          "sha1": "c09318a78c8e6aefae85d1aaa4c09da3082da373",
          "md5": "cf21979a2a0a98cc7b41cbaee16df0cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346200,
          "sha512": "6d6a13d0972d5e1a2e25b35e0ea97e746c87ff17c4aac534bad5a631930b550f7b6dc9923d0c842e19ba2d3888fee9e3855306fd0aca3208a0124fc027faf09b",
          "sha256": "471d206e916f9e1f3040f332fd2060bfffe9086da92df354dd39905e5bdc9ee1",
          "sha1": "c09318a78c8e6aefae85d1aaa4c09da3082da373",
          "md5": "cf21979a2a0a98cc7b41cbaee16df0cd"
        }
      ]
    }
  ]
}
