{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346200,
          "sha512": "466659e1ce3933f5635515d126fee12b6d03d339d93c405624b82173849eebfebc383b447937bb89f3ae94786c47ca2240667fb9a54cf50e61e5a126616da812",
          "sha256": "3a4dd26f20e88f00b82fb72308e8ab45d4795233619011c0b4362b1016eb6940",
          "sha1": "7a99c99a72d5eec22727791daa7cb36ed18d6d03",
          "md5": "31b154b523d2e19697dddca83947322f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346200,
          "sha512": "466659e1ce3933f5635515d126fee12b6d03d339d93c405624b82173849eebfebc383b447937bb89f3ae94786c47ca2240667fb9a54cf50e61e5a126616da812",
          "sha256": "3a4dd26f20e88f00b82fb72308e8ab45d4795233619011c0b4362b1016eb6940",
          "sha1": "7a99c99a72d5eec22727791daa7cb36ed18d6d03",
          "md5": "31b154b523d2e19697dddca83947322f"
        }
      ]
    }
  ]
}
