{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346200,
          "sha512": "a541d366fb58b80a7449738155d6a750e1ebe2932214b6e2659ee93b6909bafb4f5c9cdf55235c8bf5cc5482717327067a0c41e99bc5b61e7e559d2c814f072d",
          "sha256": "f292265ccc15c050785efae05acce219ead7faaf109e57a2954f40aacb5b0e0a",
          "sha1": "a17596c89ad64a2b756a4035ed519410541500b9",
          "md5": "acaea1125b97fa3b74228323d1585e01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346200,
          "sha512": "a541d366fb58b80a7449738155d6a750e1ebe2932214b6e2659ee93b6909bafb4f5c9cdf55235c8bf5cc5482717327067a0c41e99bc5b61e7e559d2c814f072d",
          "sha256": "f292265ccc15c050785efae05acce219ead7faaf109e57a2954f40aacb5b0e0a",
          "sha1": "a17596c89ad64a2b756a4035ed519410541500b9",
          "md5": "acaea1125b97fa3b74228323d1585e01"
        }
      ]
    }
  ]
}
