{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.29.0.jar",
          "url": "runelite-jshell-4.29.0.jar",
          "size": 26557,
          "sha512": "3df152c01644ee0d91773bf8fb35ec1fab81112689e481dda22b1227618c223d87b85bad2ccf0adce647d9083f3f1afda0d9def7969cb0e6bdf41219c12b8712",
          "sha256": "edecc51be2e70355293072d92536239ef18d8a99ce82ea3e75e49e12d4e931ca",
          "sha1": "3ac7d6e578b48eed1d1a6646678975692e71075f",
          "md5": "abc544b2442d519f5e40ab21e3043175"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.29.0.jar",
          "url": "runelite-jshell-4.29.0.jar",
          "size": 26557,
          "sha512": "3df152c01644ee0d91773bf8fb35ec1fab81112689e481dda22b1227618c223d87b85bad2ccf0adce647d9083f3f1afda0d9def7969cb0e6bdf41219c12b8712",
          "sha256": "edecc51be2e70355293072d92536239ef18d8a99ce82ea3e75e49e12d4e931ca",
          "sha1": "3ac7d6e578b48eed1d1a6646678975692e71075f",
          "md5": "abc544b2442d519f5e40ab21e3043175"
        }
      ]
    }
  ]
}
