{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.6"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.15.6.jar",
          "url": "runelite-client-4.15.6.jar",
          "size": 9516872,
          "sha512": "1054bdc7578b143d68c7cb85616b3dd4ad6560590af97aa130bc581efbf8369a8767528875e5823436b89ea757f8bb572a4dbebe8918d808d1b3da5c5a6e5739",
          "sha256": "03c9fc6f61f19261aa4390ef2d274b0dbcfd2ccf8b4abfb1e36e33a05249e7fa",
          "sha1": "2557b593c8c472770dfa51442eea9429e9b717d4",
          "md5": "a828a21e38f50fd5bfa6e432d728172d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "4.15.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-jshell",
          "version": {
            "requires": "4.15.6"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "5.1.9.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "substance",
          "version": {
            "requires": "8.0.02"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.madlonkay",
          "module": "desktopsupport",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.6"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "4.15.6"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "trident",
          "version": {
            "requires": "1.5.00"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt-natives-macosx",
          "version": {
            "requires": "2.4.0-rc-20210117"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all-natives-macosx",
          "version": {
            "requires": "2.4.0-rc-20210117"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-x64"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-arm64"
            }
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.15.6.jar",
          "url": "runelite-client-4.15.6.jar",
          "size": 9516872,
          "sha512": "1054bdc7578b143d68c7cb85616b3dd4ad6560590af97aa130bc581efbf8369a8767528875e5823436b89ea757f8bb572a4dbebe8918d808d1b3da5c5a6e5739",
          "sha256": "03c9fc6f61f19261aa4390ef2d274b0dbcfd2ccf8b4abfb1e36e33a05249e7fa",
          "sha1": "2557b593c8c472770dfa51442eea9429e9b717d4",
          "md5": "a828a21e38f50fd5bfa6e432d728172d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-4.15.6-shaded.jar",
          "url": "runelite-client-4.15.6-shaded.jar",
          "size": 41547574,
          "sha512": "8052f2289e9aa0914a5a75924fbf1f7f9d971eacee12719af77b9bd19a985fe7103a78072f12e2f004a62542f4f9dac5db1ecaed4fca2cdde570d95e04a74da9",
          "sha256": "694c75fb43e61fc320b1576476304172bc5612b20190601ba9471e8208dec19e",
          "sha1": "5747c44db9ff9cb9fe682fa041fc4d6a59f091b8",
          "md5": "16b014b9fd718cecbf1adef1d10f810b"
        }
      ]
    }
  ]
}
