{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.23.0.jar",
          "url": "runelite-jshell-4.23.0.jar",
          "size": 26557,
          "sha512": "b441081cc4b417cfc17183e88b9f496fd9354c0ab3953f79817576f5c33c0707c884a3b496a78a27a74079e3eab9eb6cfbda040655b74a29632377502eb88032",
          "sha256": "56446560ab620d5757cb8fd4ade8bfa0fbfe0dc4c9ee773162295f88f7b76d58",
          "sha1": "bc327aadf7502bcc3e2423d7626d68e97c2cc45f",
          "md5": "214dc41828a7939c2a06813e4568026b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.23.0.jar",
          "url": "runelite-jshell-4.23.0.jar",
          "size": 26557,
          "sha512": "b441081cc4b417cfc17183e88b9f496fd9354c0ab3953f79817576f5c33c0707c884a3b496a78a27a74079e3eab9eb6cfbda040655b74a29632377502eb88032",
          "sha256": "56446560ab620d5757cb8fd4ade8bfa0fbfe0dc4c9ee773162295f88f7b76d58",
          "sha1": "bc327aadf7502bcc3e2423d7626d68e97c2cc45f",
          "md5": "214dc41828a7939c2a06813e4568026b"
        }
      ]
    }
  ]
}
