{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.23.0.jar",
          "url": "runelite-jshell-4.23.0.jar",
          "size": 26557,
          "sha512": "0e26f2c22a8f4f11327cc3df20a57cb94dc994037ff0c860bc64e3799679465a7d878153065501500bc06e65541c032f284d1dba0bc04c3ecbf5bceb25b67701",
          "sha256": "754f47fe7f265a04ea802aafabd319e6d1a8d9e01231fa7d09fea28f4de46b4a",
          "sha1": "3f232487c93de3b28b65ec079b922ca9084ab417",
          "md5": "1b1689a83f0696b2022d29531a0975ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.23.0.jar",
          "url": "runelite-jshell-4.23.0.jar",
          "size": 26557,
          "sha512": "0e26f2c22a8f4f11327cc3df20a57cb94dc994037ff0c860bc64e3799679465a7d878153065501500bc06e65541c032f284d1dba0bc04c3ecbf5bceb25b67701",
          "sha256": "754f47fe7f265a04ea802aafabd319e6d1a8d9e01231fa7d09fea28f4de46b4a",
          "sha1": "3f232487c93de3b28b65ec079b922ca9084ab417",
          "md5": "1b1689a83f0696b2022d29531a0975ee"
        }
      ]
    }
  ]
}
