{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.23.0.jar",
          "url": "runelite-jshell-4.23.0.jar",
          "size": 26557,
          "sha512": "b6c424e3fc10c0e7fab3a86bbb585b355ec1547cefac66af50658e487f12cd80723c95eac1d3e2ffff2ee7e8513d91fbdc3548c1eb7030d619307c322d09b778",
          "sha256": "5610a5eae1429b39a0be283af13a999b2156bb7783181c884542a8ea4532de98",
          "sha1": "7d471ae7b03a042e3ecb4a6031aa759be0eb49aa",
          "md5": "00ced7853ac35b765c37cad924cbbae5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.23.0.jar",
          "url": "runelite-jshell-4.23.0.jar",
          "size": 26557,
          "sha512": "b6c424e3fc10c0e7fab3a86bbb585b355ec1547cefac66af50658e487f12cd80723c95eac1d3e2ffff2ee7e8513d91fbdc3548c1eb7030d619307c322d09b778",
          "sha256": "5610a5eae1429b39a0be283af13a999b2156bb7783181c884542a8ea4532de98",
          "sha1": "7d471ae7b03a042e3ecb4a6031aa759be0eb49aa",
          "md5": "00ced7853ac35b765c37cad924cbbae5"
        }
      ]
    }
  ]
}
