{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "869d33e9db42476c8bc00eee05d927828beabc303843a589a92130d4660c1b43c0bd1cd6df8c3b03585171587b76a5029783a48871660cf05d760d299655dfd8",
          "sha256": "0eb4a0c3db7fa6bf7396766f807efef4b3f62f8de24e46e2111e9e887f00381e",
          "sha1": "cbf52fbf1268c93e231b18435627ab6283bc3f1f",
          "md5": "cb80e414ebcfcae4576183b106bfc178"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "869d33e9db42476c8bc00eee05d927828beabc303843a589a92130d4660c1b43c0bd1cd6df8c3b03585171587b76a5029783a48871660cf05d760d299655dfd8",
          "sha256": "0eb4a0c3db7fa6bf7396766f807efef4b3f62f8de24e46e2111e9e887f00381e",
          "sha1": "cbf52fbf1268c93e231b18435627ab6283bc3f1f",
          "md5": "cb80e414ebcfcae4576183b106bfc178"
        }
      ]
    }
  ]
}
