{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "dff63c21e8baca5b947087c4faa61130574e6d6d6224f840d24b9ab2a8fd15f3e90bb9f461837a59e215e14eb3f0594d4a96c943db8d31c36a770408e9f656f0",
          "sha256": "91a1cdf7057106cf6189f2537db8c0865dc090f25d48cead2b135f4da0d454c7",
          "sha1": "71d14edda2560249ac6b1e6f25bd762e0574b054",
          "md5": "f772d5d5684d63ed8a873b02a7b6a0ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "dff63c21e8baca5b947087c4faa61130574e6d6d6224f840d24b9ab2a8fd15f3e90bb9f461837a59e215e14eb3f0594d4a96c943db8d31c36a770408e9f656f0",
          "sha256": "91a1cdf7057106cf6189f2537db8c0865dc090f25d48cead2b135f4da0d454c7",
          "sha1": "71d14edda2560249ac6b1e6f25bd762e0574b054",
          "md5": "f772d5d5684d63ed8a873b02a7b6a0ba"
        }
      ]
    }
  ]
}
