{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "1d3b6528dcba50e5a4ee1f16edf9c0af65ecb9b751617107bbdfc4fc7dbf6a2a3b7d4705c7d4482700e39b26c8e828a013317bcd6f0f0845083829f75b0543a8",
          "sha256": "62f9a8a935a01a25950dc289b593ea955e8ae2bd8edc5531c0f3f073681afe94",
          "sha1": "a31df1b61c9a36bc9e70bd726da2a28247bd1481",
          "md5": "4c9860e8d7835c5979602921cf926d1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "1d3b6528dcba50e5a4ee1f16edf9c0af65ecb9b751617107bbdfc4fc7dbf6a2a3b7d4705c7d4482700e39b26c8e828a013317bcd6f0f0845083829f75b0543a8",
          "sha256": "62f9a8a935a01a25950dc289b593ea955e8ae2bd8edc5531c0f3f073681afe94",
          "sha1": "a31df1b61c9a36bc9e70bd726da2a28247bd1481",
          "md5": "4c9860e8d7835c5979602921cf926d1e"
        }
      ]
    }
  ]
}
