{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.30.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.30.0.jar",
          "url": "runescape-api-4.30.0.jar",
          "size": 150296,
          "sha512": "3ee9d1a3d2e54913f1e3ab503ce672bfb1cbeab93561f85c551141c143275253ff849cf71642271acdcc29e391b0bac9769ec266f91982b29801dc441c06d8c8",
          "sha256": "d6d42ff0464b305967e593d1db73f3491836ca7aa62b48e4e35e7a9b3d3bba41",
          "sha1": "9b139952798bf484541c8570f6e18942de2deff9",
          "md5": "1dd0942e861591d0cbbdf0555d05c66b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.30.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.30.0.jar",
          "url": "runescape-api-4.30.0.jar",
          "size": 150296,
          "sha512": "3ee9d1a3d2e54913f1e3ab503ce672bfb1cbeab93561f85c551141c143275253ff849cf71642271acdcc29e391b0bac9769ec266f91982b29801dc441c06d8c8",
          "sha256": "d6d42ff0464b305967e593d1db73f3491836ca7aa62b48e4e35e7a9b3d3bba41",
          "sha1": "9b139952798bf484541c8570f6e18942de2deff9",
          "md5": "1dd0942e861591d0cbbdf0555d05c66b"
        }
      ]
    }
  ]
}
