{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "393923ca9d7844229b979cd95a9fe75b9b3c7942e17792a21fc7c642584f2213937fcbaa4b06888109529c70aeea3d9dcf7761324e02b649114be87c2dbe9a3d",
          "sha256": "7638f4b46d2f5552aa6f36eea73fe6134a820916ce4ce4c149f87ed656fd41ee",
          "sha1": "c1d4b6b07f7681078e7e9e05d80b9d3500f3bc67",
          "md5": "88514b271bd8af4f4d7846c019342093"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "393923ca9d7844229b979cd95a9fe75b9b3c7942e17792a21fc7c642584f2213937fcbaa4b06888109529c70aeea3d9dcf7761324e02b649114be87c2dbe9a3d",
          "sha256": "7638f4b46d2f5552aa6f36eea73fe6134a820916ce4ce4c149f87ed656fd41ee",
          "sha1": "c1d4b6b07f7681078e7e9e05d80b9d3500f3bc67",
          "md5": "88514b271bd8af4f4d7846c019342093"
        }
      ]
    }
  ]
}
