{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "1d316beb6b73b6d0fc893f1cbadaee2d9665edd9ab6b2be8ff27b7f4735d18d1fba3acdb97659f4edead7287290b6da520a307e9cb6387bea4202dd7a9781d26",
          "sha256": "55cfa38d5715fa1ca6be802284c2aae92fe0383f59135725835ee6f999561f5d",
          "sha1": "29c1452b591cb75657b3f8350d2957b2552c34bf",
          "md5": "a0b61ca60102854b678f6964a5ecae58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.19.0.jar",
          "url": "runelite-jshell-4.19.0.jar",
          "size": 26552,
          "sha512": "1d316beb6b73b6d0fc893f1cbadaee2d9665edd9ab6b2be8ff27b7f4735d18d1fba3acdb97659f4edead7287290b6da520a307e9cb6387bea4202dd7a9781d26",
          "sha256": "55cfa38d5715fa1ca6be802284c2aae92fe0383f59135725835ee6f999561f5d",
          "sha1": "29c1452b591cb75657b3f8350d2957b2552c34bf",
          "md5": "a0b61ca60102854b678f6964a5ecae58"
        }
      ]
    }
  ]
}
