{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.5.jar",
          "url": "runescape-api-4.20.5.jar",
          "size": 149203,
          "sha512": "e1ebecac095b73e19435edd96781e509fa350cc0c10938684134c6cfe8afa6c05757eb59224200a326013103d113696cc06905a8dc3b18bc2dc3f793629fffd2",
          "sha256": "67458926138867802c98a2bf0facd494ef85dcea841d518af53c841b13e5d80d",
          "sha1": "30f63241bbd373161a9fc7760f077edd7f26aee5",
          "md5": "d9d7add5c49805101e57640616abd77c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.5.jar",
          "url": "runescape-api-4.20.5.jar",
          "size": 149203,
          "sha512": "e1ebecac095b73e19435edd96781e509fa350cc0c10938684134c6cfe8afa6c05757eb59224200a326013103d113696cc06905a8dc3b18bc2dc3f793629fffd2",
          "sha256": "67458926138867802c98a2bf0facd494ef85dcea841d518af53c841b13e5d80d",
          "sha1": "30f63241bbd373161a9fc7760f077edd7f26aee5",
          "md5": "d9d7add5c49805101e57640616abd77c"
        }
      ]
    }
  ]
}
