{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.5.jar",
          "url": "runescape-api-4.20.5.jar",
          "size": 149203,
          "sha512": "2b698812b66e5974bc4987483bdd44fabbc39136bf2614ad3d5e45acac8cee00c4afee14085b6287efb08cba7a7bfe61aa6ad48b593576c4031b62bc8f3d8700",
          "sha256": "21985a9ae3adf0eabd44a01e4bfe3148ac5e5b5fab623277857ed672824c6db2",
          "sha1": "a1e40e4bdd6a5d39911f340b6d7b0877661070ba",
          "md5": "8c4f438eee0ca5173a8d1398874aeb6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.5"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.5.jar",
          "url": "runescape-api-4.20.5.jar",
          "size": 149203,
          "sha512": "2b698812b66e5974bc4987483bdd44fabbc39136bf2614ad3d5e45acac8cee00c4afee14085b6287efb08cba7a7bfe61aa6ad48b593576c4031b62bc8f3d8700",
          "sha256": "21985a9ae3adf0eabd44a01e4bfe3148ac5e5b5fab623277857ed672824c6db2",
          "sha1": "a1e40e4bdd6a5d39911f340b6d7b0877661070ba",
          "md5": "8c4f438eee0ca5173a8d1398874aeb6d"
        }
      ]
    }
  ]
}
