{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.7.jar",
          "url": "http-api-4.15.7.jar",
          "size": 172796,
          "sha512": "d30671f90441f6dced687274796537652cc8ac125763fb0c321596ae009fff9cd095ebf1cee1532359a860ad70cf2e222a55103fac3d23e86e18897389ef2074",
          "sha256": "d43fdad78a12242bd4f559a50af36a129b073d38c4c5dd4573dce5a2003e4d5e",
          "sha1": "789221ab4b53dba8d1a0c77427dbcead05990aec",
          "md5": "b3b8d106a7e9cb1a426976fb078565ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.7.jar",
          "url": "http-api-4.15.7.jar",
          "size": 172796,
          "sha512": "d30671f90441f6dced687274796537652cc8ac125763fb0c321596ae009fff9cd095ebf1cee1532359a860ad70cf2e222a55103fac3d23e86e18897389ef2074",
          "sha256": "d43fdad78a12242bd4f559a50af36a129b073d38c4c5dd4573dce5a2003e4d5e",
          "sha1": "789221ab4b53dba8d1a0c77427dbcead05990aec",
          "md5": "b3b8d106a7e9cb1a426976fb078565ad"
        }
      ]
    }
  ]
}
