{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.7.jar",
          "url": "http-api-4.15.7.jar",
          "size": 172796,
          "sha512": "96983128628ad539c73584dac402ac24049928d7811b7fd0dc8aac11d8089bb63b71f4dcbaabeff3259d50f2e82e5f3b919e3560a79bd96ca05cfaac8c87a895",
          "sha256": "bccf62442c2f473fe8abd43d3d0fb103b964173d7316eafd6faaf041ea904585",
          "sha1": "7fc3975333724af8c3d6d8d31a0797d1d14f59e3",
          "md5": "9b8049d955dc16fa1d554d31e885d645"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.7.jar",
          "url": "http-api-4.15.7.jar",
          "size": 172796,
          "sha512": "96983128628ad539c73584dac402ac24049928d7811b7fd0dc8aac11d8089bb63b71f4dcbaabeff3259d50f2e82e5f3b919e3560a79bd96ca05cfaac8c87a895",
          "sha256": "bccf62442c2f473fe8abd43d3d0fb103b964173d7316eafd6faaf041ea904585",
          "sha1": "7fc3975333724af8c3d6d8d31a0797d1d14f59e3",
          "md5": "9b8049d955dc16fa1d554d31e885d645"
        }
      ]
    }
  ]
}
