{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.13.3.jar",
          "url": "runelite-api-4.13.3.jar",
          "size": 1332566,
          "sha512": "e7f9ab39b4b903e7ad8114680cf9427db361e9daabf1d9c041f4df8caf88a1ae9ff587c7ab565a291bf825e36d448efd760358b0609ee5f1f80fbb1438bdaa1f",
          "sha256": "42b10b70dd6008a5e3415a562838ad0cc6a277f993af5d657fb46424cd9e947f",
          "sha1": "a3bcd477cf8b510ffc0c7e38ccaf0313139820f2",
          "md5": "0ee7632e6fc10194a60303538e9beedf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.13.3.jar",
          "url": "runelite-api-4.13.3.jar",
          "size": 1332566,
          "sha512": "e7f9ab39b4b903e7ad8114680cf9427db361e9daabf1d9c041f4df8caf88a1ae9ff587c7ab565a291bf825e36d448efd760358b0609ee5f1f80fbb1438bdaa1f",
          "sha256": "42b10b70dd6008a5e3415a562838ad0cc6a277f993af5d657fb46424cd9e947f",
          "sha1": "a3bcd477cf8b510ffc0c7e38ccaf0313139820f2",
          "md5": "0ee7632e6fc10194a60303538e9beedf"
        }
      ]
    }
  ]
}
