{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "slntmmpmnjf3jhz56geqrfpnpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1238276,
          "sha512": "355bb1807521d29b5d2e4928a4378fd16b5cfea48be3530cbc4ed28811e5402b999baa0f7677d06f48e9fd2ed1f09b0545fc7aab1603280f6a5d42693bea064e",
          "sha256": "27132398e94bb2b795e681f5fbaff5af817f1df4fc2a8b3d47c09b62cd335783",
          "sha1": "66f61d82708992c1bec0816c1ba618bb3cc867e6",
          "md5": "8aca0d7c3c64acdc18b9e7fd8874f307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1238276,
          "sha512": "355bb1807521d29b5d2e4928a4378fd16b5cfea48be3530cbc4ed28811e5402b999baa0f7677d06f48e9fd2ed1f09b0545fc7aab1603280f6a5d42693bea064e",
          "sha256": "27132398e94bb2b795e681f5fbaff5af817f1df4fc2a8b3d47c09b62cd335783",
          "sha1": "66f61d82708992c1bec0816c1ba618bb3cc867e6",
          "md5": "8aca0d7c3c64acdc18b9e7fd8874f307"
        }
      ]
    }
  ]
}
