{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "nutpquihfrhmvaphr3iwlzwl4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1239673,
          "sha512": "0ffdd89b555da6c8ff380a3e7d2e325c26cf5801104f762dad7f9f8ceca89445d1c5c5ce859000a5461251c3806df4ea593e9ac1561f8e2ad7919b8193944636",
          "sha256": "27cfd06a9130dd258c4c5e284f33342cb89197e199fb699ab710e60ad19d35b1",
          "sha1": "8d668bb69d06fb31ffb3d45bac445c7f7e02fd6f",
          "md5": "f9b150d69636949b378db5d1166a7dbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1239673,
          "sha512": "0ffdd89b555da6c8ff380a3e7d2e325c26cf5801104f762dad7f9f8ceca89445d1c5c5ce859000a5461251c3806df4ea593e9ac1561f8e2ad7919b8193944636",
          "sha256": "27cfd06a9130dd258c4c5e284f33342cb89197e199fb699ab710e60ad19d35b1",
          "sha1": "8d668bb69d06fb31ffb3d45bac445c7f7e02fd6f",
          "md5": "f9b150d69636949b378db5d1166a7dbe"
        }
      ]
    }
  ]
}
