{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5t5ftfxipvgalgfnhlftie22w4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1239586,
          "sha512": "36d94e695ba569333fca8fb6265d8849ade5ed62bc568260e836452faf6f722582df0d3b479f0a975ec9df9f063aa3e38d395199067568781a20dd9541ffd97d",
          "sha256": "f52bd07311d3c0c4623da1caea4d7faae3cc48e836291833f548b6c844e73b4f",
          "sha1": "dcebaf3728fa839470d78101334dbf3268818acd",
          "md5": "1409d2ceeaf6c8dbc9ca72fabdb3f52c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1239586,
          "sha512": "36d94e695ba569333fca8fb6265d8849ade5ed62bc568260e836452faf6f722582df0d3b479f0a975ec9df9f063aa3e38d395199067568781a20dd9541ffd97d",
          "sha256": "f52bd07311d3c0c4623da1caea4d7faae3cc48e836291833f548b6c844e73b4f",
          "sha1": "dcebaf3728fa839470d78101334dbf3268818acd",
          "md5": "1409d2ceeaf6c8dbc9ca72fabdb3f52c"
        }
      ]
    }
  ]
}
