{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.0.jar",
          "url": "runescape-api-4.9.0.jar",
          "size": 109466,
          "sha512": "e41a7d71c29c25077336d36eb69f5bc2143fdb571a96cbe18fc50653bec2ef0b9fe6ca7721347f937f55d3cbf55de56d956ce70996d1fb3cb04fcd584961e45e",
          "sha256": "89315678b287fb71cf8dbac4c6c7c899e427618a38a2517c9631fc7d5fdb63ac",
          "sha1": "be1d9aec3c3b3aa27ef86f57558148530d7aa7a0",
          "md5": "b01414975ff80db6d38bb00af28ac0e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.0.jar",
          "url": "runescape-api-4.9.0.jar",
          "size": 109466,
          "sha512": "e41a7d71c29c25077336d36eb69f5bc2143fdb571a96cbe18fc50653bec2ef0b9fe6ca7721347f937f55d3cbf55de56d956ce70996d1fb3cb04fcd584961e45e",
          "sha256": "89315678b287fb71cf8dbac4c6c7c899e427618a38a2517c9631fc7d5fdb63ac",
          "sha1": "be1d9aec3c3b3aa27ef86f57558148530d7aa7a0",
          "md5": "b01414975ff80db6d38bb00af28ac0e3"
        }
      ]
    }
  ]
}
