{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.8.jar",
          "url": "runelite-jshell-4.15.8.jar",
          "size": 26552,
          "sha512": "74ff2338fa3698dce326021bd35d3f2dc5b9003809bf976f90b635f4abba6703ce63bda846cce5ee1c11a4440c8153a4fb19ef29f9da9a75966d82357ddfc6ed",
          "sha256": "dc6e6822eb6a20537d9a73ab9c39b6efc69d4e14eff081e98e9f2b8c4e5907e6",
          "sha1": "ee2ba423ca2acef5fff185792f4e3ffa2f5e218f",
          "md5": "9d6ee6be89b0cda98a1b4b9a1a69090b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.8.jar",
          "url": "runelite-jshell-4.15.8.jar",
          "size": 26552,
          "sha512": "74ff2338fa3698dce326021bd35d3f2dc5b9003809bf976f90b635f4abba6703ce63bda846cce5ee1c11a4440c8153a4fb19ef29f9da9a75966d82357ddfc6ed",
          "sha256": "dc6e6822eb6a20537d9a73ab9c39b6efc69d4e14eff081e98e9f2b8c4e5907e6",
          "sha1": "ee2ba423ca2acef5fff185792f4e3ffa2f5e218f",
          "md5": "9d6ee6be89b0cda98a1b4b9a1a69090b"
        }
      ]
    }
  ]
}
