{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.8.jar",
          "url": "runelite-jshell-4.15.8.jar",
          "size": 26552,
          "sha512": "301fa8ec00116d07d99776e258ba11ebc1b59a6271fee811799bb145b4924ff5d36b54fb1fb1b387371bd8d020aecc4a7711f30f3bc6ef2b53f80c03fc672a54",
          "sha256": "225c11c4a406d9910752d0575cad8f96397a3c87bf548e045d45e4b5700570f9",
          "sha1": "328e3f8c1205553ffd09fe663a7430535aaa99c5",
          "md5": "ee31b242284abe927ca4cfb068698c53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.8.jar",
          "url": "runelite-jshell-4.15.8.jar",
          "size": 26552,
          "sha512": "301fa8ec00116d07d99776e258ba11ebc1b59a6271fee811799bb145b4924ff5d36b54fb1fb1b387371bd8d020aecc4a7711f30f3bc6ef2b53f80c03fc672a54",
          "sha256": "225c11c4a406d9910752d0575cad8f96397a3c87bf548e045d45e4b5700570f9",
          "sha1": "328e3f8c1205553ffd09fe663a7430535aaa99c5",
          "md5": "ee31b242284abe927ca4cfb068698c53"
        }
      ]
    }
  ]
}
