{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "o6tlvy7o2fcqvhljp5fituawzm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 132634,
          "sha512": "0fc5b0af81313a8554d0fb45b0c7fd11f165ebf0ae44982f80772016c915a72111b555b371cb7d53438ba173604849bb04b0b7787a2d950b33bbf3c8dc47d2f6",
          "sha256": "6e88625b2a2e58955e18216b7d37c1674d8c321fbd1ce2fcc09f964acdd55c6d",
          "sha1": "cfa39f48d45842646a7136c36d5a2ed1c41d80c6",
          "md5": "6d84544c74714bc8c941701aec91da75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 132634,
          "sha512": "0fc5b0af81313a8554d0fb45b0c7fd11f165ebf0ae44982f80772016c915a72111b555b371cb7d53438ba173604849bb04b0b7787a2d950b33bbf3c8dc47d2f6",
          "sha256": "6e88625b2a2e58955e18216b7d37c1674d8c321fbd1ce2fcc09f964acdd55c6d",
          "sha1": "cfa39f48d45842646a7136c36d5a2ed1c41d80c6",
          "md5": "6d84544c74714bc8c941701aec91da75"
        }
      ]
    }
  ]
}
