{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gjdnbyr2rrgw5kfciifuzv5xpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 136645,
          "sha512": "56a24725c7f5258a0477435ec58870dc3939182cc6bc2cb063e9b6985fd266d1484db776ea5d6210c6de5cbe4a231bf1fd9bbc0063a418447379a7e5a1835a6c",
          "sha256": "ec1e914a43f281e4061995497b18626f77e0f6b8ee022f7089d6805b6b50976d",
          "sha1": "da7751b2159a3930320e21aff7d479ec2e41c7c9",
          "md5": "db712487292af325ce1b3475c8d16113"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 136645,
          "sha512": "56a24725c7f5258a0477435ec58870dc3939182cc6bc2cb063e9b6985fd266d1484db776ea5d6210c6de5cbe4a231bf1fd9bbc0063a418447379a7e5a1835a6c",
          "sha256": "ec1e914a43f281e4061995497b18626f77e0f6b8ee022f7089d6805b6b50976d",
          "sha1": "da7751b2159a3930320e21aff7d479ec2e41c7c9",
          "md5": "db712487292af325ce1b3475c8d16113"
        }
      ]
    }
  ]
}
