{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "1a1f214fcd33f8cd5d3447cdea1f98b40c926cacc867f5a50f4038599cbb76816602b4b88ed5cd49de38ef3e2c6431e1533f8e9f8f704222cced9882a4af504c",
          "sha256": "27b98c6cc1560e01a0aebdb93640bbdb34be507ca347b7f7e8e79bbfc278f6d1",
          "sha1": "ee8bbec79d88b74b69fbbf25b247a07ee73c4023",
          "md5": "16b420e458f1e6a1881c910725a3b6c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "1a1f214fcd33f8cd5d3447cdea1f98b40c926cacc867f5a50f4038599cbb76816602b4b88ed5cd49de38ef3e2c6431e1533f8e9f8f704222cced9882a4af504c",
          "sha256": "27b98c6cc1560e01a0aebdb93640bbdb34be507ca347b7f7e8e79bbfc278f6d1",
          "sha1": "ee8bbec79d88b74b69fbbf25b247a07ee73c4023",
          "md5": "16b420e458f1e6a1881c910725a3b6c4"
        }
      ]
    }
  ]
}
