{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "b1a17ee7d9910a80172a74cfcca31afe75ca9993c815786cced120d2647249ec95e6a595749181382e8561c0cc5f06925c842d3e4434966c45598c39a2b84432",
          "sha256": "a840cdcb33ae629564a7f67d1a9d1964c411db8c188eedcd5a76be7eb45826a6",
          "sha1": "71d4466299731a2280a1576020117afb0d1258a8",
          "md5": "53a5e3ebecd04f93f8eb33a630019a34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "b1a17ee7d9910a80172a74cfcca31afe75ca9993c815786cced120d2647249ec95e6a595749181382e8561c0cc5f06925c842d3e4434966c45598c39a2b84432",
          "sha256": "a840cdcb33ae629564a7f67d1a9d1964c411db8c188eedcd5a76be7eb45826a6",
          "sha1": "71d4466299731a2280a1576020117afb0d1258a8",
          "md5": "53a5e3ebecd04f93f8eb33a630019a34"
        }
      ]
    }
  ]
}
