{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "ca8d3448d757d3c379124834ff846bfac4b5bf5ddaab5880ecf9b9cb60b4166c603f35afadd7ea48f06e4f7dad901fc14d4895914ed82a2396cb1123383aa32b",
          "sha256": "b048835cabfd25fb8d3398a2dafe4fa52bed6517df4437917885b87b15b7175b",
          "sha1": "8bc97fef8dc0eded013a9d9a596fcf2a6556fc5a",
          "md5": "2108f831c063f2a867e9f1be58ef7eae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.0.jar",
          "url": "runelite-jshell-4.20.0.jar",
          "size": 26552,
          "sha512": "ca8d3448d757d3c379124834ff846bfac4b5bf5ddaab5880ecf9b9cb60b4166c603f35afadd7ea48f06e4f7dad901fc14d4895914ed82a2396cb1123383aa32b",
          "sha256": "b048835cabfd25fb8d3398a2dafe4fa52bed6517df4437917885b87b15b7175b",
          "sha1": "8bc97fef8dc0eded013a9d9a596fcf2a6556fc5a",
          "md5": "2108f831c063f2a867e9f1be58ef7eae"
        }
      ]
    }
  ]
}
