{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.0.jar",
          "url": "runescape-api-4.16.0.jar",
          "size": 143805,
          "sha512": "da9ab8918ae15ca3729ba2f9a12f9e007c01896f64265e6b47cf53d6d047efa667c9f557569d9fb673638954576e7e21ac0a14e6f721944c66c4b5ae05fade0f",
          "sha256": "bfbaf1af9e7a7e08ca484d6be375cd924784bf3c6207f60a6098cd35630b94fb",
          "sha1": "93b97897c977b081d1d8bc8715db4cc2b9f18e86",
          "md5": "bd7ccad66cbabb5408bae5db76414246"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.0.jar",
          "url": "runescape-api-4.16.0.jar",
          "size": 143805,
          "sha512": "da9ab8918ae15ca3729ba2f9a12f9e007c01896f64265e6b47cf53d6d047efa667c9f557569d9fb673638954576e7e21ac0a14e6f721944c66c4b5ae05fade0f",
          "sha256": "bfbaf1af9e7a7e08ca484d6be375cd924784bf3c6207f60a6098cd35630b94fb",
          "sha1": "93b97897c977b081d1d8bc8715db4cc2b9f18e86",
          "md5": "bd7ccad66cbabb5408bae5db76414246"
        }
      ]
    }
  ]
}
