{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.6.2.jar",
          "url": "runelite-api-4.6.2.jar",
          "size": 1259003,
          "sha512": "1c83838c99e63062c3c9df785dab10597c63b285112b0153bed741b2e607791c7bda7f07e651f38d9098c3219ac1905927f47e89a0561f27ba054215da6994a7",
          "sha256": "96bc64d64934a9a4b5d3f878ecd109effc0ff74473c98f545c4abcfa64bd1753",
          "sha1": "b8c61aea8f5fe1d31064ffda44095e9d6adfd82a",
          "md5": "6a46d8fb113945070b5a9e3a283500e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.6.2.jar",
          "url": "runelite-api-4.6.2.jar",
          "size": 1259003,
          "sha512": "1c83838c99e63062c3c9df785dab10597c63b285112b0153bed741b2e607791c7bda7f07e651f38d9098c3219ac1905927f47e89a0561f27ba054215da6994a7",
          "sha256": "96bc64d64934a9a4b5d3f878ecd109effc0ff74473c98f545c4abcfa64bd1753",
          "sha1": "b8c61aea8f5fe1d31064ffda44095e9d6adfd82a",
          "md5": "6a46d8fb113945070b5a9e3a283500e0"
        }
      ]
    }
  ]
}
