{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "1b5f71caa3f3deaf41e5c680924b649effec9247049a35254818a1a1f11bf3b9faae0b6306e3e8f7826b1eff18a4a574c18caa881f1b93e0336245c5f09a8864",
          "sha256": "cacbcd18a0766e57672ea39f74c2def0cbfdac42effda7d00030903ebeec3469",
          "sha1": "c60af932c989aaceb08f07256318c7a38f704302",
          "md5": "57f2de5f2bbea3ebaca8ace9ee85c33c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.16.2.jar",
          "url": "runescape-api-4.16.2.jar",
          "size": 143805,
          "sha512": "1b5f71caa3f3deaf41e5c680924b649effec9247049a35254818a1a1f11bf3b9faae0b6306e3e8f7826b1eff18a4a574c18caa881f1b93e0336245c5f09a8864",
          "sha256": "cacbcd18a0766e57672ea39f74c2def0cbfdac42effda7d00030903ebeec3469",
          "sha1": "c60af932c989aaceb08f07256318c7a38f704302",
          "md5": "57f2de5f2bbea3ebaca8ace9ee85c33c"
        }
      ]
    }
  ]
}
