{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.4.jar",
          "url": "runescape-api-4.20.4.jar",
          "size": 149179,
          "sha512": "a54a5cfa71430ea460aa12d78276d22ed6c140bc3e0c3983043f79ffc1f1257619fdd863df5bedfe6a9b6b7091dd7c3ef43c395eeff9e89ced876c9a746f5264",
          "sha256": "c8708ac8f0677dfd2708dd93de3abbd18d3dcae8860d9d2efa2fb5b7c1ef2331",
          "sha1": "3bb1680f43d2665cb4502cc3da2a53b5fd22dae0",
          "md5": "79dd88c5fa27bee51f5d60eb46a41174"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.4.jar",
          "url": "runescape-api-4.20.4.jar",
          "size": 149179,
          "sha512": "a54a5cfa71430ea460aa12d78276d22ed6c140bc3e0c3983043f79ffc1f1257619fdd863df5bedfe6a9b6b7091dd7c3ef43c395eeff9e89ced876c9a746f5264",
          "sha256": "c8708ac8f0677dfd2708dd93de3abbd18d3dcae8860d9d2efa2fb5b7c1ef2331",
          "sha1": "3bb1680f43d2665cb4502cc3da2a53b5fd22dae0",
          "md5": "79dd88c5fa27bee51f5d60eb46a41174"
        }
      ]
    }
  ]
}
