{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149686,
          "sha512": "7d1e144fb0afb234576cc40a0568be0f2c170d1d419c285d94f54471432bf3250da0f3ac155faaea541a7ca28c7e48f869f7bbd8eab2550ad43e474a6f6f6c1f",
          "sha256": "a0898c4153205dd68ef1e7e408803a55748df82367064544155f7e8bbf0841c9",
          "sha1": "2ac423a7075c8d08c6d862644a556f9a6befcd5c",
          "md5": "3100b06b7b8b08d662eb1a94e05f5dbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149686,
          "sha512": "7d1e144fb0afb234576cc40a0568be0f2c170d1d419c285d94f54471432bf3250da0f3ac155faaea541a7ca28c7e48f869f7bbd8eab2550ad43e474a6f6f6c1f",
          "sha256": "a0898c4153205dd68ef1e7e408803a55748df82367064544155f7e8bbf0841c9",
          "sha1": "2ac423a7075c8d08c6d862644a556f9a6befcd5c",
          "md5": "3100b06b7b8b08d662eb1a94e05f5dbf"
        }
      ]
    }
  ]
}
