{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149686,
          "sha512": "a9479178aec8afa22e36c38e65777bbe036bee0f61c6207a22f4dc764c3b0a31ceaf45ac2b51bcacf241fde25e67b06bd8f94a9d07cc4a81a668d3e1329d12cd",
          "sha256": "ba8ddb1118b33b6da4f94375844781d4c482aff63c2797c96a19154c87b77d45",
          "sha1": "26d9608c6529d29be7e15bd70a08d38f5ace6c4b",
          "md5": "ee0a1c572e7e83060792fee7003ae98c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2.jar",
          "url": "runescape-api-4.25.2.jar",
          "size": 149686,
          "sha512": "a9479178aec8afa22e36c38e65777bbe036bee0f61c6207a22f4dc764c3b0a31ceaf45ac2b51bcacf241fde25e67b06bd8f94a9d07cc4a81a668d3e1329d12cd",
          "sha256": "ba8ddb1118b33b6da4f94375844781d4c482aff63c2797c96a19154c87b77d45",
          "sha1": "26d9608c6529d29be7e15bd70a08d38f5ace6c4b",
          "md5": "ee0a1c572e7e83060792fee7003ae98c"
        }
      ]
    }
  ]
}
