{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.0.jar",
          "url": "runescape-api-4.25.0.jar",
          "size": 149656,
          "sha512": "113d03c8d581a520d8199998180afd6efb2ffb06e4855ee0bab925189e815a52093bf0eb6b97b61b990b6d8e8522f19d07d0a738aafcd9a7d1e9699a06029be2",
          "sha256": "14aabf147278392309c5b9a6da443fb5d72103f671632e31af819b4aeeee72a9",
          "sha1": "1f957f9430e3d20dca18d46eadd4445f8e98b1a1",
          "md5": "50d78d7e3f3ad7749e9dc95488c0e90e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.0.jar",
          "url": "runescape-api-4.25.0.jar",
          "size": 149656,
          "sha512": "113d03c8d581a520d8199998180afd6efb2ffb06e4855ee0bab925189e815a52093bf0eb6b97b61b990b6d8e8522f19d07d0a738aafcd9a7d1e9699a06029be2",
          "sha256": "14aabf147278392309c5b9a6da443fb5d72103f671632e31af819b4aeeee72a9",
          "sha1": "1f957f9430e3d20dca18d46eadd4445f8e98b1a1",
          "md5": "50d78d7e3f3ad7749e9dc95488c0e90e"
        }
      ]
    }
  ]
}
