{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.0.jar",
          "url": "runescape-api-4.25.0.jar",
          "size": 149656,
          "sha512": "3837462837c3f5eb7db0e3be821edb2ce063458fea110da7a3e7c64a752ca1d705d89ac5395a12ef20ab41175e9cbf8279c013e17093722fdee3d35efd7e9c20",
          "sha256": "fae8d438196b2065b816c426fd7fb01db56e8d6452e4e7c1755bead49907c3bc",
          "sha1": "782678137f486377538683556f603f517c9b3741",
          "md5": "aec53a4038580b1c037e5b6a1a780ddf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.0.jar",
          "url": "runescape-api-4.25.0.jar",
          "size": 149656,
          "sha512": "3837462837c3f5eb7db0e3be821edb2ce063458fea110da7a3e7c64a752ca1d705d89ac5395a12ef20ab41175e9cbf8279c013e17093722fdee3d35efd7e9c20",
          "sha256": "fae8d438196b2065b816c426fd7fb01db56e8d6452e4e7c1755bead49907c3bc",
          "sha1": "782678137f486377538683556f603f517c9b3741",
          "md5": "aec53a4038580b1c037e5b6a1a780ddf"
        }
      ]
    }
  ]
}
