{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.0.jar",
          "url": "runescape-api-4.25.0.jar",
          "size": 149656,
          "sha512": "a1b9bb16a5f1e7b408928dc4c6e097417c39a32a37a8712a426384ce74d772cd511c3914e07d8fdd48e6034da68abea05c8e9cb286b03128330c0c118d16b3a5",
          "sha256": "9ab5138eef0036f4c93327ba9de1d54a0d420d02259409bd589e67babbf409b1",
          "sha1": "ec16474775e020d4bb3e070541346a9ce814330a",
          "md5": "363274dad140f4401aa8aa9699523b41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.0.jar",
          "url": "runescape-api-4.25.0.jar",
          "size": 149656,
          "sha512": "a1b9bb16a5f1e7b408928dc4c6e097417c39a32a37a8712a426384ce74d772cd511c3914e07d8fdd48e6034da68abea05c8e9cb286b03128330c0c118d16b3a5",
          "sha256": "9ab5138eef0036f4c93327ba9de1d54a0d420d02259409bd589e67babbf409b1",
          "sha1": "ec16474775e020d4bb3e070541346a9ce814330a",
          "md5": "363274dad140f4401aa8aa9699523b41"
        }
      ]
    }
  ]
}
