{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.0.jar",
          "url": "runelite-jshell-4.18.0.jar",
          "size": 26552,
          "sha512": "3b100391ce556e6a1bb35dc33d16950c5a93c8d69c479cb2cc8444eb6068cd5b14b1cc2fcb8fc038d9d2a3969e064e39e7004b96c8a2731813a18315c35f8382",
          "sha256": "86875f9fdab3b1ec49ad6fc169e8229529258e8901365a7d0feecb92e2dff595",
          "sha1": "b156e804ca7edd07364b05478ecc4b54de5db10a",
          "md5": "e112bded04e64d49c0f083b0c7c11017"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.0.jar",
          "url": "runelite-jshell-4.18.0.jar",
          "size": 26552,
          "sha512": "3b100391ce556e6a1bb35dc33d16950c5a93c8d69c479cb2cc8444eb6068cd5b14b1cc2fcb8fc038d9d2a3969e064e39e7004b96c8a2731813a18315c35f8382",
          "sha256": "86875f9fdab3b1ec49ad6fc169e8229529258e8901365a7d0feecb92e2dff595",
          "sha1": "b156e804ca7edd07364b05478ecc4b54de5db10a",
          "md5": "e112bded04e64d49c0f083b0c7c11017"
        }
      ]
    }
  ]
}
