{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.2.jar",
          "url": "runelite-jshell-4.15.2.jar",
          "size": 26552,
          "sha512": "cedff7595e9d6b71da7d6080a5cfe6c27c932d4bc14f2d6d221e5a98f87f5ebcbd0d7e5e3d118c2729f78da5adade39734dcc25cd8a95f811345c7f81dcb0746",
          "sha256": "75a661ac82858c9b6619eee8618df994bc979beeed54e07c08db15fb86c3c348",
          "sha1": "830757b37318dff92bc04d3d4b4a1709bf544574",
          "md5": "c1ded15084479c48e698ad73c5454fd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.2.jar",
          "url": "runelite-jshell-4.15.2.jar",
          "size": 26552,
          "sha512": "cedff7595e9d6b71da7d6080a5cfe6c27c932d4bc14f2d6d221e5a98f87f5ebcbd0d7e5e3d118c2729f78da5adade39734dcc25cd8a95f811345c7f81dcb0746",
          "sha256": "75a661ac82858c9b6619eee8618df994bc979beeed54e07c08db15fb86c3c348",
          "sha1": "830757b37318dff92bc04d3d4b4a1709bf544574",
          "md5": "c1ded15084479c48e698ad73c5454fd1"
        }
      ]
    }
  ]
}
