{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.6.jar",
          "url": "http-api-4.9.6.jar",
          "size": 158608,
          "sha512": "48df18294afceaf1acfe56006940c0ed1c65b39d93c53d0a580ad8ce49dd2ee696b8d0ccd7ea3c84f998136b850b52101c0a0f621142adc92be459576a0f1849",
          "sha256": "b9be484265a09fb4c732a4e16e4bfc2494bd1ed56dfbf55778590a970335d0f5",
          "sha1": "7c0734f30cfeb5ab3f6d271b705fe62a11bb640d",
          "md5": "2cfcf846409ac77fe9e730d0cdf9810e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.6.jar",
          "url": "http-api-4.9.6.jar",
          "size": 158608,
          "sha512": "48df18294afceaf1acfe56006940c0ed1c65b39d93c53d0a580ad8ce49dd2ee696b8d0ccd7ea3c84f998136b850b52101c0a0f621142adc92be459576a0f1849",
          "sha256": "b9be484265a09fb4c732a4e16e4bfc2494bd1ed56dfbf55778590a970335d0f5",
          "sha1": "7c0734f30cfeb5ab3f6d271b705fe62a11bb640d",
          "md5": "2cfcf846409ac77fe9e730d0cdf9810e"
        }
      ]
    }
  ]
}
