{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.6.jar",
          "url": "http-api-4.9.6.jar",
          "size": 158609,
          "sha512": "dc741c9599c8bd0e160d7a8e97a4494a136d107c86c4d6b1df8457256211b0b7cec46c24d9e47a3281eebd6735a6f1b77bcf6ec6d280ca93be641198df74dd52",
          "sha256": "4581f50ae21a6e08b58b8dc8a2454115a475068422053e330be65d5683d26833",
          "sha1": "eacb6682cd35ea75c6886a5ccedb4a9fe1a448d4",
          "md5": "6bd3bd9ebc7e785379e88b9b13daafba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.6.jar",
          "url": "http-api-4.9.6.jar",
          "size": 158609,
          "sha512": "dc741c9599c8bd0e160d7a8e97a4494a136d107c86c4d6b1df8457256211b0b7cec46c24d9e47a3281eebd6735a6f1b77bcf6ec6d280ca93be641198df74dd52",
          "sha256": "4581f50ae21a6e08b58b8dc8a2454115a475068422053e330be65d5683d26833",
          "sha1": "eacb6682cd35ea75c6886a5ccedb4a9fe1a448d4",
          "md5": "6bd3bd9ebc7e785379e88b9b13daafba"
        }
      ]
    }
  ]
}
