{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.12.jar",
          "url": "http-api-4.9.12.jar",
          "size": 158533,
          "sha512": "caf49ea14c67b5d6706d4492476ab7cbd06cd8f4cee2a8c49faa11db03f5d4c00d5954eefb1136909feddeacb4e31030eae03fb11e19a995d3af97a6966bcf6f",
          "sha256": "8773ae32932689c66f66629f3cfb50cb1034f7594f1bba9a0bd2ab14a1135794",
          "sha1": "a97c843bfd96e08d00aaa5ae6b51e3cbb88e2af9",
          "md5": "0a30b0d3db748268654e93d73e0c6eae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.12"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.12.jar",
          "url": "http-api-4.9.12.jar",
          "size": 158533,
          "sha512": "caf49ea14c67b5d6706d4492476ab7cbd06cd8f4cee2a8c49faa11db03f5d4c00d5954eefb1136909feddeacb4e31030eae03fb11e19a995d3af97a6966bcf6f",
          "sha256": "8773ae32932689c66f66629f3cfb50cb1034f7594f1bba9a0bd2ab14a1135794",
          "sha1": "a97c843bfd96e08d00aaa5ae6b51e3cbb88e2af9",
          "md5": "0a30b0d3db748268654e93d73e0c6eae"
        }
      ]
    }
  ]
}
