{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wpinim322bfgxcgrcmqhgfs3ae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160389,
          "sha512": "e8059a303b8e5af8da003b78baaf5d6d0d8c60a2d809ba734379bb3d4706369dbd734bed347b077813d1a70add5ef57c754bc5269e11d23b8ca4f29d8ee0f069",
          "sha256": "0d3885d120e3d307b621cbd337ce5c09aa261a00b0b46803e2334862a3f7e103",
          "sha1": "2d29d26dbb490de2a5fe3d8f530dc5d129ff28f0",
          "md5": "1da523017e1f02a111ec40af60f0b6d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160389,
          "sha512": "e8059a303b8e5af8da003b78baaf5d6d0d8c60a2d809ba734379bb3d4706369dbd734bed347b077813d1a70add5ef57c754bc5269e11d23b8ca4f29d8ee0f069",
          "sha256": "0d3885d120e3d307b621cbd337ce5c09aa261a00b0b46803e2334862a3f7e103",
          "sha1": "2d29d26dbb490de2a5fe3d8f530dc5d129ff28f0",
          "md5": "1da523017e1f02a111ec40af60f0b6d9"
        }
      ]
    }
  ]
}
