{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "bebhr4px2vg47detkn6r73s3d4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 161368,
          "sha512": "2a1286d9b7cc2c7061098b8c3aae9fe1d0fcbdfa3b45126c4778f27572cf70f283ee10081f7d8c3b005f637d5ce6d8967257d94b85d077324fef5e144641e15a",
          "sha256": "1b58f1394ff1b1da2964cf684524b8fbc6e8f252563a0babbc57156385ed785b",
          "sha1": "efb289fdb2daa90a8a55241dc3cce2ba82c948f3",
          "md5": "fe07750f2c28a84917a02f6ce1d86dc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 161368,
          "sha512": "2a1286d9b7cc2c7061098b8c3aae9fe1d0fcbdfa3b45126c4778f27572cf70f283ee10081f7d8c3b005f637d5ce6d8967257d94b85d077324fef5e144641e15a",
          "sha256": "1b58f1394ff1b1da2964cf684524b8fbc6e8f252563a0babbc57156385ed785b",
          "sha1": "efb289fdb2daa90a8a55241dc3cce2ba82c948f3",
          "md5": "fe07750f2c28a84917a02f6ce1d86dc8"
        }
      ]
    }
  ]
}
