{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "li62mcadkbcq7oimiuklvi3uqy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160389,
          "sha512": "1ef5ca26146692752360345d946716b27bb96717169e6b2904a863e6c9d22721f099997e9e86b1f1891659eef6c7467c291cfb8f0ae1c2e2bec3076384993d29",
          "sha256": "98211c82e5d19eace35c9352150a6f1b3cb90a52a2ad7827029b7f7efd1781b1",
          "sha1": "c9677f84a428ae548e5787e3dbd3e16d31d8b498",
          "md5": "7a37129fe0af5184b4912f9da4858901"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 160389,
          "sha512": "1ef5ca26146692752360345d946716b27bb96717169e6b2904a863e6c9d22721f099997e9e86b1f1891659eef6c7467c291cfb8f0ae1c2e2bec3076384993d29",
          "sha256": "98211c82e5d19eace35c9352150a6f1b3cb90a52a2ad7827029b7f7efd1781b1",
          "sha1": "c9677f84a428ae548e5787e3dbd3e16d31d8b498",
          "md5": "7a37129fe0af5184b4912f9da4858901"
        }
      ]
    }
  ]
}
