{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "71dfe141ed2906cfb09697e882ceca6c9a91c021d059a43d3771ccc1d7fb58cf6b1ba997f4fdfbdc8c0739e3461fb51268e4412f8d9a8780c256f4dfb59b407a",
          "sha256": "1d63ae2f50121659fed0ff142ad73d47b1b12594e26238c6476e747508358d83",
          "sha1": "a19a6122d30cd27c6bfc1b6293beb3d4afefe23a",
          "md5": "212f15b79c6f0c8f329a4a558796fcbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "71dfe141ed2906cfb09697e882ceca6c9a91c021d059a43d3771ccc1d7fb58cf6b1ba997f4fdfbdc8c0739e3461fb51268e4412f8d9a8780c256f4dfb59b407a",
          "sha256": "1d63ae2f50121659fed0ff142ad73d47b1b12594e26238c6476e747508358d83",
          "sha1": "a19a6122d30cd27c6bfc1b6293beb3d4afefe23a",
          "md5": "212f15b79c6f0c8f329a4a558796fcbb"
        }
      ]
    }
  ]
}
