{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "528aa65171b9dcdabd39a4f9345e5662e02b4fcdcb99a91327789f38fdce71cfdf5d5b2bf1c401fe9657ebc0462d2feae75edb357fe6bb273192de2dacb73a1c",
          "sha256": "2adc6c1977b9f68c76ea7f2d04581b2f1034674951b4e6a5c97c4c2c05484051",
          "sha1": "a1db5c12d385270e20caeae7e29f0619ec6ff24d",
          "md5": "bf33cd1d93d34915e1c7eb89e3cdec6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "528aa65171b9dcdabd39a4f9345e5662e02b4fcdcb99a91327789f38fdce71cfdf5d5b2bf1c401fe9657ebc0462d2feae75edb357fe6bb273192de2dacb73a1c",
          "sha256": "2adc6c1977b9f68c76ea7f2d04581b2f1034674951b4e6a5c97c4c2c05484051",
          "sha1": "a1db5c12d385270e20caeae7e29f0619ec6ff24d",
          "md5": "bf33cd1d93d34915e1c7eb89e3cdec6f"
        }
      ]
    }
  ]
}
