{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "75d38b9eb39e1120c8bb3a57d60b2853d3e4d1a885f4a71e341d399d804440f4bac3bf64e3307a5a8289fad3c1d37ac68e0fb3eaa98803177109ab8abb0ea067",
          "sha256": "38d4f02811bd217a2d276adea06b941123806335f278c336991b40b8ecd903ed",
          "sha1": "94135a0c7bbb5bb03e08bbeac47c51893fc63c64",
          "md5": "1376a39b4bfe5c5b578adbd8d8fbcaf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.22.0.jar",
          "url": "runescape-api-4.22.0.jar",
          "size": 149442,
          "sha512": "75d38b9eb39e1120c8bb3a57d60b2853d3e4d1a885f4a71e341d399d804440f4bac3bf64e3307a5a8289fad3c1d37ac68e0fb3eaa98803177109ab8abb0ea067",
          "sha256": "38d4f02811bd217a2d276adea06b941123806335f278c336991b40b8ecd903ed",
          "sha1": "94135a0c7bbb5bb03e08bbeac47c51893fc63c64",
          "md5": "1376a39b4bfe5c5b578adbd8d8fbcaf6"
        }
      ]
    }
  ]
}
