{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.0.jar",
          "url": "runelite-jshell-4.31.0.jar",
          "size": 26557,
          "sha512": "8692a653c5e7a086da56ef1e820843a6a3448e12946c0d27e055737ff8b6f828987dd32d612392264e7a6cb243cc1abafd0fac4de5e639d9c5382a41f653b6a1",
          "sha256": "f1ed64d2730b32843cc713eb14fc769d84abccdf13b835ca8ad9b76d3e4137db",
          "sha1": "2027e6761bbee38015af760c825aef730738a999",
          "md5": "c6b1b35d301f2f7df765850833bd1058"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.0.jar",
          "url": "runelite-jshell-4.31.0.jar",
          "size": 26557,
          "sha512": "8692a653c5e7a086da56ef1e820843a6a3448e12946c0d27e055737ff8b6f828987dd32d612392264e7a6cb243cc1abafd0fac4de5e639d9c5382a41f653b6a1",
          "sha256": "f1ed64d2730b32843cc713eb14fc769d84abccdf13b835ca8ad9b76d3e4137db",
          "sha1": "2027e6761bbee38015af760c825aef730738a999",
          "md5": "c6b1b35d301f2f7df765850833bd1058"
        }
      ]
    }
  ]
}
