{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.0.jar",
          "url": "runelite-jshell-4.31.0.jar",
          "size": 26557,
          "sha512": "2ec2214c1d9c2278576c9d9867ccc950ba87b54a7d2718613163f257d348019a3e688b54caf5dd4942a6e239e23578af582c76ad777e0446d31967b98be111e1",
          "sha256": "622a8d4062733692a469751ea30c08e969fef09d86d54abbdc2f8707deb454a6",
          "sha1": "ecb919cb4b08c4243c9ad9f809893fb44a081727",
          "md5": "13fa0a311adbb2a68abc84f31994beaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.0.jar",
          "url": "runelite-jshell-4.31.0.jar",
          "size": 26557,
          "sha512": "2ec2214c1d9c2278576c9d9867ccc950ba87b54a7d2718613163f257d348019a3e688b54caf5dd4942a6e239e23578af582c76ad777e0446d31967b98be111e1",
          "sha256": "622a8d4062733692a469751ea30c08e969fef09d86d54abbdc2f8707deb454a6",
          "sha1": "ecb919cb4b08c4243c9ad9f809893fb44a081727",
          "md5": "13fa0a311adbb2a68abc84f31994beaf"
        }
      ]
    }
  ]
}
