{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.1.jar",
          "url": "runelite-jshell-4.25.1.jar",
          "size": 26557,
          "sha512": "676542056768a549c8f72e4d438611f063d48f414bcc6e849b0a1d6aedd44755f5a2c3302a476219e869ba01dea1b68743d8ba99e5fd2aea1e9ce3e5003abf95",
          "sha256": "9aef7b36a11fbb4da51a386bd5168a178ddf39ca3a57179a06d7ac76d58ef968",
          "sha1": "08ff011a3281bb6841bb238eb91d5faf025acabd",
          "md5": "3c663513ed08d11ecee67e7ca8e1354b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.1.jar",
          "url": "runelite-jshell-4.25.1.jar",
          "size": 26557,
          "sha512": "676542056768a549c8f72e4d438611f063d48f414bcc6e849b0a1d6aedd44755f5a2c3302a476219e869ba01dea1b68743d8ba99e5fd2aea1e9ce3e5003abf95",
          "sha256": "9aef7b36a11fbb4da51a386bd5168a178ddf39ca3a57179a06d7ac76d58ef968",
          "sha1": "08ff011a3281bb6841bb238eb91d5faf025acabd",
          "md5": "3c663513ed08d11ecee67e7ca8e1354b"
        }
      ]
    }
  ]
}
