{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172795,
          "sha512": "e459793a7edd99957ae0b7a852033fbc73c3fbb4608408e090f5a0c7cad20b8e1c106745c4eab22130684d23d33ff47d4e74a79f38898d5268f630fe2b928a94",
          "sha256": "a798d9e5e3da0157c193ad453dcad6e5a32dbff25e42140d5016ae070b12309f",
          "sha1": "83f17be9d036c5ec1891fbccc941d761fad1a5c8",
          "md5": "710dd6553105255b110c090e8219d9e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172795,
          "sha512": "e459793a7edd99957ae0b7a852033fbc73c3fbb4608408e090f5a0c7cad20b8e1c106745c4eab22130684d23d33ff47d4e74a79f38898d5268f630fe2b928a94",
          "sha256": "a798d9e5e3da0157c193ad453dcad6e5a32dbff25e42140d5016ae070b12309f",
          "sha1": "83f17be9d036c5ec1891fbccc941d761fad1a5c8",
          "md5": "710dd6553105255b110c090e8219d9e3"
        }
      ]
    }
  ]
}
