{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172796,
          "sha512": "7ec2cfaab1dd7915c1ce5f242dd60bfa7f29e1a64a5aedb35973ebc57e9ad60f974aa1df4fda98857d55e97dfb75c383168405ceb2cf56f2222526bd46863e5e",
          "sha256": "570e2fa12dd1994fa9fd28e43b44825bb1196bb072a7658771c52b023c978c37",
          "sha1": "26b5cc4c513ef9bff393b8aec8f64083491c1bf0",
          "md5": "0920513316c0d51f90e0aacc23adc0f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172796,
          "sha512": "7ec2cfaab1dd7915c1ce5f242dd60bfa7f29e1a64a5aedb35973ebc57e9ad60f974aa1df4fda98857d55e97dfb75c383168405ceb2cf56f2222526bd46863e5e",
          "sha256": "570e2fa12dd1994fa9fd28e43b44825bb1196bb072a7658771c52b023c978c37",
          "sha1": "26b5cc4c513ef9bff393b8aec8f64083491c1bf0",
          "md5": "0920513316c0d51f90e0aacc23adc0f7"
        }
      ]
    }
  ]
}
