{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "0638e6f55028bd07f5fa13da2c2ba3ee8187167a9ce94380151042c1a4a443e6294b04e04117e7aacdd58b373393946f1e3a4c4bbca2205ab6fbd6be66c9020b",
          "sha256": "bc485e74405c8b1f709d45299cb966cb48ffab75b8d090923261377421f6823a",
          "sha1": "090d69eacf84a3f1b46faf934f4f5f753a7be35d",
          "md5": "5ae8ab92ce7b2dbdbe85cd9034dfd67b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "0638e6f55028bd07f5fa13da2c2ba3ee8187167a9ce94380151042c1a4a443e6294b04e04117e7aacdd58b373393946f1e3a4c4bbca2205ab6fbd6be66c9020b",
          "sha256": "bc485e74405c8b1f709d45299cb966cb48ffab75b8d090923261377421f6823a",
          "sha1": "090d69eacf84a3f1b46faf934f4f5f753a7be35d",
          "md5": "5ae8ab92ce7b2dbdbe85cd9034dfd67b"
        }
      ]
    }
  ]
}
