{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "fc3f7c37d1fcd32ba9154dbe9e0a2f3183a6acc53ca440d07a9f877d254d9658b2ad65f1809b438df6e4ea2dd3a34a6d61141fc1707c164cba3509e1b189f477",
          "sha256": "0aed04acc230a1a847cb37baaca06866951b88beb6f97c8f4e0997b355e3dcd5",
          "sha1": "55ad223c2fb929915e85c61b8e7696b33db50a38",
          "md5": "80076a86ebe0f0f86c7001d01f6182d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "fc3f7c37d1fcd32ba9154dbe9e0a2f3183a6acc53ca440d07a9f877d254d9658b2ad65f1809b438df6e4ea2dd3a34a6d61141fc1707c164cba3509e1b189f477",
          "sha256": "0aed04acc230a1a847cb37baaca06866951b88beb6f97c8f4e0997b355e3dcd5",
          "sha1": "55ad223c2fb929915e85c61b8e7696b33db50a38",
          "md5": "80076a86ebe0f0f86c7001d01f6182d2"
        }
      ]
    }
  ]
}
