{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "d93819fa1bbd254f0b1b8cca7a702cb4b9655c51bb08a6b6dbbeb5721beed55724d016067132f94149e319a68ba71ac0fa0e5817512236f179d6c0a0825661d4",
          "sha256": "aea041e3a6ced0ab872c12eebe383380bf735132c039cbb876a94c2034a85489",
          "sha1": "0bc788c079811da71744beb5c08e4514c27c1948",
          "md5": "2e40821b4cdb8a1491583e1b453f6f8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "d93819fa1bbd254f0b1b8cca7a702cb4b9655c51bb08a6b6dbbeb5721beed55724d016067132f94149e319a68ba71ac0fa0e5817512236f179d6c0a0825661d4",
          "sha256": "aea041e3a6ced0ab872c12eebe383380bf735132c039cbb876a94c2034a85489",
          "sha1": "0bc788c079811da71744beb5c08e4514c27c1948",
          "md5": "2e40821b4cdb8a1491583e1b453f6f8a"
        }
      ]
    }
  ]
}
