{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.1.jar",
          "url": "runelite-jshell-4.20.1.jar",
          "size": 26552,
          "sha512": "7b5214f0c23e4aea56202a5eeb9ee77a3c6ece78e1bc88a51b1c8cee39c4733f15300bfe930f5fc0c66834265699794c69a0a29bcc8560cb056b0f9652f613f5",
          "sha256": "391c9e1d5f63d755429232000342d983c5642c660a4de2984f401e674674045c",
          "sha1": "60114455974c8736c807654872f8b9f8b096f473",
          "md5": "a80ed6d43d390c6cc2bb338c145d84b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.1.jar",
          "url": "runelite-jshell-4.20.1.jar",
          "size": 26552,
          "sha512": "7b5214f0c23e4aea56202a5eeb9ee77a3c6ece78e1bc88a51b1c8cee39c4733f15300bfe930f5fc0c66834265699794c69a0a29bcc8560cb056b0f9652f613f5",
          "sha256": "391c9e1d5f63d755429232000342d983c5642c660a4de2984f401e674674045c",
          "sha1": "60114455974c8736c807654872f8b9f8b096f473",
          "md5": "a80ed6d43d390c6cc2bb338c145d84b0"
        }
      ]
    }
  ]
}
