{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.1.jar",
          "url": "runelite-jshell-4.20.1.jar",
          "size": 26552,
          "sha512": "99e841dcf00dd3733b79316bbad551b75d8d10c08cc285bdc18a1a09755da37159f3056d8939f14c8b7477d79a38cf132ca88e98c66f36a94b3805af1b13ec39",
          "sha256": "49a8c60f71c792c18c6205439781155b1c62eb828bf210830eb5c5be6965d6eb",
          "sha1": "fffa908cefb04d1061fb2bdad74d20f633c7210c",
          "md5": "eea03356dd0ddff50eede7e7acce5b05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.1.jar",
          "url": "runelite-jshell-4.20.1.jar",
          "size": 26552,
          "sha512": "99e841dcf00dd3733b79316bbad551b75d8d10c08cc285bdc18a1a09755da37159f3056d8939f14c8b7477d79a38cf132ca88e98c66f36a94b3805af1b13ec39",
          "sha256": "49a8c60f71c792c18c6205439781155b1c62eb828bf210830eb5c5be6965d6eb",
          "sha1": "fffa908cefb04d1061fb2bdad74d20f633c7210c",
          "md5": "eea03356dd0ddff50eede7e7acce5b05"
        }
      ]
    }
  ]
}
