{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.13.3.jar",
          "url": "http-api-4.13.3.jar",
          "size": 172797,
          "sha512": "3a30f9dbc8eaa25af056a520f3e26a67178f3caece4c480fbee4b705a50278a925c72fbe5474c97a86d0fbf9facfb00b63c8ded2721e64301b31f9b3815f9bab",
          "sha256": "5bca8ec573dcde1f0afd80f93cc3cfb46afff49f9504da687b53a5b90d756cf8",
          "sha1": "bc231bc8d868ffd6e4cb97050803b1724a39966e",
          "md5": "ac0949c28c0180ea0e2e86d838b12140"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.13.3.jar",
          "url": "http-api-4.13.3.jar",
          "size": 172797,
          "sha512": "3a30f9dbc8eaa25af056a520f3e26a67178f3caece4c480fbee4b705a50278a925c72fbe5474c97a86d0fbf9facfb00b63c8ded2721e64301b31f9b3815f9bab",
          "sha256": "5bca8ec573dcde1f0afd80f93cc3cfb46afff49f9504da687b53a5b90d756cf8",
          "sha1": "bc231bc8d868ffd6e4cb97050803b1724a39966e",
          "md5": "ac0949c28c0180ea0e2e86d838b12140"
        }
      ]
    }
  ]
}
