{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "e2b3df71daf72e153df277fb948613f10158c52999854006a792e51e122e279ba3eae0333adb2a698aa67892a9213075fe2c90f7cc8dcc849c31d2b0a25639c8",
          "sha256": "07e7195acd102d03eb690dc758b5bdf22cc5e23684e97a263202795246ed900f",
          "sha1": "e9a69cab8bf56018556fbf69ddf80ce38a9cc25a",
          "md5": "20d92f5b3bc1d087024f0148d6004a8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "e2b3df71daf72e153df277fb948613f10158c52999854006a792e51e122e279ba3eae0333adb2a698aa67892a9213075fe2c90f7cc8dcc849c31d2b0a25639c8",
          "sha256": "07e7195acd102d03eb690dc758b5bdf22cc5e23684e97a263202795246ed900f",
          "sha1": "e9a69cab8bf56018556fbf69ddf80ce38a9cc25a",
          "md5": "20d92f5b3bc1d087024f0148d6004a8f"
        }
      ]
    }
  ]
}
