{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "9ad09ef5a893f777b7e0821b9665e1c5a85ab864f544198cff3761163bef2191306177c736a3cada7d714f6b6f3a1de0ebfecf6c1a040b8aebd5738a4c20e25c",
          "sha256": "1580225f3f9d25d6dd2f229de50b29925149acc47b09f4f386e3f4c3cd1c829e",
          "sha1": "1d7500e20adaccef847ace0e52f79661a31d3c57",
          "md5": "99be82505fa913f33733041edb8ecd8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "9ad09ef5a893f777b7e0821b9665e1c5a85ab864f544198cff3761163bef2191306177c736a3cada7d714f6b6f3a1de0ebfecf6c1a040b8aebd5738a4c20e25c",
          "sha256": "1580225f3f9d25d6dd2f229de50b29925149acc47b09f4f386e3f4c3cd1c829e",
          "sha1": "1d7500e20adaccef847ace0e52f79661a31d3c57",
          "md5": "99be82505fa913f33733041edb8ecd8b"
        }
      ]
    }
  ]
}
