{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "bb281b59d4fd996c749a168c45f0efba34d1835fc746a28824d4e4a8664a3b165633616fa91e54fe44dc900d2f2e40a389cf625f963bba5c8477f3536a6c6031",
          "sha256": "c9688ac08ac53e4ef7deb137d282fcc2e081b824dde0e43f3f43af2e390d3bd0",
          "sha1": "51d089b30a51693a3c632c6460296f5ee479ae69",
          "md5": "e51bc594bcf3b3432132d9e9de8e8067"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.2.jar",
          "url": "runescape-api-4.31.2.jar",
          "size": 150312,
          "sha512": "bb281b59d4fd996c749a168c45f0efba34d1835fc746a28824d4e4a8664a3b165633616fa91e54fe44dc900d2f2e40a389cf625f963bba5c8477f3536a6c6031",
          "sha256": "c9688ac08ac53e4ef7deb137d282fcc2e081b824dde0e43f3f43af2e390d3bd0",
          "sha1": "51d089b30a51693a3c632c6460296f5ee479ae69",
          "md5": "e51bc594bcf3b3432132d9e9de8e8067"
        }
      ]
    }
  ]
}
