{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.0.jar",
          "url": "runelite-jshell-4.18.0.jar",
          "size": 26552,
          "sha512": "236866bcd0faad754fe79465952e6c060322f97b05e3fa86a2c18d3c4bd53617a1206c06a41e9cfa1cf05d03d98fe50a5aa04b480c3362f5fceee419e9ca9d47",
          "sha256": "184d8a3a790942ebe63c0a1e363fee347c8dcd22e79a58cf2721e527438bd7b9",
          "sha1": "bc669ceedee8f3c53347935a7220cf798d52267f",
          "md5": "fbfa196aa72a617750eea1ef14456f2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.0.jar",
          "url": "runelite-jshell-4.18.0.jar",
          "size": 26552,
          "sha512": "236866bcd0faad754fe79465952e6c060322f97b05e3fa86a2c18d3c4bd53617a1206c06a41e9cfa1cf05d03d98fe50a5aa04b480c3362f5fceee419e9ca9d47",
          "sha256": "184d8a3a790942ebe63c0a1e363fee347c8dcd22e79a58cf2721e527438bd7b9",
          "sha1": "bc669ceedee8f3c53347935a7220cf798d52267f",
          "md5": "fbfa196aa72a617750eea1ef14456f2f"
        }
      ]
    }
  ]
}
