{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.0.jar",
          "url": "runelite-jshell-4.18.0.jar",
          "size": 26552,
          "sha512": "b6c1516e2f00ada346b6f77888a75069eb52c8682ec90439b57eea49a9b4c90ac917c69fc6a3c6f1fd09083ab4c4e840f6788e2fed7dc3f22dac3d56c0d14042",
          "sha256": "c1853bbe4c560ff980b972a350a0500f3b75cf2abdc37d89aee7ce126fc74867",
          "sha1": "3fb2790ed904bd0227a356e4d14fb8993a8e65df",
          "md5": "89bdae4e494ad077ed334ebbec6dca0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.0.jar",
          "url": "runelite-jshell-4.18.0.jar",
          "size": 26552,
          "sha512": "b6c1516e2f00ada346b6f77888a75069eb52c8682ec90439b57eea49a9b4c90ac917c69fc6a3c6f1fd09083ab4c4e840f6788e2fed7dc3f22dac3d56c0d14042",
          "sha256": "c1853bbe4c560ff980b972a350a0500f3b75cf2abdc37d89aee7ce126fc74867",
          "sha1": "3fb2790ed904bd0227a356e4d14fb8993a8e65df",
          "md5": "89bdae4e494ad077ed334ebbec6dca0f"
        }
      ]
    }
  ]
}
