{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.1.jar",
          "url": "runelite-api-4.15.1.jar",
          "size": 1331713,
          "sha512": "047a68bce7b84c9190c8b29d460a0da08495298680be9dc6469f4c558d84e71cdfd30b8530a5ed4042ee3fde705a93485ea239e689c264889971e2d58021c1ef",
          "sha256": "18967c4367698b08e96c9ebe0e7677e7a05f5074cf70a1222fa2adf825eb250a",
          "sha1": "748a1cffc46dff6808c25525fdd424e3bc379cd3",
          "md5": "a544fe5facc6817025c41341aa9a2e32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.1.jar",
          "url": "runelite-api-4.15.1.jar",
          "size": 1331713,
          "sha512": "047a68bce7b84c9190c8b29d460a0da08495298680be9dc6469f4c558d84e71cdfd30b8530a5ed4042ee3fde705a93485ea239e689c264889971e2d58021c1ef",
          "sha256": "18967c4367698b08e96c9ebe0e7677e7a05f5074cf70a1222fa2adf825eb250a",
          "sha1": "748a1cffc46dff6808c25525fdd424e3bc379cd3",
          "md5": "a544fe5facc6817025c41341aa9a2e32"
        }
      ]
    }
  ]
}
