{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.1.jar",
          "url": "runelite-api-4.15.1.jar",
          "size": 1331713,
          "sha512": "4646c03dec195518d0a6d0f9ecb18908676b518ffacec06e26455c9998607fb5bab54f0821bf819a1399622df29a465172aa0250a48259328d1f7777bf2fbfa5",
          "sha256": "7642e6758175cdb4ac45392713251ae009bb7c59e98b4f1f05cffa5f03600843",
          "sha1": "a4f9b05e0098b5c3e73c36176f018620c79d9746",
          "md5": "cbe31e06fd7d5433ec97a39b72a485c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.1.jar",
          "url": "runelite-api-4.15.1.jar",
          "size": 1331713,
          "sha512": "4646c03dec195518d0a6d0f9ecb18908676b518ffacec06e26455c9998607fb5bab54f0821bf819a1399622df29a465172aa0250a48259328d1f7777bf2fbfa5",
          "sha256": "7642e6758175cdb4ac45392713251ae009bb7c59e98b4f1f05cffa5f03600843",
          "sha1": "a4f9b05e0098b5c3e73c36176f018620c79d9746",
          "md5": "cbe31e06fd7d5433ec97a39b72a485c2"
        }
      ]
    }
  ]
}
