{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.1.jar",
          "url": "runelite-api-4.15.1.jar",
          "size": 1331713,
          "sha512": "2c64380ffb5fb4657c7cc1e52d84c602fdcd0c8e46f21cffb377a55e3794c38edaf6f0ba32f9c8ccaf4029887215df1bf179faae68c43ead24714349b1c0353a",
          "sha256": "7a8f2aec5d3cd44f9a485257bff2a1f1698e58be4a13e88fb7bb7523f6b3f5c9",
          "sha1": "78fd729a73dbe9da2d6112df43ab71f7f23121b4",
          "md5": "3cce09855eac6a1193c6a42624987249"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.1.jar",
          "url": "runelite-api-4.15.1.jar",
          "size": 1331713,
          "sha512": "2c64380ffb5fb4657c7cc1e52d84c602fdcd0c8e46f21cffb377a55e3794c38edaf6f0ba32f9c8ccaf4029887215df1bf179faae68c43ead24714349b1c0353a",
          "sha256": "7a8f2aec5d3cd44f9a485257bff2a1f1698e58be4a13e88fb7bb7523f6b3f5c9",
          "sha1": "78fd729a73dbe9da2d6112df43ab71f7f23121b4",
          "md5": "3cce09855eac6a1193c6a42624987249"
        }
      ]
    }
  ]
}
