{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.0.jar",
          "url": "runelite-api-4.31.0.jar",
          "size": 1362036,
          "sha512": "23790621ad3411816b5a3b05d7db6144b64d5758cbff936d3d76e5eec5201bab5ff5a3e71d8deb9b3510dc4487df1c982fa41940d24f5a80d9a63a06fd45dda5",
          "sha256": "97dd1ea95efca25e971b750c6790e68dec0b71dfdf1bf3a3ba11aa3b0179040e",
          "sha1": "ac7f1b834df1cd3541a314968a0fc765da5afc15",
          "md5": "914c0c41ca61fc690e864839df5186e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.0.jar",
          "url": "runelite-api-4.31.0.jar",
          "size": 1362036,
          "sha512": "23790621ad3411816b5a3b05d7db6144b64d5758cbff936d3d76e5eec5201bab5ff5a3e71d8deb9b3510dc4487df1c982fa41940d24f5a80d9a63a06fd45dda5",
          "sha256": "97dd1ea95efca25e971b750c6790e68dec0b71dfdf1bf3a3ba11aa3b0179040e",
          "sha1": "ac7f1b834df1cd3541a314968a0fc765da5afc15",
          "md5": "914c0c41ca61fc690e864839df5186e1"
        }
      ]
    }
  ]
}
