{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.0.jar",
          "url": "runelite-api-4.31.0.jar",
          "size": 1362036,
          "sha512": "3c3932f38c4e4c0853718944f382fd9777aa64ae159dd64ce73b81ab56ec45dc807c870d4a15ab51b6acb8675ccc637f8699495212e4509853b3b9637abe0bb2",
          "sha256": "161b6a5a110218f767a380b38d1ad90a953cc8deb172c9f6c268065919328bb9",
          "sha1": "24e52bb89953a909a089e0f8f420ccd6cefeaf8d",
          "md5": "1737cafdcc8e074fc885605da2bb5ec4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.0.jar",
          "url": "runelite-api-4.31.0.jar",
          "size": 1362036,
          "sha512": "3c3932f38c4e4c0853718944f382fd9777aa64ae159dd64ce73b81ab56ec45dc807c870d4a15ab51b6acb8675ccc637f8699495212e4509853b3b9637abe0bb2",
          "sha256": "161b6a5a110218f767a380b38d1ad90a953cc8deb172c9f6c268065919328bb9",
          "sha1": "24e52bb89953a909a089e0f8f420ccd6cefeaf8d",
          "md5": "1737cafdcc8e074fc885605da2bb5ec4"
        }
      ]
    }
  ]
}
