{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99210,
          "sha512": "a635bbad4690605d512aa76e2e943fbbd4be3f0e1589458e03349b8a0097d797481caf6686a8fca8fc2eab23a9af3ff17a6b2ed954d8be60b5a74e4e69eecdf7",
          "sha256": "72f8be564d5117bf0e40cde209b46e727de902eff4ddd692431c212672ab3ea5",
          "sha1": "0a84d4e2b9dd26d15498fa4efc1969b42c161187",
          "md5": "d6269436f5471088dadfd66a4e07293a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99210,
          "sha512": "a635bbad4690605d512aa76e2e943fbbd4be3f0e1589458e03349b8a0097d797481caf6686a8fca8fc2eab23a9af3ff17a6b2ed954d8be60b5a74e4e69eecdf7",
          "sha256": "72f8be564d5117bf0e40cde209b46e727de902eff4ddd692431c212672ab3ea5",
          "sha1": "0a84d4e2b9dd26d15498fa4efc1969b42c161187",
          "md5": "d6269436f5471088dadfd66a4e07293a"
        }
      ]
    }
  ]
}
