{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99204,
          "sha512": "44bb10ef431f49ff82b65eaccdf35e1685b813ca040501759899c845496e2f65d05483ab9aea5f19f82cd0c98b33d07b716ff8ab14b83a57ccd6eb6d1fbf291d",
          "sha256": "bb7d9862b638864833db683bc34945985e745077152f86269cf099a347d6c330",
          "sha1": "ddd9f7be0df4fa17d398e96ed4626acc63b6e52a",
          "md5": "c604c2a060bb9579071c726e0a4b0de9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 99204,
          "sha512": "44bb10ef431f49ff82b65eaccdf35e1685b813ca040501759899c845496e2f65d05483ab9aea5f19f82cd0c98b33d07b716ff8ab14b83a57ccd6eb6d1fbf291d",
          "sha256": "bb7d9862b638864833db683bc34945985e745077152f86269cf099a347d6c330",
          "sha1": "ddd9f7be0df4fa17d398e96ed4626acc63b6e52a",
          "md5": "c604c2a060bb9579071c726e0a4b0de9"
        }
      ]
    }
  ]
}
