{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "817242971562b146cb2e1ef0981bc46ed21827fe45c9c9d49a6b65a98f26ae6142a7d6133ce2e71035f94fe3f3d82b26f48954f17c8c3e1bdd3448877a7d0f3f",
          "sha256": "721c787a4210acad569e5097f1dcd5385a304af73a441e76ed6ba2534d9c5111",
          "sha1": "ee6bc7a33656108bcc76d9d23f3ee2961c62a2d3",
          "md5": "c58f6d02be03150b8d1cfdd2a5cbc41a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "817242971562b146cb2e1ef0981bc46ed21827fe45c9c9d49a6b65a98f26ae6142a7d6133ce2e71035f94fe3f3d82b26f48954f17c8c3e1bdd3448877a7d0f3f",
          "sha256": "721c787a4210acad569e5097f1dcd5385a304af73a441e76ed6ba2534d9c5111",
          "sha1": "ee6bc7a33656108bcc76d9d23f3ee2961c62a2d3",
          "md5": "c58f6d02be03150b8d1cfdd2a5cbc41a"
        }
      ]
    }
  ]
}
