{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "1af004f93ea60dcbab921e6f4504c3af44c783163d31485a4485a789fc5c0e7e42dc2f61df5514f0c0bb101c4f744102a0133138ae8834ad7824475d63e4e844",
          "sha256": "7998ed75f9ed8291e8154e17faa336e6482e7058c5b5a06c6db9e59ec7e24f10",
          "sha1": "697bd6947f7531051116ebb00c47b16ec38fe214",
          "md5": "8ed4e862a6fe97ef219c40605cccdc9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "1af004f93ea60dcbab921e6f4504c3af44c783163d31485a4485a789fc5c0e7e42dc2f61df5514f0c0bb101c4f744102a0133138ae8834ad7824475d63e4e844",
          "sha256": "7998ed75f9ed8291e8154e17faa336e6482e7058c5b5a06c6db9e59ec7e24f10",
          "sha1": "697bd6947f7531051116ebb00c47b16ec38fe214",
          "md5": "8ed4e862a6fe97ef219c40605cccdc9c"
        }
      ]
    }
  ]
}
