{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "42e6dabbd5f879022d5d5169bc7d1815e5aab611d77c595a9d22322248c3a203da745d560b7f4171f49e031803fe23397c505c8add1993c9f1541b76d04a10a1",
          "sha256": "f340a02d35f9a95d7b7bf549e5fd9411a96a5c4921358eacf4b1806bbbb123c6",
          "sha1": "e9a96c8909cac20a550dc347ed0959f897d194c4",
          "md5": "eb6995e39e2ed534fb698bc42b31f5d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.3.jar",
          "url": "runelite-jshell-4.15.3.jar",
          "size": 26552,
          "sha512": "42e6dabbd5f879022d5d5169bc7d1815e5aab611d77c595a9d22322248c3a203da745d560b7f4171f49e031803fe23397c505c8add1993c9f1541b76d04a10a1",
          "sha256": "f340a02d35f9a95d7b7bf549e5fd9411a96a5c4921358eacf4b1806bbbb123c6",
          "sha1": "e9a96c8909cac20a550dc347ed0959f897d194c4",
          "md5": "eb6995e39e2ed534fb698bc42b31f5d1"
        }
      ]
    }
  ]
}
