{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.7.jar",
          "url": "runescape-api-4.15.7.jar",
          "size": 143805,
          "sha512": "c90c25c8d3d0996524506da3c13a1f4a50ae0b5962676680f152bdcc32de741db5d20381278310e7b8b9816dfce46bfabd3f1007002b8352ffeca7dfadad7ca7",
          "sha256": "74074fc7382c860e1d282cd65c13193fee5d85eb51994a5aaa2eb13de8663a4c",
          "sha1": "688b24b9063ffee7040aec49630ff090f9e1adb4",
          "md5": "2fc5b9f55693d4bce9603c8d8e77b8ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.7.jar",
          "url": "runescape-api-4.15.7.jar",
          "size": 143805,
          "sha512": "c90c25c8d3d0996524506da3c13a1f4a50ae0b5962676680f152bdcc32de741db5d20381278310e7b8b9816dfce46bfabd3f1007002b8352ffeca7dfadad7ca7",
          "sha256": "74074fc7382c860e1d282cd65c13193fee5d85eb51994a5aaa2eb13de8663a4c",
          "sha1": "688b24b9063ffee7040aec49630ff090f9e1adb4",
          "md5": "2fc5b9f55693d4bce9603c8d8e77b8ed"
        }
      ]
    }
  ]
}
