{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.1.jar",
          "url": "runescape-api-4.20.1.jar",
          "size": 148390,
          "sha512": "4b2f1224b10cfd4b3700228ae21b645724a5ab0b60ed6ac331233a0fac00867b10497b35554cad98cd745ba12b0b311043d1c99295b848cbbcb48dc8feaa9f43",
          "sha256": "2a08bdee0a77527e2be6329a6b1d11531e91aa3ed7c694bd846464494c81cd89",
          "sha1": "718ac0bc6d118dabc68debf5bea567e2cfc22f81",
          "md5": "19fa502e804319c80036fb12c8acae5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.1.jar",
          "url": "runescape-api-4.20.1.jar",
          "size": 148390,
          "sha512": "4b2f1224b10cfd4b3700228ae21b645724a5ab0b60ed6ac331233a0fac00867b10497b35554cad98cd745ba12b0b311043d1c99295b848cbbcb48dc8feaa9f43",
          "sha256": "2a08bdee0a77527e2be6329a6b1d11531e91aa3ed7c694bd846464494c81cd89",
          "sha1": "718ac0bc6d118dabc68debf5bea567e2cfc22f81",
          "md5": "19fa502e804319c80036fb12c8acae5a"
        }
      ]
    }
  ]
}
