{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.1.jar",
          "url": "runescape-api-4.20.1.jar",
          "size": 148390,
          "sha512": "b7e798808ba1beb73d92272cf002193d377bdafaf86f0dc5f803bf91141d518a328670086ffb4d7cde554db4a63723342a6a7058b17db1bc0e2fb316af82e6a3",
          "sha256": "0fd9d8c4f8edb7f4d8766648139f95b0867b14c1a0a3f82553be4f805f01535e",
          "sha1": "2f7df2ce0953712b6707deaa3850473131bc9fd6",
          "md5": "b87720f54e5504cc4499aa2146f0399a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.1.jar",
          "url": "runescape-api-4.20.1.jar",
          "size": 148390,
          "sha512": "b7e798808ba1beb73d92272cf002193d377bdafaf86f0dc5f803bf91141d518a328670086ffb4d7cde554db4a63723342a6a7058b17db1bc0e2fb316af82e6a3",
          "sha256": "0fd9d8c4f8edb7f4d8766648139f95b0867b14c1a0a3f82553be4f805f01535e",
          "sha1": "2f7df2ce0953712b6707deaa3850473131bc9fd6",
          "md5": "b87720f54e5504cc4499aa2146f0399a"
        }
      ]
    }
  ]
}
