{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 99203,
          "sha512": "fd404bea8f01bb9c03971f6c1a65eb9153de0b9878976b293f335f68933b3e269b47480c8d06895c1d96011aebf1fd37043fdaed0292e6f9705c0f4110c2c850",
          "sha256": "1f408319f99cac8d3692f7945105b9168508bbc406b33da950a0dc10794c8f08",
          "sha1": "ee3ae3b97565dbf2c5b8112f09831e3e80a0478f",
          "md5": "68dbcf4581b7c6413f4461e95783a346"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 99203,
          "sha512": "fd404bea8f01bb9c03971f6c1a65eb9153de0b9878976b293f335f68933b3e269b47480c8d06895c1d96011aebf1fd37043fdaed0292e6f9705c0f4110c2c850",
          "sha256": "1f408319f99cac8d3692f7945105b9168508bbc406b33da950a0dc10794c8f08",
          "sha1": "ee3ae3b97565dbf2c5b8112f09831e3e80a0478f",
          "md5": "68dbcf4581b7c6413f4461e95783a346"
        }
      ]
    }
  ]
}
