{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 99203,
          "sha512": "a2286f3314eb81a9da660f76f5fecf4fba2dc77981630dda36ab44dc60f387674b9cf8c4be8277bbd65c9106ee810aa15b1f1c3b9ee312b0ca0e01d93669b1d0",
          "sha256": "9fa82c76247508d0e457f435b0fe09cac78c4f59fb76acff5ab3f2b049b7f1b3",
          "sha1": "58065bb85eefc48c80e975b97366b4059bf2c50a",
          "md5": "ef0aaac26f6d225fe72858e4c82cb117"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 99203,
          "sha512": "a2286f3314eb81a9da660f76f5fecf4fba2dc77981630dda36ab44dc60f387674b9cf8c4be8277bbd65c9106ee810aa15b1f1c3b9ee312b0ca0e01d93669b1d0",
          "sha256": "9fa82c76247508d0e457f435b0fe09cac78c4f59fb76acff5ab3f2b049b7f1b3",
          "sha1": "58065bb85eefc48c80e975b97366b4059bf2c50a",
          "md5": "ef0aaac26f6d225fe72858e4c82cb117"
        }
      ]
    }
  ]
}
