{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335036,
          "sha512": "7270f48701267087424826aa5bea96d099b50f9f075693e3273a1ea30d251d3466f426344ef8a47f2e03bd4e5ee18be851ebfc580ef41fadfb13c0f4da9b5d42",
          "sha256": "c110baf8281e39a8afdb433a8b7652b35dc27b5154358483a21ec1d9c962da64",
          "sha1": "bbba535bf8316de35dda57ecd8d6596d35649352",
          "md5": "63442f794050e9f6d738831bdef76517"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.17.1.jar",
          "url": "runelite-api-4.17.1.jar",
          "size": 1335036,
          "sha512": "7270f48701267087424826aa5bea96d099b50f9f075693e3273a1ea30d251d3466f426344ef8a47f2e03bd4e5ee18be851ebfc580ef41fadfb13c0f4da9b5d42",
          "sha256": "c110baf8281e39a8afdb433a8b7652b35dc27b5154358483a21ec1d9c962da64",
          "sha1": "bbba535bf8316de35dda57ecd8d6596d35649352",
          "md5": "63442f794050e9f6d738831bdef76517"
        }
      ]
    }
  ]
}
