{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.5.6.jar",
          "url": "runescape-api-4.5.6.jar",
          "size": 107719,
          "sha512": "06299931ecf4a6f144bdd2e5c96cbe4957d6037891fdc3403ca7a1cb9c229b5a1ed199642c58fc7fb5de64a7d9bb3f997bd3d6aeedb2d272a2ba39499d9738e7",
          "sha256": "d9c836ec7aff8b1a597ccd8655e54fd23be408b36e46038e792671841d082660",
          "sha1": "11a149bfc33c715e1164c8d2411d9396e0dcb2db",
          "md5": "5e41049dc960fa4851d3058ec9da2886"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.5.6.jar",
          "url": "runescape-api-4.5.6.jar",
          "size": 107719,
          "sha512": "06299931ecf4a6f144bdd2e5c96cbe4957d6037891fdc3403ca7a1cb9c229b5a1ed199642c58fc7fb5de64a7d9bb3f997bd3d6aeedb2d272a2ba39499d9738e7",
          "sha256": "d9c836ec7aff8b1a597ccd8655e54fd23be408b36e46038e792671841d082660",
          "sha1": "11a149bfc33c715e1164c8d2411d9396e0dcb2db",
          "md5": "5e41049dc960fa4851d3058ec9da2886"
        }
      ]
    }
  ]
}
