{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "56stvg6vpff2jn5hcncetngajy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.1.0.jar",
          "url": "runelite-api-4.1.0.jar",
          "size": 1249356,
          "sha512": "59172bd41325ea1a645f783664280a86dc77219e9e9917bc0d575ce106ab76e14dfda9123a537495779bf0dc9727f5400b5a873e65664e708f1d9b576a0c8b38",
          "sha256": "9d9cae2304100689a73fc596ce2c7a9a0fee17709cc92af4a42fb4412fe48746",
          "sha1": "9e66996d0362f6d6920c0879a502bebfc5c8bfaa",
          "md5": "e9a7f243f12748f90f3bc3b0e26d40b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.1.0.jar",
          "url": "runelite-api-4.1.0.jar",
          "size": 1249356,
          "sha512": "59172bd41325ea1a645f783664280a86dc77219e9e9917bc0d575ce106ab76e14dfda9123a537495779bf0dc9727f5400b5a873e65664e708f1d9b576a0c8b38",
          "sha256": "9d9cae2304100689a73fc596ce2c7a9a0fee17709cc92af4a42fb4412fe48746",
          "sha1": "9e66996d0362f6d6920c0879a502bebfc5c8bfaa",
          "md5": "e9a7f243f12748f90f3bc3b0e26d40b0"
        }
      ]
    }
  ]
}
