{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.0.jar",
          "url": "runescape-api-4.31.0.jar",
          "size": 150296,
          "sha512": "92d3607ec5f1450166f23fe3f1fcbc59748e09ce1848a3cc8ea364054ab7f88b2310983054ce73c4d422e97fdcadd7611d7764c8240c6e5d35eae9b647942c48",
          "sha256": "238b0e3b825bec4ab716f3dddea0ee0da1ea719454b6854f9cefef8142b39d2c",
          "sha1": "00f4a18ea3db45cfbf366f02ef16b2854621cfaf",
          "md5": "85832c0769e9ad969689a8ea1ae6eb67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.31.0.jar",
          "url": "runescape-api-4.31.0.jar",
          "size": 150296,
          "sha512": "92d3607ec5f1450166f23fe3f1fcbc59748e09ce1848a3cc8ea364054ab7f88b2310983054ce73c4d422e97fdcadd7611d7764c8240c6e5d35eae9b647942c48",
          "sha256": "238b0e3b825bec4ab716f3dddea0ee0da1ea719454b6854f9cefef8142b39d2c",
          "sha1": "00f4a18ea3db45cfbf366f02ef16b2854621cfaf",
          "md5": "85832c0769e9ad969689a8ea1ae6eb67"
        }
      ]
    }
  ]
}
