{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.0.jar",
          "url": "http-api-4.15.0.jar",
          "size": 172799,
          "sha512": "7f208c20fd541226815395bb1f61fda6c5163deacb7531fc0b1b665142752412d7ba777317e5bbe471b63f43599d4e1179c5aea786e87167b8e77848e0021c72",
          "sha256": "2aa7d6a4573f93a58fd586c8ff957508d6ec0cb901261718b6cc0550e6183844",
          "sha1": "4a65adfe6d2bdc3bc07cc22cf93b44332b30caa9",
          "md5": "a0b371f0821a166bd6f0c71594e8147f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.0.jar",
          "url": "http-api-4.15.0.jar",
          "size": 172799,
          "sha512": "7f208c20fd541226815395bb1f61fda6c5163deacb7531fc0b1b665142752412d7ba777317e5bbe471b63f43599d4e1179c5aea786e87167b8e77848e0021c72",
          "sha256": "2aa7d6a4573f93a58fd586c8ff957508d6ec0cb901261718b6cc0550e6183844",
          "sha1": "4a65adfe6d2bdc3bc07cc22cf93b44332b30caa9",
          "md5": "a0b371f0821a166bd6f0c71594e8147f"
        }
      ]
    }
  ]
}
