{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0.jar",
          "url": "runescape-api-4.27.0.jar",
          "size": 150217,
          "sha512": "3b861b2470a189edbebeb3c5f0f77ddee7d2b26c689cc25ee7ee4d3af8af5305cff34f8b1ae7e756e0c404fc65905b1fef1f160b091f724d93a4853b5be6466b",
          "sha256": "23ccd537f6f267768215cb7ed882011d753b4916508577788df436c5c41e2cb7",
          "sha1": "29b86feafec5adb06291ae0ce9ffd05ec01dc1ea",
          "md5": "e780f7be06a9765e4a08694b5fc9f816"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0.jar",
          "url": "runescape-api-4.27.0.jar",
          "size": 150217,
          "sha512": "3b861b2470a189edbebeb3c5f0f77ddee7d2b26c689cc25ee7ee4d3af8af5305cff34f8b1ae7e756e0c404fc65905b1fef1f160b091f724d93a4853b5be6466b",
          "sha256": "23ccd537f6f267768215cb7ed882011d753b4916508577788df436c5c41e2cb7",
          "sha1": "29b86feafec5adb06291ae0ce9ffd05ec01dc1ea",
          "md5": "e780f7be06a9765e4a08694b5fc9f816"
        }
      ]
    }
  ]
}
