{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.7.jar",
          "url": "runelite-jshell-4.15.7.jar",
          "size": 26552,
          "sha512": "8217f429a5b864a5a90f3933415e13fa675115f36f7d9b6761a42978adcafbcf7ae9cc1eea394754cf3ad710541888f0f17c897e7e7db7cc5a4966e4e3e077b9",
          "sha256": "705feaec41e71dba2cf3bf035fc05d37765717552bd5b37f018f2660316a9b7f",
          "sha1": "5c142d683a4d248446184e786901193e3ab8a952",
          "md5": "6b696d3a864e2bb2fdcf479ce4bfcf00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.7.jar",
          "url": "runelite-jshell-4.15.7.jar",
          "size": 26552,
          "sha512": "8217f429a5b864a5a90f3933415e13fa675115f36f7d9b6761a42978adcafbcf7ae9cc1eea394754cf3ad710541888f0f17c897e7e7db7cc5a4966e4e3e077b9",
          "sha256": "705feaec41e71dba2cf3bf035fc05d37765717552bd5b37f018f2660316a9b7f",
          "sha1": "5c142d683a4d248446184e786901193e3ab8a952",
          "md5": "6b696d3a864e2bb2fdcf479ce4bfcf00"
        }
      ]
    }
  ]
}
