{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99202,
          "sha512": "85dcb6650f28a5a2a2b30cb8e4aaa371af651182485374a5b67b32ed66c0ddaa9c1ef2c79a47d74591787b6501ad3dc02f436d372046aa099d0d067b6b3d75e5",
          "sha256": "5f1cf228122f758c03708822027c111044ac34634ff5434b64b9d60d8bb0cd32",
          "sha1": "5716070daa5bb25cc14da5ac7d535559017f1927",
          "md5": "3476b63b5227eac191951104a883951a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99202,
          "sha512": "85dcb6650f28a5a2a2b30cb8e4aaa371af651182485374a5b67b32ed66c0ddaa9c1ef2c79a47d74591787b6501ad3dc02f436d372046aa099d0d067b6b3d75e5",
          "sha256": "5f1cf228122f758c03708822027c111044ac34634ff5434b64b9d60d8bb0cd32",
          "sha1": "5716070daa5bb25cc14da5ac7d535559017f1927",
          "md5": "3476b63b5227eac191951104a883951a"
        }
      ]
    }
  ]
}
