{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "3a1ec43b844d73ebcd2bdddfd99ad42e37728006f0c8834be511989c7178d78a39059f1490c90b3c8414069279c2f9d19767a8de3b583f2b122d9da17002f638",
          "sha256": "90eda7903d9e6888c99855c78c36061331a079e1c1618bdf65804377853220e8",
          "sha1": "3e6bbbf04a57c9c9299b9900d3aa67f35446e777",
          "md5": "1a6b5ec520c310dd8ba35dcf4e1a376d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1.jar",
          "url": "http-api-4.26.1.jar",
          "size": 99210,
          "sha512": "3a1ec43b844d73ebcd2bdddfd99ad42e37728006f0c8834be511989c7178d78a39059f1490c90b3c8414069279c2f9d19767a8de3b583f2b122d9da17002f638",
          "sha256": "90eda7903d9e6888c99855c78c36061331a079e1c1618bdf65804377853220e8",
          "sha1": "3e6bbbf04a57c9c9299b9900d3aa67f35446e777",
          "md5": "1a6b5ec520c310dd8ba35dcf4e1a376d"
        }
      ]
    }
  ]
}
