{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.4.0.jar",
          "url": "http-api-4.4.0.jar",
          "size": 159718,
          "sha512": "ec87bce15f9bde153cab0dffa08a5e5a39ad6fa158bf7cc198bce3b59ad1050ba77cea2b50cfc6c3a1e92487604ba5e2045bd278361502a363167382ec4b9f2f",
          "sha256": "d8f39dcbeac2069150f9de4d68c9e63478ad57e0c7b695db162f74b34a509ece",
          "sha1": "d5acd3330bb373f860c5fe475c62e08dabc4502e",
          "md5": "011abc2bde758df0fa128c5b8e78ea4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.4.0.jar",
          "url": "http-api-4.4.0.jar",
          "size": 159718,
          "sha512": "ec87bce15f9bde153cab0dffa08a5e5a39ad6fa158bf7cc198bce3b59ad1050ba77cea2b50cfc6c3a1e92487604ba5e2045bd278361502a363167382ec4b9f2f",
          "sha256": "d8f39dcbeac2069150f9de4d68c9e63478ad57e0c7b695db162f74b34a509ece",
          "sha1": "d5acd3330bb373f860c5fe475c62e08dabc4502e",
          "md5": "011abc2bde758df0fa128c5b8e78ea4a"
        }
      ]
    }
  ]
}
