{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.21.0.jar",
          "url": "runelite-jshell-4.21.0.jar",
          "size": 26557,
          "sha512": "74b517be12e7d2c384dc525426f4cdd547dad0f70a322a86248493c818b71ca09ef62425acf375715a5addfacf4ded3f927bcb4c180798e0f9a6bb27eaf5b38d",
          "sha256": "bf1d759f52d6ee8209ffcee51964921a6438c0419da416e2d7f604a28718849d",
          "sha1": "e7c6f8ab71652e563f42b78bb1959aefc99d70c1",
          "md5": "f6f821b6089be43be185fc2cd1144cd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.21.0.jar",
          "url": "runelite-jshell-4.21.0.jar",
          "size": 26557,
          "sha512": "74b517be12e7d2c384dc525426f4cdd547dad0f70a322a86248493c818b71ca09ef62425acf375715a5addfacf4ded3f927bcb4c180798e0f9a6bb27eaf5b38d",
          "sha256": "bf1d759f52d6ee8209ffcee51964921a6438c0419da416e2d7f604a28718849d",
          "sha1": "e7c6f8ab71652e563f42b78bb1959aefc99d70c1",
          "md5": "f6f821b6089be43be185fc2cd1144cd6"
        }
      ]
    }
  ]
}
