{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.21.0.jar",
          "url": "runelite-jshell-4.21.0.jar",
          "size": 26557,
          "sha512": "de34483e41242a466a8a3118367eb258df92c690343ee676ae640b04cda03aae6a57e3cedc1a943b8ae6776841f2bba265d6574b9ee5b16653dd8e3ae95ecd23",
          "sha256": "8c67d8201d1b322b79e18bbb52c8b73d70591a7261e678b7f9802df557f6e0e1",
          "sha1": "4ce5b6ad6d739937f1c12bde08ee11c29a869847",
          "md5": "8758bd0c03305a45f1f24dec5b621946"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.21.0.jar",
          "url": "runelite-jshell-4.21.0.jar",
          "size": 26557,
          "sha512": "de34483e41242a466a8a3118367eb258df92c690343ee676ae640b04cda03aae6a57e3cedc1a943b8ae6776841f2bba265d6574b9ee5b16653dd8e3ae95ecd23",
          "sha256": "8c67d8201d1b322b79e18bbb52c8b73d70591a7261e678b7f9802df557f6e0e1",
          "sha1": "4ce5b6ad6d739937f1c12bde08ee11c29a869847",
          "md5": "8758bd0c03305a45f1f24dec5b621946"
        }
      ]
    }
  ]
}
