{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "067316f0c2cd4cdc0b93f2ae73d7736a86c59c1ef3e4f1d4bfc866bf1346f8b4450931abcd390e296f809df90c0e9f742b2a2d2edb175b42daeec29d24f5f957",
          "sha256": "653df075aee04bacec234f5d244bb957abbe5dd4014d5d79fdd91b1d24cfe190",
          "sha1": "25cf2ab7a2367d19a0755fc85a2f554b2460e434",
          "md5": "fcb799f9bf8e7b8d74a9f4b2b6efcf9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.0.jar",
          "url": "runescape-api-4.18.0.jar",
          "size": 146551,
          "sha512": "067316f0c2cd4cdc0b93f2ae73d7736a86c59c1ef3e4f1d4bfc866bf1346f8b4450931abcd390e296f809df90c0e9f742b2a2d2edb175b42daeec29d24f5f957",
          "sha256": "653df075aee04bacec234f5d244bb957abbe5dd4014d5d79fdd91b1d24cfe190",
          "sha1": "25cf2ab7a2367d19a0755fc85a2f554b2460e434",
          "md5": "fcb799f9bf8e7b8d74a9f4b2b6efcf9d"
        }
      ]
    }
  ]
}
