{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.5.6.jar",
          "url": "runescape-api-4.5.6.jar",
          "size": 107774,
          "sha512": "847d2a7fe9d9c4af73cc9d38b8cfd68a304680596ce8bf957c1efc612a1607d337468895418d5e1bedbeefc8cdee0b847c5d03dc0aa63ebbc0fb39dc8bd5c2d9",
          "sha256": "071731ee310874d8e8a50a2df7956dd7dc67f3578a66f71f8213cbfad47b9065",
          "sha1": "4a1d0b3f0bc52ea1505e272f3ec020d1620d4948",
          "md5": "b9a7b6aaf4d18509065270ea66961415"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.5.6.jar",
          "url": "runescape-api-4.5.6.jar",
          "size": 107774,
          "sha512": "847d2a7fe9d9c4af73cc9d38b8cfd68a304680596ce8bf957c1efc612a1607d337468895418d5e1bedbeefc8cdee0b847c5d03dc0aa63ebbc0fb39dc8bd5c2d9",
          "sha256": "071731ee310874d8e8a50a2df7956dd7dc67f3578a66f71f8213cbfad47b9065",
          "sha1": "4a1d0b3f0bc52ea1505e272f3ec020d1620d4948",
          "md5": "b9a7b6aaf4d18509065270ea66961415"
        }
      ]
    }
  ]
}
