{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.6.2.jar",
          "url": "http-api-4.6.2.jar",
          "size": 159717,
          "sha512": "f8300be4c80c342ebe204df90f8485713ea868984385eaec47ae5d41bcc1d1de3d9af66a42e0b52041d92656946439ec546a69b17df8387f01adf8a013ad5191",
          "sha256": "9cdf66e0ef2ce060b62a6894b667119a4025d530cf2343e385e15594b8f8558a",
          "sha1": "ef4e035dc1f0ce6a5d199bb79a52cf6152ef0095",
          "md5": "4ec0364561714ed16709d8e4e84237c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.6.2.jar",
          "url": "http-api-4.6.2.jar",
          "size": 159717,
          "sha512": "f8300be4c80c342ebe204df90f8485713ea868984385eaec47ae5d41bcc1d1de3d9af66a42e0b52041d92656946439ec546a69b17df8387f01adf8a013ad5191",
          "sha256": "9cdf66e0ef2ce060b62a6894b667119a4025d530cf2343e385e15594b8f8558a",
          "sha1": "ef4e035dc1f0ce6a5d199bb79a52cf6152ef0095",
          "md5": "4ec0364561714ed16709d8e4e84237c4"
        }
      ]
    }
  ]
}
