{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.0.jar",
          "url": "runelite-jshell-4.15.0.jar",
          "size": 26552,
          "sha512": "570f3ef4509e0540b641b042dc45824d0e4befb6b3e74e51212234e268c57e5f29822ec732ae5c84c409e4be572d040f613d889ee856ac790dd0bff54b6c073d",
          "sha256": "c522041fbf38dc53a0152a0a6d75b95b587042dc99c0bdc9fc426c8b0718032c",
          "sha1": "0051311a9f874d89a54d1507b0a8817c1be3b09e",
          "md5": "3cede3734cff572e7133dbc7861077a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.0.jar",
          "url": "runelite-jshell-4.15.0.jar",
          "size": 26552,
          "sha512": "570f3ef4509e0540b641b042dc45824d0e4befb6b3e74e51212234e268c57e5f29822ec732ae5c84c409e4be572d040f613d889ee856ac790dd0bff54b6c073d",
          "sha256": "c522041fbf38dc53a0152a0a6d75b95b587042dc99c0bdc9fc426c8b0718032c",
          "sha1": "0051311a9f874d89a54d1507b0a8817c1be3b09e",
          "md5": "3cede3734cff572e7133dbc7861077a7"
        }
      ]
    }
  ]
}
