{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99208,
          "sha512": "8da4805bf3440be542424bbb8474a86145cf3f15f74d044882eb2adcc9a35bb772247021fa3adad05744f59b1832987c6cbef9cf98809fbd41e20b9e20dec809",
          "sha256": "23cd8aa22e9607871736420616663712d17e9255d8c298933528806a8d0581b4",
          "sha1": "c9631a2456efa430f6bc61867338d75427415bfb",
          "md5": "2a501118d663189bc936f448b579b8cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99208,
          "sha512": "8da4805bf3440be542424bbb8474a86145cf3f15f74d044882eb2adcc9a35bb772247021fa3adad05744f59b1832987c6cbef9cf98809fbd41e20b9e20dec809",
          "sha256": "23cd8aa22e9607871736420616663712d17e9255d8c298933528806a8d0581b4",
          "sha1": "c9631a2456efa430f6bc61867338d75427415bfb",
          "md5": "2a501118d663189bc936f448b579b8cf"
        }
      ]
    }
  ]
}
