{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99205,
          "sha512": "c6a9fd37102a4da4f997228894e30939207ac5d1843e1d66acba4a280177e9376af56ca6346cc63406e5ff1809195f59675a8e5e90f0461d9f32fc5e60a4bd11",
          "sha256": "36ba85a0be91e90855a10bf6b9c74c1bde441c9110a1743cb6e13092ed06fbb1",
          "sha1": "c4d32fbd5bad1dd1d6b9947591eb85b2f8366168",
          "md5": "f35176f93073bd69d10b909e6d22990d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99205,
          "sha512": "c6a9fd37102a4da4f997228894e30939207ac5d1843e1d66acba4a280177e9376af56ca6346cc63406e5ff1809195f59675a8e5e90f0461d9f32fc5e60a4bd11",
          "sha256": "36ba85a0be91e90855a10bf6b9c74c1bde441c9110a1743cb6e13092ed06fbb1",
          "sha1": "c4d32fbd5bad1dd1d6b9947591eb85b2f8366168",
          "md5": "f35176f93073bd69d10b909e6d22990d"
        }
      ]
    }
  ]
}
