{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "ba3ae196019d2ee25d24263163e1235aa2fd3363dd27dd00f2f8376767fd44decb83797987a6453b5989310e9f9971a23086965781a769ac2e04fcfb61607e82",
          "sha256": "fc40e170b11805c4ba71e86ad39f653ecdd0911904e2839985ba31d203c1ccc5",
          "sha1": "6098e9898fa69799a500d11ff2cf49d6c003ac60",
          "md5": "bc5d76d56f834c9d1d14e7c4c69e668a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 99206,
          "sha512": "ba3ae196019d2ee25d24263163e1235aa2fd3363dd27dd00f2f8376767fd44decb83797987a6453b5989310e9f9971a23086965781a769ac2e04fcfb61607e82",
          "sha256": "fc40e170b11805c4ba71e86ad39f653ecdd0911904e2839985ba31d203c1ccc5",
          "sha1": "6098e9898fa69799a500d11ff2cf49d6c003ac60",
          "md5": "bc5d76d56f834c9d1d14e7c4c69e668a"
        }
      ]
    }
  ]
}
