{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.3.jar",
          "url": "http-api-4.15.3.jar",
          "size": 172791,
          "sha512": "880b531cb477231531ee468d450a489ed032fac2fc94fe95372daa9448fde09f434629178e2d5afb97dfd6b84afc484bf0be84f7f32d99093252dfc98c12127f",
          "sha256": "4e270158968aa58a83a69a70c822d3b97c5434d650d8dc2fc7ab66cc25f12ec3",
          "sha1": "9cbc3fb87b2311f9edf943240a5ccbabc7a7db22",
          "md5": "c4de32e0ddd6f17918c0c097f262cb92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.3.jar",
          "url": "http-api-4.15.3.jar",
          "size": 172791,
          "sha512": "880b531cb477231531ee468d450a489ed032fac2fc94fe95372daa9448fde09f434629178e2d5afb97dfd6b84afc484bf0be84f7f32d99093252dfc98c12127f",
          "sha256": "4e270158968aa58a83a69a70c822d3b97c5434d650d8dc2fc7ab66cc25f12ec3",
          "sha1": "9cbc3fb87b2311f9edf943240a5ccbabc7a7db22",
          "md5": "c4de32e0ddd6f17918c0c097f262cb92"
        }
      ]
    }
  ]
}
