{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.3.jar",
          "url": "http-api-4.15.3.jar",
          "size": 172791,
          "sha512": "fedf6e7bbb0670d2641b8ac86698462ff8a0fca62e34d0f319c97dba63e193796af23285d83d8fca0b51c01aa5455d79f87ba0a3eea8ff4962e59e760788bdf8",
          "sha256": "5c843b3b91df37d3ab153e8bec6e1304bb590a0de1ab7a73afc4ec7473bf78d5",
          "sha1": "36c919c0f653dd0921625db289fe451a3a4ab67b",
          "md5": "c23cbf423b789eedfb601c51fc25f080"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.3.jar",
          "url": "http-api-4.15.3.jar",
          "size": 172791,
          "sha512": "fedf6e7bbb0670d2641b8ac86698462ff8a0fca62e34d0f319c97dba63e193796af23285d83d8fca0b51c01aa5455d79f87ba0a3eea8ff4962e59e760788bdf8",
          "sha256": "5c843b3b91df37d3ab153e8bec6e1304bb590a0de1ab7a73afc4ec7473bf78d5",
          "sha1": "36c919c0f653dd0921625db289fe451a3a4ab67b",
          "md5": "c23cbf423b789eedfb601c51fc25f080"
        }
      ]
    }
  ]
}
