{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.3.jar",
          "url": "http-api-4.15.3.jar",
          "size": 172791,
          "sha512": "b98a7f412e5f00b452dd81c80878a661108ab0f79ef004abf8c05c8dfb9bbbf92860ad784a134524bdf19d8bbfa93b020c160a07d342bd6e8c641fc1d0aded2f",
          "sha256": "4a7da8e73af681edb1f36286fe198bb844a72ba0689a6abf700aaccb38c1fa8d",
          "sha1": "ef50f7b7e313061cf406812016a73a04da1eca86",
          "md5": "26b9a2ba6c811a705960005ff877e16d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.3.jar",
          "url": "http-api-4.15.3.jar",
          "size": 172791,
          "sha512": "b98a7f412e5f00b452dd81c80878a661108ab0f79ef004abf8c05c8dfb9bbbf92860ad784a134524bdf19d8bbfa93b020c160a07d342bd6e8c641fc1d0aded2f",
          "sha256": "4a7da8e73af681edb1f36286fe198bb844a72ba0689a6abf700aaccb38c1fa8d",
          "sha1": "ef50f7b7e313061cf406812016a73a04da1eca86",
          "md5": "26b9a2ba6c811a705960005ff877e16d"
        }
      ]
    }
  ]
}
