{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "a3de6168cdf1156663b07a7f065ebf86336881111419d521014c1ef55c87b3421dba3b7f200815d2dc84a445869c491ebb7e7cbe322ba591b8c60d10cae48754",
          "sha256": "7d4390b114b081365cfaaf5e98df49dbd0e49591cc9d8fec75b558c18ce175bd",
          "sha1": "24909fcee790b4c007904ad279bda1c7490db257",
          "md5": "90f08ed1b340a546309835824ec523d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "a3de6168cdf1156663b07a7f065ebf86336881111419d521014c1ef55c87b3421dba3b7f200815d2dc84a445869c491ebb7e7cbe322ba591b8c60d10cae48754",
          "sha256": "7d4390b114b081365cfaaf5e98df49dbd0e49591cc9d8fec75b558c18ce175bd",
          "sha1": "24909fcee790b4c007904ad279bda1c7490db257",
          "md5": "90f08ed1b340a546309835824ec523d4"
        }
      ]
    }
  ]
}
