{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "33058c4bfcc6ed18bd36a1faaf38464e828973e59c3f5d912ddb9f2614b940dc4c5bc0fc4ef852166b2d3c244b5af5e863480547cca39a9defbe4931b99ba90b",
          "sha256": "c6c9b345f774ab51d6aee42cd6300fc358604e5e7f305ca5fea5d1808b9e775a",
          "sha1": "aecf10d2de8f23dae6f6e5909f0b3f74dedc60d7",
          "md5": "d602bdeef904c49dcc60c015de55369a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.19.0.jar",
          "url": "runescape-api-4.19.0.jar",
          "size": 147611,
          "sha512": "33058c4bfcc6ed18bd36a1faaf38464e828973e59c3f5d912ddb9f2614b940dc4c5bc0fc4ef852166b2d3c244b5af5e863480547cca39a9defbe4931b99ba90b",
          "sha256": "c6c9b345f774ab51d6aee42cd6300fc358604e5e7f305ca5fea5d1808b9e775a",
          "sha1": "aecf10d2de8f23dae6f6e5909f0b3f74dedc60d7",
          "md5": "d602bdeef904c49dcc60c015de55369a"
        }
      ]
    }
  ]
}
