{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148377,
          "sha512": "0f392768efb3be321d841fd762c68c1811d9be35a16f8791e68b6b1571ed81f80cf42ef23bb4ea4c9a1299953c1515e31cef0aefca80004b13a249898a8d8717",
          "sha256": "eeb70a962ef948c2e7eb14f3fa614ba8b328a992a2512f532f2b34cda05dae44",
          "sha1": "1e5a83c4ba0b40562d8b5bd62bd21b0d4c2ea9df",
          "md5": "46984beab7d89d65af0ee08d5c4fb59f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148377,
          "sha512": "0f392768efb3be321d841fd762c68c1811d9be35a16f8791e68b6b1571ed81f80cf42ef23bb4ea4c9a1299953c1515e31cef0aefca80004b13a249898a8d8717",
          "sha256": "eeb70a962ef948c2e7eb14f3fa614ba8b328a992a2512f532f2b34cda05dae44",
          "sha1": "1e5a83c4ba0b40562d8b5bd62bd21b0d4c2ea9df",
          "md5": "46984beab7d89d65af0ee08d5c4fb59f"
        }
      ]
    }
  ]
}
