{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148390,
          "sha512": "574cca598fe6ea7f9309c747e45af2155ee1c496ccf7079a16c0be8a06007d135f48e228fdfe5c6e0146933d2dd46dc6dd6ac124a6a0ae6dff46e72a92576572",
          "sha256": "bd0e77a48311b19a66c3f3f7d28e11227d7d287c15e17caa20f64170ab475e7a",
          "sha1": "ead20e9bf4c899f266caf171a0470b9dc9bbf767",
          "md5": "59e0b849e373e24150a4789d3940a7fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.0.jar",
          "url": "runescape-api-4.20.0.jar",
          "size": 148390,
          "sha512": "574cca598fe6ea7f9309c747e45af2155ee1c496ccf7079a16c0be8a06007d135f48e228fdfe5c6e0146933d2dd46dc6dd6ac124a6a0ae6dff46e72a92576572",
          "sha256": "bd0e77a48311b19a66c3f3f7d28e11227d7d287c15e17caa20f64170ab475e7a",
          "sha1": "ead20e9bf4c899f266caf171a0470b9dc9bbf767",
          "md5": "59e0b849e373e24150a4789d3940a7fa"
        }
      ]
    }
  ]
}
