{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2wpr6gao4zgmjlx2a3cbc3ydny"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 131383,
          "sha512": "46b9646e668b63eb3df54ccef0446ac213be668bb67c6b19d31e58a7aedbb855b904f9972d70e9d28cb5e0bbbdd8f6f883a598531ff1ec7936d403e872d79f67",
          "sha256": "6d156a447eefa90f701769200b5ba0e8d07bdfc13a88adfec3db92db0e0bf353",
          "sha1": "0f032f70b7549d8251dd98a0ea1224ed2c8c4e8b",
          "md5": "69dbf8b9185e1ee6d6ead04cfb8adb16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.4.jar",
          "url": "http-api-3.5.4.jar",
          "size": 131383,
          "sha512": "46b9646e668b63eb3df54ccef0446ac213be668bb67c6b19d31e58a7aedbb855b904f9972d70e9d28cb5e0bbbdd8f6f883a598531ff1ec7936d403e872d79f67",
          "sha256": "6d156a447eefa90f701769200b5ba0e8d07bdfc13a88adfec3db92db0e0bf353",
          "sha1": "0f032f70b7549d8251dd98a0ea1224ed2c8c4e8b",
          "md5": "69dbf8b9185e1ee6d6ead04cfb8adb16"
        }
      ]
    }
  ]
}
