{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "cmjvc3exfjgxjaaawn65ixagdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.3.0.jar",
          "url": "runescape-api-4.3.0.jar",
          "size": 107752,
          "sha512": "6299b419256de9fc038cd544d92b9c95b0ed439dff7cf2400c6c2d1ac95f91f684c1c6d9edd94028dd089b0452ec5a818396bce2a350d4a8f970841ae973c8b8",
          "sha256": "72f21408ca30055605837e795b93f3fca87889126d113ddc72949863fefa9069",
          "sha1": "8a5ac85c58c3da272cd3c6f5529943b11858c3f4",
          "md5": "0f28dbc96806deecaee19836e3279ec7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.3.0.jar",
          "url": "runescape-api-4.3.0.jar",
          "size": 107752,
          "sha512": "6299b419256de9fc038cd544d92b9c95b0ed439dff7cf2400c6c2d1ac95f91f684c1c6d9edd94028dd089b0452ec5a818396bce2a350d4a8f970841ae973c8b8",
          "sha256": "72f21408ca30055605837e795b93f3fca87889126d113ddc72949863fefa9069",
          "sha1": "8a5ac85c58c3da272cd3c6f5529943b11858c3f4",
          "md5": "0f28dbc96806deecaee19836e3279ec7"
        }
      ]
    }
  ]
}
