{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.0.jar",
          "url": "runelite-api-4.15.0.jar",
          "size": 1331666,
          "sha512": "ee7a38254d799cdc74dbdb3cc1b63e126539db87418651e93de360eed7b18680df0ca1eace4e3a5ad0e407473cf48f5ad24946e79b7f79c00ee6fe9acdfac1ae",
          "sha256": "c89c9610ba620424c617351a6b2e2946ee5c9ce8f7473761a4984066293da8f2",
          "sha1": "5b95418f70406cefcd79dbfc945c20c0e836b106",
          "md5": "3017ea66a5bbe1c4b561fbc8f5cfe448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.0.jar",
          "url": "runelite-api-4.15.0.jar",
          "size": 1331666,
          "sha512": "ee7a38254d799cdc74dbdb3cc1b63e126539db87418651e93de360eed7b18680df0ca1eace4e3a5ad0e407473cf48f5ad24946e79b7f79c00ee6fe9acdfac1ae",
          "sha256": "c89c9610ba620424c617351a6b2e2946ee5c9ce8f7473761a4984066293da8f2",
          "sha1": "5b95418f70406cefcd79dbfc945c20c0e836b106",
          "md5": "3017ea66a5bbe1c4b561fbc8f5cfe448"
        }
      ]
    }
  ]
}
