{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "578e76e2a571decaed626850635388f3d035e93b9f5296b546b1950adb43cd9f1bb4d60bee0a25ef23146aaa954d98a31e4a8bb972d29281b597c20cdd3b2e03",
          "sha256": "cc9f987eb19656f12bff0e13d195a30c32d4f9baa3f0cbe1c1e14c051ba532b0",
          "sha1": "f4ec529c49697fc5a462a32447b193aba7869064",
          "md5": "41a998f023918caea9bd759759f46629"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "578e76e2a571decaed626850635388f3d035e93b9f5296b546b1950adb43cd9f1bb4d60bee0a25ef23146aaa954d98a31e4a8bb972d29281b597c20cdd3b2e03",
          "sha256": "cc9f987eb19656f12bff0e13d195a30c32d4f9baa3f0cbe1c1e14c051ba532b0",
          "sha1": "f4ec529c49697fc5a462a32447b193aba7869064",
          "md5": "41a998f023918caea9bd759759f46629"
        }
      ]
    }
  ]
}
