{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "1f71ab224caea7c0fe4f5761346a0a77138ad2624472e8ca9d5f4d52773d04d790a21fbd42fd0fd2e51e62c43fbc653f9f90746960a895863c59e226b9cd3c6f",
          "sha256": "bd6a12db7258508cb93b0f69999d3939e982b74f1af7b4a4af226212a486cc94",
          "sha1": "ee1e7b14110af869e7983e2bb7fdb415294e2933",
          "md5": "ec816c5d8bdfdffbde9ea2f9ece6340d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "1f71ab224caea7c0fe4f5761346a0a77138ad2624472e8ca9d5f4d52773d04d790a21fbd42fd0fd2e51e62c43fbc653f9f90746960a895863c59e226b9cd3c6f",
          "sha256": "bd6a12db7258508cb93b0f69999d3939e982b74f1af7b4a4af226212a486cc94",
          "sha1": "ee1e7b14110af869e7983e2bb7fdb415294e2933",
          "md5": "ec816c5d8bdfdffbde9ea2f9ece6340d"
        }
      ]
    }
  ]
}
