{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "552c7d267ee0e73060c7b74986b6c3769411e165364d206efaec4031af9a22c66ee4d525c2961c1baacfc94f06055272ebd9dde9851d468821940a4902495b38",
          "sha256": "98621713d95b142cffab0519b0fe819ceeef4e7e52ac39ea38f2088ea54b4948",
          "sha1": "f826a65cdc6f3b4a624aa7b661f23dfe6de2288d",
          "md5": "f8a0d5a3c2e11bf218ad0f92267813aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.2.jar",
          "url": "http-api-4.16.2.jar",
          "size": 172797,
          "sha512": "552c7d267ee0e73060c7b74986b6c3769411e165364d206efaec4031af9a22c66ee4d525c2961c1baacfc94f06055272ebd9dde9851d468821940a4902495b38",
          "sha256": "98621713d95b142cffab0519b0fe819ceeef4e7e52ac39ea38f2088ea54b4948",
          "sha1": "f826a65cdc6f3b4a624aa7b661f23dfe6de2288d",
          "md5": "f8a0d5a3c2e11bf218ad0f92267813aa"
        }
      ]
    }
  ]
}
