{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.7.jar",
          "url": "runescape-api-4.15.7.jar",
          "size": 143805,
          "sha512": "902603fca77ec73e13f4b9ebf4b5df096265f30ab53a744a18100467e9a8b52a1c36b7f86aeab51889c1ec3f7c4e32cd77b550edbb400099376561c2de98fa12",
          "sha256": "9711359a1aa72f5588257720d020309d1ce2df3b8d8138096e5f679ed5ec803b",
          "sha1": "00968b2daf35cd0d411bae139a80a49fa208f6af",
          "md5": "47411678e4fc79e16012a6d0f3afc8d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.7"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.7.jar",
          "url": "runescape-api-4.15.7.jar",
          "size": 143805,
          "sha512": "902603fca77ec73e13f4b9ebf4b5df096265f30ab53a744a18100467e9a8b52a1c36b7f86aeab51889c1ec3f7c4e32cd77b550edbb400099376561c2de98fa12",
          "sha256": "9711359a1aa72f5588257720d020309d1ce2df3b8d8138096e5f679ed5ec803b",
          "sha1": "00968b2daf35cd0d411bae139a80a49fa208f6af",
          "md5": "47411678e4fc79e16012a6d0f3afc8d8"
        }
      ]
    }
  ]
}
