{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.16.2.jar",
          "url": "runelite-client-4.16.2.jar",
          "size": 9633551,
          "sha512": "47cd1315c6d9c1aa142056d40474d1046f80436da11ccba01aed5f8f429e1ef1e2944c2a3bcb4f69380ca920c4bd7fb0c5b8a6a04644cb945ae8c6cb2f71b884",
          "sha256": "3ca7fa1a821fe24badd4c42e983628acd6aa8913e03d098a8c597123ad6c15e4",
          "sha1": "dfdf38c7d854f0dca64a89acde5e894c8cce5866",
          "md5": "804f3ef0582ea10be5f7ddcc7ecc1bbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-jshell",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "5.1.9.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "substance",
          "version": {
            "requires": "8.0.02"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.madlonkay",
          "module": "desktopsupport",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "4.16.2"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "trident",
          "version": {
            "requires": "1.5.00"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt-natives-macosx",
          "version": {
            "requires": "2.4.0-rc-20210117"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all-natives-macosx",
          "version": {
            "requires": "2.4.0-rc-20210117"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-x64"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-arm64"
            }
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.16.2.jar",
          "url": "runelite-client-4.16.2.jar",
          "size": 9633551,
          "sha512": "47cd1315c6d9c1aa142056d40474d1046f80436da11ccba01aed5f8f429e1ef1e2944c2a3bcb4f69380ca920c4bd7fb0c5b8a6a04644cb945ae8c6cb2f71b884",
          "sha256": "3ca7fa1a821fe24badd4c42e983628acd6aa8913e03d098a8c597123ad6c15e4",
          "sha1": "dfdf38c7d854f0dca64a89acde5e894c8cce5866",
          "md5": "804f3ef0582ea10be5f7ddcc7ecc1bbd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-4.16.2-shaded.jar",
          "url": "runelite-client-4.16.2-shaded.jar",
          "size": 41664195,
          "sha512": "f50607b53999e6e3b83877d33977d74c23c86296a01351c7ae4dab7e246e114f28485d59aa753ef16872878ea92ecc3b862e4d08f1347b254130c1ea381f50ff",
          "sha256": "5f4166960abbfa5762bf4083aecdf287eb79786e5bed887707cf1199b0b72d30",
          "sha1": "dd48ccb604a9222c53e3d06ba991af25e522cf21",
          "md5": "6224fc8bfdc4288d4b7d82b6b50619e8"
        }
      ]
    }
  ]
}
