{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2wpr6gao4zgmjlx2a3cbc3ydny"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1248223,
          "sha512": "a15529a4f1d9739bd4eea93896b53396c866e1fe7c8f3ab356cacc1327a2d089dd88f87cc691b7ff50e832d8f5048edd6c18bbdd7c03b302215c394c41ea191e",
          "sha256": "1a0477f2c3287b5dcf3c2d06517d37dd93283f71b3786ca749a5723dbdd2affd",
          "sha1": "730848263815c3bcef0e1c29c7c495933c77808b",
          "md5": "0db031f27a0ce8572e10e71a8b6f54f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-3.5.4.jar",
          "url": "runelite-api-3.5.4.jar",
          "size": 1248223,
          "sha512": "a15529a4f1d9739bd4eea93896b53396c866e1fe7c8f3ab356cacc1327a2d089dd88f87cc691b7ff50e832d8f5048edd6c18bbdd7c03b302215c394c41ea191e",
          "sha256": "1a0477f2c3287b5dcf3c2d06517d37dd93283f71b3786ca749a5723dbdd2affd",
          "sha1": "730848263815c3bcef0e1c29c7c495933c77808b",
          "md5": "0db031f27a0ce8572e10e71a8b6f54f1"
        }
      ]
    }
  ]
}
