{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6rheulyot5fpnai4ze32orumlu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.2.1.jar",
          "url": "http-api-4.2.1.jar",
          "size": 159712,
          "sha512": "41f74c82b423989731c653a9065dc35e66af768c243cc858ab07e52450caccfd05415f01bd6e64da3196e3b4b0f30bb7de783ce14d84cae9013dc631b4f2dfe8",
          "sha256": "eb086e845e237a2c8bbc7231eb74ab673e465148b28475c9afc9cabab9c57d16",
          "sha1": "be7373399240ad3281be765d39e4727134b8e4c6",
          "md5": "1d9e602704b629a692fb9f7364445e4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.2.1.jar",
          "url": "http-api-4.2.1.jar",
          "size": 159712,
          "sha512": "41f74c82b423989731c653a9065dc35e66af768c243cc858ab07e52450caccfd05415f01bd6e64da3196e3b4b0f30bb7de783ce14d84cae9013dc631b4f2dfe8",
          "sha256": "eb086e845e237a2c8bbc7231eb74ab673e465148b28475c9afc9cabab9c57d16",
          "sha1": "be7373399240ad3281be765d39e4727134b8e4c6",
          "md5": "1d9e602704b629a692fb9f7364445e4a"
        }
      ]
    }
  ]
}
