{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "42fbce53c597efd9df0f072c382bf6d55bb817f53e8ad1c1d1b9768ce1c5bd5d1d46dd64da93bd4309a5dbb9578c1db01b9d2934c07c14de101b6dab67ce8f1c",
          "sha256": "e68544d4c2401cf28646d889de8bb8f5bdc00b727bab3d6755b6d3b3d11d3e84",
          "sha1": "849de6c397e597bdf1c7510751823c1619caf9e6",
          "md5": "0457ee0616afd845bed838bf9a4b4013"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "42fbce53c597efd9df0f072c382bf6d55bb817f53e8ad1c1d1b9768ce1c5bd5d1d46dd64da93bd4309a5dbb9578c1db01b9d2934c07c14de101b6dab67ce8f1c",
          "sha256": "e68544d4c2401cf28646d889de8bb8f5bdc00b727bab3d6755b6d3b3d11d3e84",
          "sha1": "849de6c397e597bdf1c7510751823c1619caf9e6",
          "md5": "0457ee0616afd845bed838bf9a4b4013"
        }
      ]
    }
  ]
}
