{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "a8071fcfead8ee9c42effb73e8bb1def888e9dfd4284e6fc5c39ecbcf3c6b3bccdf665ee4094c765ab087add007f02138bb817c4fcaaab62bfdce5983b13e4a7",
          "sha256": "0603c58ec69d6b2dae722fa01021e6620d27967e5a9e46f62ad9b28e412d647a",
          "sha1": "69f555a342f46905832b6ac01e01f42a8eeda524",
          "md5": "fd2b011f4719045a247431ef51dc00d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "a8071fcfead8ee9c42effb73e8bb1def888e9dfd4284e6fc5c39ecbcf3c6b3bccdf665ee4094c765ab087add007f02138bb817c4fcaaab62bfdce5983b13e4a7",
          "sha256": "0603c58ec69d6b2dae722fa01021e6620d27967e5a9e46f62ad9b28e412d647a",
          "sha1": "69f555a342f46905832b6ac01e01f42a8eeda524",
          "md5": "fd2b011f4719045a247431ef51dc00d4"
        }
      ]
    }
  ]
}
