{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "b4cc16032d5070df690f3ea59d84245ba78045467e700e96f0f5ca33ddf72d762b63586258748b8f8e8f5b97048c7888837d84deffdb473d38934c9ccfd6204f",
          "sha256": "1bfc7fa6ed9cf73ce6f63d19328ac4752d5559c9326afefd63a2cba8f2beb5b4",
          "sha1": "838fda0c31aca25d7bd44ca984cdef600e96567c",
          "md5": "652f13b303afe89a367b7fad14ec9589"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "b4cc16032d5070df690f3ea59d84245ba78045467e700e96f0f5ca33ddf72d762b63586258748b8f8e8f5b97048c7888837d84deffdb473d38934c9ccfd6204f",
          "sha256": "1bfc7fa6ed9cf73ce6f63d19328ac4752d5559c9326afefd63a2cba8f2beb5b4",
          "sha1": "838fda0c31aca25d7bd44ca984cdef600e96567c",
          "md5": "652f13b303afe89a367b7fad14ec9589"
        }
      ]
    }
  ]
}
