{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.24.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.24.1.jar",
          "url": "runelite-api-4.24.1.jar",
          "size": 1346804,
          "sha512": "ea11c703e70540e8d3f6ae2b38888ee14077553f7b63a639e2081189ca7ab87be98bf40cfe6b20f0a7082a26acfae756e2055d1615a73c3ac44b2fa82d9e7743",
          "sha256": "9c00acac5aaf3847734f40af46a9a1e598c70f3bbabc6b08f03c42fd14f664ea",
          "sha1": "6fe38e90e6706d9953be5f85bb6044009dda5f20",
          "md5": "0831fbe8bcf7c1a9a928528374190fa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.24.1.jar",
          "url": "runelite-api-4.24.1.jar",
          "size": 1346804,
          "sha512": "ea11c703e70540e8d3f6ae2b38888ee14077553f7b63a639e2081189ca7ab87be98bf40cfe6b20f0a7082a26acfae756e2055d1615a73c3ac44b2fa82d9e7743",
          "sha256": "9c00acac5aaf3847734f40af46a9a1e598c70f3bbabc6b08f03c42fd14f664ea",
          "sha1": "6fe38e90e6706d9953be5f85bb6044009dda5f20",
          "md5": "0831fbe8bcf7c1a9a928528374190fa5"
        }
      ]
    }
  ]
}
