{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99214,
          "sha512": "8ef0fa9170c1246641248928bd67a99325c93eab3c26c7654edeb344b5b231d310bf7cb2f9a3afbb0196b560b83bc65b23df832f389ad58dcdd79d0e121dae58",
          "sha256": "600e0bee1a0e630df8bdb0c2355d8f4642ce11acb35cabcce1a41b7e2ed02445",
          "sha1": "ed67db1b1076a631fa4f220a8fbe9443f757e30a",
          "md5": "53df83261b8531cd62230159a14c2aed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99214,
          "sha512": "8ef0fa9170c1246641248928bd67a99325c93eab3c26c7654edeb344b5b231d310bf7cb2f9a3afbb0196b560b83bc65b23df832f389ad58dcdd79d0e121dae58",
          "sha256": "600e0bee1a0e630df8bdb0c2355d8f4642ce11acb35cabcce1a41b7e2ed02445",
          "sha1": "ed67db1b1076a631fa4f220a8fbe9443f757e30a",
          "md5": "53df83261b8531cd62230159a14c2aed"
        }
      ]
    }
  ]
}
