{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99203,
          "sha512": "a86088431bfae82c03fa39ba89431928878b1e5caa24d3c9b58ed045280244c67b05ce4665364ef6004521a46d83e750c91f3adf33611b736aa800d5283fcac6",
          "sha256": "d00e8a12def34a697e90a442189319f5c1d853c5e17ff69fb3c2d3871ef94701",
          "sha1": "80f6e9bea8cf3d7695976856dd51ce6ea9a0a78f",
          "md5": "6f5f3a17d6088cbff2c997482fcddb8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99203,
          "sha512": "a86088431bfae82c03fa39ba89431928878b1e5caa24d3c9b58ed045280244c67b05ce4665364ef6004521a46d83e750c91f3adf33611b736aa800d5283fcac6",
          "sha256": "d00e8a12def34a697e90a442189319f5c1d853c5e17ff69fb3c2d3871ef94701",
          "sha1": "80f6e9bea8cf3d7695976856dd51ce6ea9a0a78f",
          "md5": "6f5f3a17d6088cbff2c997482fcddb8b"
        }
      ]
    }
  ]
}
