{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99209,
          "sha512": "d865c53877ad229c4c5fbf0bec8f84851715dbdf13dfa680c95e61b811b2514e57f7bf2c3fcb9236b4a4b0d0c4a674f7266f90222fc46324c7b7d7b5a3767dc2",
          "sha256": "8f5917f21a7a0abbcb936d58c61e00f9abb7842d34544a1a1d21a2f9d3bee35c",
          "sha1": "920ee3128ff875da1674dc42eeea29a03db7dadf",
          "md5": "bc04d150d6a242872dc4323b119093de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.0.jar",
          "url": "http-api-4.20.0.jar",
          "size": 99209,
          "sha512": "d865c53877ad229c4c5fbf0bec8f84851715dbdf13dfa680c95e61b811b2514e57f7bf2c3fcb9236b4a4b0d0c4a674f7266f90222fc46324c7b7d7b5a3767dc2",
          "sha256": "8f5917f21a7a0abbcb936d58c61e00f9abb7842d34544a1a1d21a2f9d3bee35c",
          "sha1": "920ee3128ff875da1674dc42eeea29a03db7dadf",
          "md5": "bc04d150d6a242872dc4323b119093de"
        }
      ]
    }
  ]
}
