{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.12.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.12.2.jar",
          "url": "runescape-api-4.12.2.jar",
          "size": 142905,
          "sha512": "bd3a571a5efae347d7ca734b6bc3f86557a657cd12d77dc066665a5c1d7e4b4bf3a3913d427f404a1fa04fe243f11fc84d492597573bdd584b34b58a6cd9c9b6",
          "sha256": "1f9047c154794e149e7fee09de09d4f013e9d346a8f83fe83ea48c75a1c0570b",
          "sha1": "2c4d60494e05ad8ac8363abb8a24b35db55e2f83",
          "md5": "5ec6fb1431f12726dcc0fd95d12bc077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.12.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.12.2.jar",
          "url": "runescape-api-4.12.2.jar",
          "size": 142905,
          "sha512": "bd3a571a5efae347d7ca734b6bc3f86557a657cd12d77dc066665a5c1d7e4b4bf3a3913d427f404a1fa04fe243f11fc84d492597573bdd584b34b58a6cd9c9b6",
          "sha256": "1f9047c154794e149e7fee09de09d4f013e9d346a8f83fe83ea48c75a1c0570b",
          "sha1": "2c4d60494e05ad8ac8363abb8a24b35db55e2f83",
          "md5": "5ec6fb1431f12726dcc0fd95d12bc077"
        }
      ]
    }
  ]
}
