{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.22.0.jar",
          "url": "runelite-jshell-4.22.0.jar",
          "size": 26557,
          "sha512": "94d20fd2971b703fa8c2d4b399c2c6b148231aa703c7e4bec5b001fde9d1c75796134364eda90eb131744a3096597a96c2cfd511671531e30f4b5c4595d67450",
          "sha256": "cfb034d2652575af845ac37b7b8e6bb5c0feccd176f02f21cecc35850d765ed3",
          "sha1": "8bbe3bdb746e2519e9300655185916bf93c633e5",
          "md5": "8c74596a43aa6ccaa1b2412644fc61d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.22.0.jar",
          "url": "runelite-jshell-4.22.0.jar",
          "size": 26557,
          "sha512": "94d20fd2971b703fa8c2d4b399c2c6b148231aa703c7e4bec5b001fde9d1c75796134364eda90eb131744a3096597a96c2cfd511671531e30f4b5c4595d67450",
          "sha256": "cfb034d2652575af845ac37b7b8e6bb5c0feccd176f02f21cecc35850d765ed3",
          "sha1": "8bbe3bdb746e2519e9300655185916bf93c633e5",
          "md5": "8c74596a43aa6ccaa1b2412644fc61d0"
        }
      ]
    }
  ]
}
