{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.22.0.jar",
          "url": "runelite-jshell-4.22.0.jar",
          "size": 26557,
          "sha512": "e2747b3cacb407b59ccee7f8e7eaedfda694423c620f6e61612b03c0cacc2cfd3121c61b7ceab3016525912594047d3a7ea760ff3ad610bc27b9521402b5e5b5",
          "sha256": "c9e295a564b305ffb1acbaff7f85e07034719c5500dbc14176108d9de21bd24b",
          "sha1": "b9693c247e2f1fdf4642f82253e5452ee1733500",
          "md5": "dc2848d3b3f4ed4f20d170b17b68b8af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.22.0.jar",
          "url": "runelite-jshell-4.22.0.jar",
          "size": 26557,
          "sha512": "e2747b3cacb407b59ccee7f8e7eaedfda694423c620f6e61612b03c0cacc2cfd3121c61b7ceab3016525912594047d3a7ea760ff3ad610bc27b9521402b5e5b5",
          "sha256": "c9e295a564b305ffb1acbaff7f85e07034719c5500dbc14176108d9de21bd24b",
          "sha1": "b9693c247e2f1fdf4642f82253e5452ee1733500",
          "md5": "dc2848d3b3f4ed4f20d170b17b68b8af"
        }
      ]
    }
  ]
}
