{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.22.0.jar",
          "url": "runelite-jshell-4.22.0.jar",
          "size": 26557,
          "sha512": "bb43041ff156370afb2bd3e27807a6f3781376b3e432db9593df6ad759b5d961b9d73fa053cbfde68e01f6072072213d4384ca11e1591e6b6da4e2ab9c00bae0",
          "sha256": "605a516131a644fce4b7aefd807fa21c2d58b738bde4a1a16c955cdfe96145db",
          "sha1": "5bbaa018ace6d65006fd52a3db94e2c89dd66101",
          "md5": "b204c7d339ad42365557bb19ef144fbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.22.0.jar",
          "url": "runelite-jshell-4.22.0.jar",
          "size": 26557,
          "sha512": "bb43041ff156370afb2bd3e27807a6f3781376b3e432db9593df6ad759b5d961b9d73fa053cbfde68e01f6072072213d4384ca11e1591e6b6da4e2ab9c00bae0",
          "sha256": "605a516131a644fce4b7aefd807fa21c2d58b738bde4a1a16c955cdfe96145db",
          "sha1": "5bbaa018ace6d65006fd52a3db94e2c89dd66101",
          "md5": "b204c7d339ad42365557bb19ef144fbb"
        }
      ]
    }
  ]
}
