{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rnnqq2tzebhmrg7wvrk7ug3h4e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.2.0.jar",
          "url": "http-api-4.2.0.jar",
          "size": 159712,
          "sha512": "f06406e1bc07514a62f1cf8b23e83e1ea26772075c9e3cdf8f71d5767cc662cc8355454ff2eacd228ab26484fb27d0e93fe6162977333aa24a48d68356b44d12",
          "sha256": "84c6bca77dc46812888a4763b615c15e6649f09a235a8185cb9db191c674831f",
          "sha1": "0fa7bcc6edd3033cd669b908c3a288da4d23440f",
          "md5": "39983b8b450b0d8310e367278a812a8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.2.0.jar",
          "url": "http-api-4.2.0.jar",
          "size": 159712,
          "sha512": "f06406e1bc07514a62f1cf8b23e83e1ea26772075c9e3cdf8f71d5767cc662cc8355454ff2eacd228ab26484fb27d0e93fe6162977333aa24a48d68356b44d12",
          "sha256": "84c6bca77dc46812888a4763b615c15e6649f09a235a8185cb9db191c674831f",
          "sha1": "0fa7bcc6edd3033cd669b908c3a288da4d23440f",
          "md5": "39983b8b450b0d8310e367278a812a8b"
        }
      ]
    }
  ]
}
