{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "a1e928f333f71c2277e0f75e344eb0d56bec1723a74de70e1f44c427265733c8f7474020d13af70f401f208617e7d361bacd74cf81e30a995aa46d9d316a6272",
          "sha256": "cd1bfa1a2a5910d579c9f48f3555a5cfa2fdafb14c702e3626bc9c674c8a9704",
          "sha1": "9f5cd81e2aac24772555711b37770f15d8b51f43",
          "md5": "fc5718472cf70f0b13682f9c79122cc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "a1e928f333f71c2277e0f75e344eb0d56bec1723a74de70e1f44c427265733c8f7474020d13af70f401f208617e7d361bacd74cf81e30a995aa46d9d316a6272",
          "sha256": "cd1bfa1a2a5910d579c9f48f3555a5cfa2fdafb14c702e3626bc9c674c8a9704",
          "sha1": "9f5cd81e2aac24772555711b37770f15d8b51f43",
          "md5": "fc5718472cf70f0b13682f9c79122cc5"
        }
      ]
    }
  ]
}
