{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.1.jar",
          "url": "http-api-4.16.1.jar",
          "size": 172792,
          "sha512": "38259802edd6f525ef6202068a1ca8beb1bb459c87b202a928ff943d12bbbe6caec171f3a188b5693f1071db5315304ba20f374a59c9bc5a18f158af30c08f10",
          "sha256": "d550fa009c9911ff5eda00a63e07f6a0015007a3920b824e80d363db3bb62646",
          "sha1": "5c598210a2284dbfdd8691a0a832529a34904978",
          "md5": "79afb5da3f10ec1c5b5ec50718f9f1f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.1.jar",
          "url": "http-api-4.16.1.jar",
          "size": 172792,
          "sha512": "38259802edd6f525ef6202068a1ca8beb1bb459c87b202a928ff943d12bbbe6caec171f3a188b5693f1071db5315304ba20f374a59c9bc5a18f158af30c08f10",
          "sha256": "d550fa009c9911ff5eda00a63e07f6a0015007a3920b824e80d363db3bb62646",
          "sha1": "5c598210a2284dbfdd8691a0a832529a34904978",
          "md5": "79afb5da3f10ec1c5b5ec50718f9f1f5"
        }
      ]
    }
  ]
}
