{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.8.0.jar",
          "url": "runelite-api-4.8.0.jar",
          "size": 1271040,
          "sha512": "239f3b3425c8917ecc33190e1a7defde885884d03cd6f069c31228d5a00ef074e41869b7460e93abb86107b1a5cbdc9056da260ed9390f4ff03bf95c8737b8bc",
          "sha256": "fc559005d9f057c38baac54fa889530ae79564b1a2a7205edabdc6ccc55e2f70",
          "sha1": "6a7ab6d3349e970d89c9b5116811fae08267afae",
          "md5": "e18f81982d7552a85e5abf07bc8f58ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.8.0.jar",
          "url": "runelite-api-4.8.0.jar",
          "size": 1271040,
          "sha512": "239f3b3425c8917ecc33190e1a7defde885884d03cd6f069c31228d5a00ef074e41869b7460e93abb86107b1a5cbdc9056da260ed9390f4ff03bf95c8737b8bc",
          "sha256": "fc559005d9f057c38baac54fa889530ae79564b1a2a7205edabdc6ccc55e2f70",
          "sha1": "6a7ab6d3349e970d89c9b5116811fae08267afae",
          "md5": "e18f81982d7552a85e5abf07bc8f58ec"
        }
      ]
    }
  ]
}
