{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.31.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.31.1.jar",
          "url": "runelite-api-4.31.1.jar",
          "size": 1362056,
          "sha512": "53831830efbe8a8352bc49e68737c9256ce7e51cb512b203d8583a1ea58a6f0e56a535d2794573ea676c9141ff676cfdee56f26582f47722040666d992d666b4",
          "sha256": "77723c2ec2ad7dde804091bb064931a80d88e407276938784c809a628d66a8ca",
          "sha1": "0b508ee060b24d99c85092ce9c03d674166a18b5",
          "md5": "e292bbc8ca231d3c03c7f3f31067351c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.31.1.jar",
          "url": "runelite-api-4.31.1.jar",
          "size": 1362056,
          "sha512": "53831830efbe8a8352bc49e68737c9256ce7e51cb512b203d8583a1ea58a6f0e56a535d2794573ea676c9141ff676cfdee56f26582f47722040666d992d666b4",
          "sha256": "77723c2ec2ad7dde804091bb064931a80d88e407276938784c809a628d66a8ca",
          "sha1": "0b508ee060b24d99c85092ce9c03d674166a18b5",
          "md5": "e292bbc8ca231d3c03c7f3f31067351c"
        }
      ]
    }
  ]
}
