{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346194,
          "sha512": "6009710043bb2a02233416d7e77a9825dd5631a2c160516fd0f71714dafda71907c29485f3306771778b81cbe33ae7c5a1f7f80ce9bdb04a1e478ecdba454dc3",
          "sha256": "42359b2b99b52e7fcca0f7cc59ef41e24afe4e6e2856c1cdff358845afbc5afb",
          "sha1": "8e04e4b713c03cac51f1f44c97180b43bfc2f2f9",
          "md5": "afaea505f90efbd451fb70055e411d43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346194,
          "sha512": "6009710043bb2a02233416d7e77a9825dd5631a2c160516fd0f71714dafda71907c29485f3306771778b81cbe33ae7c5a1f7f80ce9bdb04a1e478ecdba454dc3",
          "sha256": "42359b2b99b52e7fcca0f7cc59ef41e24afe4e6e2856c1cdff358845afbc5afb",
          "sha1": "8e04e4b713c03cac51f1f44c97180b43bfc2f2f9",
          "md5": "afaea505f90efbd451fb70055e411d43"
        }
      ]
    }
  ]
}
