{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346194,
          "sha512": "c9bff09a3d3b31776fda437b590676ecbb4494903036e93d293e0ce7b3291bf0e60eadbc1a5b6cfee345fc1ff339c171616fa63eeea71cdc5237c20f064127ec",
          "sha256": "26cf7c58d89f12f71b0f1ee0c52f57891202712edd16bfb646243399c308f943",
          "sha1": "33df4ddd71d91225a176e0099687aaf61c8beb6a",
          "md5": "29967a8446e8dec0ea790838c4189d86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.0.jar",
          "url": "runelite-api-4.20.0.jar",
          "size": 1346194,
          "sha512": "c9bff09a3d3b31776fda437b590676ecbb4494903036e93d293e0ce7b3291bf0e60eadbc1a5b6cfee345fc1ff339c171616fa63eeea71cdc5237c20f064127ec",
          "sha256": "26cf7c58d89f12f71b0f1ee0c52f57891202712edd16bfb646243399c308f943",
          "sha1": "33df4ddd71d91225a176e0099687aaf61c8beb6a",
          "md5": "29967a8446e8dec0ea790838c4189d86"
        }
      ]
    }
  ]
}
