{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.29.0.jar",
          "url": "runelite-jshell-4.29.0.jar",
          "size": 26557,
          "sha512": "1fe066b13ba63dbf2a77ac7200f76862444187713ddce9ab72d8ffad16a40732c109cf8b70532a3e9c90ea98a063660b57662a012634b9cbd5b3f4d8dd375fdc",
          "sha256": "64488e8fce632626408fda7550bca5448d254969bd706f2961a6c3c722dcad3d",
          "sha1": "d8e1ea62309b9d5f56073eb96474fc1ebdd46ff8",
          "md5": "62deae6f14c6aa8e791e4a638e445273"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.29.0.jar",
          "url": "runelite-jshell-4.29.0.jar",
          "size": 26557,
          "sha512": "1fe066b13ba63dbf2a77ac7200f76862444187713ddce9ab72d8ffad16a40732c109cf8b70532a3e9c90ea98a063660b57662a012634b9cbd5b3f4d8dd375fdc",
          "sha256": "64488e8fce632626408fda7550bca5448d254969bd706f2961a6c3c722dcad3d",
          "sha1": "d8e1ea62309b9d5f56073eb96474fc1ebdd46ff8",
          "md5": "62deae6f14c6aa8e791e4a638e445273"
        }
      ]
    }
  ]
}
