{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.12.0.jar",
          "url": "runelite-api-4.12.0.jar",
          "size": 1288354,
          "sha512": "abb920b8b8068ac830506c5d5c4e1c7feb6bec289cbaaaeaa8f240d7fc0b835da9c85c5f7579400c8849a6238e0273d21c33f7628d1520da863b58a552cba983",
          "sha256": "0fad82e024996b2c06c7c88ed36506532f6bd047d96690debe58148071550fd0",
          "sha1": "f9b8f6ee1c9f7dcfcb6d725711396ad73a4f3a72",
          "md5": "3d870dbc73fdefee70a41e64f39d7724"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.12.0.jar",
          "url": "runelite-api-4.12.0.jar",
          "size": 1288354,
          "sha512": "abb920b8b8068ac830506c5d5c4e1c7feb6bec289cbaaaeaa8f240d7fc0b835da9c85c5f7579400c8849a6238e0273d21c33f7628d1520da863b58a552cba983",
          "sha256": "0fad82e024996b2c06c7c88ed36506532f6bd047d96690debe58148071550fd0",
          "sha1": "f9b8f6ee1c9f7dcfcb6d725711396ad73a4f3a72",
          "md5": "3d870dbc73fdefee70a41e64f39d7724"
        }
      ]
    }
  ]
}
