{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "b0498aca318a31d2415a74d88d7e0ae4adf59e06d36de95a06ce295f04a98a784e8d21db1f66d4771b1a9ff0fef8ad14bed970e2fd138a696cbe6f26cdcb925d",
          "sha256": "396da2380851fc6755e54a56ddbbd9fddc4aee48205cf5c006c261e996f833cf",
          "sha1": "87c4986e721cf1b4ed0510c465af99df4157e016",
          "md5": "22503d42bbf903291ca5de9d0a58e774"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "b0498aca318a31d2415a74d88d7e0ae4adf59e06d36de95a06ce295f04a98a784e8d21db1f66d4771b1a9ff0fef8ad14bed970e2fd138a696cbe6f26cdcb925d",
          "sha256": "396da2380851fc6755e54a56ddbbd9fddc4aee48205cf5c006c261e996f833cf",
          "sha1": "87c4986e721cf1b4ed0510c465af99df4157e016",
          "md5": "22503d42bbf903291ca5de9d0a58e774"
        }
      ]
    }
  ]
}
