{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "6c7da598a1453c5253e41615ea79728b5aa4b8087c9fb5e664476912fc05ee643c777aec942d01b6423d025b8dd48c9da9e9a72ed053cc0a1d0ecea33ec80074",
          "sha256": "530110e686084fe1f7bdc2a1a2073087dee8827aa827af70bcf5b940362347aa",
          "sha1": "11ea647c77e436ed114c20450ed33dedec826402",
          "md5": "efdb6500e748351e460aaac9b0b0b469"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.27.0.jar",
          "url": "runelite-api-4.27.0.jar",
          "size": 1357499,
          "sha512": "6c7da598a1453c5253e41615ea79728b5aa4b8087c9fb5e664476912fc05ee643c777aec942d01b6423d025b8dd48c9da9e9a72ed053cc0a1d0ecea33ec80074",
          "sha256": "530110e686084fe1f7bdc2a1a2073087dee8827aa827af70bcf5b940362347aa",
          "sha1": "11ea647c77e436ed114c20450ed33dedec826402",
          "md5": "efdb6500e748351e460aaac9b0b0b469"
        }
      ]
    }
  ]
}
