{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "b822dae91a08f1fa917be9011098df4e18888c959df72f7bd2b2c774c092f3f476c52be8f0b4bec03ea3086dbb4278d1341b30d727e6a673196fbab7a536c590",
          "sha256": "de5777def0fa5e4eac2902d022958015c2f72547072fbbaf982b7f1433aa79e6",
          "sha1": "b19f4929cebd1d52bf2d453b07e465ca3f31c4fc",
          "md5": "b441bf50c2fa19387280ecfd763c67b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "b822dae91a08f1fa917be9011098df4e18888c959df72f7bd2b2c774c092f3f476c52be8f0b4bec03ea3086dbb4278d1341b30d727e6a673196fbab7a536c590",
          "sha256": "de5777def0fa5e4eac2902d022958015c2f72547072fbbaf982b7f1433aa79e6",
          "sha1": "b19f4929cebd1d52bf2d453b07e465ca3f31c4fc",
          "md5": "b441bf50c2fa19387280ecfd763c67b9"
        }
      ]
    }
  ]
}
