{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "4ed384f4fd7616a12214c6f29704c1c450d856bff31351d01ea9005a5f9b4a86b8197223cec53cb8b999c25e6783ffa3a6875d4b1c99343b2725579c02bb27bd",
          "sha256": "b0ff9a3705aede8df0ddedce20f672e318ef91df7a23d2623dd42574b159aa71",
          "sha1": "62c809cb7821a9a03747f29c214c2f1becb5cb5a",
          "md5": "b8567e637894029e78a1922c89f0bf5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "4ed384f4fd7616a12214c6f29704c1c450d856bff31351d01ea9005a5f9b4a86b8197223cec53cb8b999c25e6783ffa3a6875d4b1c99343b2725579c02bb27bd",
          "sha256": "b0ff9a3705aede8df0ddedce20f672e318ef91df7a23d2623dd42574b159aa71",
          "sha1": "62c809cb7821a9a03747f29c214c2f1becb5cb5a",
          "md5": "b8567e637894029e78a1922c89f0bf5c"
        }
      ]
    }
  ]
}
