{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "0d917135be8def346b7914478950fc2946507d7a02dd537e3dfb5dbadd5c417c6873dc93249dd3c3363ca2a80c45b8239af34b02a463fa9ed722ad5a7a041904",
          "sha256": "00ef6ab39b168b2a48426413c43c8a32e405d264f9ed7135293312e59eb80d71",
          "sha1": "68299ad238427956ddf70eb66ed4b691b3d53b7f",
          "md5": "c54fcbfed7c75ca474a792a6371bcdb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.27.0.jar",
          "url": "runelite-jshell-4.27.0.jar",
          "size": 26557,
          "sha512": "0d917135be8def346b7914478950fc2946507d7a02dd537e3dfb5dbadd5c417c6873dc93249dd3c3363ca2a80c45b8239af34b02a463fa9ed722ad5a7a041904",
          "sha256": "00ef6ab39b168b2a48426413c43c8a32e405d264f9ed7135293312e59eb80d71",
          "sha1": "68299ad238427956ddf70eb66ed4b691b3d53b7f",
          "md5": "c54fcbfed7c75ca474a792a6371bcdb1"
        }
      ]
    }
  ]
}
