{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.2.jar",
          "url": "runelite-api-4.15.2.jar",
          "size": 1331151,
          "sha512": "5cc6d2804a839f78974e026760779a4febef004939f7b4224c18b36b53f1ad09b0f234fdab4ef70b4d059348233a984ea13dac35149fe0b6239935938954dfda",
          "sha256": "fc272bf77ff63e7313a045e06c045635df4db9ddff84aeb67fba7518af0bcf62",
          "sha1": "c760e5b61d46b1de0d1ffee32e384cb91f74f750",
          "md5": "8d26ae0a7e6faabfe175ae3143e5624d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.2.jar",
          "url": "runelite-api-4.15.2.jar",
          "size": 1331151,
          "sha512": "5cc6d2804a839f78974e026760779a4febef004939f7b4224c18b36b53f1ad09b0f234fdab4ef70b4d059348233a984ea13dac35149fe0b6239935938954dfda",
          "sha256": "fc272bf77ff63e7313a045e06c045635df4db9ddff84aeb67fba7518af0bcf62",
          "sha1": "c760e5b61d46b1de0d1ffee32e384cb91f74f750",
          "md5": "8d26ae0a7e6faabfe175ae3143e5624d"
        }
      ]
    }
  ]
}
