{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.2.jar",
          "url": "runelite-api-4.15.2.jar",
          "size": 1331151,
          "sha512": "064ad71db7c27d35704e632df6231bd4dc3b8d8b6a4097c0f80da143b9de0f8e106806f7f7ec60d95570b99e4a9ad60fa913d9c7c85003897c48a6ac0125b292",
          "sha256": "1fe5aa9262e5fa14f4a97dde6bd3651130188e9bad79bbe623bd1dbb23b3daab",
          "sha1": "362a98a56b17a94161ce28f411584db207ca8787",
          "md5": "667a93ce1e3162c66ca0ce5bad00a8a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.2.jar",
          "url": "runelite-api-4.15.2.jar",
          "size": 1331151,
          "sha512": "064ad71db7c27d35704e632df6231bd4dc3b8d8b6a4097c0f80da143b9de0f8e106806f7f7ec60d95570b99e4a9ad60fa913d9c7c85003897c48a6ac0125b292",
          "sha256": "1fe5aa9262e5fa14f4a97dde6bd3651130188e9bad79bbe623bd1dbb23b3daab",
          "sha1": "362a98a56b17a94161ce28f411584db207ca8787",
          "md5": "667a93ce1e3162c66ca0ce5bad00a8a2"
        }
      ]
    }
  ]
}
