{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.2.jar",
          "url": "runelite-api-4.15.2.jar",
          "size": 1331151,
          "sha512": "319a7bcf098d5a89d5da635fbaab645e54981295171ebfb9665345d27930f210b10e462fd7f7b49d9f32ec5b11796e908b71666bcc900943e94ad350d43c1207",
          "sha256": "cffb9d32e00d4d0414223adc07686af86756186e15a8eee6f27d79e8e6f64cc0",
          "sha1": "92f6e0f4eb632b8b3326e7835696916be9e54c7b",
          "md5": "3b7425afa219e94775b17bcda94fd55c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.2.jar",
          "url": "runelite-api-4.15.2.jar",
          "size": 1331151,
          "sha512": "319a7bcf098d5a89d5da635fbaab645e54981295171ebfb9665345d27930f210b10e462fd7f7b49d9f32ec5b11796e908b71666bcc900943e94ad350d43c1207",
          "sha256": "cffb9d32e00d4d0414223adc07686af86756186e15a8eee6f27d79e8e6f64cc0",
          "sha1": "92f6e0f4eb632b8b3326e7835696916be9e54c7b",
          "md5": "3b7425afa219e94775b17bcda94fd55c"
        }
      ]
    }
  ]
}
