{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "1197d6e1f32c6662f64688ec0c2b4806fbe2387cc4429a249b61f0859fbc99c0678cdf0e953760c654b9adc981ce15e23e837034409959ca90ca44d1c2382cf0",
          "sha256": "b2dfce302d19c1a7737c9cb6a4a5287ba8e7c0ff6cf11b554f41f592805a2c94",
          "sha1": "4e58b5efd92ebda67556c5f000efc28d2b83d01e",
          "md5": "6f516f21586e4784e59a61319c82009b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "1197d6e1f32c6662f64688ec0c2b4806fbe2387cc4429a249b61f0859fbc99c0678cdf0e953760c654b9adc981ce15e23e837034409959ca90ca44d1c2382cf0",
          "sha256": "b2dfce302d19c1a7737c9cb6a4a5287ba8e7c0ff6cf11b554f41f592805a2c94",
          "sha1": "4e58b5efd92ebda67556c5f000efc28d2b83d01e",
          "md5": "6f516f21586e4784e59a61319c82009b"
        }
      ]
    }
  ]
}
