{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "4d73e0e9cc21b318dfa2caaa4dc3f6eff8a2b9382b6ed2a2a5db3d360fa60290979a1f98aaf05aaebf2bb9b161ea691024c59e0b20facba5c9c2ce1dfc29f7de",
          "sha256": "89809d259c4e26f640873791b7de865531a53f2f478269fac5ef3deacba53f66",
          "sha1": "bac9b5d0e85bfbeac6c79079211aab205eb27aff",
          "md5": "bc6dbd861a0ee76314546af311e3d013"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "4d73e0e9cc21b318dfa2caaa4dc3f6eff8a2b9382b6ed2a2a5db3d360fa60290979a1f98aaf05aaebf2bb9b161ea691024c59e0b20facba5c9c2ce1dfc29f7de",
          "sha256": "89809d259c4e26f640873791b7de865531a53f2f478269fac5ef3deacba53f66",
          "sha1": "bac9b5d0e85bfbeac6c79079211aab205eb27aff",
          "md5": "bc6dbd861a0ee76314546af311e3d013"
        }
      ]
    }
  ]
}
