{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "f78c8d03d2abb263e4002c6cc6f50a9d67b8134acccc59a2d21195facf450d6b9028d83fdff7fc9deba48b79a177dc72f17078decd8568db4056fe01877c73d9",
          "sha256": "fbc80ffd8e4ee4648f092702c52d4739f7e6ccbfc13af7882d019649524549dc",
          "sha1": "11e901c7d8db1b12f9d7e91de3af13fd36474068",
          "md5": "ac81f644ecc52461b4316286c6e9a7f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.2.jar",
          "url": "runelite-jshell-4.20.2.jar",
          "size": 26557,
          "sha512": "f78c8d03d2abb263e4002c6cc6f50a9d67b8134acccc59a2d21195facf450d6b9028d83fdff7fc9deba48b79a177dc72f17078decd8568db4056fe01877c73d9",
          "sha256": "fbc80ffd8e4ee4648f092702c52d4739f7e6ccbfc13af7882d019649524549dc",
          "sha1": "11e901c7d8db1b12f9d7e91de3af13fd36474068",
          "md5": "ac81f644ecc52461b4316286c6e9a7f0"
        }
      ]
    }
  ]
}
