{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.6.1.jar",
          "url": "http-api-4.6.1.jar",
          "size": 159717,
          "sha512": "01185bfd9ed647825d088b6ded92b84840777f447432fe9e7bc3e538d5ed29eacbe09d8dc77e380badb1c92802dff5504ed143938ec54216c8b6158314e17a90",
          "sha256": "8877bc7a129252223a162ffa30945a6573fb1756a9d4be0798a59bacddd8a5cd",
          "sha1": "d7c67095879f66594783de347501c885858e6e73",
          "md5": "7be49561b917b79f881c57daffecf71b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.6.1.jar",
          "url": "http-api-4.6.1.jar",
          "size": 159717,
          "sha512": "01185bfd9ed647825d088b6ded92b84840777f447432fe9e7bc3e538d5ed29eacbe09d8dc77e380badb1c92802dff5504ed143938ec54216c8b6158314e17a90",
          "sha256": "8877bc7a129252223a162ffa30945a6573fb1756a9d4be0798a59bacddd8a5cd",
          "sha1": "d7c67095879f66594783de347501c885858e6e73",
          "md5": "7be49561b917b79f881c57daffecf71b"
        }
      ]
    }
  ]
}
