{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.16.2.jar",
          "url": "runelite-jshell-4.16.2.jar",
          "size": 26552,
          "sha512": "3cf48b140eb37da2d461179bab20098bb3de7f2400f281725b34c46e1bfa85f2f2354ddd475d4d9637326d28902d2900fa8a6c200a4987fc4831601c544a59b2",
          "sha256": "a2e4bd7483b7926768ff8cde39bdefc7e1a54f2d4a1b0b99ba476fcba4c2dc78",
          "sha1": "b50e3e87e4be6fcbe18ce3e48f2157f1855b1e7d",
          "md5": "95c53856fc02176f3c3eb647f89201cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.16.2.jar",
          "url": "runelite-jshell-4.16.2.jar",
          "size": 26552,
          "sha512": "3cf48b140eb37da2d461179bab20098bb3de7f2400f281725b34c46e1bfa85f2f2354ddd475d4d9637326d28902d2900fa8a6c200a4987fc4831601c544a59b2",
          "sha256": "a2e4bd7483b7926768ff8cde39bdefc7e1a54f2d4a1b0b99ba476fcba4c2dc78",
          "sha1": "b50e3e87e4be6fcbe18ce3e48f2157f1855b1e7d",
          "md5": "95c53856fc02176f3c3eb647f89201cc"
        }
      ]
    }
  ]
}
