{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.16.2.jar",
          "url": "runelite-jshell-4.16.2.jar",
          "size": 26552,
          "sha512": "6b3b289d1b1bc270863ab4c613a9983c2a337b653ff10becea1f2581a76d9fcd351cf1859067612f760dc7e568ed197406b46d96e413bfe72d064166d6624795",
          "sha256": "9fe4b0efaf392499f7bf9f449fb6922ba0b24e1d3a5b7b0b5732a9a0cdd57267",
          "sha1": "d8463426e4c404722b991497a4ed84b48bf7d2f7",
          "md5": "1182add9cabbc3614cb7dcff9d95bdb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.16.2.jar",
          "url": "runelite-jshell-4.16.2.jar",
          "size": 26552,
          "sha512": "6b3b289d1b1bc270863ab4c613a9983c2a337b653ff10becea1f2581a76d9fcd351cf1859067612f760dc7e568ed197406b46d96e413bfe72d064166d6624795",
          "sha256": "9fe4b0efaf392499f7bf9f449fb6922ba0b24e1d3a5b7b0b5732a9a0cdd57267",
          "sha1": "d8463426e4c404722b991497a4ed84b48bf7d2f7",
          "md5": "1182add9cabbc3614cb7dcff9d95bdb2"
        }
      ]
    }
  ]
}
