{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.16.2.jar",
          "url": "runelite-jshell-4.16.2.jar",
          "size": 26552,
          "sha512": "10055e87af72dd3565abcf0c2294286e51e08ae9d85eb54bf16846cf841e994f88f5ed311f58b69eb3cba3d5ff14c8e5669b9735f03271aeafdec5311f4e0061",
          "sha256": "1595e19c80dade3b2f2a6624e0ca7047e8775aa4d516fc7d3593e233883b98d4",
          "sha1": "4e2c4b967b04161d83dd082fe6ac4f99ba4412e4",
          "md5": "631e271b3ab02bbbe86223dd2b8227d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.16.2.jar",
          "url": "runelite-jshell-4.16.2.jar",
          "size": 26552,
          "sha512": "10055e87af72dd3565abcf0c2294286e51e08ae9d85eb54bf16846cf841e994f88f5ed311f58b69eb3cba3d5ff14c8e5669b9735f03271aeafdec5311f4e0061",
          "sha256": "1595e19c80dade3b2f2a6624e0ca7047e8775aa4d516fc7d3593e233883b98d4",
          "sha1": "4e2c4b967b04161d83dd082fe6ac4f99ba4412e4",
          "md5": "631e271b3ab02bbbe86223dd2b8227d8"
        }
      ]
    }
  ]
}
