{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.13.jar",
          "url": "http-api-4.9.13.jar",
          "size": 158715,
          "sha512": "6a819720d445577b47a67e61f2bb063a894718613defdaacb8632f3fb655b32a5b6e6726441116d02bd90e4a36990d1818d6f249f52851a19c947c56bebf90aa",
          "sha256": "182859175e6b8e6d768fcd20e9838f67407b65ce773d2e1eb47b76d618241e95",
          "sha1": "19126fb3b972ab5840486f8d1d7dd0a045d6ba60",
          "md5": "281f101c4148b373891965db90285b25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.13.jar",
          "url": "http-api-4.9.13.jar",
          "size": 158715,
          "sha512": "6a819720d445577b47a67e61f2bb063a894718613defdaacb8632f3fb655b32a5b6e6726441116d02bd90e4a36990d1818d6f249f52851a19c947c56bebf90aa",
          "sha256": "182859175e6b8e6d768fcd20e9838f67407b65ce773d2e1eb47b76d618241e95",
          "sha1": "19126fb3b972ab5840486f8d1d7dd0a045d6ba60",
          "md5": "281f101c4148b373891965db90285b25"
        }
      ]
    }
  ]
}
