{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.13.jar",
          "url": "http-api-4.9.13.jar",
          "size": 158716,
          "sha512": "11565bcc6a09351508443eef94fb360d38bdad3e2859a346f14902b9afcfdc515e173f5a9edd760eb266a1ae2ad914c8bfe1983f6586a0af87eddd97c4b5ea23",
          "sha256": "eafea35ee6c8b4debbfcba24c3729f19c4d6b7e1a963bd339165e50bd4b9bd12",
          "sha1": "21b456162dba59acfa28de29a966b64bdd9faed0",
          "md5": "f6a01708631833d1f375cb898c1333ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.13.jar",
          "url": "http-api-4.9.13.jar",
          "size": 158716,
          "sha512": "11565bcc6a09351508443eef94fb360d38bdad3e2859a346f14902b9afcfdc515e173f5a9edd760eb266a1ae2ad914c8bfe1983f6586a0af87eddd97c4b5ea23",
          "sha256": "eafea35ee6c8b4debbfcba24c3729f19c4d6b7e1a963bd339165e50bd4b9bd12",
          "sha1": "21b456162dba59acfa28de29a966b64bdd9faed0",
          "md5": "f6a01708631833d1f375cb898c1333ad"
        }
      ]
    }
  ]
}
