{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.13.jar",
          "url": "http-api-4.9.13.jar",
          "size": 158714,
          "sha512": "026b2ed65057023c013f49003250b6947de6841e71b0f5993f7fe51ef2cab4503d57c334d6d8f61c23e276130f142d4786980854c524a0b2d24a57d7eedac531",
          "sha256": "db7144a26b68c3203e98da2e3403152981dd6455aa2a0c791e470339666ba49f",
          "sha1": "516c075466f8156150fe2db51751504a9baefeaa",
          "md5": "f93b8b77db50fde588815ee7ebf9de65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.13.jar",
          "url": "http-api-4.9.13.jar",
          "size": 158714,
          "sha512": "026b2ed65057023c013f49003250b6947de6841e71b0f5993f7fe51ef2cab4503d57c334d6d8f61c23e276130f142d4786980854c524a0b2d24a57d7eedac531",
          "sha256": "db7144a26b68c3203e98da2e3403152981dd6455aa2a0c791e470339666ba49f",
          "sha1": "516c075466f8156150fe2db51751504a9baefeaa",
          "md5": "f93b8b77db50fde588815ee7ebf9de65"
        }
      ]
    }
  ]
}
