{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "483bd9611cdc6efe15f5323b2f5f45ea85ae043421fbb46a53b236a546f58fad2e0c85df93b53d496958049713be75e1549fed0f1233e6cdb8d55b65f4ea879c",
          "sha256": "c9c7b1eec1e78ae455f3c27b6ef6fa36bd8babba84ce04a78e994560b19806e0",
          "sha1": "9168be3461c9ceec22b609752268e29a22e96010",
          "md5": "8cc1e75c1fe7c6321eb56e6a35ce1016"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 149656,
          "sha512": "483bd9611cdc6efe15f5323b2f5f45ea85ae043421fbb46a53b236a546f58fad2e0c85df93b53d496958049713be75e1549fed0f1233e6cdb8d55b65f4ea879c",
          "sha256": "c9c7b1eec1e78ae455f3c27b6ef6fa36bd8babba84ce04a78e994560b19806e0",
          "sha1": "9168be3461c9ceec22b609752268e29a22e96010",
          "md5": "8cc1e75c1fe7c6321eb56e6a35ce1016"
        }
      ]
    }
  ]
}
