{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1361948,
          "sha512": "3a5030bea534e397621ebf64e4ed82bd9049507dfae8e635a31fc84525c9024aa742b8b749ba70eca4e0f85b103344acfed5d8fa14302d94098f428fd3d8ccf8",
          "sha256": "4819e7c271a944fd1a731e35bc84881f9b1dbf00d8fbc77c1a669e9368847d92",
          "sha1": "0d028e4ad5fcfaec06f1fe570421bb8d319c3dcd",
          "md5": "0c6327c1a932fee5e49a57dac0031234"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1361948,
          "sha512": "3a5030bea534e397621ebf64e4ed82bd9049507dfae8e635a31fc84525c9024aa742b8b749ba70eca4e0f85b103344acfed5d8fa14302d94098f428fd3d8ccf8",
          "sha256": "4819e7c271a944fd1a731e35bc84881f9b1dbf00d8fbc77c1a669e9368847d92",
          "sha1": "0d028e4ad5fcfaec06f1fe570421bb8d319c3dcd",
          "md5": "0c6327c1a932fee5e49a57dac0031234"
        }
      ]
    }
  ]
}
