{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1361948,
          "sha512": "4dcbaa3f000d5c8f198aa9daf80583a34db1f4881d5bbdda762657dfdefa1abbe57a064f9dee48fe474fbe8b8a5576715e5bf184fb2f013a781a81aca881256f",
          "sha256": "3cfa7532fb7f44081653752adf5835d91732fab63913cdaeb5c55e4665c0b315",
          "sha1": "13e8cda9046f1b0716810e0bd0f19941ebf3bfee",
          "md5": "bead3d01cbc14085ded578a79c2ec2ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1361948,
          "sha512": "4dcbaa3f000d5c8f198aa9daf80583a34db1f4881d5bbdda762657dfdefa1abbe57a064f9dee48fe474fbe8b8a5576715e5bf184fb2f013a781a81aca881256f",
          "sha256": "3cfa7532fb7f44081653752adf5835d91732fab63913cdaeb5c55e4665c0b315",
          "sha1": "13e8cda9046f1b0716810e0bd0f19941ebf3bfee",
          "md5": "bead3d01cbc14085ded578a79c2ec2ff"
        }
      ]
    }
  ]
}
