{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "654172e58963315fdb227643220d7de5f4421b590b6c6c9a99a1e2c276fd082d08e84a9a9825b2404b509d876182c00c23cc4f3809bef6e1355d6b6fdf1338cd",
          "sha256": "76133fc55be918df65a60e36b6dca3bc82942d4f1aa0a2e48c310287d3e76fb9",
          "sha1": "f3af00340c49f6d67b8b20ac5459fa6a5a143fb5",
          "md5": "2243bbb4365b5d2786a9118a1caea746"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "654172e58963315fdb227643220d7de5f4421b590b6c6c9a99a1e2c276fd082d08e84a9a9825b2404b509d876182c00c23cc4f3809bef6e1355d6b6fdf1338cd",
          "sha256": "76133fc55be918df65a60e36b6dca3bc82942d4f1aa0a2e48c310287d3e76fb9",
          "sha1": "f3af00340c49f6d67b8b20ac5459fa6a5a143fb5",
          "md5": "2243bbb4365b5d2786a9118a1caea746"
        }
      ]
    }
  ]
}
