{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "e8ca40d7f907cb2cea2ba3cf54c6e028e9647cbbe2cb073ae2500b0c41fdde022e282a558975c63a7e2e8723c52c2c693f5d83b4f7e5450bcae95aed3770fab5",
          "sha256": "2adc38a8c10b3139b655bbc378e26bedc63764c8a82d21847e196bf413df3289",
          "sha1": "b1b77e9fb86c3224c28195ff51111ac015c1abbe",
          "md5": "0a9de3231c94588cc00e77aca225aa91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "e8ca40d7f907cb2cea2ba3cf54c6e028e9647cbbe2cb073ae2500b0c41fdde022e282a558975c63a7e2e8723c52c2c693f5d83b4f7e5450bcae95aed3770fab5",
          "sha256": "2adc38a8c10b3139b655bbc378e26bedc63764c8a82d21847e196bf413df3289",
          "sha1": "b1b77e9fb86c3224c28195ff51111ac015c1abbe",
          "md5": "0a9de3231c94588cc00e77aca225aa91"
        }
      ]
    }
  ]
}
