{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "45ea92b93d8cf92c865a9424407a9ed3ba5168c48e7681c1624b06152f32a34830604ec07439edefc3d1dae525b30910b11c97dce9eaa325f735fd6c19f47441",
          "sha256": "fa67decc30fb3721ec8b8e9f1570fdc8986bb6d4ee0217c0dedcbb9a343cd7ea",
          "sha1": "b0100e0eda49e45f6ba661327819e5a0f40d6118",
          "md5": "7d310c41811f8c2150704608c93b47ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "45ea92b93d8cf92c865a9424407a9ed3ba5168c48e7681c1624b06152f32a34830604ec07439edefc3d1dae525b30910b11c97dce9eaa325f735fd6c19f47441",
          "sha256": "fa67decc30fb3721ec8b8e9f1570fdc8986bb6d4ee0217c0dedcbb9a343cd7ea",
          "sha1": "b0100e0eda49e45f6ba661327819e5a0f40d6118",
          "md5": "7d310c41811f8c2150704608c93b47ae"
        }
      ]
    }
  ]
}
