{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172801,
          "sha512": "443436785310759236bfa7018d47d91cd98aa6198de870d798f9db935dd5e8589e57829e4575d41377ca12351e0675b7e987b3dbc481dd3be882bc9631d779e5",
          "sha256": "745a5d100b12d8db118f716715fa8256cc9dda321afafe67c64885af739ac279",
          "sha1": "dea6d55c22f76af28cadcc0519b8445d83873162",
          "md5": "efa63860f737d53fbfed437bfd8c1448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172801,
          "sha512": "443436785310759236bfa7018d47d91cd98aa6198de870d798f9db935dd5e8589e57829e4575d41377ca12351e0675b7e987b3dbc481dd3be882bc9631d779e5",
          "sha256": "745a5d100b12d8db118f716715fa8256cc9dda321afafe67c64885af739ac279",
          "sha1": "dea6d55c22f76af28cadcc0519b8445d83873162",
          "md5": "efa63860f737d53fbfed437bfd8c1448"
        }
      ]
    }
  ]
}
