{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.0.jar",
          "url": "runescape-api-4.15.0.jar",
          "size": 143787,
          "sha512": "8032cdec2aa11ea066ca54e4772fd7cc984faa6192bfc0492f19460687234ea095e0baed8feb11911382ba556b01bcb21d1ccec7308a7b7b64d9324408eed99c",
          "sha256": "2d633e649855fb0e9578628bb0bf410289eec400520a3fdf5c718dda32f29f17",
          "sha1": "f05a3d53cebad61e8f6813d246e6e73b5f7a6951",
          "md5": "4f941841c7cd77671b8b807b33266391"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.0.jar",
          "url": "runescape-api-4.15.0.jar",
          "size": 143787,
          "sha512": "8032cdec2aa11ea066ca54e4772fd7cc984faa6192bfc0492f19460687234ea095e0baed8feb11911382ba556b01bcb21d1ccec7308a7b7b64d9324408eed99c",
          "sha256": "2d633e649855fb0e9578628bb0bf410289eec400520a3fdf5c718dda32f29f17",
          "sha1": "f05a3d53cebad61e8f6813d246e6e73b5f7a6951",
          "md5": "4f941841c7cd77671b8b807b33266391"
        }
      ]
    }
  ]
}
