{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.0.jar",
          "url": "runescape-api-4.15.0.jar",
          "size": 143787,
          "sha512": "cb15901646469571d8814b2efd058afd2de57872cecc66d2e898a9ef7856a9fc4b62380a8253c6b0eaff82b80f1af60aec324cafd1c1de029d34e4654e217895",
          "sha256": "470097ffaf0c4370c1ef72a01b6c51ca65e02395154a11dd7343885f304837eb",
          "sha1": "3fb95c21225e1611201fdcffea63a2f1712e308b",
          "md5": "038a1f45ff6c2799478a8a10456301d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.0.jar",
          "url": "runescape-api-4.15.0.jar",
          "size": 143787,
          "sha512": "cb15901646469571d8814b2efd058afd2de57872cecc66d2e898a9ef7856a9fc4b62380a8253c6b0eaff82b80f1af60aec324cafd1c1de029d34e4654e217895",
          "sha256": "470097ffaf0c4370c1ef72a01b6c51ca65e02395154a11dd7343885f304837eb",
          "sha1": "3fb95c21225e1611201fdcffea63a2f1712e308b",
          "md5": "038a1f45ff6c2799478a8a10456301d6"
        }
      ]
    }
  ]
}
