{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357249,
          "sha512": "4575c62262a70e93b36199045c421c6e0b04d9154932365f6f16ee9bec8493c2ec3c72ebb3e51253950566ad9fe89e8b7bd42ea61ac5f7a12c8e10b09dd069b7",
          "sha256": "b98956ae7e001fc1ac84d92eb5686a3a0db7d86d65b2f39eba16867871b948c3",
          "sha1": "3933556b619af20fa0d12eeb26bcf2a15f00bae0",
          "md5": "93ab07220424fdcdcad63ebd404b48cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357249,
          "sha512": "4575c62262a70e93b36199045c421c6e0b04d9154932365f6f16ee9bec8493c2ec3c72ebb3e51253950566ad9fe89e8b7bd42ea61ac5f7a12c8e10b09dd069b7",
          "sha256": "b98956ae7e001fc1ac84d92eb5686a3a0db7d86d65b2f39eba16867871b948c3",
          "sha1": "3933556b619af20fa0d12eeb26bcf2a15f00bae0",
          "md5": "93ab07220424fdcdcad63ebd404b48cd"
        }
      ]
    }
  ]
}
