{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357249,
          "sha512": "135f84752f01b1d6b656ae26ae1f4b32872a9c5e4b6278a5ed79a7ffd8f7f7ce7d36f89e27da163f1c89a5880edb0881971c4232384556d89202f4009e9f38f0",
          "sha256": "eb223914a819a0da99fae17e18a134debd72e4639b050860f9f7fe0cf7255057",
          "sha1": "b8d9c6f48fc57ba5f670e22db769f142ad17a589",
          "md5": "c1daac17cdcd6da0740e69d2620fbf4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357249,
          "sha512": "135f84752f01b1d6b656ae26ae1f4b32872a9c5e4b6278a5ed79a7ffd8f7f7ce7d36f89e27da163f1c89a5880edb0881971c4232384556d89202f4009e9f38f0",
          "sha256": "eb223914a819a0da99fae17e18a134debd72e4639b050860f9f7fe0cf7255057",
          "sha1": "b8d9c6f48fc57ba5f670e22db769f142ad17a589",
          "md5": "c1daac17cdcd6da0740e69d2620fbf4e"
        }
      ]
    }
  ]
}
