{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.6.jar",
          "url": "runelite-api-4.15.6.jar",
          "size": 1331360,
          "sha512": "07580b7f46945dac6cef321ba73b1227e47b29fc7344e237f3395ce5a30b30e9c9056227978918fa5a4b2213b5ade904ce0dc30f02e38f71293bff4155ad0bfb",
          "sha256": "fb643c7c250d5aeb4fbc53026ed6649b9be2760c7c334bb716e616384cc87293",
          "sha1": "1dce840e5bccc5b8fe3e49edc1783c36a7c3a247",
          "md5": "82b66ed45a4233a4707e007adfbeb764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.6.jar",
          "url": "runelite-api-4.15.6.jar",
          "size": 1331360,
          "sha512": "07580b7f46945dac6cef321ba73b1227e47b29fc7344e237f3395ce5a30b30e9c9056227978918fa5a4b2213b5ade904ce0dc30f02e38f71293bff4155ad0bfb",
          "sha256": "fb643c7c250d5aeb4fbc53026ed6649b9be2760c7c334bb716e616384cc87293",
          "sha1": "1dce840e5bccc5b8fe3e49edc1783c36a7c3a247",
          "md5": "82b66ed45a4233a4707e007adfbeb764"
        }
      ]
    }
  ]
}
