{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "4.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.9"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.9.9.jar",
          "url": "runelite-client-4.9.9.jar",
          "size": 8057896,
          "sha512": "75108515a2c61d9821311868feed2386a509fceb53ac3b45237e4e0bcd54721da2895dfcbf4f4cc6b85aba8b45ad6308f8bc0273940427a079bbf6e0a5a31668",
          "sha256": "6b5b75163b4fb0f7e564fa69500182afcc94349c81cffe4d44ee2f78ce41d46f",
          "sha1": "d00d04014f191adfcb97f73192d3be39d3256df6",
          "md5": "1b6c777f3f72dd8b98adb0703e183b44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-jshell",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "5.0.4.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "substance",
          "version": {
            "requires": "8.0.02"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "trident",
          "version": {
            "requires": "1.5.00"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt-natives-macosx",
          "version": {
            "requires": "2.4.0-rc-20210117"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all",
          "version": {
            "requires": "2.4.0-rc-20200429"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-all-natives-macosx",
          "version": {
            "requires": "2.4.0-rc-20210117"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-x64"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-arm64"
            }
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.9.9.jar",
          "url": "runelite-client-4.9.9.jar",
          "size": 8057896,
          "sha512": "75108515a2c61d9821311868feed2386a509fceb53ac3b45237e4e0bcd54721da2895dfcbf4f4cc6b85aba8b45ad6308f8bc0273940427a079bbf6e0a5a31668",
          "sha256": "6b5b75163b4fb0f7e564fa69500182afcc94349c81cffe4d44ee2f78ce41d46f",
          "sha1": "d00d04014f191adfcb97f73192d3be39d3256df6",
          "md5": "1b6c777f3f72dd8b98adb0703e183b44"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-4.9.9-shaded.jar",
          "url": "runelite-client-4.9.9-shaded.jar",
          "size": 34832524,
          "sha512": "e8c4ce87861af7213cce2c178cd31498ff38f1d59398ece013ced68a822b7901b78e98d8751325cb4ba4cc3bf26641255cc7061f328dbaebd59ae612cb8e45ed",
          "sha256": "41c71fc51150648b864547506d0cbd7a21dcb7605c61a3d9f34f7cfff2e571d7",
          "sha1": "71d35710b299ed570e17151c29c2b07b3c5299eb",
          "md5": "d5abedde269e903650ac2ab0aafa70b1"
        }
      ]
    }
  ]
}
