{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "60c64c69e84e1117e4cb1b5f8fba0cdcbbf3eb339c90eb3f3e009120348c6404ce61bed18ef41891a0275e6bf1e4eccd8c5626984695e88a86baf6d2f812e70e",
          "sha256": "ee4f21314835d0b8ed8870a3062dfcb511223f9fe4ceace7867b2d8e5b5f3f95",
          "sha1": "17ecfbc13c631708e15e4340f28dfad1f4c92b5f",
          "md5": "b79feb911c23fed4931c9be30041cfb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.15.3.jar",
          "url": "runelite-api-4.15.3.jar",
          "size": 1331183,
          "sha512": "60c64c69e84e1117e4cb1b5f8fba0cdcbbf3eb339c90eb3f3e009120348c6404ce61bed18ef41891a0275e6bf1e4eccd8c5626984695e88a86baf6d2f812e70e",
          "sha256": "ee4f21314835d0b8ed8870a3062dfcb511223f9fe4ceace7867b2d8e5b5f3f95",
          "sha1": "17ecfbc13c631708e15e4340f28dfad1f4c92b5f",
          "md5": "b79feb911c23fed4931c9be30041cfb8"
        }
      ]
    }
  ]
}
