{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149498,
          "sha512": "ab8ed72e5ec9340204a021a17327bd8b6f9e8f98c4c405165e1540a4b7393b0f950ad975fcf25b691f22cb26abd36881e6d3bc6404f6a659ee605ff32a94414f",
          "sha256": "efdfe39e71ab3ef1c19bd8597d4cccc6637d5742c41a1d84feb5a7e127fc1275",
          "sha1": "2b2a2af5a9aea991aadac6aa2f2aa374910a5f0a",
          "md5": "aaf38c15a0415d9ac3a77f9b9bd46c8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149498,
          "sha512": "ab8ed72e5ec9340204a021a17327bd8b6f9e8f98c4c405165e1540a4b7393b0f950ad975fcf25b691f22cb26abd36881e6d3bc6404f6a659ee605ff32a94414f",
          "sha256": "efdfe39e71ab3ef1c19bd8597d4cccc6637d5742c41a1d84feb5a7e127fc1275",
          "sha1": "2b2a2af5a9aea991aadac6aa2f2aa374910a5f0a",
          "md5": "aaf38c15a0415d9ac3a77f9b9bd46c8e"
        }
      ]
    }
  ]
}
