{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149546,
          "sha512": "5494c11d886429c14873e29b0f88e496cd517e02f1661610cf1918619de8d3eeea3b58175194faaf2a4e92a0065b1023904a93cffe9db2494d02ace20635d6fe",
          "sha256": "2ee12df3182de61504d1789d8d312f9e4f8ced7d453d819e02ce8de036ef3e4c",
          "sha1": "fcf1a6ee387f93fcf60e8d82b28a047ba1bb352b",
          "md5": "5cce440f3b27f889928d3e46348bdc6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149546,
          "sha512": "5494c11d886429c14873e29b0f88e496cd517e02f1661610cf1918619de8d3eeea3b58175194faaf2a4e92a0065b1023904a93cffe9db2494d02ace20635d6fe",
          "sha256": "2ee12df3182de61504d1789d8d312f9e4f8ced7d453d819e02ce8de036ef3e4c",
          "sha1": "fcf1a6ee387f93fcf60e8d82b28a047ba1bb352b",
          "md5": "5cce440f3b27f889928d3e46348bdc6a"
        }
      ]
    }
  ]
}
