{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149498,
          "sha512": "d70a59ed7df7be793be1858cac548da123f7f583e98fadea361062ef7957d4b473920bc17505f6f050010e988655a38a8dcbee22bd48e35b34e499a3f18f8f50",
          "sha256": "12f8826532c6413715d4137fd6a75fe64ca070138caca21c0bb50e8396c4c0ce",
          "sha1": "858e111ab1b0ed5d24b0b6e600380fe3ad8e7b53",
          "md5": "d3e341f5280afd4f967e1650f62a9e5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.23.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.23.0.jar",
          "url": "runescape-api-4.23.0.jar",
          "size": 149498,
          "sha512": "d70a59ed7df7be793be1858cac548da123f7f583e98fadea361062ef7957d4b473920bc17505f6f050010e988655a38a8dcbee22bd48e35b34e499a3f18f8f50",
          "sha256": "12f8826532c6413715d4137fd6a75fe64ca070138caca21c0bb50e8396c4c0ce",
          "sha1": "858e111ab1b0ed5d24b0b6e600380fe3ad8e7b53",
          "md5": "d3e341f5280afd4f967e1650f62a9e5e"
        }
      ]
    }
  ]
}
