{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "5df0c96b6756e69a2ff9406fd21fab6e6a9b583bb8c0f7c480244331953df56af25d29201a2438c94cd86da3b9d3d8a1184513aaa917af79f2483130265167c3",
          "sha256": "1437fbc709f65475ca7ea21e12b02d80bf5bd96183d874755d3b0aeaa415e42e",
          "sha1": "4f3a0eaf6c4b01db005a4a620f9e44795b5cbda8",
          "md5": "1af0f1d2a600f57480f0444627804caf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "5df0c96b6756e69a2ff9406fd21fab6e6a9b583bb8c0f7c480244331953df56af25d29201a2438c94cd86da3b9d3d8a1184513aaa917af79f2483130265167c3",
          "sha256": "1437fbc709f65475ca7ea21e12b02d80bf5bd96183d874755d3b0aeaa415e42e",
          "sha1": "4f3a0eaf6c4b01db005a4a620f9e44795b5cbda8",
          "md5": "1af0f1d2a600f57480f0444627804caf"
        }
      ]
    }
  ]
}
