{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "6e96fe0bade1ea075c7a5f0c0c43305ce8a5b634d3f0e626c8df506c72818004c81fe2fda3b3ffcb242da7da8f999d2808e976c79a6a8dd9f660b0a56cf5ed6a",
          "sha256": "9830c857cd7b1f9ec2e14bd8bded27b2b02fe86c0c5de482bf36b525ad6dcb81",
          "sha1": "832b10c07f35aa84ba046ec2181db5410ccdc2ac",
          "md5": "7518071bb33c70616a0720c8b73b0c20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "6e96fe0bade1ea075c7a5f0c0c43305ce8a5b634d3f0e626c8df506c72818004c81fe2fda3b3ffcb242da7da8f999d2808e976c79a6a8dd9f660b0a56cf5ed6a",
          "sha256": "9830c857cd7b1f9ec2e14bd8bded27b2b02fe86c0c5de482bf36b525ad6dcb81",
          "sha1": "832b10c07f35aa84ba046ec2181db5410ccdc2ac",
          "md5": "7518071bb33c70616a0720c8b73b0c20"
        }
      ]
    }
  ]
}
