{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.13"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.13.jar",
          "url": "runescape-api-4.9.13.jar",
          "size": 109489,
          "sha512": "069d2edc16d602c572865945b0876763716877ece81a076f96d065414973054ae4999ba969f16a2980eee43e8907e5c025888a9af75867089df20e70cd6d892e",
          "sha256": "0043019675640b9171e6b12dd0428b8506249c96e8ed6e4112b005b8b842debb",
          "sha1": "7f969ce06d6d1baa7676431f0d7fcff5e35255bd",
          "md5": "82175b6fc6453a0c9e20c23a186fea84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.13"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.9.13.jar",
          "url": "runescape-api-4.9.13.jar",
          "size": 109489,
          "sha512": "069d2edc16d602c572865945b0876763716877ece81a076f96d065414973054ae4999ba969f16a2980eee43e8907e5c025888a9af75867089df20e70cd6d892e",
          "sha256": "0043019675640b9171e6b12dd0428b8506249c96e8ed6e4112b005b8b842debb",
          "sha1": "7f969ce06d6d1baa7676431f0d7fcff5e35255bd",
          "md5": "82175b6fc6453a0c9e20c23a186fea84"
        }
      ]
    }
  ]
}
