{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rnnqq2tzebhmrg7wvrk7ug3h4e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.2.0.jar",
          "url": "runescape-api-4.2.0.jar",
          "size": 107741,
          "sha512": "dd7aa6cbf6f14ec4c2a38eb27d8ddaae2ae583d30eb6f51427156e35fdbe063863bef5b7d7b3d6c691988a40669b313d24512d71a6289cb54c2d26b478d37c78",
          "sha256": "5b058d840556390e60cec15597020a65cddcff45c1194734a0976fda227604bd",
          "sha1": "1e0a257c26fed5cfadb14a6d653a29c7daac93c0",
          "md5": "da5e45b00f2cf488d0c05b1b14ed4a5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.2.0.jar",
          "url": "runescape-api-4.2.0.jar",
          "size": 107741,
          "sha512": "dd7aa6cbf6f14ec4c2a38eb27d8ddaae2ae583d30eb6f51427156e35fdbe063863bef5b7d7b3d6c691988a40669b313d24512d71a6289cb54c2d26b478d37c78",
          "sha256": "5b058d840556390e60cec15597020a65cddcff45c1194734a0976fda227604bd",
          "sha1": "1e0a257c26fed5cfadb14a6d653a29c7daac93c0",
          "md5": "da5e45b00f2cf488d0c05b1b14ed4a5b"
        }
      ]
    }
  ]
}
