{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.0.jar",
          "url": "http-api-4.15.0.jar",
          "size": 172799,
          "sha512": "c1cd1896fd071931788cf55b8e3eadb296706150a0285429e4aee2fd372de631b2999a0af00443ffc542d936d70166580c711172fe3503ec389ff238607642a3",
          "sha256": "2e7528b243e48fc0f7fc248d4af5ec51957999296541efeb766620f33ff2ebbb",
          "sha1": "9d9537d908e732e6db26871169c883217153c9c5",
          "md5": "250b30362aa23fe1dfad7e53e0de85ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.0.jar",
          "url": "http-api-4.15.0.jar",
          "size": 172799,
          "sha512": "c1cd1896fd071931788cf55b8e3eadb296706150a0285429e4aee2fd372de631b2999a0af00443ffc542d936d70166580c711172fe3503ec389ff238607642a3",
          "sha256": "2e7528b243e48fc0f7fc248d4af5ec51957999296541efeb766620f33ff2ebbb",
          "sha1": "9d9537d908e732e6db26871169c883217153c9c5",
          "md5": "250b30362aa23fe1dfad7e53e0de85ac"
        }
      ]
    }
  ]
}
