{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.0.jar",
          "url": "http-api-4.15.0.jar",
          "size": 172799,
          "sha512": "374096dc186722864a01a55443824b6598fc9c03c3707a07db598df41f7ef73a1b4a7879027d3b540b69d1875f7789776a8de673c008c3e8a160d8d1e653ed3a",
          "sha256": "dff7aa9af63bc6c36dd832c5cb22bff1204ef6ed00959352132894c1dd56c9c9",
          "sha1": "b22ec62e3cfe073a2a933bed5e71a19c8bf29de7",
          "md5": "b35be6a769fcc6ef3553f9f5958884fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.0.jar",
          "url": "http-api-4.15.0.jar",
          "size": 172799,
          "sha512": "374096dc186722864a01a55443824b6598fc9c03c3707a07db598df41f7ef73a1b4a7879027d3b540b69d1875f7789776a8de673c008c3e8a160d8d1e653ed3a",
          "sha256": "dff7aa9af63bc6c36dd832c5cb22bff1204ef6ed00959352132894c1dd56c9c9",
          "sha1": "b22ec62e3cfe073a2a933bed5e71a19c8bf29de7",
          "md5": "b35be6a769fcc6ef3553f9f5958884fa"
        }
      ]
    }
  ]
}
