{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.18.2.jar",
          "url": "http-api-4.18.2.jar",
          "size": 99206,
          "sha512": "3a32e7bbb22b3e4edb30846833e8c5d5f7cda3bb8b10c4608cb1414d6021a8c5e5e76c09d22f9f4f09f6b6c8a54ba8604a7ff639b6714403fd79ffb167d482af",
          "sha256": "9dca2dae066dcf1e59596aafc92670a4b9fcb64dc09c6a5c26ea3d90f3bcf966",
          "sha1": "6829049f982999b85110feec5f0cdfe96c105336",
          "md5": "a86603ef02744645b8d02dde589dccb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.18.2.jar",
          "url": "http-api-4.18.2.jar",
          "size": 99206,
          "sha512": "3a32e7bbb22b3e4edb30846833e8c5d5f7cda3bb8b10c4608cb1414d6021a8c5e5e76c09d22f9f4f09f6b6c8a54ba8604a7ff639b6714403fd79ffb167d482af",
          "sha256": "9dca2dae066dcf1e59596aafc92670a4b9fcb64dc09c6a5c26ea3d90f3bcf966",
          "sha1": "6829049f982999b85110feec5f0cdfe96c105336",
          "md5": "a86603ef02744645b8d02dde589dccb9"
        }
      ]
    }
  ]
}
