{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.1.jar",
          "url": "runelite-jshell-4.25.1.jar",
          "size": 26557,
          "sha512": "d7eb771ab986140826dfbad58477d333a7f03537f3e44895cf319d5ad6e7f8b4fbf3aca94e92dac4822a4523fbe262dcf8ad3878223f9cc890e452607dddde0b",
          "sha256": "5c1d73609072fbbcc56a51db9e948938823538d2ed8e61aef455a554b454faa3",
          "sha1": "999ee63f5a07f3c9f74e952c731a790a6e50c210",
          "md5": "bf3a56ba833a78c9bd82757af02a8de2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.1.jar",
          "url": "runelite-jshell-4.25.1.jar",
          "size": 26557,
          "sha512": "d7eb771ab986140826dfbad58477d333a7f03537f3e44895cf319d5ad6e7f8b4fbf3aca94e92dac4822a4523fbe262dcf8ad3878223f9cc890e452607dddde0b",
          "sha256": "5c1d73609072fbbcc56a51db9e948938823538d2ed8e61aef455a554b454faa3",
          "sha1": "999ee63f5a07f3c9f74e952c731a790a6e50c210",
          "md5": "bf3a56ba833a78c9bd82757af02a8de2"
        }
      ]
    }
  ]
}
