{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "71fbab8a1700f5d7ebdb09618a2752751cf380600c8e9edbe3fbe84847a1c9d070cd2706f0321898bf8817a316d33112618b5bc175df20a3829743ef6d9595d0",
          "sha256": "857c70fddb3728bdccea6c8b6a87a2a5e5c9d76185c4f2214201fc20d9941517",
          "sha1": "8c1dcb670448a7ca75538e0ea9515577b1cc1e86",
          "md5": "061fe9c6671f082e3b8081080762de90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "71fbab8a1700f5d7ebdb09618a2752751cf380600c8e9edbe3fbe84847a1c9d070cd2706f0321898bf8817a316d33112618b5bc175df20a3829743ef6d9595d0",
          "sha256": "857c70fddb3728bdccea6c8b6a87a2a5e5c9d76185c4f2214201fc20d9941517",
          "sha1": "8c1dcb670448a7ca75538e0ea9515577b1cc1e86",
          "md5": "061fe9c6671f082e3b8081080762de90"
        }
      ]
    }
  ]
}
