{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "5bbe80268022ae25ff8fd3ada027883aedb339b0129e18ebfff494362e3a61b3866b12cc292783cb245ba9b81caa7a131dc262acd93e1e46f4526d547408c3d8",
          "sha256": "570cd0e4b28d2730b837962d31f6a50fc416b226b63de77e14f9f7d6f61926c5",
          "sha1": "6979670e655b8c2d417b0c6476434358df4ce45a",
          "md5": "0117229fc68c01b6adb667ae874b8b3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.0.jar",
          "url": "http-api-4.9.0.jar",
          "size": 157340,
          "sha512": "5bbe80268022ae25ff8fd3ada027883aedb339b0129e18ebfff494362e3a61b3866b12cc292783cb245ba9b81caa7a131dc262acd93e1e46f4526d547408c3d8",
          "sha256": "570cd0e4b28d2730b837962d31f6a50fc416b226b63de77e14f9f7d6f61926c5",
          "sha1": "6979670e655b8c2d417b0c6476434358df4ce45a",
          "md5": "0117229fc68c01b6adb667ae874b8b3f"
        }
      ]
    }
  ]
}
