{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.0.jar",
          "url": "http-api-4.16.0.jar",
          "size": 172800,
          "sha512": "2b9dafb139eeab0453d6726c0d89ba0738d87667e5921b231cd29011c3c0f2786650b143fafb3f23250892dc9cc6ef94b201331b4ec3061fc05bfbdf2dbcb231",
          "sha256": "9f70ea52e9646a0898d6713a2c361122cf09fdbf39c5a40b8313fed06dcdc07a",
          "sha1": "dbd193db90e1c0e9d27c963746ab7729a136d3cd",
          "md5": "95dd4db2f71ca8206474b89ce3ac423e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.0.jar",
          "url": "http-api-4.16.0.jar",
          "size": 172800,
          "sha512": "2b9dafb139eeab0453d6726c0d89ba0738d87667e5921b231cd29011c3c0f2786650b143fafb3f23250892dc9cc6ef94b201331b4ec3061fc05bfbdf2dbcb231",
          "sha256": "9f70ea52e9646a0898d6713a2c361122cf09fdbf39c5a40b8313fed06dcdc07a",
          "sha1": "dbd193db90e1c0e9d27c963746ab7729a136d3cd",
          "md5": "95dd4db2f71ca8206474b89ce3ac423e"
        }
      ]
    }
  ]
}
