{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.16.0.jar",
          "url": "http-api-4.16.0.jar",
          "size": 172794,
          "sha512": "9a1d9214620b2b769c38173d34977add79defd27f0108d61e1c11846979765fa5172f58ac305f6e6e3a936eec7bbcc657e464db97f7d0453e323556858bad6c3",
          "sha256": "9075eaeb85a4947d1dbc13573761e35484a3a29215aba3cab106b5bd01a4b85a",
          "sha1": "5b2930b7ca1440dc573335b7093f290a6072e341",
          "md5": "33bd5f745b019374d21c33036eb8ca57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.16.0.jar",
          "url": "http-api-4.16.0.jar",
          "size": 172794,
          "sha512": "9a1d9214620b2b769c38173d34977add79defd27f0108d61e1c11846979765fa5172f58ac305f6e6e3a936eec7bbcc657e464db97f7d0453e323556858bad6c3",
          "sha256": "9075eaeb85a4947d1dbc13573761e35484a3a29215aba3cab106b5bd01a4b85a",
          "sha1": "5b2930b7ca1440dc573335b7093f290a6072e341",
          "md5": "33bd5f745b019374d21c33036eb8ca57"
        }
      ]
    }
  ]
}
