{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.5.jar",
          "url": "runelite-api-4.9.5.jar",
          "size": 1274650,
          "sha512": "de3d8a4e2144b0ee1f8f2f17050af461e03291b8767fb6848109957dafd0636ad4aa322143abd3dc5fee8c1b9f5770a4212f5dfd081392fc4fd8d034ae00e399",
          "sha256": "c1d99f8413a58ec318318675e00f483f9e5901afda589f5043984b88b555db31",
          "sha1": "5f52c0d8a08f53955c2e7a3eb7ce28b8f7965864",
          "md5": "bb38e7b6dc288ee7223aa5f1c95ce06b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.5.jar",
          "url": "runelite-api-4.9.5.jar",
          "size": 1274650,
          "sha512": "de3d8a4e2144b0ee1f8f2f17050af461e03291b8767fb6848109957dafd0636ad4aa322143abd3dc5fee8c1b9f5770a4212f5dfd081392fc4fd8d034ae00e399",
          "sha256": "c1d99f8413a58ec318318675e00f483f9e5901afda589f5043984b88b555db31",
          "sha1": "5f52c0d8a08f53955c2e7a3eb7ce28b8f7965864",
          "md5": "bb38e7b6dc288ee7223aa5f1c95ce06b"
        }
      ]
    }
  ]
}
