{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.12.0.jar",
          "url": "http-api-4.12.0.jar",
          "size": 158715,
          "sha512": "47efb47e8b053d3a209e7149632b309ec9c83c31d9f363ea391991fb1e079034bbd51cddeba79ca30a4da9e30523d08b5e0ebafb8cb815ef90c69269704e6986",
          "sha256": "334e4ca26ca8afd853fa3c1b1436e1ceb0c1274f0151ffd5fee72bb11580dc87",
          "sha1": "2d1f9a9668b679052f9659f462768d3cb0724ebd",
          "md5": "24aaf03fa58e0398ed1e2c3bcea555d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.12.0.jar",
          "url": "http-api-4.12.0.jar",
          "size": 158715,
          "sha512": "47efb47e8b053d3a209e7149632b309ec9c83c31d9f363ea391991fb1e079034bbd51cddeba79ca30a4da9e30523d08b5e0ebafb8cb815ef90c69269704e6986",
          "sha256": "334e4ca26ca8afd853fa3c1b1436e1ceb0c1274f0151ffd5fee72bb11580dc87",
          "sha1": "2d1f9a9668b679052f9659f462768d3cb0724ebd",
          "md5": "24aaf03fa58e0398ed1e2c3bcea555d6"
        }
      ]
    }
  ]
}
