{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.12.0.jar",
          "url": "http-api-4.12.0.jar",
          "size": 158714,
          "sha512": "cea6d5783f25155451b4950ee52198d8fdc8311325fcd9f759783e520f34cf775649c47827a824cd53d53467f9c6e8d11f87d8d35230bb2b7b260743152d4ae1",
          "sha256": "e8505406d679d375d50b02ce815396c1e3ab6dc953e37e254da50f99ac7df81e",
          "sha1": "6973b17039c2ebb06460ad2d37104a102e72c86e",
          "md5": "2249af617055a00cadec8dc830ba3c7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.12.0.jar",
          "url": "http-api-4.12.0.jar",
          "size": 158714,
          "sha512": "cea6d5783f25155451b4950ee52198d8fdc8311325fcd9f759783e520f34cf775649c47827a824cd53d53467f9c6e8d11f87d8d35230bb2b7b260743152d4ae1",
          "sha256": "e8505406d679d375d50b02ce815396c1e3ab6dc953e37e254da50f99ac7df81e",
          "sha1": "6973b17039c2ebb06460ad2d37104a102e72c86e",
          "md5": "2249af617055a00cadec8dc830ba3c7b"
        }
      ]
    }
  ]
}
