{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "91d2d215d04416d73071f4a35a7ac36ca0a254380a83c63cc876496cd91ff34ab43942186a0576f18a273b8768caa226ab0fa544d9b169bc1f18bdfa8426c153",
          "sha256": "c9102105fda552652a22b86570cef3102ea93437e9ecacf4e52b0680e24a85e2",
          "sha1": "6ac4ec681ee7e53e6f3ec760564f14ce7ded9f66",
          "md5": "9139aa828188e4c78c00b5a89be36998"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "91d2d215d04416d73071f4a35a7ac36ca0a254380a83c63cc876496cd91ff34ab43942186a0576f18a273b8768caa226ab0fa544d9b169bc1f18bdfa8426c153",
          "sha256": "c9102105fda552652a22b86570cef3102ea93437e9ecacf4e52b0680e24a85e2",
          "sha1": "6ac4ec681ee7e53e6f3ec760564f14ce7ded9f66",
          "md5": "9139aa828188e4c78c00b5a89be36998"
        }
      ]
    }
  ]
}
