{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "ac3e5452b37d6d7b0da37fb7b371bfc988fea2ea594ed41daf5d3278e3f211789f264c2b0b0468d48af38d11e438682c889982b508076cb44358aa7828455290",
          "sha256": "23319fb824ba89cac0a077907ce33be5ca8978242c364960b054dfc29b391591",
          "sha1": "7b17815d6cd297ddeed22af70bed3a4e5f02a26e",
          "md5": "713bf55d2abdfcb7970ca9f71852c7fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "ac3e5452b37d6d7b0da37fb7b371bfc988fea2ea594ed41daf5d3278e3f211789f264c2b0b0468d48af38d11e438682c889982b508076cb44358aa7828455290",
          "sha256": "23319fb824ba89cac0a077907ce33be5ca8978242c364960b054dfc29b391591",
          "sha1": "7b17815d6cd297ddeed22af70bed3a4e5f02a26e",
          "md5": "713bf55d2abdfcb7970ca9f71852c7fe"
        }
      ]
    }
  ]
}
