{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "bd0391114ee4458bde63f2808ce4d211ef03df2120e75cc6ff92cd61c696d46da438918980a31b6afc49b5eb223f7825f4474bb4bce424c416e3b688151bb953",
          "sha256": "4f51ade1c3801b7b61e6ad05efeef1b427e7d1c7c5e72e875c2cb2791f79b17f",
          "sha1": "7218a43aabab8674fc8d2e4d3ab05ff28b526315",
          "md5": "7ce9d212c3f48b28822ab7d33923e034"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.18.1.jar",
          "url": "runelite-jshell-4.18.1.jar",
          "size": 26552,
          "sha512": "bd0391114ee4458bde63f2808ce4d211ef03df2120e75cc6ff92cd61c696d46da438918980a31b6afc49b5eb223f7825f4474bb4bce424c416e3b688151bb953",
          "sha256": "4f51ade1c3801b7b61e6ad05efeef1b427e7d1c7c5e72e875c2cb2791f79b17f",
          "sha1": "7218a43aabab8674fc8d2e4d3ab05ff28b526315",
          "md5": "7ce9d212c3f48b28822ab7d33923e034"
        }
      ]
    }
  ]
}
