{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "cf09f961d4ff33cd6888407d505031066cc11da56db2656551843343db6a70204ed02f0e101efd6eb44e70c859e00c8be0d0c80babb9c9123d9f65a7d7b80d89",
          "sha256": "92400b1a0c31d9f45df537107d6fc14c44749cbaf9b11abc11cf3b1ed48a89fb",
          "sha1": "47c4968c754e773c26526ff064290f9fb556c1f0",
          "md5": "4cd4daa463323f93f2aca91c544e5009"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "cf09f961d4ff33cd6888407d505031066cc11da56db2656551843343db6a70204ed02f0e101efd6eb44e70c859e00c8be0d0c80babb9c9123d9f65a7d7b80d89",
          "sha256": "92400b1a0c31d9f45df537107d6fc14c44749cbaf9b11abc11cf3b1ed48a89fb",
          "sha1": "47c4968c754e773c26526ff064290f9fb556c1f0",
          "md5": "4cd4daa463323f93f2aca91c544e5009"
        }
      ]
    }
  ]
}
