{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "a7fa8974dd1471c7074d54fac50e8e713bdb483390997cf8b7efd3f02d9916d200353f9c30216d3bc3bd00b1cbdf4d5e60deffc4037fef9fb31c9c2fd378d128",
          "sha256": "7da57153bccbdde5f11e4b98d5445c9143184f1cefef3e1cadf1ed7ba3d13470",
          "sha1": "7b8c9028c6362055f85d8df3cd1f6e9f56dcf4fd",
          "md5": "bc9b56a453489d060904a41200125340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "a7fa8974dd1471c7074d54fac50e8e713bdb483390997cf8b7efd3f02d9916d200353f9c30216d3bc3bd00b1cbdf4d5e60deffc4037fef9fb31c9c2fd378d128",
          "sha256": "7da57153bccbdde5f11e4b98d5445c9143184f1cefef3e1cadf1ed7ba3d13470",
          "sha1": "7b8c9028c6362055f85d8df3cd1f6e9f56dcf4fd",
          "md5": "bc9b56a453489d060904a41200125340"
        }
      ]
    }
  ]
}
