{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "571004a70541a98be9a86a83d06fccb836c5ffd85ea0f61058a7bbe9fdeb7fbe5b9b8c68eccdcec08d74462f2ac38f59c09224b034eda6c085a4ee3297cc489a",
          "sha256": "827aa60d6799f0e5d65da6a7f603bea57095799666bd97337179d8a036bc7bfb",
          "sha1": "77fa1ea5d8151cf888be11a7a52bb6bb407739ff",
          "md5": "f3fca9b455f67de8e98299b815885ad6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.18.1.jar",
          "url": "runelite-api-4.18.1.jar",
          "size": 1335318,
          "sha512": "571004a70541a98be9a86a83d06fccb836c5ffd85ea0f61058a7bbe9fdeb7fbe5b9b8c68eccdcec08d74462f2ac38f59c09224b034eda6c085a4ee3297cc489a",
          "sha256": "827aa60d6799f0e5d65da6a7f603bea57095799666bd97337179d8a036bc7bfb",
          "sha1": "77fa1ea5d8151cf888be11a7a52bb6bb407739ff",
          "md5": "f3fca9b455f67de8e98299b815885ad6"
        }
      ]
    }
  ]
}
