{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357278,
          "sha512": "08079a25468e0703379cfad4b0af179f01d0acaafe48a8c743de0fd8dee867c7a95dd1cc588f1117556ec2e655513d99782b5af2e336ede98057619f9508e0b2",
          "sha256": "ebfdc5b362dae10c04822fe89153c9823596af57c9a38370533fc5351c955f3c",
          "sha1": "a69706b704779c28853417efbd318ab9580870b9",
          "md5": "a0946970d3d1ecf8d299cbe6ea994f37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357278,
          "sha512": "08079a25468e0703379cfad4b0af179f01d0acaafe48a8c743de0fd8dee867c7a95dd1cc588f1117556ec2e655513d99782b5af2e336ede98057619f9508e0b2",
          "sha256": "ebfdc5b362dae10c04822fe89153c9823596af57c9a38370533fc5351c955f3c",
          "sha1": "a69706b704779c28853417efbd318ab9580870b9",
          "md5": "a0946970d3d1ecf8d299cbe6ea994f37"
        }
      ]
    }
  ]
}
