{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357159,
          "sha512": "375d72368b83a54bc37a2994fbb348183007108f76a091f5002373fa1cd74ae54de0f8ef3c28a145d227a4a5dbd72a3cf3464568a26454974f10c052c0f866f0",
          "sha256": "8c0b2dbf8adf82680ad4ec18123fec4a5eee4152533b399afb3688b3c41e2142",
          "sha1": "ce72538004faaa3d1dd148a90c1071a54dae8f76",
          "md5": "fc4177870bc291420f4541cdefb79f47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1.jar",
          "url": "runelite-api-4.26.1.jar",
          "size": 1357159,
          "sha512": "375d72368b83a54bc37a2994fbb348183007108f76a091f5002373fa1cd74ae54de0f8ef3c28a145d227a4a5dbd72a3cf3464568a26454974f10c052c0f866f0",
          "sha256": "8c0b2dbf8adf82680ad4ec18123fec4a5eee4152533b399afb3688b3c41e2142",
          "sha1": "ce72538004faaa3d1dd148a90c1071a54dae8f76",
          "md5": "fc4177870bc291420f4541cdefb79f47"
        }
      ]
    }
  ]
}
