{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.8.0.jar",
          "url": "http-api-4.8.0.jar",
          "size": 159634,
          "sha512": "80a182c9358da9f1933f317706d4f3ec1bd541ad6669de1605b4b940b6b6a7e3c460a6a1e6dcd22079762e636f94e4f7c3d5f6c800892cdb0e76488f6a5c94d5",
          "sha256": "7a5f16437f5a171fef26482047d62eb45909443d594dc4d71cb4d08733f8b5df",
          "sha1": "abdd9d912fdc11985bdff1243acc2bcd58675c41",
          "md5": "e0f91e1aca8c2dcccc2d627d8f49f3ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.8.0.jar",
          "url": "http-api-4.8.0.jar",
          "size": 159634,
          "sha512": "80a182c9358da9f1933f317706d4f3ec1bd541ad6669de1605b4b940b6b6a7e3c460a6a1e6dcd22079762e636f94e4f7c3d5f6c800892cdb0e76488f6a5c94d5",
          "sha256": "7a5f16437f5a171fef26482047d62eb45909443d594dc4d71cb4d08733f8b5df",
          "sha1": "abdd9d912fdc11985bdff1243acc2bcd58675c41",
          "md5": "e0f91e1aca8c2dcccc2d627d8f49f3ba"
        }
      ]
    }
  ]
}
