{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.3.jar",
          "url": "http-api-4.9.3.jar",
          "size": 157567,
          "sha512": "35504b34ffb336e937c865d094c12e3e2e238c99aef5d3a9dd513bd49802d0afdcf1949d057bf9f402854bf983fd850c5ce775798b97a71305c63404bd33558b",
          "sha256": "ad1504e2b663d4373c1ffafd7eec6a582f8f7a57ec27f400b1f13066758bf89b",
          "sha1": "834f618f740739e0054352567ec3bc6c7e87df84",
          "md5": "704588422c7225e38bdb9b2d24a17b56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.3.jar",
          "url": "http-api-4.9.3.jar",
          "size": 157567,
          "sha512": "35504b34ffb336e937c865d094c12e3e2e238c99aef5d3a9dd513bd49802d0afdcf1949d057bf9f402854bf983fd850c5ce775798b97a71305c63404bd33558b",
          "sha256": "ad1504e2b663d4373c1ffafd7eec6a582f8f7a57ec27f400b1f13066758bf89b",
          "sha1": "834f618f740739e0054352567ec3bc6c7e87df84",
          "md5": "704588422c7225e38bdb9b2d24a17b56"
        }
      ]
    }
  ]
}
