{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rktcpl45hnbmpe4o3j6ndsbf5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.0.0.jar",
          "url": "runescape-api-4.0.0.jar",
          "size": 107534,
          "sha512": "b9b36a9ca00745e82b1d0b71c68f39b2569f8639c5d2ba90c3fe842d5fbd2f17e0cb17a9d17942e0b5b6673b4c8db5575620941bd7c642d40d95353c4bffa6e5",
          "sha256": "60d58e603b99e7cc8f63ea5e9bf1640227733c34584ef1ba22d843cb7e93e2cb",
          "sha1": "0b9797889028bbdc82723e820b0421d5c4858008",
          "md5": "35214c24b82caac2733ffc68e723e4c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.0.0.jar",
          "url": "runescape-api-4.0.0.jar",
          "size": 107534,
          "sha512": "b9b36a9ca00745e82b1d0b71c68f39b2569f8639c5d2ba90c3fe842d5fbd2f17e0cb17a9d17942e0b5b6673b4c8db5575620941bd7c642d40d95353c4bffa6e5",
          "sha256": "60d58e603b99e7cc8f63ea5e9bf1640227733c34584ef1ba22d843cb7e93e2cb",
          "sha1": "0b9797889028bbdc82723e820b0421d5c4858008",
          "md5": "35214c24b82caac2733ffc68e723e4c8"
        }
      ]
    }
  ]
}
