{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "28434f72ae972572722879d924aeadbb2668fce80a45efae3d7ab531392219355600482cac83ee2fd7ddd678c31a7cd71cd84651c98b6f39df8d60ecd2c903e3",
          "sha256": "26ca4abe9506888e3fa88f27e0b356ee9df3abac9ad7468d69a5c4b32adb705e",
          "sha1": "bc220acaed172f83777dafe8e8752a765f8b0157",
          "md5": "fe526b11e895b09931011f49912fb5fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "28434f72ae972572722879d924aeadbb2668fce80a45efae3d7ab531392219355600482cac83ee2fd7ddd678c31a7cd71cd84651c98b6f39df8d60ecd2c903e3",
          "sha256": "26ca4abe9506888e3fa88f27e0b356ee9df3abac9ad7468d69a5c4b32adb705e",
          "sha1": "bc220acaed172f83777dafe8e8752a765f8b0157",
          "md5": "fe526b11e895b09931011f49912fb5fb"
        }
      ]
    }
  ]
}
