{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "243c73e19356f1902f47be72ec3f858f25675defe61db45ab0176bae571233c0b205d3de939499d0156ff699bea86cf09e11db5fc645f2b8b32786849eba3b90",
          "sha256": "88e11b0c2e28931d06208294c6994e6acd0a841b46a48d70e592958298a6b8be",
          "sha1": "55245fcd857347762fda1a8c6f6b18a87ba18239",
          "md5": "46d78b6fda6df7a3b41036f91e06e9ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "243c73e19356f1902f47be72ec3f858f25675defe61db45ab0176bae571233c0b205d3de939499d0156ff699bea86cf09e11db5fc645f2b8b32786849eba3b90",
          "sha256": "88e11b0c2e28931d06208294c6994e6acd0a841b46a48d70e592958298a6b8be",
          "sha1": "55245fcd857347762fda1a8c6f6b18a87ba18239",
          "md5": "46d78b6fda6df7a3b41036f91e06e9ce"
        }
      ]
    }
  ]
}
