{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "49f95b20135bdab3b5930bb296ac763d18c6de7f320275364a2f7e9550c9ef904686fc0e2800ab7a61588a5148c361513ed35d372fcebccc061a89629f2589bc",
          "sha256": "b071dc989779c2d14ed7a76ea8b8c5c242d7f9b99e3519b634f13edf2d6ca757",
          "sha1": "2116085efe41292b76d8aa91252ecb73f3e41903",
          "md5": "d06463040029efa8bc77fc9362210848"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.2.jar",
          "url": "http-api-4.20.2.jar",
          "size": 99205,
          "sha512": "49f95b20135bdab3b5930bb296ac763d18c6de7f320275364a2f7e9550c9ef904686fc0e2800ab7a61588a5148c361513ed35d372fcebccc061a89629f2589bc",
          "sha256": "b071dc989779c2d14ed7a76ea8b8c5c242d7f9b99e3519b634f13edf2d6ca757",
          "sha1": "2116085efe41292b76d8aa91252ecb73f3e41903",
          "md5": "d06463040029efa8bc77fc9362210848"
        }
      ]
    }
  ]
}
