{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "fbcb610832d8679ecfa83c6c9a34828f801172404336d4b391ce13e2f14197b5d2254603534200805b15ab55ea294204e73b2ca6aeedab7bf430ae3643ea5c13",
          "sha256": "dc9bf71c32966e15fa4015f398b1c14875cbbedbf8a12383a39ccf310984115a",
          "sha1": "3a2ea506916e6e0b01496d4d3776ba56e45ca7db",
          "md5": "1146714623cb8ab9f7a1302b7ace9136"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "fbcb610832d8679ecfa83c6c9a34828f801172404336d4b391ce13e2f14197b5d2254603534200805b15ab55ea294204e73b2ca6aeedab7bf430ae3643ea5c13",
          "sha256": "dc9bf71c32966e15fa4015f398b1c14875cbbedbf8a12383a39ccf310984115a",
          "sha1": "3a2ea506916e6e0b01496d4d3776ba56e45ca7db",
          "md5": "1146714623cb8ab9f7a1302b7ace9136"
        }
      ]
    }
  ]
}
