{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "fbc4f219b85d384d1ad229cc05dce70ae7ba14c04165cf3eb6780b27d1e37d6bff277e94c443274b31f2c9d8be3798ed6fafa3f669dc6c987c1be48062cb2316",
          "sha256": "69324ed7b8567200025c9521b4216e4d7e907b78322b312d8b86bb755539a853",
          "sha1": "e9a6839cd8160233682cffa5749db6141dfca3fe",
          "md5": "9c15765e66775c510d8b67201a4c234c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "fbc4f219b85d384d1ad229cc05dce70ae7ba14c04165cf3eb6780b27d1e37d6bff277e94c443274b31f2c9d8be3798ed6fafa3f669dc6c987c1be48062cb2316",
          "sha256": "69324ed7b8567200025c9521b4216e4d7e907b78322b312d8b86bb755539a853",
          "sha1": "e9a6839cd8160233682cffa5749db6141dfca3fe",
          "md5": "9c15765e66775c510d8b67201a4c234c"
        }
      ]
    }
  ]
}
