{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "0c575bed3787e918596faa2cc957f544a3d1ecdb704aa1122a4ff284ab3fb5ebe7ffa2ca9a6e515e3bd7f8ed6c176602829d9de9008ebc06dbf543155bf9f224",
          "sha256": "f40df77cbec6a9a40e619cd2bde3a38c74d3066182522d7dafec118c9ce7174f",
          "sha1": "40cb85822c0fa3dbcc768fe3a4606b6455b88efc",
          "md5": "eb275a05445215cc3941ae638e9f4de8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.2.jar",
          "url": "runelite-jshell-4.25.2.jar",
          "size": 26557,
          "sha512": "0c575bed3787e918596faa2cc957f544a3d1ecdb704aa1122a4ff284ab3fb5ebe7ffa2ca9a6e515e3bd7f8ed6c176602829d9de9008ebc06dbf543155bf9f224",
          "sha256": "f40df77cbec6a9a40e619cd2bde3a38c74d3066182522d7dafec118c9ce7174f",
          "sha1": "40cb85822c0fa3dbcc768fe3a4606b6455b88efc",
          "md5": "eb275a05445215cc3941ae638e9f4de8"
        }
      ]
    }
  ]
}
