{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.12.2.jar",
          "url": "runelite-jshell-4.12.2.jar",
          "size": 26575,
          "sha512": "37f4c5396948b7fc72537b666e3fea14b2984c348174b6780573eee7847023bca5453b6e7eec16dc391ad00a7ba69ee501c3f19fc41a9e85d5715449f6c2965e",
          "sha256": "32488c3add0c71c15a7a7e57fbf9ab1ad5cc9ebb704eb8c6db6b3b9cde745216",
          "sha1": "579b180e2cfbfa888cd007efaf97b115aa9a0884",
          "md5": "ae23ce2cf6b7ffcca77dc82d363ab0cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.12.2.jar",
          "url": "runelite-jshell-4.12.2.jar",
          "size": 26575,
          "sha512": "37f4c5396948b7fc72537b666e3fea14b2984c348174b6780573eee7847023bca5453b6e7eec16dc391ad00a7ba69ee501c3f19fc41a9e85d5715449f6c2965e",
          "sha256": "32488c3add0c71c15a7a7e57fbf9ab1ad5cc9ebb704eb8c6db6b3b9cde745216",
          "sha1": "579b180e2cfbfa888cd007efaf97b115aa9a0884",
          "md5": "ae23ce2cf6b7ffcca77dc82d363ab0cb"
        }
      ]
    }
  ]
}
