{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "c2b22c83571c139b353daa61c64d74c9e2ed7c20b15c80c19afdf86eb5cf4509a6f9336ac432534ba075bf4c9e1271f5f7e4a1eca52e1245c422ec5d49c39d32",
          "sha256": "50dae687df5ebcc5a1d41012c230cfc78e0e9f1460368133f8e6057483b4b603",
          "sha1": "ed666dc0024533c7fa6f704eece965ffe5476b16",
          "md5": "3608927ca0a137f4c25718ac3a38c33a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.14.0.jar",
          "url": "runelite-api-4.14.0.jar",
          "size": 1332566,
          "sha512": "c2b22c83571c139b353daa61c64d74c9e2ed7c20b15c80c19afdf86eb5cf4509a6f9336ac432534ba075bf4c9e1271f5f7e4a1eca52e1245c422ec5d49c39d32",
          "sha256": "50dae687df5ebcc5a1d41012c230cfc78e0e9f1460368133f8e6057483b4b603",
          "sha1": "ed666dc0024533c7fa6f704eece965ffe5476b16",
          "md5": "3608927ca0a137f4c25718ac3a38c33a"
        }
      ]
    }
  ]
}
