{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "99750a46274a9e579bd48768064ed676d3c1c0b53ad8e6876abbe4da86070fea505253ba23d24c1c86020d00a3c1296dd89a3195c2431aa5712455bde59ad489",
          "sha256": "b77bf65a5fb535b56965fc143d0329cf4fcb5d68304498710ad60dc5fe666888",
          "sha1": "830ec441898440a2d6d222e34ed2b737630abc6e",
          "md5": "6e725b178d08f3e24b360af144fc2c1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "99750a46274a9e579bd48768064ed676d3c1c0b53ad8e6876abbe4da86070fea505253ba23d24c1c86020d00a3c1296dd89a3195c2431aa5712455bde59ad489",
          "sha256": "b77bf65a5fb535b56965fc143d0329cf4fcb5d68304498710ad60dc5fe666888",
          "sha1": "830ec441898440a2d6d222e34ed2b737630abc6e",
          "md5": "6e725b178d08f3e24b360af144fc2c1c"
        }
      ]
    }
  ]
}
