{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "53b2eb7b41ec96f0ca2de6b7668ac1361f4df1ea3e06d06903bb700095da7863c8e848ccaf36211ec64ade881d03b8cd8d2256ac7a35f87aa7cd77ffcdf84b42",
          "sha256": "e72635ce777d9bf1569ec0b4de9b49547e4dd9c922ac217611a5a12e81f36927",
          "sha1": "3a45ba4458f83177549962cb7da0e9d59f016179",
          "md5": "39a80c00c3ed035a719295f1134763b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "53b2eb7b41ec96f0ca2de6b7668ac1361f4df1ea3e06d06903bb700095da7863c8e848ccaf36211ec64ade881d03b8cd8d2256ac7a35f87aa7cd77ffcdf84b42",
          "sha256": "e72635ce777d9bf1569ec0b4de9b49547e4dd9c922ac217611a5a12e81f36927",
          "sha1": "3a45ba4458f83177549962cb7da0e9d59f016179",
          "md5": "39a80c00c3ed035a719295f1134763b4"
        }
      ]
    }
  ]
}
