{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "0c5b620fe79cc96a46122ebc561d2fc1fc7b97ec570cef3e2b8b8dcb3db6a136bf9db2ff5719f15a6c9ea7c0d531a5dac5c93418946cf07b53b8e758e5754bbf",
          "sha256": "aec2a4bee819a06d92140229163610ccbf8157b9a4bab1d0e33dcf8e319f2314",
          "sha1": "c4abccda076f01b06678b66c02bb02058de6d880",
          "md5": "270ced8559f8ddc266a96154a3eb45a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2.jar",
          "url": "runelite-api-4.25.2.jar",
          "size": 1356979,
          "sha512": "0c5b620fe79cc96a46122ebc561d2fc1fc7b97ec570cef3e2b8b8dcb3db6a136bf9db2ff5719f15a6c9ea7c0d531a5dac5c93418946cf07b53b8e758e5754bbf",
          "sha256": "aec2a4bee819a06d92140229163610ccbf8157b9a4bab1d0e33dcf8e319f2314",
          "sha1": "c4abccda076f01b06678b66c02bb02058de6d880",
          "md5": "270ced8559f8ddc266a96154a3eb45a0"
        }
      ]
    }
  ]
}
