{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.30.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.30.0.jar",
          "url": "runescape-api-4.30.0.jar",
          "size": 150296,
          "sha512": "54f09e35631af2f9cc7a08db843a2f4e38cf66582747b377045218472b3e01fd8bcfc6156168b9bf7d1df4fac9208b39b2f2979426d2d409fa2b7bfe55415bc9",
          "sha256": "f0b278ce45fe23be0f50b5fb734bfeea78ab65de1cb8fbe1dab48f368897af52",
          "sha1": "49f0b08d622bea575b0f54ed17560b242c360ad5",
          "md5": "d1b2ca792336d4af4e2831cee36bcb0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.30.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.30.0.jar",
          "url": "runescape-api-4.30.0.jar",
          "size": 150296,
          "sha512": "54f09e35631af2f9cc7a08db843a2f4e38cf66582747b377045218472b3e01fd8bcfc6156168b9bf7d1df4fac9208b39b2f2979426d2d409fa2b7bfe55415bc9",
          "sha256": "f0b278ce45fe23be0f50b5fb734bfeea78ab65de1cb8fbe1dab48f368897af52",
          "sha1": "49f0b08d622bea575b0f54ed17560b242c360ad5",
          "md5": "d1b2ca792336d4af4e2831cee36bcb0d"
        }
      ]
    }
  ]
}
