{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.8.jar",
          "url": "http-api-4.9.8.jar",
          "size": 158608,
          "sha512": "79c8275b2addb98f268255d49116bd8c28e76249ca475034f8ef2311a276c878a785ad1b77f0e2b327ec920caea5dbfb7734fa1893487e366f3a467a4e60fc96",
          "sha256": "e90a5f09da3be3a2d33570d50bd885399190c32f472942f2dcae437e66d4cfad",
          "sha1": "ed0cdfc0c48edf36e7fd6a69247aadbf47c16253",
          "md5": "98a757b2444f525968aaad7d328c753e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.8.jar",
          "url": "http-api-4.9.8.jar",
          "size": 158608,
          "sha512": "79c8275b2addb98f268255d49116bd8c28e76249ca475034f8ef2311a276c878a785ad1b77f0e2b327ec920caea5dbfb7734fa1893487e366f3a467a4e60fc96",
          "sha256": "e90a5f09da3be3a2d33570d50bd885399190c32f472942f2dcae437e66d4cfad",
          "sha1": "ed0cdfc0c48edf36e7fd6a69247aadbf47c16253",
          "md5": "98a757b2444f525968aaad7d328c753e"
        }
      ]
    }
  ]
}
