{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99206,
          "sha512": "39150ef2c5e7754e2b8b30ee11c6dec4d11aa7d29bec80e859f1f2e4c9c037a37ceb219b7283b2b4dde5467684ae55dd56cb58c445d651ebf1203c8e63abe9fc",
          "sha256": "b80c8eaecb4e9f3c3e73cb45b9e55c01370bc1fbec76159eecce25ee4aa4fdb0",
          "sha1": "ef89b61cdc916a6088e425eadc12b6c549cf2eaa",
          "md5": "f2d2c6a2162aca6c2656fceaa2bb712b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99206,
          "sha512": "39150ef2c5e7754e2b8b30ee11c6dec4d11aa7d29bec80e859f1f2e4c9c037a37ceb219b7283b2b4dde5467684ae55dd56cb58c445d651ebf1203c8e63abe9fc",
          "sha256": "b80c8eaecb4e9f3c3e73cb45b9e55c01370bc1fbec76159eecce25ee4aa4fdb0",
          "sha1": "ef89b61cdc916a6088e425eadc12b6c549cf2eaa",
          "md5": "f2d2c6a2162aca6c2656fceaa2bb712b"
        }
      ]
    }
  ]
}
