{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99206,
          "sha512": "39c03ebf9e7767c55f4d05ddd33debacae42f3a8c14121e008ed247881ba67d7b6cdd8511e2e531ac51080530b91fa2485f0a9b5ab76f0fb20558a97fe76418a",
          "sha256": "7e8dff6975d15ecd99aa8612639a8a4c4eec4a3459b58c3571cec0bd3b3ea8d6",
          "sha1": "9ee0948a6dcb4f6ed6c43f7014e83e5dfae8dafd",
          "md5": "230e9fd570938cefafe5ded95de9f35a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99206,
          "sha512": "39c03ebf9e7767c55f4d05ddd33debacae42f3a8c14121e008ed247881ba67d7b6cdd8511e2e531ac51080530b91fa2485f0a9b5ab76f0fb20558a97fe76418a",
          "sha256": "7e8dff6975d15ecd99aa8612639a8a4c4eec4a3459b58c3571cec0bd3b3ea8d6",
          "sha1": "9ee0948a6dcb4f6ed6c43f7014e83e5dfae8dafd",
          "md5": "230e9fd570938cefafe5ded95de9f35a"
        }
      ]
    }
  ]
}
