{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99206,
          "sha512": "fd2f0a7da111fa0d647fec4ac46f2e3fd9f183bf0091411c5113cbfab7ee646394f7de8ac20ee482282d34c71e0415a6d9c92d08ef789ee15ffdf5c034a6437f",
          "sha256": "1370cc4e36d32b298eaad07bf89e16623c18f122bb21695e4b35241d1fe672e4",
          "sha1": "4c315fed1f4253f8ecea796ddeeb439467761978",
          "md5": "86b85f6204a5797da9c88b52c3a96195"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.21.0.jar",
          "url": "http-api-4.21.0.jar",
          "size": 99206,
          "sha512": "fd2f0a7da111fa0d647fec4ac46f2e3fd9f183bf0091411c5113cbfab7ee646394f7de8ac20ee482282d34c71e0415a6d9c92d08ef789ee15ffdf5c034a6437f",
          "sha256": "1370cc4e36d32b298eaad07bf89e16623c18f122bb21695e4b35241d1fe672e4",
          "sha1": "4c315fed1f4253f8ecea796ddeeb439467761978",
          "md5": "86b85f6204a5797da9c88b52c3a96195"
        }
      ]
    }
  ]
}
