{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gjdnbyr2rrgw5kfciifuzv5xpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.4.jar",
          "url": "runescape-api-3.5.4.jar",
          "size": 107089,
          "sha512": "f1f6c09bfda399317679c0da9b3c8b3f98c01556ab892ecdadc259dee77158800201e649e3943167897c7134e41bd20b535b001d32d19d65e146d4d43abbea4d",
          "sha256": "2f8d34f24eb4685e81c6f772d059d8f02975885fdd92756ce423ab904265f484",
          "sha1": "24d9805770619f12d72a3c4b49a4581a1fc343eb",
          "md5": "0272342fa82826835d3790009317245f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.4.jar",
          "url": "runescape-api-3.5.4.jar",
          "size": 107089,
          "sha512": "f1f6c09bfda399317679c0da9b3c8b3f98c01556ab892ecdadc259dee77158800201e649e3943167897c7134e41bd20b535b001d32d19d65e146d4d43abbea4d",
          "sha256": "2f8d34f24eb4685e81c6f772d059d8f02975885fdd92756ce423ab904265f484",
          "sha1": "24d9805770619f12d72a3c4b49a4581a1fc343eb",
          "md5": "0272342fa82826835d3790009317245f"
        }
      ]
    }
  ]
}
