{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "iepaqu75mvgvjgroiixl6eooru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.0.0.jar",
          "url": "runelite-api-4.0.0.jar",
          "size": 1253678,
          "sha512": "56b07f670925603291541c90c543ef94705f94effb3c58ffb76903489df6a3f6197d2102e77f4be688dc5eeb9c3d080c83ccf5fbe5bc0d306611d782bb6a2e9d",
          "sha256": "c3ae2478faf591eee13e10b778d7db4bdeafa82e17c6e2abc8e63474441c8ae1",
          "sha1": "52965088a7e9bee62f25b6fbffcb4d5cfa9354ab",
          "md5": "573d7e88b54ef39e8127b52b57dfcbb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.0.0.jar",
          "url": "runelite-api-4.0.0.jar",
          "size": 1253678,
          "sha512": "56b07f670925603291541c90c543ef94705f94effb3c58ffb76903489df6a3f6197d2102e77f4be688dc5eeb9c3d080c83ccf5fbe5bc0d306611d782bb6a2e9d",
          "sha256": "c3ae2478faf591eee13e10b778d7db4bdeafa82e17c6e2abc8e63474441c8ae1",
          "sha1": "52965088a7e9bee62f25b6fbffcb4d5cfa9354ab",
          "md5": "573d7e88b54ef39e8127b52b57dfcbb4"
        }
      ]
    }
  ]
}
