{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "fd5bfb320fbc478e2fdcf2b2a1b695f76cd9ddd91bb224ae8e12302d9f58b371a61f882d10b7335bc894b071a0b4a9fac7f68b3436e5325f7d01f69ad02755d6",
          "sha256": "f7ede8772742e0f925a52d50b26a3405e1ba03daf18f24595baf8e208283aa4d",
          "sha1": "6324a8d0bce939c5cc7fe56d50d19fb80d7e8a04",
          "md5": "580a0f4726e5b3e4ffa9655a22775535"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "fd5bfb320fbc478e2fdcf2b2a1b695f76cd9ddd91bb224ae8e12302d9f58b371a61f882d10b7335bc894b071a0b4a9fac7f68b3436e5325f7d01f69ad02755d6",
          "sha256": "f7ede8772742e0f925a52d50b26a3405e1ba03daf18f24595baf8e208283aa4d",
          "sha1": "6324a8d0bce939c5cc7fe56d50d19fb80d7e8a04",
          "md5": "580a0f4726e5b3e4ffa9655a22775535"
        }
      ]
    }
  ]
}
