{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "52e4763e8c61873714eb1dbb04b3ebd373435d6d057fe797f4ef49de3a783bf8f09ac2baddfe61b799b0f7623370ccc1fc0ad20c9f956f7d961dc8cc254d229a",
          "sha256": "4a29c8bd59835b1dd6043bd11f4821fe2dcfbb0c2a0592c63a2bc8f83b0f118a",
          "sha1": "4accb48d0168b1785aa236d896db1f53cc1a1b71",
          "md5": "527f98ef55e93a2aae7978946a090ae5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "52e4763e8c61873714eb1dbb04b3ebd373435d6d057fe797f4ef49de3a783bf8f09ac2baddfe61b799b0f7623370ccc1fc0ad20c9f956f7d961dc8cc254d229a",
          "sha256": "4a29c8bd59835b1dd6043bd11f4821fe2dcfbb0c2a0592c63a2bc8f83b0f118a",
          "sha1": "4accb48d0168b1785aa236d896db1f53cc1a1b71",
          "md5": "527f98ef55e93a2aae7978946a090ae5"
        }
      ]
    }
  ]
}
