{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "94340cf64f4b7c1f0a563b731830047f8260936f4c9f2d1194e4915b581db6f0bce43f2b0cdc6c9fa88c78ada1f210f6637b969270f83a7b8bcf8bbd19d42bd9",
          "sha256": "94504dfc7fadef7e1095605c1c360197a26bc1b3bcdcd64ed89063aea550ec96",
          "sha1": "f518805b495406021ba8284b3da92ff462f5a93b",
          "md5": "6cb76b4e643e2029a50b4aaec92dd9a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.21.0.jar",
          "url": "runelite-api-4.21.0.jar",
          "size": 1353889,
          "sha512": "94340cf64f4b7c1f0a563b731830047f8260936f4c9f2d1194e4915b581db6f0bce43f2b0cdc6c9fa88c78ada1f210f6637b969270f83a7b8bcf8bbd19d42bd9",
          "sha256": "94504dfc7fadef7e1095605c1c360197a26bc1b3bcdcd64ed89063aea550ec96",
          "sha1": "f518805b495406021ba8284b3da92ff462f5a93b",
          "md5": "6cb76b4e643e2029a50b4aaec92dd9a3"
        }
      ]
    }
  ]
}
