{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "f1f37dadce93837aca73a0cd75b3427a3471fdfeb02b27d4f4ecd35be4d7160a391c0fe1717c9b14d45faee5964beaf3b1445d02b974b902a00987b439cb4f12",
          "sha256": "de18ea3a168955dc299fb601a53583a3f1b5a75d218820bba237112bc481d2cf",
          "sha1": "3fee3e78782567d7863f586506feb966236dccd1",
          "md5": "401d325ecea12c28a7f364fa215e4654"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "f1f37dadce93837aca73a0cd75b3427a3471fdfeb02b27d4f4ecd35be4d7160a391c0fe1717c9b14d45faee5964beaf3b1445d02b974b902a00987b439cb4f12",
          "sha256": "de18ea3a168955dc299fb601a53583a3f1b5a75d218820bba237112bc481d2cf",
          "sha1": "3fee3e78782567d7863f586506feb966236dccd1",
          "md5": "401d325ecea12c28a7f364fa215e4654"
        }
      ]
    }
  ]
}
