{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "578f8241f057608f3687fbf9a76708fae5426e8b1709f232ddccf16f8cb2b80cad1cc52aed17ad72da6b66ea4546a44963720e075e56002c989124748306c589",
          "sha256": "45ca9a51dd7002fbcbbfb74c9a981db3a1892deee6397645930a322799a606ff",
          "sha1": "98d9d6e000db2973c6ee415a97214b0831054d5a",
          "md5": "08883cdfab72721ee1fd777169cd3dd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.4.jar",
          "url": "runelite-api-4.20.4.jar",
          "size": 1347527,
          "sha512": "578f8241f057608f3687fbf9a76708fae5426e8b1709f232ddccf16f8cb2b80cad1cc52aed17ad72da6b66ea4546a44963720e075e56002c989124748306c589",
          "sha256": "45ca9a51dd7002fbcbbfb74c9a981db3a1892deee6397645930a322799a606ff",
          "sha1": "98d9d6e000db2973c6ee415a97214b0831054d5a",
          "md5": "08883cdfab72721ee1fd777169cd3dd9"
        }
      ]
    }
  ]
}
