{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "95114409b19cdb2d7faacdf5b1b2ddf7f74fabbfb50f64f0b2f334070dab92ed0302b7179f4166eb2d712e15df81ae2c6123fb8978600f349bb3202435db20e4",
          "sha256": "8175108a4a00d24a2e43a3d08bbcb6917bf60b14910cbbecec810556b24d2e00",
          "sha1": "2429aef9710450b49446283b3fd7c06d16cbe5e3",
          "md5": "36c197afbeff745f9b116aa97134c2bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "95114409b19cdb2d7faacdf5b1b2ddf7f74fabbfb50f64f0b2f334070dab92ed0302b7179f4166eb2d712e15df81ae2c6123fb8978600f349bb3202435db20e4",
          "sha256": "8175108a4a00d24a2e43a3d08bbcb6917bf60b14910cbbecec810556b24d2e00",
          "sha1": "2429aef9710450b49446283b3fd7c06d16cbe5e3",
          "md5": "36c197afbeff745f9b116aa97134c2bd"
        }
      ]
    }
  ]
}
