{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "ed111365e812cdd4c368e7bd3fc0e61046bd8c82bb4369e91bf075da8b3eaf516d6c7e1b55ac9bd9907253ef95f0eebb64c0bf57449cfd52c54419f0ff1dafda",
          "sha256": "73b44cf68cc4bc714f9fa1808b244de3dede1e31fc92deedc148725679579319",
          "sha1": "a967bb71fc42e56bee6558fc02f5ab1875bb4b47",
          "md5": "876e34f5716bd4383c2dacea9ba19053"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "ed111365e812cdd4c368e7bd3fc0e61046bd8c82bb4369e91bf075da8b3eaf516d6c7e1b55ac9bd9907253ef95f0eebb64c0bf57449cfd52c54419f0ff1dafda",
          "sha256": "73b44cf68cc4bc714f9fa1808b244de3dede1e31fc92deedc148725679579319",
          "sha1": "a967bb71fc42e56bee6558fc02f5ab1875bb4b47",
          "md5": "876e34f5716bd4383c2dacea9ba19053"
        }
      ]
    }
  ]
}
