{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "d4511bef075a260a2d056e48ec55d8faf0338e49eb347522f4e12c65b6535b5ba2de39adb0ac4402aff44703b92cf88c78446a7ccde93a1f4f7f8e6903b90b32",
          "sha256": "83ec79e2ff80298538b00166124630e4ea1a9a4d973176a7158d59406c222822",
          "sha1": "750c2bf13445c778c5525424bf208458ce2bbddc",
          "md5": "4daf1d55c4bd04b64b49bcd25ef163fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.2.jar",
          "url": "http-api-4.31.2.jar",
          "size": 99209,
          "sha512": "d4511bef075a260a2d056e48ec55d8faf0338e49eb347522f4e12c65b6535b5ba2de39adb0ac4402aff44703b92cf88c78446a7ccde93a1f4f7f8e6903b90b32",
          "sha256": "83ec79e2ff80298538b00166124630e4ea1a9a4d973176a7158d59406c222822",
          "sha1": "750c2bf13445c778c5525424bf208458ce2bbddc",
          "md5": "4daf1d55c4bd04b64b49bcd25ef163fc"
        }
      ]
    }
  ]
}
