{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.13.0.jar",
          "url": "http-api-4.13.0.jar",
          "size": 172797,
          "sha512": "7441d9b540f31765db4d1818628201de19e96afb5e3fc6dc7e462aac45a0e096ab20ed135561adfae24482d8de582aa742bed873b955fdea2ac178e60967bc2c",
          "sha256": "cc2ae293bac205ffb8de4f7352ce94a955c89b01c040dfc105a22af13737804c",
          "sha1": "f24df11d329a6fba8d87ef391b6fd0af4e1c2a2f",
          "md5": "236fb8fbb9904171df4509774cc3f1ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.13.0.jar",
          "url": "http-api-4.13.0.jar",
          "size": 172797,
          "sha512": "7441d9b540f31765db4d1818628201de19e96afb5e3fc6dc7e462aac45a0e096ab20ed135561adfae24482d8de582aa742bed873b955fdea2ac178e60967bc2c",
          "sha256": "cc2ae293bac205ffb8de4f7352ce94a955c89b01c040dfc105a22af13737804c",
          "sha1": "f24df11d329a6fba8d87ef391b6fd0af4e1c2a2f",
          "md5": "236fb8fbb9904171df4509774cc3f1ec"
        }
      ]
    }
  ]
}
