{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.0.jar",
          "url": "runelite-api-4.9.0.jar",
          "size": 1272022,
          "sha512": "aab23301db1fd389f21f6af14222537f60d2ef3a8608147ed0cbdd405af07db4931d788008dd8a3f0567d1b57969417028a42ff3128ca3f04977a59f346edd63",
          "sha256": "2a21dd8a5d7b7b0f49c83200e667dcf9211a0856b3e179adacd18e8fcc8b9a47",
          "sha1": "595ff97f5c04e6c124722b926018186dfb5fa836",
          "md5": "df0cb960d71023dbbd2fbf19e79a75dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.0.jar",
          "url": "runelite-api-4.9.0.jar",
          "size": 1272022,
          "sha512": "aab23301db1fd389f21f6af14222537f60d2ef3a8608147ed0cbdd405af07db4931d788008dd8a3f0567d1b57969417028a42ff3128ca3f04977a59f346edd63",
          "sha256": "2a21dd8a5d7b7b0f49c83200e667dcf9211a0856b3e179adacd18e8fcc8b9a47",
          "sha1": "595ff97f5c04e6c124722b926018186dfb5fa836",
          "md5": "df0cb960d71023dbbd2fbf19e79a75dc"
        }
      ]
    }
  ]
}
