{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.13.3.jar",
          "url": "http-api-4.13.3.jar",
          "size": 172797,
          "sha512": "443e06ad46b3c8c901945c5270befcf120974752dcbfb71403f677802c8a8fe73e12386d195b07fa91a0a53c05aced73c28f9454fa13ae00d34efc1859330335",
          "sha256": "077fbfd338dc2acfe67908b493781c5d6d55d66b9bc8f3ffb5b47c132342cf75",
          "sha1": "507fc539d04d38210732b881dfdff394b1b923a3",
          "md5": "70a34e7a390dcce0641fe664c1e129ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.13.3.jar",
          "url": "http-api-4.13.3.jar",
          "size": 172797,
          "sha512": "443e06ad46b3c8c901945c5270befcf120974752dcbfb71403f677802c8a8fe73e12386d195b07fa91a0a53c05aced73c28f9454fa13ae00d34efc1859330335",
          "sha256": "077fbfd338dc2acfe67908b493781c5d6d55d66b9bc8f3ffb5b47c132342cf75",
          "sha1": "507fc539d04d38210732b881dfdff394b1b923a3",
          "md5": "70a34e7a390dcce0641fe664c1e129ff"
        }
      ]
    }
  ]
}
