{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.7.jar",
          "url": "http-api-4.15.7.jar",
          "size": 172796,
          "sha512": "95adc22b5d49ef1e8756bf053a89db0ad14a3b68431918a34e1266b734b87ba70cad7deff9eb77525415c4e7cac05547480a74bdbbda1db2c86be358c0b0acd7",
          "sha256": "c774d8c66fca668141243fd8ea0aaae5b72d521f26ae5e8e1500244ab6ddad1f",
          "sha1": "7f7e9c928e07f4fa3b3f74ffbde2c0930a846ad7",
          "md5": "a9320c660480017ff8c6ef32a148b46b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.7.jar",
          "url": "http-api-4.15.7.jar",
          "size": 172796,
          "sha512": "95adc22b5d49ef1e8756bf053a89db0ad14a3b68431918a34e1266b734b87ba70cad7deff9eb77525415c4e7cac05547480a74bdbbda1db2c86be358c0b0acd7",
          "sha256": "c774d8c66fca668141243fd8ea0aaae5b72d521f26ae5e8e1500244ab6ddad1f",
          "sha1": "7f7e9c928e07f4fa3b3f74ffbde2c0930a846ad7",
          "md5": "a9320c660480017ff8c6ef32a148b46b"
        }
      ]
    }
  ]
}
