{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.24.0.jar",
          "url": "runescape-api-4.24.0.jar",
          "size": 149638,
          "sha512": "c463fffa606b4049b169300d73ac2a717d548d274c3b0fab828d395cf4620c99eb3685bf1ad526623cc05640ffba04b9d24c3e9c55fdb0adccd58d71c180f42a",
          "sha256": "24e0d71e338471714c829496c6ccc354e07f60c0bad19c83ab13e2b0edfb9bbc",
          "sha1": "928e5a6604d01cf4e19695dd805f948e8e073f5a",
          "md5": "a56eba028eb488e8af84d33b6d335d0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.24.0.jar",
          "url": "runescape-api-4.24.0.jar",
          "size": 149638,
          "sha512": "c463fffa606b4049b169300d73ac2a717d548d274c3b0fab828d395cf4620c99eb3685bf1ad526623cc05640ffba04b9d24c3e9c55fdb0adccd58d71c180f42a",
          "sha256": "24e0d71e338471714c829496c6ccc354e07f60c0bad19c83ab13e2b0edfb9bbc",
          "sha1": "928e5a6604d01cf4e19695dd805f948e8e073f5a",
          "md5": "a56eba028eb488e8af84d33b6d335d0b"
        }
      ]
    }
  ]
}
