{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "5bee10450a909983ee3ca0ee979ecce8ff388fe07c528fa56694736a367f9231f75e8aa3161eb1024aa0a9866800d4071950ab58bd0453c7bf8fa57d327b419a",
          "sha256": "5bcefc28596b8640b0163c4a4dc5a1647f909bfc763eb03cfc3cf07748e3c8d7",
          "sha1": "b08f69107dfd184d08b0b3cb654eb29c241f6631",
          "md5": "c9421db5dd5656d1fca3a066da683660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "5bee10450a909983ee3ca0ee979ecce8ff388fe07c528fa56694736a367f9231f75e8aa3161eb1024aa0a9866800d4071950ab58bd0453c7bf8fa57d327b419a",
          "sha256": "5bcefc28596b8640b0163c4a4dc5a1647f909bfc763eb03cfc3cf07748e3c8d7",
          "sha1": "b08f69107dfd184d08b0b3cb654eb29c241f6631",
          "md5": "c9421db5dd5656d1fca3a066da683660"
        }
      ]
    }
  ]
}
