{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "7204e2e7a110dafcdaa5440c3738cd28de5b26888ba8fa9aa56371de784e398f8445b1df94ab91b2f10e6409f0f07875870421bad84efba0a05b8851a27666a3",
          "sha256": "f4ae9dc8e2a34b2a98a16cf16ea633f5e61ed08ef3742b58230c2a2a50ab67bb",
          "sha1": "85ce4889b92f38a9036ce6fe534a01599ba2ffb7",
          "md5": "21388d8e3af1e6face474b281b537438"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.20.2.jar",
          "url": "runelite-api-4.20.2.jar",
          "size": 1347347,
          "sha512": "7204e2e7a110dafcdaa5440c3738cd28de5b26888ba8fa9aa56371de784e398f8445b1df94ab91b2f10e6409f0f07875870421bad84efba0a05b8851a27666a3",
          "sha256": "f4ae9dc8e2a34b2a98a16cf16ea633f5e61ed08ef3742b58230c2a2a50ab67bb",
          "sha1": "85ce4889b92f38a9036ce6fe534a01599ba2ffb7",
          "md5": "21388d8e3af1e6face474b281b537438"
        }
      ]
    }
  ]
}
