{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99206,
          "sha512": "14fc2fc98db20bd8d033d7ef891a5c599c8ab4a7ef99397792a67cabd54189395813373f9662e618efa52dfa7fc45c1ea1a26e3c8efbeb86834485fc3a44c759",
          "sha256": "fbfd39e01b473ad02abb208fd5ef4c47468c499508a118f5f5f3ca04bc912928",
          "sha1": "f5ae9de9b1de3549c9880bdecb27ed22d0f5edf7",
          "md5": "0b06781afa50e09c230e6519e2ec2d57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.4.jar",
          "url": "http-api-4.20.4.jar",
          "size": 99206,
          "sha512": "14fc2fc98db20bd8d033d7ef891a5c599c8ab4a7ef99397792a67cabd54189395813373f9662e618efa52dfa7fc45c1ea1a26e3c8efbeb86834485fc3a44c759",
          "sha256": "fbfd39e01b473ad02abb208fd5ef4c47468c499508a118f5f5f3ca04bc912928",
          "sha1": "f5ae9de9b1de3549c9880bdecb27ed22d0f5edf7",
          "md5": "0b06781afa50e09c230e6519e2ec2d57"
        }
      ]
    }
  ]
}
