{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.16.2.jar",
          "url": "runelite-api-4.16.2.jar",
          "size": 1331368,
          "sha512": "a14169643f285b9e5040af7d941ed4e50556eea1e813f02994943aaf0256b3bcdb5e1390fbd99875810d3b69d0a9b3409f771f467f6d276d3e6afaaa2e842f43",
          "sha256": "98ca23025d60f6a5801eb89e2985408156e3d8c92cae49219d2f6dd95924bc5f",
          "sha1": "52296a1d6382a9c20b9d4336b937fbff1b1d0283",
          "md5": "49c21979d7aca6b3ca3da233748d6a38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.16.2.jar",
          "url": "runelite-api-4.16.2.jar",
          "size": 1331368,
          "sha512": "a14169643f285b9e5040af7d941ed4e50556eea1e813f02994943aaf0256b3bcdb5e1390fbd99875810d3b69d0a9b3409f771f467f6d276d3e6afaaa2e842f43",
          "sha256": "98ca23025d60f6a5801eb89e2985408156e3d8c92cae49219d2f6dd95924bc5f",
          "sha1": "52296a1d6382a9c20b9d4336b937fbff1b1d0283",
          "md5": "49c21979d7aca6b3ca3da233748d6a38"
        }
      ]
    }
  ]
}
