{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.16.2.jar",
          "url": "runelite-api-4.16.2.jar",
          "size": 1331368,
          "sha512": "f13ec56c14bce586a7385137722676b720a7f3f588f3afafb0ecf2a6b79050ebb8e7dafd3ff2d83c4809c69c001a3b47a4d78b546bb6c3c2b034ee4850073fd9",
          "sha256": "5c72f3bbe0170373370d3e725c4e0c67a3975181755b1de3bef97bb10699ccbe",
          "sha1": "1e8521f7fbfc8fcd1017fd926d47da7214b1d5ed",
          "md5": "27f7694c7ae2fbab80eb30b3c3dddbdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.16.2.jar",
          "url": "runelite-api-4.16.2.jar",
          "size": 1331368,
          "sha512": "f13ec56c14bce586a7385137722676b720a7f3f588f3afafb0ecf2a6b79050ebb8e7dafd3ff2d83c4809c69c001a3b47a4d78b546bb6c3c2b034ee4850073fd9",
          "sha256": "5c72f3bbe0170373370d3e725c4e0c67a3975181755b1de3bef97bb10699ccbe",
          "sha1": "1e8521f7fbfc8fcd1017fd926d47da7214b1d5ed",
          "md5": "27f7694c7ae2fbab80eb30b3c3dddbdd"
        }
      ]
    }
  ]
}
