{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.16.2.jar",
          "url": "runelite-api-4.16.2.jar",
          "size": 1331368,
          "sha512": "97e3dd3dd7485f83c0ff3733cd3e17bbf26c5284f3267a060f013c01dfa2957c4064fde501bb82ebad100d1e14894c0d0b72d78b8c1790b5fa727c3ff68b5be4",
          "sha256": "d2195bc36e6967e6fb377ed3ac3266a3372e0d4968fa40133184d695becaa4c4",
          "sha1": "c1d8e7318918490130cfbdaa7a027e44f9fd453f",
          "md5": "2510926f4ce0bde5cbd71b4eb2701cc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.16.2.jar",
          "url": "runelite-api-4.16.2.jar",
          "size": 1331368,
          "sha512": "97e3dd3dd7485f83c0ff3733cd3e17bbf26c5284f3267a060f013c01dfa2957c4064fde501bb82ebad100d1e14894c0d0b72d78b8c1790b5fa727c3ff68b5be4",
          "sha256": "d2195bc36e6967e6fb377ed3ac3266a3372e0d4968fa40133184d695becaa4c4",
          "sha1": "c1d8e7318918490130cfbdaa7a027e44f9fd453f",
          "md5": "2510926f4ce0bde5cbd71b4eb2701cc4"
        }
      ]
    }
  ]
}
