{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.10.0.jar",
          "url": "runelite-api-4.10.0.jar",
          "size": 1285043,
          "sha512": "c8723af26f3f8376e87681fc27b4400b593eba8a2b0545d4304f8a198f6f88437614ea631410511cf0315f05e6cd4f197fc236e544092b51db5b03057b0ab7fa",
          "sha256": "dded692378561c396413a9134d1a757dbb136f142fc0d07b397431c5b6dc645b",
          "sha1": "8622fbcaf432cea1ae97bbcb75c7b2443490d758",
          "md5": "f603d75f2def25484e15107a646a2eb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.10.0.jar",
          "url": "runelite-api-4.10.0.jar",
          "size": 1285043,
          "sha512": "c8723af26f3f8376e87681fc27b4400b593eba8a2b0545d4304f8a198f6f88437614ea631410511cf0315f05e6cd4f197fc236e544092b51db5b03057b0ab7fa",
          "sha256": "dded692378561c396413a9134d1a757dbb136f142fc0d07b397431c5b6dc645b",
          "sha1": "8622fbcaf432cea1ae97bbcb75c7b2443490d758",
          "md5": "f603d75f2def25484e15107a646a2eb1"
        }
      ]
    }
  ]
}
