{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.4.0.jar",
          "url": "runescape-api-4.4.0.jar",
          "size": 107719,
          "sha512": "739dbc508e42b88c1db1436443e99df9ec8f9d01a85357ba91dc99df14e746985221929d6247448ddacf2981955cb954e19b336b7cbfed9397c1966359f3ba84",
          "sha256": "7326e3de28042604951c0a3fef11de70815676df902cd79f33d0a87d0a61e25f",
          "sha1": "c7981dccb53aad7f35e4766bc7dca2efb98004d1",
          "md5": "50c52d71e0fcde55c3e56feb8d01b168"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.4.0.jar",
          "url": "runescape-api-4.4.0.jar",
          "size": 107719,
          "sha512": "739dbc508e42b88c1db1436443e99df9ec8f9d01a85357ba91dc99df14e746985221929d6247448ddacf2981955cb954e19b336b7cbfed9397c1966359f3ba84",
          "sha256": "7326e3de28042604951c0a3fef11de70815676df902cd79f33d0a87d0a61e25f",
          "sha1": "c7981dccb53aad7f35e4766bc7dca2efb98004d1",
          "md5": "50c52d71e0fcde55c3e56feb8d01b168"
        }
      ]
    }
  ]
}
