{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "3974eeb08d871f14a0b20a784c19c9df896311e25789f01c262d2ec1368cd77a68809e0f4d1401b711de7ac0a1beadd0a86be36899ced7a445a4025d89d72c38",
          "sha256": "59395a02f18215d4c2ce0a96c6e4a6317fb4431378d895a6be9aaee5a4523dde",
          "sha1": "d08b60886f3f2ef732e4148df95360b8f43311fc",
          "md5": "f499e27fc89d7d38d4a9da458f8cd043"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "3974eeb08d871f14a0b20a784c19c9df896311e25789f01c262d2ec1368cd77a68809e0f4d1401b711de7ac0a1beadd0a86be36899ced7a445a4025d89d72c38",
          "sha256": "59395a02f18215d4c2ce0a96c6e4a6317fb4431378d895a6be9aaee5a4523dde",
          "sha1": "d08b60886f3f2ef732e4148df95360b8f43311fc",
          "md5": "f499e27fc89d7d38d4a9da458f8cd043"
        }
      ]
    }
  ]
}
