{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "69ed777cbdf911d74d280e27e9b39884d753810b1410bece8371d7655fe7995bd467ac4c9b2e3a9742bd06f0d3d1c9968f92777b120fd76b60798f75097f682d",
          "sha256": "ebd84c40b5ef0817eb838478f98f2144e8d1d3ee494dc31974d5d3db462e2cf9",
          "sha1": "90d11d05f6a86ecc837f580e0ebcebda04af58a2",
          "md5": "ce3e870b37f8e59f0b85ea7a684b32af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "69ed777cbdf911d74d280e27e9b39884d753810b1410bece8371d7655fe7995bd467ac4c9b2e3a9742bd06f0d3d1c9968f92777b120fd76b60798f75097f682d",
          "sha256": "ebd84c40b5ef0817eb838478f98f2144e8d1d3ee494dc31974d5d3db462e2cf9",
          "sha1": "90d11d05f6a86ecc837f580e0ebcebda04af58a2",
          "md5": "ce3e870b37f8e59f0b85ea7a684b32af"
        }
      ]
    }
  ]
}
