{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "9abae04f3c1fbd66cb77f21c40c9df8153592ddad49b81e990364a7d9792b5fb2eb8b696120f3be6d0eb7ce1cb1278aa990e1aa65db346fa368cb14270cd9e64",
          "sha256": "76aae78b153a81d2e78e6afa33dccdc8c1a717bd67853999610ca3ed8671a1af",
          "sha1": "7d53b510c925cf1f86f557fb93697871ea1acbd0",
          "md5": "168b5fc5f83199272ff83684df08e9b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.20.3.jar",
          "url": "runelite-jshell-4.20.3.jar",
          "size": 26557,
          "sha512": "9abae04f3c1fbd66cb77f21c40c9df8153592ddad49b81e990364a7d9792b5fb2eb8b696120f3be6d0eb7ce1cb1278aa990e1aa65db346fa368cb14270cd9e64",
          "sha256": "76aae78b153a81d2e78e6afa33dccdc8c1a717bd67853999610ca3ed8671a1af",
          "sha1": "7d53b510c925cf1f86f557fb93697871ea1acbd0",
          "md5": "168b5fc5f83199272ff83684df08e9b7"
        }
      ]
    }
  ]
}
