{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.1.jar",
          "url": "runescape-api-4.17.1.jar",
          "size": 146486,
          "sha512": "0ae839ec6f5d24f8c56e867d9e16229feec36ff48e0bbe58fabc1416870528db0ce087c107b8a4d876b0b8760da655c79fe130328d7fc5115f7a7b39eec811b1",
          "sha256": "3af706e405ae7c08b760c1b1f40371c5ecca826cd6f6297ad9a77b8d77bdbbcd",
          "sha1": "70c5dbd48b61e0df2ec7d34fd0d70e9d3edf7400",
          "md5": "e6f06353b5039fe130b5f28e0aa3ce6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.1.jar",
          "url": "runescape-api-4.17.1.jar",
          "size": 146486,
          "sha512": "0ae839ec6f5d24f8c56e867d9e16229feec36ff48e0bbe58fabc1416870528db0ce087c107b8a4d876b0b8760da655c79fe130328d7fc5115f7a7b39eec811b1",
          "sha256": "3af706e405ae7c08b760c1b1f40371c5ecca826cd6f6297ad9a77b8d77bdbbcd",
          "sha1": "70c5dbd48b61e0df2ec7d34fd0d70e9d3edf7400",
          "md5": "e6f06353b5039fe130b5f28e0aa3ce6f"
        }
      ]
    }
  ]
}
