{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.1.jar",
          "url": "runescape-api-4.17.1.jar",
          "size": 146467,
          "sha512": "22db3698134d09a41adb00251000a137bb97b53150f5f6f6bcab8fe7fd36f0fcde0f8685c988c58acb8ef5f14b9e447d316211a9c16732a8eb92f2bf285f91a2",
          "sha256": "e5cede264f9bc2121f62bd9fd8986a0e2f283e383f66bada0fcca1f9c52949f3",
          "sha1": "da5685f48f0ddae44bf63882d7dd70a78328fa57",
          "md5": "86f52883dfe6b8fc4cd21e763cc83b65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.1.jar",
          "url": "runescape-api-4.17.1.jar",
          "size": 146467,
          "sha512": "22db3698134d09a41adb00251000a137bb97b53150f5f6f6bcab8fe7fd36f0fcde0f8685c988c58acb8ef5f14b9e447d316211a9c16732a8eb92f2bf285f91a2",
          "sha256": "e5cede264f9bc2121f62bd9fd8986a0e2f283e383f66bada0fcca1f9c52949f3",
          "sha1": "da5685f48f0ddae44bf63882d7dd70a78328fa57",
          "md5": "86f52883dfe6b8fc4cd21e763cc83b65"
        }
      ]
    }
  ]
}
