{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.1.jar",
          "url": "runescape-api-4.17.1.jar",
          "size": 146467,
          "sha512": "632c2a84b671211299bf70c8f9fe536a79a26f5ec7d4599d0e37fb20505c311f31c7ccbf68dbeca9447f1e4be5473390d591cb39b24186469b1e07e484a67ec2",
          "sha256": "9312102b013a3049d681c40289c76729990065bf6505c48dbc5873089a90fb33",
          "sha1": "1321d387ab1297aff777b463b57632a3be6372bd",
          "md5": "5937a00879f804bfc7ac32e2bcd0936e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.17.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.17.1.jar",
          "url": "runescape-api-4.17.1.jar",
          "size": 146467,
          "sha512": "632c2a84b671211299bf70c8f9fe536a79a26f5ec7d4599d0e37fb20505c311f31c7ccbf68dbeca9447f1e4be5473390d591cb39b24186469b1e07e484a67ec2",
          "sha256": "9312102b013a3049d681c40289c76729990065bf6505c48dbc5873089a90fb33",
          "sha1": "1321d387ab1297aff777b463b57632a3be6372bd",
          "md5": "5937a00879f804bfc7ac32e2bcd0936e"
        }
      ]
    }
  ]
}
