{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.9.9.jar",
          "url": "http-api-4.9.9.jar",
          "size": 158609,
          "sha512": "645d59731bc00995e2efec4f01dec3e1571f8faeb15d5422ad0f0e9e4dbb6f4faeae463ef0581c59a6d0986f9a9a9251a2dc5424ecbfee6bd0c35ea940462268",
          "sha256": "af2b2b818bf2410c348f45176700b088ff04082a229dd57bc67341568b9844a1",
          "sha1": "785ede622789dcbab9521df8517cdd7c9e738799",
          "md5": "938a202b7939902819ae7de6648e8710"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.9.9.jar",
          "url": "http-api-4.9.9.jar",
          "size": 158609,
          "sha512": "645d59731bc00995e2efec4f01dec3e1571f8faeb15d5422ad0f0e9e4dbb6f4faeae463ef0581c59a6d0986f9a9a9251a2dc5424ecbfee6bd0c35ea940462268",
          "sha256": "af2b2b818bf2410c348f45176700b088ff04082a229dd57bc67341568b9844a1",
          "sha1": "785ede622789dcbab9521df8517cdd7c9e738799",
          "md5": "938a202b7939902819ae7de6648e8710"
        }
      ]
    }
  ]
}
