{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.31.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.31.1.jar",
          "url": "runelite-jshell-4.31.1.jar",
          "size": 26557,
          "sha512": "31bd1206ee7fdfc12f006ec038050f571bc79dbbcd89f0cbe51332f882fa23b36771cabbf95283bf065d035c1d01d04e30c36c8a3d28c8b43addb7c1927bcac1",
          "sha256": "8bc3c8835bee2d352667687e5dd16cb95d3ec51a35d0422f2e3dd7916bfd6236",
          "sha1": "a1be09d5da9a929bdcacebfd1d27b2c018b283b6",
          "md5": "1388cb9c499df99d16229cda793256a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.31.1.jar",
          "url": "runelite-jshell-4.31.1.jar",
          "size": 26557,
          "sha512": "31bd1206ee7fdfc12f006ec038050f571bc79dbbcd89f0cbe51332f882fa23b36771cabbf95283bf065d035c1d01d04e30c36c8a3d28c8b43addb7c1927bcac1",
          "sha256": "8bc3c8835bee2d352667687e5dd16cb95d3ec51a35d0422f2e3dd7916bfd6236",
          "sha1": "a1be09d5da9a929bdcacebfd1d27b2c018b283b6",
          "md5": "1388cb9c499df99d16229cda793256a1"
        }
      ]
    }
  ]
}
