{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359500,
          "sha512": "e95662c4dfcb0cdf96a31f2a984154e8e5477199790b8119d3eef7fb61586c617c46e4d06622d1909be8143acd468d012928cb06c633670d813b78b95238a7ff",
          "sha256": "1998a24df336a30f2d1bb14e6d5dabeedcfe505bf74ff51c7381d9e8b0a58556",
          "sha1": "788cee8f7c3e3e2a41cdf6f29bb99815e675a7ef",
          "md5": "a10bc1efff37b4b11f3aa69c5f95bea6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359500,
          "sha512": "e95662c4dfcb0cdf96a31f2a984154e8e5477199790b8119d3eef7fb61586c617c46e4d06622d1909be8143acd468d012928cb06c633670d813b78b95238a7ff",
          "sha256": "1998a24df336a30f2d1bb14e6d5dabeedcfe505bf74ff51c7381d9e8b0a58556",
          "sha1": "788cee8f7c3e3e2a41cdf6f29bb99815e675a7ef",
          "md5": "a10bc1efff37b4b11f3aa69c5f95bea6"
        }
      ]
    }
  ]
}
