{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359379,
          "sha512": "e12c2bdc13dce30e9f6b309a414060fbc21d63ecc1dabf86c19cf7cc7c85e5d572f7a740dfcde4f4706381a9d1446c02f4496ddbc26cc40c5149fb4ff25a5fe7",
          "sha256": "3ddb6af28acc59bc485fcb832e2e5f0a1ffec1cbdac3c49ee575ce6864ff78c5",
          "sha1": "279ab3ebddd869a27d74c6a314e99a258c6fd3df",
          "md5": "ef4b4c229c49b64b399654dd8ca7070f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359379,
          "sha512": "e12c2bdc13dce30e9f6b309a414060fbc21d63ecc1dabf86c19cf7cc7c85e5d572f7a740dfcde4f4706381a9d1446c02f4496ddbc26cc40c5149fb4ff25a5fe7",
          "sha256": "3ddb6af28acc59bc485fcb832e2e5f0a1ffec1cbdac3c49ee575ce6864ff78c5",
          "sha1": "279ab3ebddd869a27d74c6a314e99a258c6fd3df",
          "md5": "ef4b4c229c49b64b399654dd8ca7070f"
        }
      ]
    }
  ]
}
