{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359500,
          "sha512": "555084f5d9560c136b1ca53ac7771750c6e6ddcf351bf68fcd07baa1e36b7ec6d4e756cfe79af2cd78541eb04ff90e5b87c4ad3d6737154d1f50b3b3d67d7c19",
          "sha256": "212a1b8ca3881663f719aa99597bdf22705e55aab4727a5bed16241a084a474d",
          "sha1": "84285af86e3345838970a8007ce604332061d67d",
          "md5": "090d6757f47a36908dca13541a7c345c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0.jar",
          "url": "runelite-api-4.28.0.jar",
          "size": 1359500,
          "sha512": "555084f5d9560c136b1ca53ac7771750c6e6ddcf351bf68fcd07baa1e36b7ec6d4e756cfe79af2cd78541eb04ff90e5b87c4ad3d6737154d1f50b3b3d67d7c19",
          "sha256": "212a1b8ca3881663f719aa99597bdf22705e55aab4727a5bed16241a084a474d",
          "sha1": "84285af86e3345838970a8007ce604332061d67d",
          "md5": "090d6757f47a36908dca13541a7c345c"
        }
      ]
    }
  ]
}
