{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "c7ybiprcerguphp6mgmj3v3pjy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.4.jar",
          "url": "runescape-api-3.5.4.jar",
          "size": 104907,
          "sha512": "eb95830fc7b120cd43841679e5393d03176c49baf5ff83f0100eff39b6d6744d1d11d125f59a54882b6ba5137ee45157f752e6f2f82ea4369fe574ad704a2cb5",
          "sha256": "e9b298f12627536f3dcd22269f44965f59770b6f2c34fb0b8b66872e502f7fd8",
          "sha1": "22baed08d29bb5312de605ba2e1be1412603e9b4",
          "md5": "4f0587c17e5ff73599018d3846113e60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-3.5.4.jar",
          "url": "runescape-api-3.5.4.jar",
          "size": 104907,
          "sha512": "eb95830fc7b120cd43841679e5393d03176c49baf5ff83f0100eff39b6d6744d1d11d125f59a54882b6ba5137ee45157f752e6f2f82ea4369fe574ad704a2cb5",
          "sha256": "e9b298f12627536f3dcd22269f44965f59770b6f2c34fb0b8b66872e502f7fd8",
          "sha1": "22baed08d29bb5312de605ba2e1be1412603e9b4",
          "md5": "4f0587c17e5ff73599018d3846113e60"
        }
      ]
    }
  ]
}
