{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.1.jar",
          "url": "runelite-jshell-4.15.1.jar",
          "size": 26552,
          "sha512": "07ca0602fef0de772617d25eeb85a31bde7a833e65ee497be3dfa4fe6f66b461f2b56a2d3f3131e604df90ffc872856b273c7f36aff08ccc0fbf9a5680d12cbf",
          "sha256": "08e3e7976138b662f5bc6d9021fa4b2ff2ca6da93cfbaf69f0e4667edb5c46b7",
          "sha1": "6b4a58636ff6339a3643608160d6658c4e729b3d",
          "md5": "41298344e2ccd9b2c10a78b225106dbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.1.jar",
          "url": "runelite-jshell-4.15.1.jar",
          "size": 26552,
          "sha512": "07ca0602fef0de772617d25eeb85a31bde7a833e65ee497be3dfa4fe6f66b461f2b56a2d3f3131e604df90ffc872856b273c7f36aff08ccc0fbf9a5680d12cbf",
          "sha256": "08e3e7976138b662f5bc6d9021fa4b2ff2ca6da93cfbaf69f0e4667edb5c46b7",
          "sha1": "6b4a58636ff6339a3643608160d6658c4e729b3d",
          "md5": "41298344e2ccd9b2c10a78b225106dbc"
        }
      ]
    }
  ]
}
