{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.1.jar",
          "url": "runelite-jshell-4.15.1.jar",
          "size": 26552,
          "sha512": "72121605b0148f29f5421c4305df5a4521399f21ed6266621ad8f0ef3a11c9b8d825ebef8da86f7c9cbfd3483aa55f1d6d2b56c5be6ae904d22eaa5b1e548f2f",
          "sha256": "bddfb8be1ce7c9d015df18c2e7ce62a4f3b839895b613df42d6a77a3336e044c",
          "sha1": "fbce8efad4aafde37bc98d5544d93c296bdf2ca9",
          "md5": "18b0461c536b0f1387f6bf43a3520efc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.1.jar",
          "url": "runelite-jshell-4.15.1.jar",
          "size": 26552,
          "sha512": "72121605b0148f29f5421c4305df5a4521399f21ed6266621ad8f0ef3a11c9b8d825ebef8da86f7c9cbfd3483aa55f1d6d2b56c5be6ae904d22eaa5b1e548f2f",
          "sha256": "bddfb8be1ce7c9d015df18c2e7ce62a4f3b839895b613df42d6a77a3336e044c",
          "sha1": "fbce8efad4aafde37bc98d5544d93c296bdf2ca9",
          "md5": "18b0461c536b0f1387f6bf43a3520efc"
        }
      ]
    }
  ]
}
