{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.15.1.jar",
          "url": "runelite-jshell-4.15.1.jar",
          "size": 26552,
          "sha512": "cd1bb90cc0cb0706cd2499426f0ad0094e5d2f0732bf72ffcbfcb691a8cbbd8976e64bafabf0fae4e5558b08924559c3634ade91110b1eaaea4805bd3b1289c4",
          "sha256": "6837356124ac6f2481f5b66277fe1b9faa5ba9e96361af6de5176d44eba1c9ec",
          "sha1": "99ff81de0aedfe5eab2d555e73a8b2993d3d04f0",
          "md5": "9c3d153364b41172916516592e1fea7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.15.1.jar",
          "url": "runelite-jshell-4.15.1.jar",
          "size": 26552,
          "sha512": "cd1bb90cc0cb0706cd2499426f0ad0094e5d2f0732bf72ffcbfcb691a8cbbd8976e64bafabf0fae4e5558b08924559c3634ade91110b1eaaea4805bd3b1289c4",
          "sha256": "6837356124ac6f2481f5b66277fe1b9faa5ba9e96361af6de5176d44eba1c9ec",
          "sha1": "99ff81de0aedfe5eab2d555e73a8b2993d3d04f0",
          "md5": "9c3d153364b41172916516592e1fea7d"
        }
      ]
    }
  ]
}
