{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 172791,
          "sha512": "3e1485e1a7b83d58ac3e9bdb9129fbd9bf75fbf3d1b14a6cdafb75dd553c53d85173d917835091b4a6d88e02616450a2535819920ed32281b4aebe0fdf50db41",
          "sha256": "7924902b889c3594c9f06e5e3c9b69afc431f0bfb7beefc3a3133dfc1595f066",
          "sha1": "ea1e4af78adf28268f1b934ca80204b3450667d0",
          "md5": "be9574191671190a1e0002e3b4ecd1ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.6.jar",
          "url": "http-api-4.15.6.jar",
          "size": 172791,
          "sha512": "3e1485e1a7b83d58ac3e9bdb9129fbd9bf75fbf3d1b14a6cdafb75dd553c53d85173d917835091b4a6d88e02616450a2535819920ed32281b4aebe0fdf50db41",
          "sha256": "7924902b889c3594c9f06e5e3c9b69afc431f0bfb7beefc3a3133dfc1595f066",
          "sha1": "ea1e4af78adf28268f1b934ca80204b3450667d0",
          "md5": "be9574191671190a1e0002e3b4ecd1ad"
        }
      ]
    }
  ]
}
