{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.12.2.jar",
          "url": "http-api-4.12.2.jar",
          "size": 172799,
          "sha512": "01846b731960d84d2a420c554172c6659dab7ca5013072f83ef842c3792372846e6af523e2cea1478fe4a1e1cbbb7e01ed5c5f4ea7f1f91fb0224d4736959908",
          "sha256": "9ba54499ed60564d53d29f49b4a2029e7f3df998cc73adaf2fe7206c4aa859f6",
          "sha1": "cb24a4a1bafa2b7001d8ee0205590fde06afbbe1",
          "md5": "29511a8c4f20b1ac3b9fac93b043fbf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.12.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.12.2.jar",
          "url": "http-api-4.12.2.jar",
          "size": 172799,
          "sha512": "01846b731960d84d2a420c554172c6659dab7ca5013072f83ef842c3792372846e6af523e2cea1478fe4a1e1cbbb7e01ed5c5f4ea7f1f91fb0224d4736959908",
          "sha256": "9ba54499ed60564d53d29f49b4a2029e7f3df998cc73adaf2fe7206c4aa859f6",
          "sha1": "cb24a4a1bafa2b7001d8ee0205590fde06afbbe1",
          "md5": "29511a8c4f20b1ac3b9fac93b043fbf3"
        }
      ]
    }
  ]
}
