{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wpinim322bfgxcgrcmqhgfs3ae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.5.4.jar",
          "url": "injected-client-3.5.4.jar",
          "size": 2234719,
          "sha512": "d07b8b4387c773dbe19868d046a48fd62347cc727af4903246fbb56c88f7e1ecede2264d4ebe9bc7206445e1bbead1c586786ffbbb707cec9b59ea489b08b2b2",
          "sha256": "419310eef99babb885f6f1c270cf5bf7fd9bd7507b5bf8b48efd3387dce4424f",
          "sha1": "9e360a2b5fd5a1cb264faed6bc8fb186dda2eb17",
          "md5": "1482278b757ce1359f9794ac76df2d5e"
        }
      ]
    }
  ]
}
