{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injected-client",
    "version": "3.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "a5znc4b4ynautnxnvtgtn3arsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      }
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "injected-client-3.5.4.jar",
          "url": "injected-client-3.5.4.jar",
          "size": 2234770,
          "sha512": "fd4fc55bbf8f061609821b4c306170d88fc6ea140d81e5f3dacedbf668bab6f9e89e78a4985081099b6b3d60acc812f797167a69a39e27a4518912441436cb95",
          "sha256": "025e03b7e86b528cb19353b6b1d1026db638a5907d7748cae81dcb1b84a55a58",
          "sha1": "a94fb6a2d9f4e11dd0ab60bbe1e01b1237c337ec",
          "md5": "21da11d6d63bb8e375e972b65423be0a"
        }
      ]
    }
  ]
}
