{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.14.0.jar",
          "url": "runelite-jshell-4.14.0.jar",
          "size": 26552,
          "sha512": "f65f464bca87f2ea0f95648d6837b02e42c09f4015b8267c9c40f0c340b3ed9ab75fc470ac331ba5a0575324f7a899fc890fbe8af3916395096b8851afd128d5",
          "sha256": "aa9c22c95b550055c89aaea99bb9432ac8fa6f63926276faf98bb2300dcf8e0d",
          "sha1": "ebed99a37c93817e9cf0d8bf1d9e917355866a68",
          "md5": "0504f2d1e7aa22ac9bc3b5b9f498a9b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.14.0.jar",
          "url": "runelite-jshell-4.14.0.jar",
          "size": 26552,
          "sha512": "f65f464bca87f2ea0f95648d6837b02e42c09f4015b8267c9c40f0c340b3ed9ab75fc470ac331ba5a0575324f7a899fc890fbe8af3916395096b8851afd128d5",
          "sha256": "aa9c22c95b550055c89aaea99bb9432ac8fa6f63926276faf98bb2300dcf8e0d",
          "sha1": "ebed99a37c93817e9cf0d8bf1d9e917355866a68",
          "md5": "0504f2d1e7aa22ac9bc3b5b9f498a9b4"
        }
      ]
    }
  ]
}
