{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.14.0.jar",
          "url": "runelite-jshell-4.14.0.jar",
          "size": 26552,
          "sha512": "1b7c0ef5d9f47690987ad9206ece4b4b22dabbaa49954e497ac9454e5bc77d7a5931e66637a2a70cdaf2ab8c65057b99727d2bd913b69ac7ace2a24b5e163dbf",
          "sha256": "03bc9de1267865056d6567dad561a1c2859a674bed8a2cf17f14da749c4d58f6",
          "sha1": "79d27a0de2d0ad9ead37817be2f35e307f52c30d",
          "md5": "673d2a0cc404c71d5eef6ac730fc1712"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.14.0.jar",
          "url": "runelite-jshell-4.14.0.jar",
          "size": 26552,
          "sha512": "1b7c0ef5d9f47690987ad9206ece4b4b22dabbaa49954e497ac9454e5bc77d7a5931e66637a2a70cdaf2ab8c65057b99727d2bd913b69ac7ace2a24b5e163dbf",
          "sha256": "03bc9de1267865056d6567dad561a1c2859a674bed8a2cf17f14da749c4d58f6",
          "sha1": "79d27a0de2d0ad9ead37817be2f35e307f52c30d",
          "md5": "673d2a0cc404c71d5eef6ac730fc1712"
        }
      ]
    }
  ]
}
