{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.14.0.jar",
          "url": "runelite-jshell-4.14.0.jar",
          "size": 26552,
          "sha512": "276d679d6f95a393d3f83c81540ad19ff96a2a309c8e78824adccbaf1ec8a42af9e5fe9c77e14de360ed4e3b7159a6113d1a1bd1eaa49e50418cce635e67cd42",
          "sha256": "3c5870f92ba61555a2ef9f478a902b5b248faca78786f8fc2aaaa485f79bd9b6",
          "sha1": "3edb1fdc47439a255f94fe38fa51a240e0855526",
          "md5": "b8186fc749d071c900600b4a004eda10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.14.0.jar",
          "url": "runelite-jshell-4.14.0.jar",
          "size": 26552,
          "sha512": "276d679d6f95a393d3f83c81540ad19ff96a2a309c8e78824adccbaf1ec8a42af9e5fe9c77e14de360ed4e3b7159a6113d1a1bd1eaa49e50418cce635e67cd42",
          "sha256": "3c5870f92ba61555a2ef9f478a902b5b248faca78786f8fc2aaaa485f79bd9b6",
          "sha1": "3edb1fdc47439a255f94fe38fa51a240e0855526",
          "md5": "b8186fc749d071c900600b4a004eda10"
        }
      ]
    }
  ]
}
