{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.25.0.jar",
          "url": "runelite-jshell-4.25.0.jar",
          "size": 26557,
          "sha512": "c3b7cfd1420404cbbd95d205068c13352c84d5d8daccf6d04fd877d1988e70c8976bc94a051125a1dfe6b1d77268d14e10df0d4fc54c55513c10f1113309e814",
          "sha256": "55a07458a481f02124a38e1c500d0c3c93d984cf7c3d97ef361b3a4eee9ea578",
          "sha1": "54d5c3e0292e5c141a7ec1361172a7cc309f0b7c",
          "md5": "f1408de574a5089a043f8b1ad2e8a1f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.25.0.jar",
          "url": "runelite-jshell-4.25.0.jar",
          "size": 26557,
          "sha512": "c3b7cfd1420404cbbd95d205068c13352c84d5d8daccf6d04fd877d1988e70c8976bc94a051125a1dfe6b1d77268d14e10df0d4fc54c55513c10f1113309e814",
          "sha256": "55a07458a481f02124a38e1c500d0c3c93d984cf7c3d97ef361b3a4eee9ea578",
          "sha1": "54d5c3e0292e5c141a7ec1361172a7cc309f0b7c",
          "md5": "f1408de574a5089a043f8b1ad2e8a1f5"
        }
      ]
    }
  ]
}
