{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "ecd4bc088eed18c775aa7f41e1ee37ab78482c64c18a251a296e3ab93f8228eb79a1ddadbd96894bd4f3d3fd9bdc81e5f8f5c6e8ac2f0c7cea7d2e7b106e5e2b",
          "sha256": "7e92acdadfc45b04913d4e0ec29bed5e62d4d4c91ff5e4b1760d172692204da4",
          "sha1": "b271aac63e71de6681134929332c3b2f507c0dca",
          "md5": "1e0f389eb979a987b55468e5ce80879a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "ecd4bc088eed18c775aa7f41e1ee37ab78482c64c18a251a296e3ab93f8228eb79a1ddadbd96894bd4f3d3fd9bdc81e5f8f5c6e8ac2f0c7cea7d2e7b106e5e2b",
          "sha256": "7e92acdadfc45b04913d4e0ec29bed5e62d4d4c91ff5e4b1760d172692204da4",
          "sha1": "b271aac63e71de6681134929332c3b2f507c0dca",
          "md5": "1e0f389eb979a987b55468e5ce80879a"
        }
      ]
    }
  ]
}
