{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "1f1c0eac91dbc660b6e9ef29eeebd8e26ebba8ee79ea501751a91a19e9524ba1e67e21cc9bd37d1628a73a6ecec27f69ce23a68dca6e0eb9c15412c992bcf021",
          "sha256": "c41ffb72d652520769e18870d21cc7499a76f58107e26856689972f03cb7ef63",
          "sha1": "69014ff89c87dc719dc602d6f384945ab7dcb2e1",
          "md5": "a8eb0327c3ee681f8c9b3dc5c6b44d90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "1f1c0eac91dbc660b6e9ef29eeebd8e26ebba8ee79ea501751a91a19e9524ba1e67e21cc9bd37d1628a73a6ecec27f69ce23a68dca6e0eb9c15412c992bcf021",
          "sha256": "c41ffb72d652520769e18870d21cc7499a76f58107e26856689972f03cb7ef63",
          "sha1": "69014ff89c87dc719dc602d6f384945ab7dcb2e1",
          "md5": "a8eb0327c3ee681f8c9b3dc5c6b44d90"
        }
      ]
    }
  ]
}
