{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "71d9397cdd83a68f19ca9fc706c8ea5c3e31019a19fc4f9fdb60fd3888cb8bc25a59ce4e9e8dca58b1d0ab70c5f6bacffabec333e9fd7510b21cf9b210e61fcd",
          "sha256": "1e57ca108926d59eb7adffcff3655f6fda0c4824bb581eef0d7c663c5d46e995",
          "sha1": "f866502bf8788804c35f0fa16dc7f17d326cbeb2",
          "md5": "cb2145be132d13ddca61d8e1860a1fdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.28.0.jar",
          "url": "runelite-jshell-4.28.0.jar",
          "size": 26557,
          "sha512": "71d9397cdd83a68f19ca9fc706c8ea5c3e31019a19fc4f9fdb60fd3888cb8bc25a59ce4e9e8dca58b1d0ab70c5f6bacffabec333e9fd7510b21cf9b210e61fcd",
          "sha256": "1e57ca108926d59eb7adffcff3655f6fda0c4824bb581eef0d7c663c5d46e995",
          "sha1": "f866502bf8788804c35f0fa16dc7f17d326cbeb2",
          "md5": "cb2145be132d13ddca61d8e1860a1fdc"
        }
      ]
    }
  ]
}
