{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "970eb1bcc92e17e7c89bb73a16c2635b77ca62249f012730fe4eab8e67e9bde420185f824209037788534732da1cfcc32ef87b8406a18451ae5722f937be1740",
          "sha256": "7a247c1c3e08d4bb70a4ad16d8c6151aab2a6083393c3da0b5957efdca1dc664",
          "sha1": "c3b64da9de2d1259511c37f12b5c8e3425896fea",
          "md5": "8ca89b6bebfadf8a4a2983ae0e0be221"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.21.0.jar",
          "url": "runescape-api-4.21.0.jar",
          "size": 149225,
          "sha512": "970eb1bcc92e17e7c89bb73a16c2635b77ca62249f012730fe4eab8e67e9bde420185f824209037788534732da1cfcc32ef87b8406a18451ae5722f937be1740",
          "sha256": "7a247c1c3e08d4bb70a4ad16d8c6151aab2a6083393c3da0b5957efdca1dc664",
          "sha1": "c3b64da9de2d1259511c37f12b5c8e3425896fea",
          "md5": "8ca89b6bebfadf8a4a2983ae0e0be221"
        }
      ]
    }
  ]
}
