{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "d5b22d94a38385689455ec7bf0fdaaa6772d4a2d5cbbe3dc87a75d7685d61effe44d094c3c604ed749565c3ac31684c1680aa4379108999cd05f0d241d8eccdd",
          "sha256": "444415cc22de0b1a88fbff8e5312e3b5f4a14be655a6a1d1ac86fe6fae04b856",
          "sha1": "5db44994aaf328e009779cf8cc18b29a95baf362",
          "md5": "527f43eb91855af33b04b7d0a1631a26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "d5b22d94a38385689455ec7bf0fdaaa6772d4a2d5cbbe3dc87a75d7685d61effe44d094c3c604ed749565c3ac31684c1680aa4379108999cd05f0d241d8eccdd",
          "sha256": "444415cc22de0b1a88fbff8e5312e3b5f4a14be655a6a1d1ac86fe6fae04b856",
          "sha1": "5db44994aaf328e009779cf8cc18b29a95baf362",
          "md5": "527f43eb91855af33b04b7d0a1631a26"
        }
      ]
    }
  ]
}
