{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "d1eaee2af497c2beecb0e6b94ee24b3d213ad4450bad9016883fa58ad275d287ec5f39cfe591b3eb3016a3d90801e7b7335f359a54992790a044fe87470ef356",
          "sha256": "d264e84b9c5f149b2333d5d90b26760961b3bad8e236d1c119e9bc80f879600b",
          "sha1": "4e509f82380e39a436bb2eb29b84d7d1a0bbd690",
          "md5": "45d05826c2d1351602b53a6b1ccfb5c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "d1eaee2af497c2beecb0e6b94ee24b3d213ad4450bad9016883fa58ad275d287ec5f39cfe591b3eb3016a3d90801e7b7335f359a54992790a044fe87470ef356",
          "sha256": "d264e84b9c5f149b2333d5d90b26760961b3bad8e236d1c119e9bc80f879600b",
          "sha1": "4e509f82380e39a436bb2eb29b84d7d1a0bbd690",
          "md5": "45d05826c2d1351602b53a6b1ccfb5c5"
        }
      ]
    }
  ]
}
