{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "78c4b04bc6c1486e1b1269b19b2e2b31a5b08afa00a44b91df142905d6a7720b2a653e32633d4ae4a5ff39bfbe4e45c8fb8bad274b7e4c2cca123e0b01942f46",
          "sha256": "180963f6646bc8cf8ae3dbec359d432a9095da28a7dfdb98d8145974e760597c",
          "sha1": "aeee85a16c944e06906a2feae37e7c6ded690539",
          "md5": "1845dfa9bfb2a90da3b264219640bd11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.26.1.jar",
          "url": "runelite-jshell-4.26.1.jar",
          "size": 26557,
          "sha512": "78c4b04bc6c1486e1b1269b19b2e2b31a5b08afa00a44b91df142905d6a7720b2a653e32633d4ae4a5ff39bfbe4e45c8fb8bad274b7e4c2cca123e0b01942f46",
          "sha256": "180963f6646bc8cf8ae3dbec359d432a9095da28a7dfdb98d8145974e760597c",
          "sha1": "aeee85a16c944e06906a2feae37e7c6ded690539",
          "md5": "1845dfa9bfb2a90da3b264219640bd11"
        }
      ]
    }
  ]
}
