{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99205,
          "sha512": "570292abba2635f7cda223597f4a80f5559a11828ebe7e49bc9b572c329b26ab19ae541868db6e3946fb3c54aecf545e3213e269519e4462b17f6652e45733f9",
          "sha256": "1ff4ba3a7a54da1f40541064d95d5c864855f2fd003e2369b91478392e9d8d11",
          "sha1": "263fbe0d1439ca31c0319572888cd3750e2fc062",
          "md5": "2f24d3485a0eb8ccdbb223c48ad9a5e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99205,
          "sha512": "570292abba2635f7cda223597f4a80f5559a11828ebe7e49bc9b572c329b26ab19ae541868db6e3946fb3c54aecf545e3213e269519e4462b17f6652e45733f9",
          "sha256": "1ff4ba3a7a54da1f40541064d95d5c864855f2fd003e2369b91478392e9d8d11",
          "sha1": "263fbe0d1439ca31c0319572888cd3750e2fc062",
          "md5": "2f24d3485a0eb8ccdbb223c48ad9a5e7"
        }
      ]
    }
  ]
}
