{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99202,
          "sha512": "e7e9638c1239aace87ac1c78ef729d49b1eafca6b43d9d7a9965e105ac2dd726b35d56a9059fe9a15ffb4ee855efebccdb76397906e094d94edfb74cfd40e30f",
          "sha256": "04d144beab4a053d835e3853bc7c8f9ad3b57ec4ff52e10202143996e0538b48",
          "sha1": "7384b5369a8db486fb4f40202def32a342a55331",
          "md5": "364f621357e8a7dca7383b660baa7d95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99202,
          "sha512": "e7e9638c1239aace87ac1c78ef729d49b1eafca6b43d9d7a9965e105ac2dd726b35d56a9059fe9a15ffb4ee855efebccdb76397906e094d94edfb74cfd40e30f",
          "sha256": "04d144beab4a053d835e3853bc7c8f9ad3b57ec4ff52e10202143996e0538b48",
          "sha1": "7384b5369a8db486fb4f40202def32a342a55331",
          "md5": "364f621357e8a7dca7383b660baa7d95"
        }
      ]
    }
  ]
}
