{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99205,
          "sha512": "3844898ca71bb47ec096e303ae6f81631f2a5028d150e22e799dcc6eb9db79e6947ac6b5a3e121525d0092ee00d4afcc3a4b919cd19157bdf97d0e67c616880c",
          "sha256": "cd9c697c7c3ffd5cf8874cc8a3241a48ab2e4945790197738bed973bc4c037fe",
          "sha1": "27199fd5d56cc228beffd11dc65e08473a9e2986",
          "md5": "4abcdcaf0553ef1fd98b3c0547791388"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.20.3.jar",
          "url": "http-api-4.20.3.jar",
          "size": 99205,
          "sha512": "3844898ca71bb47ec096e303ae6f81631f2a5028d150e22e799dcc6eb9db79e6947ac6b5a3e121525d0092ee00d4afcc3a4b919cd19157bdf97d0e67c616880c",
          "sha256": "cd9c697c7c3ffd5cf8874cc8a3241a48ab2e4945790197738bed973bc4c037fe",
          "sha1": "27199fd5d56cc228beffd11dc65e08473a9e2986",
          "md5": "4abcdcaf0553ef1fd98b3c0547791388"
        }
      ]
    }
  ]
}
