{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.4.jar",
          "url": "runescape-api-4.15.4.jar",
          "size": 143805,
          "sha512": "be46a3688ddc0240e82b41c34ad3ede322d6265b22fd50f13d7baea36f36899419c57f68f4b0beb574de3974cf1b3510f4f5224586384e84878de005e396db7d",
          "sha256": "cb1e1dabd60d4dab81cef6334b2c94f481c5f5dc0c22036e0f91363544409ccf",
          "sha1": "6c1738e539d08041f32d0d46971dc47342794b49",
          "md5": "e4356291ad59784b16033f58d0dcd18a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.4.jar",
          "url": "runescape-api-4.15.4.jar",
          "size": 143805,
          "sha512": "be46a3688ddc0240e82b41c34ad3ede322d6265b22fd50f13d7baea36f36899419c57f68f4b0beb574de3974cf1b3510f4f5224586384e84878de005e396db7d",
          "sha256": "cb1e1dabd60d4dab81cef6334b2c94f481c5f5dc0c22036e0f91363544409ccf",
          "sha1": "6c1738e539d08041f32d0d46971dc47342794b49",
          "md5": "e4356291ad59784b16033f58d0dcd18a"
        }
      ]
    }
  ]
}
