{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.4.jar",
          "url": "runescape-api-4.15.4.jar",
          "size": 143805,
          "sha512": "c7de539adbf7c458b1d4d2ca45a8b362327df7603ea66f8d6143519385a38215a33ea37c28b6541083b4093abdee3b06deca44ddbbfc2d6d8dde1493ed95e0cc",
          "sha256": "b4e9c73118b416cc9b17d7ad369e8ff2b8edd1c2a65e349511cb6551358044e8",
          "sha1": "5c7c7c6f5b9dc5dbc0fdadce13e1ee35e3d61888",
          "md5": "a3aa793125b1965bebe08fd209e3e9da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.4.jar",
          "url": "runescape-api-4.15.4.jar",
          "size": 143805,
          "sha512": "c7de539adbf7c458b1d4d2ca45a8b362327df7603ea66f8d6143519385a38215a33ea37c28b6541083b4093abdee3b06deca44ddbbfc2d6d8dde1493ed95e0cc",
          "sha256": "b4e9c73118b416cc9b17d7ad369e8ff2b8edd1c2a65e349511cb6551358044e8",
          "sha1": "5c7c7c6f5b9dc5dbc0fdadce13e1ee35e3d61888",
          "md5": "a3aa793125b1965bebe08fd209e3e9da"
        }
      ]
    }
  ]
}
