{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.4.jar",
          "url": "runescape-api-4.15.4.jar",
          "size": 143805,
          "sha512": "4c761f63805aa6b5ffa5c1712702c0da1572c8bf641c3709649c4ca7fde2cc876e944fd1eaa1470cbbbb47fe0e6e07bda132d2d00e031640e34f4ed9f9117b14",
          "sha256": "44b77dcd799f1b2cf50bcd17e3ef32dbc37b702828b76a781c11bee5998a4bc9",
          "sha1": "c9ab7f5c39dc2bb1e22479281b2623deedc83441",
          "md5": "ec4e8329eab9aba849b1a66e3cfa7e63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.4"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.4.jar",
          "url": "runescape-api-4.15.4.jar",
          "size": 143805,
          "sha512": "4c761f63805aa6b5ffa5c1712702c0da1572c8bf641c3709649c4ca7fde2cc876e944fd1eaa1470cbbbb47fe0e6e07bda132d2d00e031640e34f4ed9f9117b14",
          "sha256": "44b77dcd799f1b2cf50bcd17e3ef32dbc37b702828b76a781c11bee5998a4bc9",
          "sha1": "c9ab7f5c39dc2bb1e22479281b2623deedc83441",
          "md5": "ec4e8329eab9aba849b1a66e3cfa7e63"
        }
      ]
    }
  ]
}
