{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.6.0.jar",
          "url": "http-api-4.6.0.jar",
          "size": 159716,
          "sha512": "db18dbf9ac43e7cc4c40f24b210bbbadabb61490c4b7908ee7f2b6c2eee11c6b882bdac30128b17ec4a2c43cee929b1c1e060a054ff52adf059f4f2ad0cc1faf",
          "sha256": "890513cee511700b1021da5dd52f4f0444169541e1959bbd5c1d03acc3ee9dd8",
          "sha1": "388f8ab6d1a85e5034021842e0238ac3aab56383",
          "md5": "c2aead9d032e1c6ec009ce1d004d20a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.6.0.jar",
          "url": "http-api-4.6.0.jar",
          "size": 159716,
          "sha512": "db18dbf9ac43e7cc4c40f24b210bbbadabb61490c4b7908ee7f2b6c2eee11c6b882bdac30128b17ec4a2c43cee929b1c1e060a054ff52adf059f4f2ad0cc1faf",
          "sha256": "890513cee511700b1021da5dd52f4f0444169541e1959bbd5c1d03acc3ee9dd8",
          "sha1": "388f8ab6d1a85e5034021842e0238ac3aab56383",
          "md5": "c2aead9d032e1c6ec009ce1d004d20a6"
        }
      ]
    }
  ]
}
