{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159868,
          "sha512": "cdf7ab93cf348feb6964a4bbe3ae9a9d4a8b4b7936f77edd9bf45a2e9909bd35e82b4e89c19da6cdb402b00ad6f07c7ef3ac6d08312cffd2dae85b062f9bfef5",
          "sha256": "4c6605752f218932bf35346d3c7e2b05deaaf92eedc565995a18454714a4201c",
          "sha1": "643ba2dbcc58b459c57d050db59364168f2f6e9a",
          "md5": "f3fc0d1ad66607975f5e072760f26106"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159868,
          "sha512": "cdf7ab93cf348feb6964a4bbe3ae9a9d4a8b4b7936f77edd9bf45a2e9909bd35e82b4e89c19da6cdb402b00ad6f07c7ef3ac6d08312cffd2dae85b062f9bfef5",
          "sha256": "4c6605752f218932bf35346d3c7e2b05deaaf92eedc565995a18454714a4201c",
          "sha1": "643ba2dbcc58b459c57d050db59364168f2f6e9a",
          "md5": "f3fc0d1ad66607975f5e072760f26106"
        }
      ]
    }
  ]
}
