{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159633,
          "sha512": "25a416dae776fa43e2a91518e95a6c8590edbde170e0726978df3dd43e64c02649faa812867ef3e56b412fcdf39e16684ff11a7c000c070f9a52fe4d76f8332b",
          "sha256": "921f8b39cb1950978b662f54b60421e3e647bc29848cf9186f8978955dd8c0fc",
          "sha1": "52ac8bc5e645d31f41fe3aee81889b20b9d4f63b",
          "md5": "99f7fe1089504ab153928e9e3707e3a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159633,
          "sha512": "25a416dae776fa43e2a91518e95a6c8590edbde170e0726978df3dd43e64c02649faa812867ef3e56b412fcdf39e16684ff11a7c000c070f9a52fe4d76f8332b",
          "sha256": "921f8b39cb1950978b662f54b60421e3e647bc29848cf9186f8978955dd8c0fc",
          "sha1": "52ac8bc5e645d31f41fe3aee81889b20b9d4f63b",
          "md5": "99f7fe1089504ab153928e9e3707e3a8"
        }
      ]
    }
  ]
}
