{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159868,
          "sha512": "e099a82b89cfec5fba4d50b9a2f9b5b9fa6580bc315bef8ecefc5aeac2e59932c650b96baad4e2a380e92d475bd51619ba92eb3c9d3695e8aed428f874c3f32b",
          "sha256": "406744b1933cd18962fc79ab34dc1ef86b14f1a53bcbf9f25b9e194cb5e80db0",
          "sha1": "a05ea8048f355f304d01e12cd627016939bfc8bd",
          "md5": "4018398beca6c76356d2026a5a936870"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.8.1.jar",
          "url": "http-api-4.8.1.jar",
          "size": 159868,
          "sha512": "e099a82b89cfec5fba4d50b9a2f9b5b9fa6580bc315bef8ecefc5aeac2e59932c650b96baad4e2a380e92d475bd51619ba92eb3c9d3695e8aed428f874c3f32b",
          "sha256": "406744b1933cd18962fc79ab34dc1ef86b14f1a53bcbf9f25b9e194cb5e80db0",
          "sha1": "a05ea8048f355f304d01e12cd627016939bfc8bd",
          "md5": "4018398beca6c76356d2026a5a936870"
        }
      ]
    }
  ]
}
