{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "a5b230dd835f248ef13264692e1b88e82968c0150712df6a3d5b9376b7678b95a05878f502900141471735e13884094b744df90723566f1c8b03596cefa6b3b3",
          "sha256": "cef26b63fae92e2520fb83cf0b7b66022467a32b036aad761209fd375ea9af36",
          "sha1": "288e740172b51692d9116493de1728012465d83e",
          "md5": "5847fe932242301c90d1930fb04e4af5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "a5b230dd835f248ef13264692e1b88e82968c0150712df6a3d5b9376b7678b95a05878f502900141471735e13884094b744df90723566f1c8b03596cefa6b3b3",
          "sha256": "cef26b63fae92e2520fb83cf0b7b66022467a32b036aad761209fd375ea9af36",
          "sha1": "288e740172b51692d9116493de1728012465d83e",
          "md5": "5847fe932242301c90d1930fb04e4af5"
        }
      ]
    }
  ]
}
