{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "bdcdd58dee0e341a0becd5c631a3a920a0cbae68e3a4e1d18e1406f2d8d9f603926e81e5b9b3d1738a4b0332784ec3ffab78c70091de8c5ee968fc18db5a95df",
          "sha256": "e779f5f79320e77e3fd8d9a47479ba55f1a774b9cbf3651e0016d4b16113a2cc",
          "sha1": "859778544576cf2c686e6e6e147b98972ebb329e",
          "md5": "ce4f5bb7cee9df4f5ebada46c70e4ff5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "bdcdd58dee0e341a0becd5c631a3a920a0cbae68e3a4e1d18e1406f2d8d9f603926e81e5b9b3d1738a4b0332784ec3ffab78c70091de8c5ee968fc18db5a95df",
          "sha256": "e779f5f79320e77e3fd8d9a47479ba55f1a774b9cbf3651e0016d4b16113a2cc",
          "sha1": "859778544576cf2c686e6e6e147b98972ebb329e",
          "md5": "ce4f5bb7cee9df4f5ebada46c70e4ff5"
        }
      ]
    }
  ]
}
