{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.20.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "2794f94e5ded0456ee184dc4c0e8b8899674aaea72e460068a1fbdae1b28901356f22fe1ef5abf803d834de6646ca1c65553fe8cd44457e1cfad3c7f0a6e7e3f",
          "sha256": "61b2454b79efdc2f9cf6f2571261d85a1315161c1843520032f435fc90f886f6",
          "sha1": "920f7a004d8e2f7499e3743eea4967cf4e8d8057",
          "md5": "12e3455341ab9653fa51287b9474373c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.20.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.20.3.jar",
          "url": "runescape-api-4.20.3.jar",
          "size": 149179,
          "sha512": "2794f94e5ded0456ee184dc4c0e8b8899674aaea72e460068a1fbdae1b28901356f22fe1ef5abf803d834de6646ca1c65553fe8cd44457e1cfad3c7f0a6e7e3f",
          "sha256": "61b2454b79efdc2f9cf6f2571261d85a1315161c1843520032f435fc90f886f6",
          "sha1": "920f7a004d8e2f7499e3743eea4967cf4e8d8057",
          "md5": "12e3455341ab9653fa51287b9474373c"
        }
      ]
    }
  ]
}
