{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "fd107400acc3b9511661f6bf8aa458095096528bf0230d4244d1c3d843052195250e89e9fe6384e83ff1226411ea222ae34b7131125f398048530261ab82ac42",
          "sha256": "a27be54d73b8e048546841e62f8b05b8476607ade5c2b936fda81397086ee513",
          "sha1": "92aa5928aa41c21d1dd62d4679e9dbf145e1ddcf",
          "md5": "9b9c9322742284d3e4148076515b28de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "fd107400acc3b9511661f6bf8aa458095096528bf0230d4244d1c3d843052195250e89e9fe6384e83ff1226411ea222ae34b7131125f398048530261ab82ac42",
          "sha256": "a27be54d73b8e048546841e62f8b05b8476607ade5c2b936fda81397086ee513",
          "sha1": "92aa5928aa41c21d1dd62d4679e9dbf145e1ddcf",
          "md5": "9b9c9322742284d3e4148076515b28de"
        }
      ]
    }
  ]
}
