{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "0c17e8e18b7848da1f1a39a9adf4cd43d651727a8ef711e8579d27141efdc703248138145b01ef215fd62bc5c9fee5bf2422d8d8fad1e059e8a288925ddd3aa4",
          "sha256": "8634a4f48ecd886f134a37ac68dac05809699a860a7a866e9de6578b2bc95bd0",
          "sha1": "1f5b24bf9f7ba74dd607897039e8ecf4eaba18b1",
          "md5": "4991efc019aad9cb4640c5f3c8292651"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "0c17e8e18b7848da1f1a39a9adf4cd43d651727a8ef711e8579d27141efdc703248138145b01ef215fd62bc5c9fee5bf2422d8d8fad1e059e8a288925ddd3aa4",
          "sha256": "8634a4f48ecd886f134a37ac68dac05809699a860a7a866e9de6578b2bc95bd0",
          "sha1": "1f5b24bf9f7ba74dd607897039e8ecf4eaba18b1",
          "md5": "4991efc019aad9cb4640c5f3c8292651"
        }
      ]
    }
  ]
}
