{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "c142c89242b347aba79d84b0cd215a30855ab72301a598420392ee2e0d5b3930a58427cdb65b6b49529b98b8b9a2bfdb9c2401367922a8bcd30346894430b5b6",
          "sha256": "807e8950500f0e5ac9b28cbeb3f7fcdbdf151824006bf68ee6dcf1e53f346223",
          "sha1": "a716e14dcaa8451ffa244dcd0d2bc6fc8a4b9889",
          "md5": "5bcbc5f77764d6510bb74c82a06ee407"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "c142c89242b347aba79d84b0cd215a30855ab72301a598420392ee2e0d5b3930a58427cdb65b6b49529b98b8b9a2bfdb9c2401367922a8bcd30346894430b5b6",
          "sha256": "807e8950500f0e5ac9b28cbeb3f7fcdbdf151824006bf68ee6dcf1e53f346223",
          "sha1": "a716e14dcaa8451ffa244dcd0d2bc6fc8a4b9889",
          "md5": "5bcbc5f77764d6510bb74c82a06ee407"
        }
      ]
    }
  ]
}
