{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "q4z5cyo65ne6hcs5il3lt4z7xa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160353,
          "sha512": "62507d9093622546f8284a6bf3dbfb41b3d1c1f371198df75b0d8d1d891337b8f89d5c8f9538611035ac958f3e1d978861c3c7ad35ab3343e8a36ec3a5940547",
          "sha256": "fb8e90fff251fc3b41d5ef108841b6e0d38e3aedf8919c224eff8ea196eb48eb",
          "sha1": "f990c088ff7ed0dc0384d5df10eeff78544a85e8",
          "md5": "a56e749eee366041b835eff1fd9202b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-3.5.2.jar",
          "url": "http-api-3.5.2.jar",
          "size": 160353,
          "sha512": "62507d9093622546f8284a6bf3dbfb41b3d1c1f371198df75b0d8d1d891337b8f89d5c8f9538611035ac958f3e1d978861c3c7ad35ab3343e8a36ec3a5940547",
          "sha256": "fb8e90fff251fc3b41d5ef108841b6e0d38e3aedf8919c224eff8ea196eb48eb",
          "sha1": "f990c088ff7ed0dc0384d5df10eeff78544a85e8",
          "md5": "a56e749eee366041b835eff1fd9202b9"
        }
      ]
    }
  ]
}
