{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172801,
          "sha512": "70b93ccdd9d557d86ea86dade3e57a853f370ee90130f3ec6a054a7ea636ab01c922702b446e36461e6c623fa087c67e61f5adf637a2fb5be589331df31dc6f2",
          "sha256": "71b5fd98b92aa4b6f12557cb1b35d1e56d88a6dd2f03bde78e55e003f8190254",
          "sha1": "d9066bab5541c21400c4827bc7e4defae92a84bd",
          "md5": "2549fbdff8c488030f64cfe3280a3ec6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.15.5.jar",
          "url": "http-api-4.15.5.jar",
          "size": 172801,
          "sha512": "70b93ccdd9d557d86ea86dade3e57a853f370ee90130f3ec6a054a7ea636ab01c922702b446e36461e6c623fa087c67e61f5adf637a2fb5be589331df31dc6f2",
          "sha256": "71b5fd98b92aa4b6f12557cb1b35d1e56d88a6dd2f03bde78e55e003f8190254",
          "sha1": "d9066bab5541c21400c4827bc7e4defae92a84bd",
          "md5": "2549fbdff8c488030f64cfe3280a3ec6"
        }
      ]
    }
  ]
}
