{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159719,
          "sha512": "c3dab00c20d3a3f8ef0ff7f24463b76318d455b66b8dd4d7a10dead780e7cd543485fb7cb4410db4ec9b2a27ee2e99eed70ea2c9af17468dae7b3c142be5a59e",
          "sha256": "c6e78f04e3dc74b3828e15e03dc6d40b85faf9760fcab80f70a2135d0f7f24de",
          "sha1": "7dfdce497afc9fe05ec1fabf01d0f7d1c307c839",
          "md5": "816768387a35d4f867fe6ad707ac7901"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159719,
          "sha512": "c3dab00c20d3a3f8ef0ff7f24463b76318d455b66b8dd4d7a10dead780e7cd543485fb7cb4410db4ec9b2a27ee2e99eed70ea2c9af17468dae7b3c142be5a59e",
          "sha256": "c6e78f04e3dc74b3828e15e03dc6d40b85faf9760fcab80f70a2135d0f7f24de",
          "sha1": "7dfdce497afc9fe05ec1fabf01d0f7d1c307c839",
          "md5": "816768387a35d4f867fe6ad707ac7901"
        }
      ]
    }
  ]
}
