{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159717,
          "sha512": "a001747e104223299e510fa0a3c7247ae587ccec271ab7aad2913b44a699b17af23a8cab70eb2218a511ddc43b1b5d7b7cc5d1e530cfb8f07af21bfadbabf0f7",
          "sha256": "4f24cc5fbd920daa8b68eecadae7e991958d5bd94c1dcc19f89d5347d4d99061",
          "sha1": "054445f58bf7efb53e1ca172a1b7dd7a6880918c",
          "md5": "2da2e8b6208f14aa90e0521ec45f5169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.7.0.jar",
          "url": "http-api-4.7.0.jar",
          "size": 159717,
          "sha512": "a001747e104223299e510fa0a3c7247ae587ccec271ab7aad2913b44a699b17af23a8cab70eb2218a511ddc43b1b5d7b7cc5d1e530cfb8f07af21bfadbabf0f7",
          "sha256": "4f24cc5fbd920daa8b68eecadae7e991958d5bd94c1dcc19f89d5347d4d99061",
          "sha1": "054445f58bf7efb53e1ca172a1b7dd7a6880918c",
          "md5": "2da2e8b6208f14aa90e0521ec45f5169"
        }
      ]
    }
  ]
}
