{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "af9e563343b2412c322a6203f5e6d13d3ad773077453801ede733947de69eaafc234e5ea842168516328e499b31fa1dc138a11a2fa080b8664838ee6a238174b",
          "sha256": "183a5b20fbf3c5e262c161f2a5b39dd3666603f637b97477b0bba73f283ef2bb",
          "sha1": "0634683b5de1ed3eb6ad92090047c47565c5d842",
          "md5": "edb38618fef63f4fd59c3511d7a7b59b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.15.3"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.15.3.jar",
          "url": "runescape-api-4.15.3.jar",
          "size": 143805,
          "sha512": "af9e563343b2412c322a6203f5e6d13d3ad773077453801ede733947de69eaafc234e5ea842168516328e499b31fa1dc138a11a2fa080b8664838ee6a238174b",
          "sha256": "183a5b20fbf3c5e262c161f2a5b39dd3666603f637b97477b0bba73f283ef2bb",
          "sha1": "0634683b5de1ed3eb6ad92090047c47565c5d842",
          "md5": "edb38618fef63f4fd59c3511d7a7b59b"
        }
      ]
    }
  ]
}
