{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158715,
          "sha512": "533afee3ca3f3c602042332db2ed0f40e0557759da1ee2fcb4d8ea4c49eb287a8993655bb0134de498560fb668a69973a45b810ad5fb240f7f55b51aa70ce2ca",
          "sha256": "69911854339de710685cfb9a3a3ad99763700e4141b47eb0dcbde69a238b1b83",
          "sha1": "ad60ba482591bee7b5fafe99143dd62b6ddc97d0",
          "md5": "e3611cd84a898ccfcbf2cf25b9849f57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.10.0.jar",
          "url": "http-api-4.10.0.jar",
          "size": 158715,
          "sha512": "533afee3ca3f3c602042332db2ed0f40e0557759da1ee2fcb4d8ea4c49eb287a8993655bb0134de498560fb668a69973a45b810ad5fb240f7f55b51aa70ce2ca",
          "sha256": "69911854339de710685cfb9a3a3ad99763700e4141b47eb0dcbde69a238b1b83",
          "sha1": "ad60ba482591bee7b5fafe99143dd62b6ddc97d0",
          "md5": "e3611cd84a898ccfcbf2cf25b9849f57"
        }
      ]
    }
  ]
}
