{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.9.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.9.10.jar",
          "url": "runelite-api-4.9.10.jar",
          "size": 1281922,
          "sha512": "345a1d6890c67097c3f4736a25a8cf2c2d756daef0f525c7156d6c4a76c055d879c06cba7d9a2e3b98791e834150384b0d6c76729f6b21149a33f7e5a3bb7e14",
          "sha256": "174cc73d7b4bf4c67c03359abd62e623825b3f7dc8ba9cd280f81924a0a432a4",
          "sha1": "9dddb30c70d3c752c3b1baba03e94e17a15a231b",
          "md5": "5697dd36098e9fb2b7e4f355312a416b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.12"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.9.10.jar",
          "url": "runelite-api-4.9.10.jar",
          "size": 1281922,
          "sha512": "345a1d6890c67097c3f4736a25a8cf2c2d756daef0f525c7156d6c4a76c055d879c06cba7d9a2e3b98791e834150384b0d6c76729f6b21149a33f7e5a3bb7e14",
          "sha256": "174cc73d7b4bf4c67c03359abd62e623825b3f7dc8ba9cd280f81924a0a432a4",
          "sha1": "9dddb30c70d3c752c3b1baba03e94e17a15a231b",
          "md5": "5697dd36098e9fb2b7e4f355312a416b"
        }
      ]
    }
  ]
}
