{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.2.jar",
          "url": "runescape-api-4.18.2.jar",
          "size": 146573,
          "sha512": "5f362125436d5298bae078514405d9bb6efb511eb0b202a0f366067a43db3995ffd6f85f0e10745f4f6b2efe53442c72e1dc352ead593e213ee9183e64bb5fdd",
          "sha256": "ef73bb3f2036288e1a8aead924bbe9ca9796c02ee10f094f55524fca611d3cbb",
          "sha1": "5785e5a83f9491899a0288324db455ab8a8209bb",
          "md5": "7c59342e6eed9067cfe7566ae9fd1a29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.18.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.18.2.jar",
          "url": "runescape-api-4.18.2.jar",
          "size": 146573,
          "sha512": "5f362125436d5298bae078514405d9bb6efb511eb0b202a0f366067a43db3995ffd6f85f0e10745f4f6b2efe53442c72e1dc352ead593e213ee9183e64bb5fdd",
          "sha256": "ef73bb3f2036288e1a8aead924bbe9ca9796c02ee10f094f55524fca611d3cbb",
          "sha1": "5785e5a83f9491899a0288324db455ab8a8209bb",
          "md5": "7c59342e6eed9067cfe7566ae9fd1a29"
        }
      ]
    }
  ]
}
