{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-jshell",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "e34f1cd38cd1fd24385387da1164ccf69f40b041da7a3bc6bdd727838969f8b87f642c89f527c106d8ad8cbb829e488bde827d73a03258b9ed427287d25de406",
          "sha256": "c7003863be9b28f86be5f6e1970ab14a5753e477f63bf91a02ce311125fcb7c1",
          "sha1": "7349c92a76e0cdd8f469cad9d4fcc4e3d17e7f3e",
          "md5": "7645f0e2be92d5e104835997c3a397e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fifesoft",
          "module": "autocomplete",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-jshell-4.17.0.jar",
          "url": "runelite-jshell-4.17.0.jar",
          "size": 26552,
          "sha512": "e34f1cd38cd1fd24385387da1164ccf69f40b041da7a3bc6bdd727838969f8b87f642c89f527c106d8ad8cbb829e488bde827d73a03258b9ed427287d25de406",
          "sha256": "c7003863be9b28f86be5f6e1970ab14a5753e477f63bf91a02ce311125fcb7c1",
          "sha1": "7349c92a76e0cdd8f469cad9d4fcc4e3d17e7f3e",
          "md5": "7645f0e2be92d5e104835997c3a397e8"
        }
      ]
    }
  ]
}
