{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.16.1.jar",
          "url": "runelite-api-4.16.1.jar",
          "size": 1331368,
          "sha512": "dd619e99eb8b7d59456e1b4deddfb895fb4a2a4458eb691121f193a2e820cfb8d6aae9fdcc8eb00d52e49cb2e8f0c8e5d66615a82638e3384f9c851b056fdc6e",
          "sha256": "f94d39ac27476d151f5837404130015c11fa0660c807bc6edc30ae7db5c9f68a",
          "sha1": "39714134a78b0989f3095a2c404c42ca08e5adf2",
          "md5": "4b55c4c563f47bdfe79a0c467f57febb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.16.1.jar",
          "url": "runelite-api-4.16.1.jar",
          "size": 1331368,
          "sha512": "dd619e99eb8b7d59456e1b4deddfb895fb4a2a4458eb691121f193a2e820cfb8d6aae9fdcc8eb00d52e49cb2e8f0c8e5d66615a82638e3384f9c851b056fdc6e",
          "sha256": "f94d39ac27476d151f5837404130015c11fa0660c807bc6edc30ae7db5c9f68a",
          "sha1": "39714134a78b0989f3095a2c404c42ca08e5adf2",
          "md5": "4b55c4c563f47bdfe79a0c467f57febb"
        }
      ]
    }
  ]
}
